Repository kata-containers/kata-containers, pull requests merged in 2020-09, with the labels that each got.

#668 virtcontainers: Add unit test for utils/compare.go
  src/runtime/virtcontainers/utils/compare_test.go
Labels: needs-review

#742 Generate version file with more information in it.
  src/agent/Makefile
  src/agent/kata-agent.service.in
  src/agent/src/main.rs
  src/agent/src/version.rs
  src/agent/src/version.rs.in
Labels: no-backport-needed, no-forward-port-needed

#737 runtime: Don't use hard-coded crio config
  src/runtime/data/kata-collect-data.sh.in
Labels: needs-backport, no-forward-port-needed

#764 Fix release notes
  docs/Release-Process.md
  tools/packaging/release/runtime-release-notes.sh
Labels: no-backport-needed

#772 fix guest panic when running agent as init
  .gitignore
  src/agent/src/main.rs
Labels: no-backport-needed, no-forward-port-needed

#768 Fix developer guide
  docs/Developer-Guide.md
  docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
Labels: no-backport-needed, no-forward-port-needed

#774 docs: Fix the kata-pkgsync tool's docs script path
  tools/packaging/cmd/kata-pkgsync/README.md
Labels: no-backport-needed, no-forward-port-needed

#776 how-to: add privileged_without_host_devices to containerd guide
  docs/how-to/containerd-kata.md
Labels: no-backport-needed, no-forward-port-needed

#735 runtime: make kata-check check for newer release
  src/runtime/Makefile
  src/runtime/cli/config-generated.go.in
  src/runtime/cli/kata-check.go
  src/runtime/cli/release.go
  src/runtime/cli/release_test.go
Labels: needs-backport, no-forward-port-needed

#778 docs: Update the reference path of kata-deploy in the packaging
  tools/packaging/kata-deploy/README.md
Labels: no-backport-needed, no-forward-port-needed

#779 agent: update cgroups crate
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
Labels: no-backport-needed, no-forward-port-needed

#780 ci: use Travis cache to reduce build time
  .travis.yml
Labels: no-backport-needed, no-forward-port-needed

#784 runtime: Fix linter errors in release files
  src/runtime/cli/release.go
  src/runtime/cli/release_test.go
Labels: no-backport-needed, no-forward-port-needed

#697 runtime: Call s.newStore.Destroy if globalSandboxList.addSandbox
  src/runtime/virtcontainers/sandbox.go
Labels: forward-port

#441 kata 2.0: add debug console service
  docs/Developer-Guide.md
  src/agent/src/main.rs
  src/runtime/cli/config/configuration-acrn.toml.in
  src/runtime/cli/config/configuration-clh.toml.in
  src/runtime/cli/config/configuration-fc.toml.in
  src/runtime/cli/config/configuration-qemu-virtiofs.toml.in
  src/runtime/cli/config/configuration-qemu.toml.in
  src/runtime/cli/kata-exec.go
  src/runtime/cli/kata-monitor/main.go
  src/runtime/cli/main.go
  src/runtime/containerd-shim-v2/shim_management.go
  src/runtime/pkg/kata-monitor/metrics.go
  src/runtime/pkg/kata-monitor/monitor.go
  src/runtime/pkg/kata-monitor/pprof.go
  src/runtime/pkg/kata-monitor/shim_client.go
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/interfaces.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/pkg/vcmock/sandbox.go
  src/runtime/virtcontainers/pkg/vcmock/types.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/vm_test.go
Labels: no-backport-needed, no-forward-port-needed

#808 agent: Only allow proc mount if it is procfs
  src/agent/rustjail/src/mount.rs
Labels: no-backport-needed, no-forward-port-needed

#814 agent: fix UT failures due to chdir
  .gitignore
  src/agent/Cargo.lock
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/mount.rs
Labels: no-backport-needed, no-forward-port-needed

#811 ci: resurrect travis static checkers
  .travis.yml
  CODEOWNERS
  ci/go-no-os-exit.sh
  ci/lib.sh
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/Developer-Guide.md
  docs/README.md
  snap/README.md
  src/agent/protocols/src/lib.rs
  src/runtime/CONTRIBUTING.md
  src/runtime/Makefile
  src/runtime/cli/console_test.go
  src/runtime/containerd-shim-v2/shim_metrics_test.go
  src/runtime/virtcontainers/device/manager/utils_test.go
  src/runtime/virtcontainers/documentation/Developers.md
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_s390x.go
  tools/packaging/CODE_OF_CONDUCT.md
  tools/packaging/CONTRIBUTING.md
  tools/packaging/README.md
Labels: no-backport-needed, no-forward-port-needed

#813 agent: Set LIBC=gnu for ppc64le arch by default
  src/agent/Makefile
Labels: no-backport-needed, no-forward-port-needed, release-gating

#822 ci: fix clone_tests_repo function
  ci/lib.sh
Labels: no-backport-needed, no-forward-port-needed, release-gating

#825 agent: propagate the internal detail errors to users
  src/agent/src/rpc.rs
Labels: no-backport-needed, no-forward-port-needed

#747 devices: fix go test warning in manager_test.go
  src/runtime/virtcontainers/device/manager/manager_test.go
Labels: needs-backport, no-forward-port-needed, release-gating

#794 rust-agent: Replaces improper use of match for non-constant patterns
  src/agent/rustjail/src/cgroups/notifier.rs
Labels: no-backport-needed, no-forward-port-needed, release-gating

#830 Packaging: release notes script using error kernel path urls
  tools/packaging/release/runtime-release-notes.sh
Labels: no-backport-needed, no-forward-port-needed
