Repository kata-containers/kata-containers, pull requests merged in 2020-11, with the labels that each got.

#1037 versions: Update crio version
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#1062 runtime: readonly volume should be bind mounted readonly on the host
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/pkg/oci/utils.go
  src/runtime/virtcontainers/sandbox_test.go
  versions.yaml
Labels: needs-backport, no-forward-port-needed

#1086 annotations: Improve asset annotation handling
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_test.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/pkg/oci/utils.go
  src/runtime/virtcontainers/pkg/oci/utils_test.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
  src/runtime/virtcontainers/types/asset.go
  src/runtime/virtcontainers/types/asset_test.go
  src/runtime/virtcontainers/virtcontainers_test.go
Labels: forward-port

#979 agent: Log ttrpc messages
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/config.rs
  src/agent/src/main.rs
Labels: no-backport-needed, no-forward-port-needed

#1077 clh: Consolidate the code path for device unplug
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
Labels: forward-port

#1045 Forward port annotation doc
  docs/how-to/how-to-load-kernel-modules-with-kata.md
  docs/how-to/how-to-set-sandbox-config-kata.md
Labels: forward-port, no-backport-needed

#1084 runtime: clean/refactor code
  src/runtime/virtcontainers/nsenter.go
  src/runtime/virtcontainers/nsenter_test.go
  src/runtime/virtcontainers/pkg/nsenter/nsenter.go
  src/runtime/virtcontainers/pkg/nsenter/nsenter_test.go
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, no-forward-port-needed

#1094 runtime: sleep 1 second after GetOOMEvent failed
  src/runtime/containerd-shim-v2/wait.go
Labels: needs-backport, no-forward-port-needed

#1105 release: Fix release candidate to major version upgrade check
  src/runtime/cli/release.go
  src/runtime/cli/release_test.go
Labels: needs-backport, no-forward-port-needed

#1095 versions: Use release-1.18 (commit ee9128444bec10)
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#1079 runtime: delete sandboxlist.go and sandboxlist_test.go
  src/runtime/containerd-shim-v2/service.go
  src/runtime/containerd-shim-v2/utils.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/acrn_test.go
  src/runtime/virtcontainers/api.go
  src/runtime/virtcontainers/api_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/implementation.go
  src/runtime/virtcontainers/interfaces.go
  src/runtime/virtcontainers/mock_hypervisor.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/pkg/vcmock/mock.go
  src/runtime/virtcontainers/pkg/vcmock/mock_test.go
  src/runtime/virtcontainers/pkg/vcmock/types.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
  src/runtime/virtcontainers/sandboxlist.go
  src/runtime/virtcontainers/sandboxlist_test.go
  src/runtime/virtcontainers/virtcontainers_test.go
Labels: no-backport-needed, no-forward-port-needed

#1110 runtime: change configuration key name from EnablePprof to enable_pprof
  src/runtime/cli/config/configuration-acrn.toml.in
  src/runtime/cli/config/configuration-clh.toml.in
  src/runtime/cli/config/configuration-fc.toml.in
  src/runtime/cli/config/configuration-qemu.toml.in
Labels: no-backport-needed, no-forward-port-needed

#1117 versions: Use CRI-O v1.18.4-4-g6dee3891e
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#1121 Add hyperlink and fix typo
  docs/design/virtualization.md
Labels: needs-backport, no-forward-port-needed

#1065 docs: Create hypervisor summary document
  docs/design/virtualization.md
  docs/hypervisors.md
  src/runtime/README.md
Labels: no-backport-needed, no-forward-port-needed

#1120 virtcontainers: revert CleanupContainer from PR 1079
  src/runtime/containerd-shim-v2/service.go
  src/runtime/containerd-shim-v2/utils.go
  src/runtime/virtcontainers/api.go
  src/runtime/virtcontainers/api_test.go
  src/runtime/virtcontainers/implementation.go
  src/runtime/virtcontainers/interfaces.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/pkg/vcmock/mock.go
  src/runtime/virtcontainers/pkg/vcmock/mock_test.go
  src/runtime/virtcontainers/pkg/vcmock/types.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: no-backport-needed, no-forward-port-needed

#1126 agent: enable lto flag for Cargo to get better optimized code
  src/agent/Cargo.toml
Labels: no-backport-needed, no-forward-port-needed

#1128 runtime: don't wait the second shim process in shim start
  src/runtime/containerd-shim-v2/service.go
Labels: no-backport-needed, no-forward-port-needed

#1124 snap: update apps section
  snap/snapcraft.yaml
Labels: no-backport-needed, no-forward-port-needed

#1139 rustjail: remove the network ns validation against container
  src/agent/rustjail/src/validator.rs
Labels: no-backport-needed, no-forward-port-needed

#1141 rustjail: fork a new child process to change the pid ns
  src/agent/rustjail/src/container.rs
Labels: no-backport-needed, no-forward-port-needed

#1145 backport fixes to stable-2.0.0
  .gitignore
  docs/design/kata-api-design.md
  docs/how-to/how-to-load-kernel-modules-with-kata.md
  src/agent/Cargo.lock
  src/agent/Makefile
  src/agent/protocols/Cargo.toml
  src/agent/protocols/build.rs
  src/agent/protocols/hack/update-generated-proto.sh
  src/agent/protocols/protos/agent.proto
  src/agent/protocols/protos/gogo/protobuf/gogoproto/gogo.proto
  src/agent/protocols/protos/health.proto
  src/agent/protocols/protos/oci.proto
  src/agent/protocols/protos/types.proto
  src/agent/protocols/src/agent.rs
  src/agent/protocols/src/agent_ttrpc.rs
  src/agent/protocols/src/empty.rs
  src/agent/protocols/src/health.rs
  src/agent/protocols/src/health_ttrpc.rs
  src/agent/protocols/src/oci.rs
  src/agent/protocols/src/types.rs
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.proto
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/health.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/health.proto
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.proto
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.proto
  tools/agent-ctl/Cargo.lock
Labels: no-backport-needed, no-forward-port-needed

#1024 [backport] snap: add GH actions jobs to release the snap package
  .github/workflows/snap-release.yaml
  snap/snapcraft.yaml
Labels: no-backport-needed, no-forward-port-needed
