Repository kata-containers/kata-containers, pull requests merged in 2020-12, with the labels that each got.

#1146 [forward port] cli: make check subcommand more tolerant to failures
  src/runtime/cli/kata-check.go
  src/runtime/cli/kata-check_test.go
  src/runtime/cli/release.go
Labels: no-backport-needed, no-forward-port-needed

#1114 agent: Adjust OOM Score to avoid agent being killed.
  src/agent/kata-agent.service.in
Labels: needs-backport, no-forward-port-needed

#1103 runtime: clh: Enforce to call 'cleanupVM' for 'stopSandbox'
  src/runtime/virtcontainers/clh.go
Labels: needs-backport, no-forward-port-needed

#1166 shimv2: handle ctx passed by containerd
  src/runtime/containerd-shim-v2/service.go
Labels: forward-port, needs-review

#1158 handle vcpus properly utilized in the guest
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/mock.rs
  src/agent/src/sandbox.rs
Labels: no-backport-needed, no-forward-port-needed

#1173 [forwardport] install: Improve snap documentation
  docs/install/snap-installation-guide.md
Labels: no-backport-needed, no-forward-port-needed

#1199 Fixes for make generate-protocols
  src/agent/protocols/hack/update-generated-proto.sh
  src/agent/protocols/protos/oci.proto
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/ocipb_test.go
Labels: no-backport-needed, no-forward-port-needed

#1175 snap: fix snap release channel
  .github/workflows/snap-release.yaml
Labels: needs-backport, no-forward-port-needed

#1183 runtime: Allow to overwrite DESTDIR
  src/runtime/Makefile
Labels: no-backport-needed, no-forward-port-needed

#1189 rootfs: reduce size of debian image
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
Labels: no-backport-needed

#1212 oci: fix a typo in "addtionalGids"
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/oci/src/lib.rs
  src/agent/protocols/Cargo.toml
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/lib.rs
Labels: no-backport-needed, no-forward-port-needed

#1177 [forwardport] Add support for Gentoo
  tools/osbuilder/rootfs-builder/gentoo/Dockerfile.in
  tools/osbuilder/rootfs-builder/gentoo/config.sh
  tools/osbuilder/rootfs-builder/gentoo/rootfs_lib.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/template/rootfs_lib_template.sh
  tools/osbuilder/scripts/lib.sh
Labels: no-backport-needed, no-forward-port-needed

#1150 Add void "install" targets for both "trace-forwarder" and "agent-ctl"
  src/trace-forwarder/Makefile
  tools/agent-ctl/Makefile
Labels: needs-backport, no-forward-port-needed

#1215 improve rustjail validator
  src/agent/rustjail/src/validator.rs
Labels: no-backport-needed, no-forward-port-needed
