Repository kata-containers/kata-containers, pull requests merged in 2020-10, with the labels that each got.

#827 docs: fix broken links
  docs/install/README.md
  docs/install/azure-installation-guide.md
  docs/install/docker/opensuse-leap-docker-install.md
  docs/install/docker/opensuse-tumbleweed-docker-install.md
  docs/install/docker/rhel-docker-install.md
  docs/install/docker/sles-docker-install.md
  docs/install/installing-with-kata-doc-to-script.md
  docs/install/installing-with-kata-manager.md
  docs/install/vexxhost-installation-guide.md
Labels: no-backport-needed, no-forward-port-needed

#817 version: upgrade qemu version to v5.1.0 for arm64
  tools/packaging/qemu/patches/5.1.x/0001-arm-enable-cold-plug-nvdimm-using-DT.patch
  tools/packaging/scripts/configure-hypervisor.sh
  versions.yaml
Labels: release-gating

#832 docs: update architecture.md
  docs/design/arch-images/docker-kata.png
  docs/design/arch-images/kata-oci-create.svg
  docs/design/architecture.md
  docs/install/README.md
  docs/install/centos-installation-guide.md
  docs/install/debian-installation-guide.md
  docs/install/docker/centos-docker-install.md
  docs/install/docker/debian-docker-install.md
  docs/install/docker/fedora-docker-install.md
  docs/install/docker/opensuse-docker-install.md
  docs/install/docker/sles-docker-install.md
  docs/install/docker/ubuntu-docker-install.md
  docs/install/fedora-installation-guide.md
  docs/install/opensuse-installation-guide.md
  docs/install/opensuse-leap-15.1-installation-guide.md
  docs/install/sle-installation-guide.md
  docs/install/ubuntu-installation-guide.md
Labels: no-backport-needed, no-forward-port-needed

#833 rust-agent: Update README
  src/agent/README.md
Labels: no-backport-needed, no-forward-port-needed

#798 docs: update networking description
  docs/design/architecture.md
Labels: forward-port, needs-review, release-gating

#839 ci: add github action to test the snap
  .github/workflows/snap.yaml
Labels: no-backport-needed

#861 clh: Support VFIO device unplug
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmAddDevice.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_add_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: forward-port

#878 snap: specify python version
  snap/snapcraft.yaml
Labels: no-backport-needed, no-forward-port-needed

#795 Remove compilation warnings
  pkg/logging/src/lib.rs
  src/agent/Makefile
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/mod.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/mount.rs
  src/agent/rustjail/src/process.rs
  src/agent/rustjail/src/sync.rs
  src/agent/rustjail/src/validator.rs
  src/agent/src/main.rs
  src/agent/src/mount.rs
  src/agent/src/network.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/trace-forwarder/Makefile
  tools/agent-ctl/Cargo.lock
  tools/agent-ctl/Makefile
  tools/agent-ctl/src/utils.rs
Labels: no-backport-needed, no-forward-port-needed, release-gating

#546 docs: Update docs for enabling agent debug console
  docs/Developer-Guide.md
Labels: release-gating

#876 virtiofs: Disable DAX
  src/runtime/Makefile
Labels: forward-port

#891 agent: set init process non-dumpable
  src/agent/rustjail/src/container.rs
Labels: no-backport-needed, no-forward-port-needed

#884 agent-ctl: include cargo lock updates
  tools/agent-ctl/Cargo.lock
Labels: no-backport-needed, no-forward-port-needed

#886 agent: do not follow link when mounting container proc and sysfs
  src/agent/rustjail/src/mount.rs
Labels: no-backport-needed, no-forward-port-needed

#897 ci: snap: add event filtering
  .github/workflows/snap.yaml
Labels: no-backport-needed

#888 docs: Add crictl example json files
  docs/how-to/README.md
  docs/how-to/data/crictl/busybox/container_config.json
  docs/how-to/data/crictl/busybox/sandbox_config.json
  docs/how-to/data/crictl/redis/redis_client_container_config.json
  docs/how-to/data/crictl/redis/redis_client_sandbox_config.json
  docs/how-to/data/crictl/redis/redis_server_container_config.json
  docs/how-to/data/crictl/redis/redis_server_sandbox_config.json
  docs/how-to/run-kata-with-crictl.md
Labels: no-backport-needed, no-forward-port-needed

#915 agent: use macro to simplify parse_cmdline function in config.rs
  src/agent/src/config.rs
Labels: no-backport-needed, no-forward-port-needed

#910 agent: fix errorneous parsing for guest block size
  src/agent/src/rpc.rs
Labels: release-gating

#923 agent: simplify codes
  src/agent/rustjail/src/cgroups/mod.rs
  src/agent/rustjail/src/configs/mod.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/mount.rs
  src/agent/rustjail/src/process.rs
  src/agent/rustjail/src/specconv.rs
  src/agent/src/mount.rs
  src/agent/src/namespace.rs
  src/agent/src/rpc.rs
Labels: no-backport-needed, no-forward-port-needed

#739 docs: Add containerd install guide
  docs/install/README.md
  docs/install/container-manager/containerd/containerd-install.md
  docs/install/installing-with-kata-doc-to-script.md
  docs/install/installing-with-kata-manager.md
  utils/README.md
  utils/kata-manager.sh
Labels: no-backport-needed, no-forward-port-needed, release-gating

#931 Forward port device conflict fixes from Kata 1 / Go agent
  src/agent/src/device.rs
Labels: forward-port, no-backport-needed

#947 agent: fix panic on malformed device resource in container update
  src/agent/rustjail/src/cgroups/fs/mod.rs
Labels: no-backport-needed, no-forward-port-needed

#964 kata-monitor: use regexp to check if runtime is kata containers
  src/runtime/cli/containerd-shim-kata-v2/main.go
  src/runtime/pkg/kata-monitor/containerd.go
  src/runtime/pkg/kata-monitor/sandbox_cache.go
  src/runtime/pkg/types/types.go
  src/runtime/pkg/types/types_test.go
Labels: no-backport-needed, no-forward-port-needed

#953 rustjail: add length check for uid_mappings in rootless euid mapping
  src/agent/rustjail/src/validator.rs
Labels: no-backport-needed, no-forward-port-needed

#965 agent: fix crashers if API requests empty
  src/agent/src/rpc.rs
Labels: bug, no-backport-needed, no-forward-port-needed, release-gating

#942 agent: Optimize error handling
  src/agent/rustjail/src/capabilities.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/mount.rs
  src/agent/rustjail/src/sync.rs
  src/agent/src/device.rs
  src/agent/src/main.rs
  src/agent/src/mount.rs
  src/agent/src/namespace.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/uevent.rs
Labels: no-backport-needed, no-forward-port-needed

#902 Validate runtime annotations
  src/runtime/Makefile
  src/runtime/cli/config/configuration-acrn.toml.in
  src/runtime/cli/config/configuration-clh.toml.in
  src/runtime/cli/config/configuration-fc.toml.in
  src/runtime/cli/config/configuration-qemu-virtiofs.toml.in
  src/runtime/cli/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/pkg/oci/utils.go
  src/runtime/virtcontainers/pkg/oci/utils_test.go
Labels: forward-port

#970 tools: Make agent-ctl support more APIs
  tools/agent-ctl/Cargo.lock
  tools/agent-ctl/Cargo.toml
  tools/agent-ctl/README.md
  tools/agent-ctl/src/client.rs
  tools/agent-ctl/src/main.rs
  tools/agent-ctl/src/utils.rs
Labels: no-backport-needed, no-forward-port-needed

#945 VirtioFS: backports & default settings to improve performance
  src/runtime/Makefile
  tools/packaging/qemu/patches/5.0.x/0003-virtiofsd-Used-glib-shared-thread-pool.patch
  tools/packaging/qemu/patches/5.1.x/0006-virtiofsd-Used-glib-shared-thread-pool.patch
Labels: needs-backport, no-forward-port-needed

#983 snap: install libseccomp-dev
  snap/snapcraft.yaml
Labels: needs-backport, no-forward-port-needed

#992 # Kata Containers 2.0.0
  VERSION
Labels: no-backport-needed, no-forward-port-needed

#994 Replace @RUNTIME_NAME@ with the target in generated files
  src/runtime/Makefile
Labels: needs-backport, no-forward-port-needed

#976 agent: simplify ttrpc error construction
  src/agent/src/rpc.rs
Labels: no-backport-needed, no-forward-port-needed

#977 agent: clear clippy warnings
  .gitignore
  .travis.yml
  pkg/logging/src/lib.rs
  src/agent/Makefile
  src/agent/oci/src/serialize.rs
  src/agent/protocols/src/lib.rs
  src/agent/rustjail/src/capabilities.rs
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/notifier.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/mount.rs
  src/agent/rustjail/src/sync.rs
  src/agent/rustjail/src/validator.rs
  src/agent/src/config.rs
  src/agent/src/device.rs
  src/agent/src/main.rs
  src/agent/src/metrics.rs
  src/agent/src/mount.rs
  src/agent/src/namespace.rs
  src/agent/src/network.rs
  src/agent/src/random.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/test_utils.rs
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#1007 snap: add GH actions jobs to release the snap package
  .github/workflows/snap-release.yaml
  snap/snapcraft.yaml
Labels: needs-backport, no-forward-port-needed

#1002 runtime: Fix firecracker config
  src/runtime/Makefile
Labels: needs-backport, no-forward-port-needed

#1021 agent: Generate proto files programmatically
  .gitignore
  src/agent/Cargo.lock
  src/agent/protocols/Cargo.toml
  src/agent/protocols/build.rs
  src/agent/protocols/hack/update-generated-proto.sh
  src/agent/protocols/protos/agent.proto
  src/agent/protocols/protos/types.proto
  src/agent/protocols/src/agent.rs
  src/agent/protocols/src/agent_ttrpc.rs
  src/agent/protocols/src/empty.rs
  src/agent/protocols/src/health.rs
  src/agent/protocols/src/health_ttrpc.rs
  src/agent/protocols/src/oci.rs
  src/agent/protocols/src/types.rs
Labels: no-backport-needed, no-forward-port-needed

#1010 Feature/1004 add version for kata monitor
  src/runtime/Makefile
  src/runtime/cli/kata-monitor/main.go
  src/runtime/data/kata-collect-data.sh.in
Labels: no-backport-needed, no-forward-port-needed

#1023 agent: fixes the permissions of PID 1's STDIO
  src/agent/rustjail/src/container.rs
Labels: no-backport-needed, no-forward-port-needed

#1029 clean up agent proto files
  src/agent/Makefile
  src/agent/protocols/protos/gogo/protobuf/gogoproto/gogo.proto
  src/agent/protocols/protos/health.proto
  src/agent/protocols/protos/oci.proto
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.proto
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/health.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/health.proto
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.proto
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.proto
  tools/agent-ctl/Cargo.lock
Labels: no-backport-needed, no-forward-port-needed

#1032 Improve unit test coverage for rustjail/container.rs
  src/agent/rustjail/src/cgroups/mock.rs
  src/agent/rustjail/src/cgroups/mod.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/mount.rs
Labels: no-backport-needed, no-forward-port-needed

#1035 rustjail: fix the issue of create thread failed causing current thread panic
  src/agent/rustjail/src/container.rs
Labels: no-backport-needed, no-forward-port-needed

#1042 agent: Improve unit test coverage for src/sandbox.rs
  src/agent/src/sandbox.rs
Labels: no-backport-needed, no-forward-port-needed
