Repository kata-containers/kata-containers, pull requests merged in 2021-07, with the labels that each got.

#2154 docs: Fix url in virtiofs documentation
  docs/how-to/how-to-use-virtio-fs-with-kata.md
Labels: area/documentation, no-backport-needed, no-forward-port-needed

#2152 agent: update netlink libraries
  src/agent/.gitignore
  src/agent/Cargo.lock
  src/agent/Cargo.toml
Labels: area/agent

#1969 Pass span context from runtime to agent to get a full trace #1968
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/tracer.rs
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/vm.go
Labels: area/agent, area/runtime, no-backport-needed

#2173 agent: enhance tests of execute_hook
  src/agent/rustjail/src/container.rs
Labels: needs-backport

#2084 runtime: refact virtcontainers/pkg/oci
  src/runtime/virtcontainers/pkg/oci/utils.go
  src/runtime/virtcontainers/pkg/oci/utils_test.go
Labels: area/runtime

#2137 runtime: Remove the version check for cloud hypervisor
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
Labels: area/cloud-hypervisor

#2168 runtime: Use CC=gcc on all RPM-based s390x
  src/runtime/arch/s390x-options.mk
Labels: area/architecture/s390x, area/runtime

#2216 ci: static checks: use defined target_branch
  .github/workflows/static-checks.yaml
  ci/lib.sh
Labels: needs-backport

#2257 shim-v2: Be compatible with the old runtime options
  src/runtime/containerd-shim-v2/create.go
Labels: area/runtime, needs-review, no-backport-needed, release-gating

#2235 vsock-exporter: switch to tokio runtime
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/tracer.rs
  src/agent/vsock-exporter/Cargo.toml
  src/agent/vsock-exporter/src/lib.rs
Labels: no-backport-needed, no-forward-port-needed

#2245 agent-ctl: Use a common Makefile style like other components
  tools/agent-ctl/Makefile
Labels: no-backport-needed

#2171 osbuilder: Skip installing golang for building rootfs
  tools/osbuilder/rootfs-builder/centos/Dockerfile.in
  tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile.in
  tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
  tools/osbuilder/rootfs-builder/gentoo/Dockerfile.in
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/suse/Dockerfile.in
  tools/osbuilder/rootfs-builder/template/Dockerfile.template
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/scripts/lib.sh
Labels: area/osbuilder

#2239 static-checks: Add a make target to run static-checks locally
  .github/workflows/static-checks.yaml
  Makefile
Labels: area/ci, area/testing, no-backport-needed

#2202 Add swap support
  src/agent/protocols/protos/agent.proto
  src/agent/src/device.rs
  src/agent/src/rpc.rs
  src/runtime/cli/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/device/config/config.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/pkg/mock/mock.go
  src/runtime/virtcontainers/pkg/oci/utils.go
  src/runtime/virtcontainers/pkg/types/pcipath.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: no-backport-needed, no-forward-port-needed

#2318 docs: Update experimental documentation
  src/runtime/virtcontainers/experimental/README.md
Labels: area/documentation

#2329 docs: Update url for log parser in Developer guide
  docs/Developer-Guide.md
Labels: area/documentation

#2349 how-to-use-virtio-mem-with-kata.md: Remove undefined ${REPORT_DIR}
  docs/how-to/how-to-use-virtio-mem-with-kata.md
Labels: no-backport-needed, no-forward-port-needed

#2155 kata-deploy: Allow build kata-deploy tarball from HEAD
  .github/workflows/gather-artifacts.sh
  .github/workflows/generate-artifact-tarball.sh
  .github/workflows/generate-local-artifact-tarball.sh
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/release.yaml
  Makefile
  ci/install_yq.sh
  snap/snapcraft.yaml
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/release/kata-deploy-binaries.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/firecracker/build-static-firecracker.sh
  tools/packaging/static-build/kernel/Dockerfile
  tools/packaging/static-build/kernel/build.sh
  tools/packaging/static-build/shim-v2/Dockerfile
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/shim-v2/install_go.sh
Labels: area/kata-deploy, release-gating
