Repository kata-containers/kata-containers, pull requests merged in 2021-04, with the labels that each got.

#1612 runtime: use concrete KataAgentConfig instead of interface type
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mock_agent.go
Labels: no-backport-needed, no-forward-port-needed

#1608 runtime: Format auto-generated client code for cloud-hypervisor API
  src/runtime/virtcontainers/pkg/cloud-hypervisor/Makefile
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/configuration.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_balloon_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cmd_line_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_console_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpu_topology.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_node.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_initramfs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_kernel_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_zone_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_numa_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_numa_distance.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pci_device_info.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_rate_limiter_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_restore_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_rng_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_sgx_epc_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_token_bucket.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_add_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_info.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_remove_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize_zone.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_snapshot_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vmm_ping_response.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vsock_config.go
Labels: needs-backport, no-forward-port-needed

#1607 Only keep one VERSION file
  VERSION
  src/agent/VERSION
  src/runtime/VERSION
  tools/osbuilder/VERSION
  tools/packaging/cmd/kata-pkgsync/VERSION
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: needs-backport, no-forward-port-needed

#1623 osbuilder: update dockerfiles to utilize IMAGE_REGISTRY
  tools/osbuilder/image-builder/Dockerfile
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  tools/osbuilder/rootfs-builder/centos/Dockerfile.in
  tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile.in
  tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
  tools/osbuilder/rootfs-builder/gentoo/Dockerfile.in
  tools/osbuilder/rootfs-builder/suse/Dockerfile.in
  tools/osbuilder/rootfs-builder/template/Dockerfile.template
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
Labels: no-backport-needed

#1605 [backport] versions: Update cloud-hypervisor to release v0.14.1
  src/runtime/virtcontainers/pkg/cloud-hypervisor/Makefile
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/configuration.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryZoneConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/RateLimiterConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/TokenBucket.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_balloon_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cmd_line_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_console_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpu_topology.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_node.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_initramfs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_kernel_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_zone_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_numa_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_numa_distance.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pci_device_info.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_rate_limiter_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_restore_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_rng_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_sgx_epc_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_token_bucket.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_add_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_info.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_remove_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize_zone.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_snapshot_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vmm_ping_response.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vsock_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: backport

#1627 agent: Remove many "panic message is not string literal" warnings
  src/agent/rustjail/src/mount.rs
  src/agent/src/config.rs
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
Labels: no-backport-needed, no-forward-port-needed

#1613 Don't do anything in Pipestream::shutdown
  src/agent/rustjail/src/pipestream.rs
  src/agent/rustjail/src/sync_with_async.rs
Labels: no-backport-needed, no-forward-port-needed

#1561 agent: s390x statfs constants
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/mount.rs
Labels: no-backport-needed, no-forward-port-needed

#1635 github: Remove kata-deploy-test action
  .github/workflows/kata-deploy-test.yaml
Labels: needs-backport, no-forward-port-needed

#1625 qemu experimental: Move to latest tree on virtio-fs-dev (qemu 6.0 + DAX patches).
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0001-DAX-libvhost-user-Allow-popping-a-queue-element-with.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0001-virtiofsd-Allow-to-build-it-without-the-tools.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0002-virtiofsd-add-security-guide-document.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0003-DAX-contrib-libvhost-user-Add-virtio-fs-slave-types.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0004-DAX-virtio-Add-shared-memory-capability.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0005-DAX-virtio-fs-Add-cache-BAR.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0006-DAX-virtio-fs-Add-vhost-user-slave-commands-for-mapp.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0007-9p-removing-coroutines-of-9p-to-increase-the-I-O-per.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0007-DAX-virtio-fs-Fill-in-slave-commands-for-mapping.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0008-DAX-virtiofsd-Add-cache-accessor-functions.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0009-DAX-virtiofsd-Add-setup-remove-mappings-fuse-command.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0010-DAX-virtiofsd-Add-setup-remove-mapping-handlers-to-p.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0011-DAX-virtiofsd-Wire-up-passthrough_ll-s-lo_setupmappi.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0012-DAX-virtiofsd-Make-lo_removemapping-work.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0013-DAX-virtiofsd-Make-setupmapping-work-only-with-inode.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0014-DAX-virtiofsd-route-se-down-to-destroy-method.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0015-DAX-virtiofsd-Perform-an-unmap-on-destroy.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0016-DAX-libvhost-user-Allow-popping-a-queue-element-with.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0017-DAX-unmap-virtiofsd-Add-VHOST_USER_SLAVE_FS_IO.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0018-DAX-unmap-virtiofsd-Add-wrappers-for-VHOST_USER_SLAV.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0019-DAX-unmap-virtiofsd-Parse-unmappable-elements.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0020-DAX-unmap-virtiofsd-Route-unmappable-reads.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0021-DAX-unmap-virtiofsd-route-unmappable-write-to-slave-.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0022-DAX-vhost-user-Rework-slave-return-values.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0023-DAX-libvhost-user-Route-slave-message-payload.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0024-DAX-virtiofsd-Rework-fs-cache-request-error-path.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0025-DAX-virtiofsd-make-FUSE_REMOVEMAPPING-support-multip.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0026-DAX-virtiofsd-implement-FUSE_INIT-map_alignment-fiel.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0027-virtiofsd-add-initial-support-for-shared-versions.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0028-virtio-fs-Allow-mapping-of-meta-data-version-table.patch
  tools/packaging/qemu/patches/tag_patches/470dd6bd360782f5137f7e3376af6a44658eb1d3/0029-virtiofsd-Add-printf-checking-to-fuse_log.patch
  tools/packaging/scripts/apply_patches.sh
  tools/packaging/scripts/patch_qemu.sh
  tools/packaging/static-build/qemu/Dockerfile
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#1544 runtime: increase dial timeout
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
Labels: needs-backport, no-forward-port-needed

#1630 docs: update configuration for passing annotations in conatinerd
  docs/how-to/how-to-set-sandbox-config-kata.md
Labels: no-backport-needed, no-forward-port-needed

#1637 ci/openshift-ci: Prepare to build on CentOS 8
  ci/lib.sh
  ci/openshift-ci/images/Dockerfile.buildroot
Labels: area/ci, no-backport-needed, no-forward-port-needed

#1492 Make uevent watching mechanism more flexible
  src/agent/src/device.rs
  src/agent/src/main.rs
  src/agent/src/sandbox.rs
  src/agent/src/uevent.rs
Labels: no-backport-needed, no-forward-port-needed

#1646 github: Fix slash-command-action usage
  .github/workflows/kata-deploy-test.yaml
Labels: needs-backport, no-forward-port-needed

#1400 oci: Update seccomp configuration
  src/agent/oci/src/lib.rs
  src/agent/protocols/protos/oci.proto
  src/agent/rustjail/src/lib.rs
Labels: no-backport-needed, no-forward-port-needed

#1658 stable-2.0 | agent-ctl: update ttrpc version
  tools/agent-ctl/Cargo.lock
  tools/agent-ctl/Cargo.toml
Labels: no-backport-needed, no-forward-port-needed

#1659 stable-2.0 | A bunch of backports fixing documentation
  docs/how-to/how-to-set-sandbox-config-kata.md
  docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
  docs/install/README.md
  docs/install/centos-installation-guide.md
  docs/install/fedora-installation-guide.md
  docs/install/sle-installation-guide.md
  docs/install/snap-installation-guide.md
  docs/install/ubuntu-installation-guide.md
  docs/use-cases/zun_kata.md
Labels: backport

#1649 stable-2.0 | cherry-pick fixes for test-kata-deploy GitHub actions
  .github/workflows/kata-deploy-test.yaml
Labels: backport

#1648 agent: Rework the debug console
  src/agent/src/console.rs
  src/agent/src/main.rs
  src/agent/src/util.rs
Labels: no-backport-needed, no-forward-port-needed

#1652 stable-2.0 | build: Only keep one VERSION file
  tools/packaging/cmd/kata-pkgsync/VERSION
Labels: backport

#1656 tools/agent-ctl: Update Cargo.lock
  tools/agent-ctl/Cargo.lock
Labels: no-backport-needed, no-forward-port-needed

#1604 agent: log the mount point if it is already mounted
  src/agent/src/mount.rs
Labels: area/agent

#1653 stable-2.0 | kata-deploy: Fix test-kata.sh and do some small cleanups / improvements in the kata-deploy script
  tools/packaging/kata-deploy/action/test-kata.sh
  tools/packaging/release/Makefile
  tools/packaging/release/kata-deploy-binaries.sh
  tools/packaging/release/tag_repos.sh
  tools/packaging/release/update-repository-version_test.sh
Labels: backport

#1664 ci: Fix travis for stable-2.0
  ci/lib.sh
Labels: no-backport-needed, no-forward-port-needed

#1642 Refine uevent matching conditions
  src/agent/src/device.rs
  src/agent/src/linux_abi.rs
  src/agent/src/mount.rs
Labels: no-backport-needed, no-forward-port-needed

#1667 release: automatically bump the version of the kata-deploy images
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/release/update-repository-version.sh
Labels: needs-backport, no-forward-port-needed

#1666 kata-deploy: add runtimeclass that includes pod overhead
  tools/packaging/kata-deploy/k8s-1.18/kata-runtimeClasses.yaml
Labels: needs-backport, no-forward-port-needed

#1673 release: Do not git add kata-{deploy,cleanup}.yaml for the tests repo
  tools/packaging/release/update-repository-version.sh
Labels: needs-backport, no-forward-port-needed

#1671 stable-2.x | backports for 2.0.3
  docs/Developer-Guide.md
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/mock.rs
  src/agent/src/sandbox.rs
  tools/packaging/kata-deploy/k8s-1.18/kata-runtimeClasses.yaml
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/release/update-repository-version.sh
Labels: backport

#1681 Update the information about the release process
  docs/Release-Process.md
Labels: needs-backport, no-forward-port-needed

#1684 runtime/tests: Change "moo FAILURE" message
  src/runtime/cli/main_test.go
Labels: no-backport-needed, no-forward-port-needed

#1565 cli: Use genericGetExpectedHostDetails on s390x
  src/runtime/cli/kata-env_s390x_test.go
Labels: needs-backport, no-forward-port-needed

#1705 agent/rustjail: Fix accidental damage from tokio conversion
  src/agent/rustjail/src/cgroups/notifier.rs
Labels: no-backport-needed, no-forward-port-needed, release-gating

#1678 runtime: Disable trace for healthcheck
  src/runtime/virtcontainers/kata_agent.go
Labels: no-backport-needed, no-forward-port-needed, release-gating

#1432 block: Generate PCI path for virtio-blk devices on clh
  src/agent/src/device.rs
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
Labels: no-backport-needed, no-forward-port-needed, release-gating

#1599 Enable virtio-fs on s390x
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_s390x_test.go
Labels: no-backport-needed, no-forward-port-needed, release-gating

#1697 Improve agent shutdown handling
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/mock_hypervisor.go
  src/runtime/virtcontainers/mock_hypervisor_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/utils/utils.go
  src/runtime/virtcontainers/utils/utils_test.go
  src/runtime/virtcontainers/vm.go
Labels: no-backport-needed, no-forward-port-needed, release-gating

#1722 agent: use channel instead of pipe(2) to send exit signal of process
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/process.rs
  src/agent/src/rpc.rs
  src/agent/src/signal.rs
Labels: no-backport-needed, no-forward-port-needed, release-gating

#1701 Assorted clippy fixes for Rust agent
  src/agent/oci/src/lib.rs
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/notifier.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/validator.rs
  src/agent/src/config.rs
  src/agent/src/device.rs
  src/agent/src/namespace.rs
  src/agent/src/netlink.rs
  src/agent/src/uevent.rs
Labels: no-backport-needed, no-forward-port-needed, release-gating

#1718 qemu: Fix assertion failure on shutdown
  tools/packaging/qemu/patches/5.2.x/0009-monitor-Fix-assertion-failure-on-shutdown.patch
Labels: area/QEMU, bug, needs-backport, no-forward-port-needed, release-gating

#1703 fix the issue of missing set fsGroup for EphemeralStorage
  src/agent/src/mount.rs
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
Labels: needs-backport, no-forward-port-needed, release-gating

#1714 runtime: Fix stdout/stderr output from container being truncated
  src/runtime/containerd-shim-v2/stream.go
Labels: needs-backport, no-forward-port-needed, release-gating

#1049 Entropy source annotation
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/runtime/Makefile
  src/runtime/cli/config/configuration-fc.toml.in
  src/runtime/cli/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/pkg/oci/utils.go
  src/runtime/virtcontainers/pkg/oci/utils_test.go
Labels: needs-backport, no-forward-port-needed

#1739 add io.katacontainers.config.hypervisor.virtio_fs_extra_args handling
  src/runtime/virtcontainers/pkg/oci/utils.go
  src/runtime/virtcontainers/pkg/oci/utils_test.go
Labels: needs-backport

#1747 cli: delete not used files
  src/runtime/cli/console.go
  src/runtime/cli/console_test.go
Labels: area/cli, low-priority, no-backport-needed, no-forward-port-needed

#1752 runtime: handle io.katacontainers.config.hypervisor.virtio_fs_extra_args
  src/runtime/virtcontainers/pkg/oci/utils.go
  src/runtime/virtcontainers/pkg/oci/utils_test.go
Labels: backport

#1765 runtime/virtcontainers: Fix typo on qmp error msg
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, no-forward-port-needed

#1756 qemu: kill virtiofsd if failure to start VMM
  src/runtime/virtcontainers/qemu.go
Labels: release-gating

#1762 Makefile: Replace @RUNTIME_NAME@ with the target in generated files
  src/runtime/Makefile
Labels: no-backport-needed, no-forward-port-needed

#1733 docs: Document limitation regarding subpaths
  docs/Limitations.md
Labels: needs-backport, no-forward-port-needed, release-gating

#1773 docs: Document limitation regarding subpaths
  docs/Limitations.md
Labels: backport

#1759 Fix the issue that sandbox size is not right after update
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/sandbox.go
Labels: needs-backport, no-forward-port-needed

#1743 runtime: fix dropped error
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go
Labels: no-backport-needed, no-forward-port-needed, release-gating

#1725 clh: return error if apiSocketPath failed
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
Labels: area/runtime, needs-backport, no-forward-port-needed, release-gating

#1780 versions: Upgrade to cloud-hypervisor v15.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: needs-backport, no-forward-port-needed, release-gating

#1754 virtcontainers: Fix virtio-fs on s390x
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go
  src/runtime/vendor/github.com/kata-containers/govmm/qemu/qmp.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_s390x_test.go
Labels: no-backport-needed, no-forward-port-needed, release-gating

#1766 fix build kernel shell error when setup with `-f`
  tools/packaging/kernel/build-kernel.sh
Labels: needs-backport, no-forward-port-needed, release-gating

#1689 Update dependencies versions
  versions.yaml
Labels: needs-backport, no-forward-port-needed, release-gating

#1782 Update kata-deploy to use CRI-O drop-in files
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: no-backport-needed, no-forward-port-needed, release-gating

#1786 # Kata Containers 2.1.0-rc0
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: no-backport-needed, no-forward-port-needed
