Repository kata-containers/kata-containers, pull requests merged in 2021-08, with the labels that each got.

#2373 Container: Add initConfigResourcesMemory and call it in newContainer
  src/runtime/virtcontainers/container.go
Labels: no-backport-needed, no-forward-port-needed

#2385 osbuilder/dracut: Add missing libraries
  tools/osbuilder/.gitignore
  tools/osbuilder/Makefile
  tools/osbuilder/dracut/add_libs.sh
Labels: release-gating

#2226 stable 2.1 | Backports
  .github/workflows/snap-release.yaml
  .github/workflows/snap.yaml
  .github/workflows/static-checks.yaml
  ci/lib.sh
  src/agent/.gitignore
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/container.rs
  src/runtime/containerd-shim-v2/service.go
  src/runtime/containerd-shim-v2/start.go
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/sandbox.go
  tools/osbuilder/rootfs-builder/centos/Dockerfile.in
  tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile.in
  tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
  tools/osbuilder/rootfs-builder/gentoo/Dockerfile.in
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/suse/Dockerfile.in
  tools/osbuilder/rootfs-builder/template/Dockerfile.template
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/scripts/lib.sh
  versions.yaml
Labels: backport

#2392 docs: Remove kata-proxy and invalid script reference
  docs/how-to/how-to-import-kata-logs-with-fluentd.md
Labels: area/documentation

#1809 CI: Call agent shutdown test
  ci/run.sh
Labels: no-backport-needed, no-forward-port-needed

#2413 stable-2.1 | virtcontainers: fc: properly remove jailed block device
  src/runtime/virtcontainers/fc.go
Labels: backport

#2200 [backport] runtime: Remove the version check for cloud hypervisor
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
Labels: backport

#2424 tracing: Return context in runHooks() span creation
  src/runtime/pkg/katautils/hook.go
Labels: no-backport-needed, no-forward-port-needed

#2425 Cleanup kernel packaging
  tools/packaging/Jenkinsfiles/README.md
  tools/packaging/Jenkinsfiles/release_pipeline/Jenkinsfile
  tools/packaging/Jenkinsfiles/release_pipeline/bump.sh
  tools/packaging/Jenkinsfiles/release_pipeline/git_credential_cache.sh
  tools/packaging/README.md
  tools/packaging/kernel/README.md
  tools/packaging/kernel/build-kernel.sh
  versions.yaml
Labels: no-backport-needed

#2451 workflows: Actually push the release to quay.io
  .github/workflows/release.yaml
Labels: needs-backport

#2530 drop qemu-lite support
  docs/how-to/what-is-vm-templating-and-how-do-I-use-it.md
  src/runtime/cli/main_test.go
  src/runtime/containerd-shim-v2/utils_test.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/create_test.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
Labels: needs-backport

#2528 shimv2: add logging to shimv2 api calls
  src/runtime/containerd-shim-v2/service.go
  src/runtime/virtcontainers/sandbox.go
Labels: area/logging, needs-backport

#2531 backport ci: Temporarily skip agent shutdown test on s390x
  ci/run.sh
Labels: backport

#2513 tracing: Change runtime tracing tags to vars
  src/runtime/pkg/katautils/katatrace/tracing.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed

#2533 runtime: drop qemu-lite support
  docs/how-to/what-is-vm-templating-and-how-do-I-use-it.md
  src/runtime/cli/main_test.go
  src/runtime/containerd-shim-v2/utils_test.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/create_test.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
Labels: no-backport-needed, no-forward-port-needed
