Repository kata-containers/kata-containers, pull requests merged in 2021-02, with the labels that each got.

#1253 shimv2: log a warning and continue on post-stop hook failure
  src/runtime/containerd-shim-v2/delete.go
  src/runtime/containerd-shim-v2/start.go
Labels: needs-backport, needs-review, no-forward-port-needed

#1340 osbuilder: Enforcing LIBC=gnu to rootfs build for ppc64le
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: no-backport-needed, no-forward-port-needed

#1360 qemu: Add security fixes for CVE-2020-35517
  tools/packaging/qemu/patches/5.0.x/0004-virtiofsd-Add-o-allow_direct_io-no_allow_direct_io-o.patch
  tools/packaging/qemu/patches/5.0.x/0005-virtiofsd-extract-lo_do_open-from-lo_open.patch
  tools/packaging/qemu/patches/5.0.x/0006-virtiofsd-optionally-return-inode-pointer-from-lo_do.patch
  tools/packaging/qemu/patches/5.0.x/0007-virtiofsd-prevent-opening-of-special-files-CVE-2020-.patch
  tools/packaging/qemu/patches/5.0.x/0008-virtiofsd-Add-_llseek-to-the-seccomp-whitelist.patch
  tools/packaging/qemu/patches/5.0.x/0009-virtiofsd-Add-restart_syscall-to-the-seccomp-whiteli.patch
  tools/packaging/qemu/patches/5.1.x/0007-virtiofsd-Add-o-allow_direct_io-no_allow_direct_io-o.patch
  tools/packaging/qemu/patches/5.1.x/0008-virtiofsd-extract-lo_do_open-from-lo_open.patch
  tools/packaging/qemu/patches/5.1.x/0009-virtiofsd-optionally-return-inode-pointer-from-lo_do.patch
  tools/packaging/qemu/patches/5.1.x/0010-virtiofsd-prevent-opening-of-special-files-CVE-2020-.patch
  tools/packaging/qemu/patches/5.1.x/0011-virtiofsd-Add-_llseek-to-the-seccomp-whitelist.patch
  tools/packaging/qemu/patches/5.1.x/0012-virtiofsd-Add-restart_syscall-to-the-seccomp-whiteli.patch
Labels: needs-backport, no-forward-port-needed, security

#1334 agent: README update to install protoc for ppc64le
  src/agent/README.md
Labels: no-backport-needed, no-forward-port-needed

#1261 ci: Upgrade to yq 3.4.1
  ci/install_yq.sh
Labels: needs-backport, no-forward-port-needed

#1265 packaging: Fix vmlinux kernel install on s390x
  tools/packaging/kernel/build-kernel.sh
Labels: area/packaging, no-backport-needed, no-forward-port-needed

#1263 Build for glibc on s390x
  src/agent/Makefile
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: area/agent, no-backport-needed, no-forward-port-needed

#1385 docs: Fix the installation directory of virtiofsd
  docs/Developer-Guide.md
Labels: no-backport-needed, no-forward-port-needed

#1364 github: Only run kata-deploy-test on pull-requests
  .github/workflows/kata-deploy-test.yaml
Labels: no-backport-needed, no-forward-port-needed

#1396 agent: Remove bogus check from list_interfaces() unit test
  src/agent/src/netlink.rs
Labels: no-backport-needed, no-forward-port-needed

#1406 runtime: cpuset: when creating container, don't pass cpuset details
  src/runtime/virtcontainers/kata_agent.go
Labels: bug, needs-backport, no-forward-port-needed

#1414 docs: Update licensing strategy to use kata 2.0 repository
  docs/Licensing-strategy.md
Labels: no-backport-needed, no-forward-port-needed

#1407 Agent: OCI hooks return malformed json
  src/agent/oci/src/lib.rs
  src/agent/rustjail/src/container.rs
Labels: needs-backport, no-forward-port-needed

#1428 runtime: Create tracer later in shimv2
  src/runtime/containerd-shim-v2/create.go
  src/runtime/containerd-shim-v2/service.go
Labels: area/runtime, area/tracing, bug, needs-backport, no-forward-port-needed

#1190 Clean up PCI path handling
  .gitignore
  src/agent/protocols/protos/types.proto
  src/agent/src/device.rs
  src/agent/src/linux_abi.rs
  src/agent/src/main.rs
  src/agent/src/mount.rs
  src/agent/src/pci.rs
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/bridgedmacvlan_endpoint.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/device/config/config.go
  src/runtime/virtcontainers/device/drivers/block.go
  src/runtime/virtcontainers/device/drivers/vhost_user_blk.go
  src/runtime/virtcontainers/endpoint.go
  src/runtime/virtcontainers/ipvlan_endpoint.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/macvtap_endpoint.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/persist/api/device.go
  src/runtime/virtcontainers/persist/api/network.go
  src/runtime/virtcontainers/physical_endpoint.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
  src/runtime/virtcontainers/pkg/types/pcipath.go
  src/runtime/virtcontainers/pkg/types/pcipath_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/tap_endpoint.go
  src/runtime/virtcontainers/tuntap_endpoint.go
  src/runtime/virtcontainers/veth_endpoint.go
  src/runtime/virtcontainers/vhostuser_endpoint.go
Labels: forward-port, no-backport-needed

#1423 kata-deploy: Ensure CRI-O uses shimv2 & the "vm" runtime type
  tools/packaging/kata-deploy/README.md
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
  tools/packaging/release/kata-deploy-binaries.sh
Labels: needs-backport, no-forward-port-needed

#1450 Remove "Docker" & "[kata] runtime" references from the release scripts & process documentation
  docs/Release-Process.md
  tools/packaging/release/release-notes.sh
Labels: needs-backport, no-forward-port-needed

#1447 agent: Stop receive message from Receiver if got None
  src/agent/rustjail/src/cgroups/notifier.rs
  src/agent/src/sandbox.rs
Labels: needs-backport

#1434 kata-deploy: stop mentioning qemu-virtiofsd, as the default qemu supports virtiofsd already (plus some cleanups)
  .github/workflows/main.yaml
  .github/workflows/release.yaml
  docs/how-to/how-to-use-virtio-fs-with-kata.md
  src/runtime/.gitignore
  src/runtime/arch/amd64-options.mk
  tools/packaging/artifact-list.sh
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/README.md
  tools/packaging/kata-deploy/action/test-kata.sh
  tools/packaging/kata-deploy/examples/test-deploy-kata-qemu-virtiofs.yaml
  tools/packaging/kata-deploy/k8s-1.13/kata-qemu-virtiofs-runtimeClass.yaml
  tools/packaging/kata-deploy/k8s-1.14/kata-qemu-virtiofs-runtimeClass.yaml
  tools/packaging/release/kata-deploy-binaries.sh
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/static-build/qemu-virtiofs/Dockerfile
  tools/packaging/static-build/qemu-virtiofs/Makefile
  tools/packaging/static-build/qemu-virtiofs/build-static-qemu-virtiofs.sh
Labels: needs-backport, no-forward-port-needed

#1444 rustjail: fix blkio conversion
  src/agent/rustjail/src/cgroups/fs/mod.rs
Labels: no-backport-needed, no-forward-port-needed

#1305 agent: Upgrade tokio to 1.2.0
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/protocols/Cargo.toml
  src/agent/protocols/build.rs
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/cgroups/notifier.rs
  src/agent/rustjail/src/pipestream.rs
  src/agent/rustjail/src/process.rs
  src/agent/src/device.rs
  src/agent/src/main.rs
  src/agent/src/netlink.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/uevent.rs
Labels: no-backport-needed, no-forward-port-needed

#1462 agent: fix clippy for rustc 1.5
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/notifier.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/validator.rs
  src/agent/src/device.rs
  src/agent/src/mount.rs
  src/agent/src/namespace.rs
  src/agent/src/netlink.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/uevent.rs
Labels: no-backport-needed, no-forward-port-needed

#1475 runtime: check if error loading runtime config
  src/runtime/containerd-shim-v2/create.go
Labels: bug, no-backport-needed, no-forward-port-needed
