Repository kata-containers/kata-containers, pull requests merged in 2021-11, with the labels that each got.

#2265 virtcontainers: simplify read-only mount handling
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/mount.go
Labels: needs-rebase

#2935 ci/install_libseccomp: Fix libseccomp build and misc improvement
  ci/install_libseccomp.sh
Labels: no-backport-needed, no-forward-port-needed, area/ci, area/agent

#2945 agent: refactor process IO processing
  src/agent/rustjail/src/process.rs
  src/agent/src/rpc.rs
Labels: no-backport-needed, no-forward-port-needed, area/agent

#2962 osbuilder: build image-builder image from Fedora 34
  tools/osbuilder/image-builder/Dockerfile
Labels: needs-backport, no-forward-port-needed, area/osbuilder

#2943 runtime: Enhancement for Makefile
  src/runtime/Makefile
Labels: no-backport-needed, no-forward-port-needed, area/runtime

#2948 CCv0 | version: Update CCv0 fork of containerd used
  tools/osbuilder/image-builder/Dockerfile
  versions.yaml
Labels: area/confidential-containers

#2620 tracing: Accept multiple dynamic tags
  src/runtime/pkg/katautils/create.go
  src/runtime/pkg/katautils/hook.go
  src/runtime/pkg/katautils/katatrace/tracing.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, no-forward-port-needed

#2971 stable-2.2 | osbuilder: build image-builder image from Fedora 34
  tools/osbuilder/image-builder/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, backport, area/osbuilder

#2975 # Kata Containers 2.2.3
  VERSION
  docs/how-to/how-to-use-kata-containers-with-acrn.md
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/linux_abi.rs
  src/agent/src/sandbox.rs
  src/agent/src/uevent.rs
  src/agent/src/watcher.rs
  src/runtime/pkg/katatestutils/constraints.go
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/factory/template/template_test.go
  src/runtime/virtcontainers/hypervisor.go
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/static-build/kernel/Dockerfile
  tools/packaging/static-build/qemu.blacklist
  tools/packaging/static-build/qemu/Dockerfile
Labels: no-backport-needed, no-forward-port-needed

#2976 # Kata Containers 2.3.0-rc0
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: no-backport-needed, no-forward-port-needed

#2992 kernel: add VFIO kernel dependencies for ppc64le
  tools/packaging/kernel/configs/fragments/powerpc/vfio.conf
Labels: needs-backport, no-forward-port-needed

#3000 runtime: Revert "runtime: use containerd package instead of cri-containerd"
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/vendor/github.com/containerd/containerd/pkg/cri/annotations/annotations.go
  src/runtime/vendor/github.com/containerd/cri-containerd/LICENSE
  src/runtime/vendor/github.com/containerd/cri-containerd/pkg/annotations/annotations.go
  src/runtime/vendor/github.com/containerd/cri-containerd/pkg/api/runtimeoptions/v1/api.pb.go
  src/runtime/vendor/github.com/containerd/cri-containerd/pkg/api/runtimeoptions/v1/api.proto
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/pkg/oci/utils.go
Labels: needs-backport, no-forward-port-needed

#2908 osbuilder: Build attestation-agent and friends
  docs/how-to/ccv0.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/scripts/lib.sh
  versions.yaml
Labels: area/confidential-containers

#3007 agent: check environment variables if empty or invalid
  src/agent/rustjail/src/container.rs
Labels: bug, needs-backport, no-forward-port-needed, area/agent

#2997 virtcontainers: Lint protection types
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arm64_test.go
Labels: enhancement, no-backport-needed, no-forward-port-needed, area/runtime

#3015 release: Use ${GOPATH}/bin/yq for upload-libseccomp-tarball action
  .github/workflows/release.yaml
Labels: needs-backport, no-forward-port-needed

#3017 versions: bump golang to 1.17.x
  .github/workflows/static-checks.yaml
  versions.yaml
Labels: needs-backport, no-forward-port-needed

#3030 runtime: delete not used codes
  src/runtime/virtcontainers/pkg/oci/utils.go
  src/runtime/virtcontainers/pkg/oci/utils_test.go
Labels: enhancement, cleanup, no-backport-needed, no-forward-port-needed, area/runtime

#3034 workflows: Remove non-used main.yaml
  .github/workflows/main.yaml
  docs/Release-Process.md
Labels: no-backport-needed, no-forward-port-needed

#3032 runtime: merge virtcontainers/pkg/types into virtcontainers/types
  src/runtime/pkg/containerd-shim-v2/errors.go
  src/runtime/pkg/containerd-shim-v2/errors_test.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/api.go
  src/runtime/virtcontainers/bridgedmacvlan_endpoint.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/device/config/config.go
  src/runtime/virtcontainers/endpoint.go
  src/runtime/virtcontainers/ipvlan_endpoint.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/macvtap_endpoint.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/persist/api/device.go
  src/runtime/virtcontainers/persist/api/network.go
  src/runtime/virtcontainers/physical_endpoint.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/tap_endpoint.go
  src/runtime/virtcontainers/tuntap_endpoint.go
  src/runtime/virtcontainers/types/errors.go
  src/runtime/virtcontainers/types/pcipath.go
  src/runtime/virtcontainers/types/pcipath_test.go
  src/runtime/virtcontainers/veth_endpoint.go
  src/runtime/virtcontainers/vhostuser_endpoint.go
Labels: enhancement, refactor, no-backport-needed, no-forward-port-needed

#3039 stable-2.3:remove non used actions
  .github/workflows/main.yaml
  docs/Release-Process.md
Labels: backport

#3040 CCv0|agent-ctl: fix compile error
  tools/agent-ctl/src/client.rs
Labels: area/confidential-containers

#3046 Update CRI-O documentation
  docs/how-to/run-kata-with-k8s.md
Labels: no-backport-needed, no-forward-port-needed, area/CRI-O, area/documentation

#3051 macvlan: drop bridged part of name
  src/runtime/virtcontainers/endpoint.go
  src/runtime/virtcontainers/endpoint_test.go
  src/runtime/virtcontainers/macvlan_endpoint.go
  src/runtime/virtcontainers/macvlan_endpoint_test.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/network.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
Labels: no-backport-needed, no-forward-port-needed

#2973 Remove cruft, do some simple non-functional cleanup in the runtime
  src/runtime/cmd/kata-runtime/factory.go
  src/runtime/cmd/kata-runtime/kata-check.go
  src/runtime/cmd/kata-runtime/kata-check_generic_test.go
  src/runtime/cmd/kata-runtime/kata-env.go
  src/runtime/cmd/kata-runtime/kata-env_generic_test.go
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/cmd/kata-runtime/main.go
  src/runtime/cmd/kata-runtime/main_test.go
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/containerd-shim-v2/service.go
  src/runtime/pkg/containerd-shim-v2/utils.go
  src/runtime/pkg/containerd-shim-v2/utils_test.go
  src/runtime/pkg/containerd-shim-v2/wait.go
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/katautils/create.go
  src/runtime/pkg/katautils/create_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/pkg/oci/utils_test_config.go
  src/runtime/pkg/uuid/uuid.go
  src/runtime/pkg/uuid/uuid_test.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/pkg/nsenter/nsenter.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/tap_endpoint.go
  src/runtime/virtcontainers/utils/utils.go
  src/runtime/virtcontainers/utils/utils_linux_generic.go
  src/runtime/virtcontainers/utils/utils_test.go
  src/runtime/virtcontainers/vm.go
Labels: no-backport-needed, no-forward-port-needed

#3072 stable-2.3: virtcontainers: fix failing template test on ppc64le
  src/runtime/virtcontainers/factory/template/template_test.go
Labels: backport

#3070 stable-2.3: disable libudev when building static QEMU
  tools/packaging/scripts/configure-hypervisor.sh
Labels: backport

#3075 runtime: Update containerd to 1.5.8
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/github.com/Microsoft/hcsshim/go.mod
  src/runtime/vendor/github.com/Microsoft/hcsshim/go.sum
  src/runtime/vendor/github.com/containerd/containerd/version/version.go
  src/runtime/vendor/github.com/containerd/ttrpc/.gitignore
  src/runtime/vendor/github.com/containerd/ttrpc/.travis.yml
  src/runtime/vendor/github.com/containerd/ttrpc/README.md
  src/runtime/vendor/github.com/containerd/ttrpc/channel.go
  src/runtime/vendor/github.com/containerd/ttrpc/client.go
  src/runtime/vendor/github.com/containerd/ttrpc/codec.go
  src/runtime/vendor/github.com/containerd/ttrpc/config.go
  src/runtime/vendor/github.com/containerd/ttrpc/go.mod
  src/runtime/vendor/github.com/containerd/ttrpc/go.sum
  src/runtime/vendor/github.com/containerd/ttrpc/server.go
  src/runtime/vendor/github.com/containerd/ttrpc/services.go
  src/runtime/vendor/github.com/containerd/ttrpc/unixcreds_linux.go
  src/runtime/vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  src/runtime/vendor/google.golang.org/protobuf/internal/encoding/text/encode.go
  src/runtime/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  src/runtime/vendor/google.golang.org/protobuf/internal/version/version.go
  src/runtime/vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  src/runtime/vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  src/runtime/vendor/modules.txt
Labels: needs-backport, no-forward-port-needed

#3064 agent: fix the issue of missing create a new session for container
  src/agent/rustjail/src/container.rs
Labels: backport

#3076 [stable] runtime: Update containerd to 1.5.8
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/github.com/Microsoft/hcsshim/go.mod
  src/runtime/vendor/github.com/Microsoft/hcsshim/go.sum
  src/runtime/vendor/github.com/containerd/containerd/version/version.go
  src/runtime/vendor/github.com/containerd/ttrpc/.gitignore
  src/runtime/vendor/github.com/containerd/ttrpc/.travis.yml
  src/runtime/vendor/github.com/containerd/ttrpc/README.md
  src/runtime/vendor/github.com/containerd/ttrpc/channel.go
  src/runtime/vendor/github.com/containerd/ttrpc/client.go
  src/runtime/vendor/github.com/containerd/ttrpc/codec.go
  src/runtime/vendor/github.com/containerd/ttrpc/config.go
  src/runtime/vendor/github.com/containerd/ttrpc/go.mod
  src/runtime/vendor/github.com/containerd/ttrpc/go.sum
  src/runtime/vendor/github.com/containerd/ttrpc/server.go
  src/runtime/vendor/github.com/containerd/ttrpc/services.go
  src/runtime/vendor/github.com/containerd/ttrpc/unixcreds_linux.go
  src/runtime/vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  src/runtime/vendor/google.golang.org/protobuf/internal/encoding/text/encode.go
  src/runtime/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  src/runtime/vendor/google.golang.org/protobuf/internal/version/version.go
  src/runtime/vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  src/runtime/vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  src/runtime/vendor/modules.txt
Labels: no-forward-port-needed, backport

#3055 docs: update using-SPDK-vhostuser-and-kata.md
  docs/use-cases/using-SPDK-vhostuser-and-kata.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3071 kata-deploy: Ensure we test HEAD with `/test_kata_deploy`
  .github/workflows/kata-deploy-test.yaml
Labels: needs-backport, no-forward-port-needed, area/kata-deploy

#3098 docs: make kata-deploy more visible
  docs/install/README.md
  tools/packaging/kata-deploy/README.md
Labels: no-backport-needed, no-forward-port-needed

#2911 CCv0: Attestation Agent Integration
  src/agent/src/config.rs
  src/agent/src/image_rpc.rs
Labels: area/agent, area/confidential-containers

#3113 runtime: delete netmon
  src/runtime/.gitignore
  src/runtime/Makefile
  src/runtime/cmd/kata-runtime/kata-env.go
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/cmd/netmon/netmon.go
  src/runtime/cmd/netmon/netmon_test.go
  src/runtime/config/configuration-acrn.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/netmon.go
  src/runtime/virtcontainers/netmon_test.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/network.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: cleanup, no-backport-needed, no-forward-port-needed, area/runtime

#3089 tools: Automatically revert kata-deploy changes
  tools/packaging/release/update-repository-version.sh
Labels: no-backport-needed, no-forward-port-needed, area/kata-deploy

#3100 docs: Add a code PR advice document
  docs/README.md
  docs/Unit-Test-Advice.md
  docs/code-pr-advice.md
Labels: no-backport-needed, no-forward-port-needed

#3092 agent: clear cargo test warnings
  src/agent/rustjail/src/mount.rs
Labels: no-backport-needed, no-forward-port-needed, area/agent

#3028 Hypervisor cleanup, refactoring
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/pkg/hypervisors/hypervisor_state.go
  src/runtime/pkg/katautils/create.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/acrn_test.go
  src/runtime/virtcontainers/api.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mock_hypervisor.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/sandbox.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_test.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/virtcontainers_test.go
  src/runtime/virtcontainers/virtiofsd.go
Labels: no-backport-needed, no-forward-port-needed

#3118 agent: refactor find_process function and add test cases
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
Labels: refactor, no-backport-needed, no-forward-port-needed, area/agent

#3136 tools/osbuilder: build QAT kernel in fedora 34
  tools/osbuilder/dockerfiles/QAT/Dockerfile
Labels: no-backport-needed, no-forward-port-needed

#3129 agent: use temp directory for test containers
  src/agent/src/sandbox.rs
Labels: enhancement, no-backport-needed, no-forward-port-needed, area/agent

#3134 workflows: only allow org members to run `/test_kata_deploy`
  .github/workflows/kata-deploy-test.yaml
Labels: needs-backport, no-forward-port-needed

#3139 osbuilder: add coreutils to guest rootfs
  tools/osbuilder/rootfs-builder/centos/config.sh
  tools/osbuilder/rootfs-builder/debian/config.sh
  tools/osbuilder/rootfs-builder/fedora/config.sh
  tools/osbuilder/rootfs-builder/gentoo/config.sh
  tools/osbuilder/rootfs-builder/suse/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
Labels: needs-backport, no-forward-port-needed

#3142 stable-2.3 | tools/osbuilder: build QAT kernel in fedora 34
  tools/osbuilder/dockerfiles/QAT/Dockerfile
Labels: no-forward-port-needed, backport

#3141 stable-2.3 | backport kata-deploy fixes / improvements
  .github/workflows/kata-deploy-test.yaml
Labels: no-forward-port-needed, backport

#3147 osbuilder: fix missing cpio package when building rootfs-initrd image
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/initrd-builder/initrd_builder.sh
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Labels: needs-backport, no-forward-port-needed

#3148 stable-2.3 | osbuilder: fix missing cpio package when building rootfs-initrd image
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/initrd-builder/initrd_builder.sh
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Labels: no-forward-port-needed, backport

#3149 # Kata Containers 2.4.0-alpha0
  VERSION
Labels: no-backport-needed, no-forward-port-needed
