Repository kata-containers/kata-containers, pull requests merged in 2021-12, with the labels that each got.

#3154 osbuilder: Remove debian as a rootfs
  docs/use-cases/using-Intel-QAT-and-kata.md
  src/runtime/pkg/katatestutils/constraints_test.go
  tools/osbuilder/dockerfiles/QAT/Dockerfile
  tools/osbuilder/dockerfiles/QAT/README.md
  tools/osbuilder/dockerfiles/QAT/run.sh
  tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile.in
  tools/osbuilder/rootfs-builder/debian/config.sh
  tools/osbuilder/rootfs-builder/debian/rootfs_lib.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/static-build/scripts/kata-configure-docker.sh
  utils/kata-manager.sh
Labels: no-backport-needed, no-forward-port-needed, area/osbuilder

#3125 Update rust crate versions
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/mount.rs
  src/agent/rustjail/src/pipestream.rs
  src/agent/rustjail/src/sync.rs
  src/agent/rustjail/src/validator.rs
  src/agent/src/console.rs
  src/agent/src/device.rs
  src/agent/src/netlink.rs
  src/agent/src/rpc.rs
  src/agent/src/uevent.rs
  src/agent/vsock-exporter/Cargo.toml
  src/trace-forwarder/Cargo.lock
  tools/agent-ctl/Cargo.lock
Labels: security, area/security

#3164 runtime: Update comments for virtcontainers to use kata 2.0
  src/runtime/config/configuration-acrn.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
Labels: no-backport-needed, no-forward-port-needed

#3152 agent: copy empty directories for watchable-bind mounts
  src/agent/rustjail/src/mount.rs
  src/agent/src/watcher.rs
Labels: bug, needs-backport, no-forward-port-needed, area/agent

#3166 runtime: Enable FUSE_DAX kernel config for DAX
  tools/packaging/kernel/configs/fragments/common/dax.conf
  tools/packaging/kernel/kata_config_version
Labels: needs-backport, no-forward-port-needed

#3175 docs: Update limitation document regarding docker swarm
  docs/Limitations.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3179 Upgrade to Cloud Hypervisor v20.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpuAffinity.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DeviceConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PmemConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VsockConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpu_affinity.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vsock_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: needs-backport, no-forward-port-needed

#3181 Cleanup some unused variables, definitions
  src/agent/rustjail/src/mount.rs
  src/agent/src/network.rs
Labels: no-backport-needed, no-forward-port-needed

#3177 runtime: enable FUSE_DAX kernel config for DAX
  tools/packaging/kernel/configs/fragments/common/dax.conf
  tools/packaging/kernel/kata_config_version
Labels: no-backport-needed, backport

#3151 CCv0|osbuilder: integrate AA's EAA KBC into ubuntu rootfs image
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
  tools/osbuilder/scripts/lib.sh
Labels: area/confidential-containers

#3183 runtime: enable vhost-net for rootless hypervisor
  src/runtime/virtcontainers/network.go
Labels: needs-backport, no-forward-port-needed, area/runtime

#3173 agent: user container ID as watchable storage key for hashmap
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
Labels: needs-backport, no-forward-port-needed, area/agent, area/debug

#3171 Stop skopeo being installed by default
  docs/how-to/ccv0.sh
  docs/how-to/how-to-build-and-test-ccv0.md
  tools/osbuilder/rootfs-builder/README.md
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/scripts/lib.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
Labels: area/confidential-containers

#3200 virtcontainers: clh: Upgrade to openapi-generator v5.3.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/Makefile
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/VERSION
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/git_push.sh
Labels: needs-backport, no-forward-port-needed

#3197 packaging: Fix missing commit message in building kata-runtime
  tools/packaging/static-build/shim-v2/Dockerfile
Labels: needs-backport, no-forward-port-needed

#3213 versions: Use Ubuntu initrd for non-musl archs
  versions.yaml
Labels: needs-backport, no-forward-port-needed, area/osbuilder, area/s390x, area/ppc64le

#3211 snap: read initrd and image distros from version.yaml
  snap/snapcraft.yaml
Labels: no-backport-needed, no-forward-port-needed

#3220 runtime: only call stopVirtiofsd when shared_fs is virtio-fs
  src/runtime/virtcontainers/qemu.go
Labels: enhancement, needs-backport, no-forward-port-needed, area/runtime

#3215 stable-2.3 | Upgrade to Cloud Hypervisor v20.0 and Openapi-generator v5.3.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/Makefile
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/VERSION
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpuAffinity.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DeviceConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PmemConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VsockConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/git_push.sh
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpu_affinity.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vsock_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: backport

#3218 runtime: correct span name for stopSandbox function
  src/runtime/virtcontainers/kata_agent.go
Labels: enhancement, no-backport-needed, no-forward-port-needed, area/runtime

#3224 Backport versions: Use Ubuntu initrd for non-musl archs
  versions.yaml
Labels: no-forward-port-needed, backport, area/osbuilder, area/s390x, area/ppc64le

#3241 docs: fix check-markdown test
  docs/code-pr-advice.md
Labels: no-backport-needed, no-forward-port-needed

#3226 runtime/template: Handling new attributes for hypervisor config
  src/runtime/virtcontainers/factory/factory.go
  src/runtime/virtcontainers/factory/template/template.go
Labels: needs-backport, no-forward-port-needed, area/runtime

#3222 osbuilder: Revert to using apk.static for Alpine
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  tools/osbuilder/rootfs-builder/alpine/config.sh
  tools/osbuilder/rootfs-builder/alpine/rootfs_lib.sh
  versions.yaml
Labels: needs-backport, no-forward-port-needed, area/osbuilder

#3238 osbuilder: be runtime consistent with podman build
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: needs-backport, no-forward-port-needed

#3235 image_build: add help info for '-f' option and 'BLOCK_SIZE' env.
  tools/osbuilder/image-builder/image_builder.sh
Labels: no-backport-needed, no-forward-port-needed

#3247 Backport osbuilder: Revert to using apk.static for Alpine
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  tools/osbuilder/rootfs-builder/alpine/config.sh
  tools/osbuilder/rootfs-builder/alpine/rootfs_lib.sh
  versions.yaml
Labels: no-forward-port-needed, backport, area/osbuilder

#3263 Upgrade to Cloud Hypervisor v20.1
  versions.yaml
Labels: needs-backport, no-forward-port-needed

#3257 osbuilder: show usage if no options/arguments specified
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: enhancement, no-backport-needed, no-forward-port-needed, area/osbuilder

#3244 src: reorg source code directory
  Makefile
  README.md
  docs/design/proposals/tracing-proposals.md
  docs/tracing.md
  src/agent/Cargo.toml
  src/agent/Makefile
  src/agent/README.md
  src/libs/logging/Cargo.lock
  src/libs/logging/Cargo.toml
  src/libs/logging/Makefile
  src/libs/logging/src/lib.rs
  src/tools/agent-ctl/.gitignore
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Cargo.toml
  src/tools/agent-ctl/Makefile
  src/tools/agent-ctl/README.md
  src/tools/agent-ctl/src/client.rs
  src/tools/agent-ctl/src/main.rs
  src/tools/agent-ctl/src/rpc.rs
  src/tools/agent-ctl/src/types.rs
  src/tools/agent-ctl/src/utils.rs
  src/tools/trace-forwarder/.gitignore
  src/tools/trace-forwarder/Cargo.lock
  src/tools/trace-forwarder/Cargo.toml
  src/tools/trace-forwarder/Makefile
  src/tools/trace-forwarder/README.md
  src/tools/trace-forwarder/src/handler.rs
  src/tools/trace-forwarder/src/main.rs
  src/tools/trace-forwarder/src/server.rs
  src/tools/trace-forwarder/src/tracer.rs
  src/tools/trace-forwarder/src/utils.rs
  utils.mk
Labels: no-backport-needed, no-forward-port-needed

#3258 kata-deploy: Deal with empty containerd conf file
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: needs-backport, no-forward-port-needed, area/containerd, area/kata-deploy

#3260 CCv0: Merge main into CCv0 branch
  docs/code-pr-advice.md
  snap/snapcraft.yaml
  src/runtime/virtcontainers/factory/factory.go
  src/runtime/virtcontainers/factory/template/template.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/qemu.go
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  tools/osbuilder/rootfs-builder/alpine/config.sh
  tools/osbuilder/rootfs-builder/alpine/rootfs_lib.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  versions.yaml
Labels: area/confidential-containers

#3261 agent: Add config file option to cli
  src/agent/src/config.rs
  src/agent/src/main.rs
Labels: no-backport-needed, no-forward-port-needed

#3286 docs: Update code PR advice document
  docs/code-pr-advice.md
Labels: no-backport-needed, no-forward-port-needed, force-skip-ci

#3290 tracing: Add span name to logging error
  src/runtime/pkg/katautils/katatrace/tracing.go
Labels: no-backport-needed, no-forward-port-needed

#3299 docs: Update the stable branch strategy
  docs/Stable-Branch-Strategy.md
Labels: no-backport-needed, no-forward-port-needed, community, area/documentation

#3287 Split architecture doc into separate files
  docs/README.md
  docs/Upgrading.md
  docs/design/README.md
  docs/design/architecture.md
  docs/design/architecture/README.md
  docs/design/architecture/background.md
  docs/design/architecture/example-command.md
  docs/design/architecture/guest-assets.md
  docs/design/architecture/history.md
  docs/design/architecture/kubernetes.md
  docs/design/architecture/networking.md
  docs/design/architecture/storage.md
  docs/design/virtualization.md
  snap/README.md
  src/agent/README.md
  src/runtime/README.md
  src/runtime/virtcontainers/README.md
Labels: no-backport-needed, no-forward-port-needed

#3315 CI: Switch to a mirror as gnu.org is down
  ci/install_libseccomp.sh
Labels: no-backport-needed, no-forward-port-needed, force-skip-ci

#3302 packaging/qemu: partial git clone
  tools/packaging/static-build/qemu/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, area/QEMU, area/packaging

#3318 docs: Clarify where to run agent API generation commands
  src/agent/README.md
Labels: force-skip-ci

#3199 github: Add workflow for deploying a CCv0 demo
  .github/workflows/deploy-ccv0-demo.yaml
  docs/how-to/data/confidential-agent-config.toml.in
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: area/github, area/confidential-containers

#3324 osbuilder: Add protoc to the alpine container
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
Labels: needs-backport, no-forward-port-needed

#3288 qemu: Disable libudev for QEMU 5.2 and newer
  tools/packaging/scripts/configure-hypervisor.sh
Labels: enhancement, no-backport-needed, no-forward-port-needed, area/QEMU

#3294 osbuilder: avoid to copy versions.txt which already deprecated
  tools/osbuilder/Makefile
Labels: needs-backport, no-forward-port-needed

#3271 kata-manager: Retrieve static tarball
  utils/kata-manager.sh
Labels: needs-backport, no-forward-port-needed, area/packaging

#3297 security: Update rust crate versions
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/oci/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/src/metrics.rs
  src/agent/src/rpc.rs
  src/libs/logging/Cargo.lock
  src/libs/logging/Cargo.toml
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Cargo.toml
  src/tools/agent-ctl/src/utils.rs
  src/tools/trace-forwarder/Cargo.lock
  src/tools/trace-forwarder/Cargo.toml
Labels: security, needs-backport, no-forward-port-needed, area/security

#3339 docs: Fix kernel configs README spelling errors
  tools/packaging/kernel/configs/README.md
Labels: needs-backport, no-forward-port-needed, area/documentation

#3337 docs: Fix outdated links
  docs/design/host-cgroups.md
  src/runtime/virtcontainers/README.md
Labels: needs-backport, no-forward-port-needed, area/documentation

#3335 docs: Fix outdated links
  docs/design/host-cgroups.md
  docs/how-to/run-kata-with-k8s.md
  docs/tracing.md
  src/runtime/virtcontainers/README.md
Labels: no-forward-port-needed, backport, area/documentation

#2958 agent: Ignore unknown seccomp system calls
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/seccomp.rs
Labels: no-backport-needed, no-forward-port-needed

#3137 docs: add how-to on DinD in Kata
  docs/how-to/README.md
  docs/how-to/how-to-run-docker-with-kata.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3347 stable-2.3 | docs: Fix kernel configs README spelling errors
  tools/packaging/kernel/configs/README.md
Labels: no-forward-port-needed, backport, area/documentation

#2481 Makefile: update `make go-test` call
  ci/go-test.sh
  src/runtime/Makefile
  src/runtime/pkg/containerd-shim-v2/stream.go
Labels: needs-rebase

#3346 CCv0 | actions: Push demo image to runtime-payload
  .github/workflows/deploy-ccv0-demo.yaml
Labels: area/github, area/confidential-containers

#3109 Delint dockerfiles
  ci/openshift-ci/images/Dockerfile.buildroot
  tools/osbuilder/dockerfiles/QAT/Dockerfile
  tools/osbuilder/dracut/Dockerfile.in
  tools/osbuilder/image-builder/Dockerfile
  tools/osbuilder/rootfs-builder/centos/Dockerfile.in
  tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
  tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
  tools/osbuilder/rootfs-builder/gentoo/Dockerfile.in
  tools/osbuilder/rootfs-builder/suse/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/action/Dockerfile
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-monitor/Dockerfile
  tools/packaging/static-build/kernel/Dockerfile
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/shim-v2/Dockerfile
  tools/packaging/tests/Dockerfile/FedoraDockerfile.in
Labels: no-backport-needed, no-forward-port-needed
