Repository kata-containers/kata-containers, pull requests merged in 2021-01, with the labels that each got.

#1207 Fix error reporting in listInterfaces() and listRoutes()
  src/runtime/virtcontainers/kata_agent.go
Labels: forward-port

#1202 agent: Simplify .or_else() to .or()
  src/agent/src/config.rs
Labels: no-backport-needed, no-forward-port-needed

#1169 packaging/qemu: Build and package completely inside the container
  tools/packaging/static-build/qemu-virtiofs/Dockerfile
  tools/packaging/static-build/qemu-virtiofs/build-static-qemu-virtiofs.sh
  tools/packaging/static-build/qemu.blacklist
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/qemu/build-static-qemu.sh
  tools/packaging/static-build/scripts/qemu-build-post.sh
Labels: no-backport-needed, no-forward-port-needed

#1230 rustjail: fix the issue of bind mount /dev
  src/agent/rustjail/src/mount.rs
Labels: no-backport-needed, no-forward-port-needed

#1234 rustjail: fix the issue of sync read
  src/agent/rustjail/src/sync.rs
Labels: no-backport-needed, no-forward-port-needed

#1229 rustjail: allow network sysctls
  src/agent/rustjail/src/validator.rs
Labels: area/agent, needs-backport, no-forward-port-needed

#1221 Agent: return error on trying to persist a pid namespace and minor improvements
  src/agent/src/namespace.rs
  src/agent/src/sandbox.rs
Labels: area/agent, no-backport-needed, no-forward-port-needed

#1217 shimv2: Avoid double removing of container from sandbox
  src/runtime/containerd-shim-v2/delete.go
Labels: area/runtime, needs-backport, no-forward-port-needed

#1176 [backport] snap: fix snap release channel
  .github/workflows/snap-release.yaml
Labels: no-backport-needed, no-forward-port-needed

#1208 github: Add github actions
  .github/workflows/static-checks.yaml
  .travis.yml
  src/agent/VERSION
  src/runtime/VERSION
  tools/osbuilder/VERSION
Labels: no-backport-needed, no-forward-port-needed

#1196 rootfs: Don't fallthrough in the docker_extra_args() switch
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: needs-backport, no-forward-port-needed

#1268 Fix snap CI
  snap/snapcraft.yaml
Labels: needs-backport

#1271 [backport] snap: tag yq version
  snap/snapcraft.yaml
Labels: no-backport-needed, no-forward-port-needed

#1270 # Kata Containers 2.0.1
  VERSION
Labels: no-backport-needed, no-forward-port-needed

#1269 # Kata Containers 2.1-alpha0
  VERSION
Labels: no-backport-needed, no-forward-port-needed

#904 shimv2: Add tracing to shimv2
  src/runtime/containerd-shim-v2/service.go
Labels: forward-port, needs-review

#1279 actions: fixup release/main workflow
  .github/workflows/main.yaml
  .github/workflows/release.yaml
Labels: needs-backport

#1292 rustjail: fix the issue of missing destroy contaienr cgroups
  src/agent/rustjail/src/container.rs
Labels: no-backport-needed, no-forward-port-needed

#1290 agent: implement NVDIMM/PMEM block driver
  src/agent/src/device.rs
  src/agent/src/linux_abi.rs
  src/agent/src/mount.rs
  src/agent/src/uevent.rs
Labels: no-backport-needed, no-forward-port-needed

#1296 github: Update ubuntu version to 20.04
  .github/workflows/static-checks.yaml
Labels: no-backport-needed, no-forward-port-needed

#1301 agent: Add underscore for constants
  src/agent/src/device.rs
  src/agent/src/mount.rs
  src/agent/src/sandbox.rs
Labels: no-backport-needed, no-forward-port-needed

#1297 Migrate to rtnetlink
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/netlink/Cargo.toml
  src/agent/netlink/src/agent_handler.rs
  src/agent/netlink/src/lib.rs
  src/agent/netlink/src/parser.rs
  src/agent/src/main.rs
  src/agent/src/netlink.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
Labels: no-backport-needed, no-forward-port-needed

#1304 snap: Don't release Kata Alpha/RC in snap store
  .github/workflows/snap-release.yaml
Labels: needs-backport, no-forward-port-needed

#1311 branch: change 2.0-dev to main
  .github/workflows/kata-deploy-test.yaml
  README.md
  ci/lib.sh
  docs/how-to/how-to-set-prometheus-in-k8s.md
  docs/install/snap-installation-guide.md
  tools/packaging/kernel/README.md
  tools/packaging/release/tag_repos_test.sh
  tools/packaging/scripts/gen_versions_txt.sh
  utils/README.md
Labels: no-backport-needed, no-forward-port-needed

#1322 osbuilder: miscelaneous fixes/improvements
  tools/osbuilder/README.md
  tools/osbuilder/image-builder/Dockerfile
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/rootfs-builder/README.md
  tools/osbuilder/rootfs-builder/centos/Dockerfile.in
  tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: no-backport-needed, no-forward-port-needed

#1306 osbuilder: remove traces of cmake
  tools/osbuilder/dracut/Dockerfile.in
  tools/osbuilder/rootfs-builder/centos/Dockerfile.in
  tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile.in
  tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/suse/install-packages.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/scripts/lib.sh
  tools/osbuilder/tests/test_images.sh
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#1320 rustjail: fix the issue of container's cgroup root path
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/src/cgroups/fs/mod.rs
Labels: no-backport-needed, no-forward-port-needed

#1338 kernel: Updates to kernel config for ppc64le
  tools/packaging/kernel/configs/powerpc_kata_kvm_5.4.x
Labels: no-backport-needed, no-forward-port-needed
