Repository kata-containers/kata-containers, pull requests merged in 2021-05, with the labels that each got.

#1785 [backport] versions: Upgrade to cloud-hypervisor v15.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: backport

#1751 runtime: fix some comments
  src/runtime/containerd-shim-v2/start.go
Labels: area/runtime, no-backport-needed, no-forward-port-needed

#1805 runtime: use s.ctx instead ctx for checking cancellation
  src/runtime/containerd-shim-v2/wait.go
Labels: area/runtime, needs-backport, no-forward-port-needed

#1777 ci/install_yq.sh: install_yq: Check version before return
  ci/install_yq.sh
Labels: no-backport-needed, no-forward-port-needed

#1778 Set fixed NOFILE limit value for kata-agent
  src/agent/kata-agent.service.in
Labels: needs-backport, no-forward-port-needed

#1800 Fix issue of virtio-mem
  src/runtime/virtcontainers/qemu.go
Labels: needs-backport, no-forward-port-needed

#1745 docs: add per-Pod Kata configurations for `enable_pprof`
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/runtime/containerd-shim-v2/shim_management.go
Labels: area/debug, area/documentation, no-backport-needed

#1812 [2.1.0] Fix issue of virtio-mem
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, no-forward-port-needed

#1749 cli: delete tracing code for kata-runtime binary
  src/runtime/cli/kata-check.go
  src/runtime/cli/kata-env.go
  src/runtime/cli/kata-exec.go
  src/runtime/cli/main.go
  src/runtime/cli/version.go
Labels: area/cli, low-priority, no-backport-needed, no-forward-port-needed

#1730 [backport] runtime: fix static check errors
  .github/workflows/static-checks.yaml
  .gitignore
  .travis.yml
  pkg/logging/src/lib.rs
  src/agent/.gitignore
  src/agent/Makefile
  src/agent/oci/src/serialize.rs
  src/agent/protocols/src/lib.rs
  src/agent/rustjail/src/capabilities.rs
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/notifier.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/mount.rs
  src/agent/rustjail/src/sync.rs
  src/agent/rustjail/src/validator.rs
  src/agent/src/config.rs
  src/agent/src/device.rs
  src/agent/src/main.rs
  src/agent/src/metrics.rs
  src/agent/src/mount.rs
  src/agent/src/namespace.rs
  src/agent/src/netlink.rs
  src/agent/src/network.rs
  src/agent/src/random.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/test_utils.rs
  src/agent/src/uevent.rs
  src/runtime/Makefile
  src/runtime/cli/kata-check.go
  src/runtime/cli/main.go
  src/runtime/cli/main_test.go
  src/runtime/cli/utils.go
  src/runtime/containerd-shim-v2/shim_management.go
  src/runtime/containerd-shim-v2/shim_metrics.go
  src/runtime/containerd-shim-v2/shim_metrics_test.go
  src/runtime/pkg/kata-monitor/metrics_test.go
  src/runtime/pkg/kata-monitor/monitor.go
  src/runtime/pkg/kata-monitor/pprof.go
  src/runtime/pkg/kata-monitor/sandbox_cache.go
  src/runtime/pkg/kata-monitor/shim_client.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/api_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/fc_metrics.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
  src/runtime/virtcontainers/pkg/oci/utils.go
  src/runtime/virtcontainers/pkg/vcmock/types.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_metrics.go
  versions.yaml
Labels: backport, needs-review

#1784 agent: delete code which is no longer used
  src/agent/rustjail/src/configs/device.rs
  src/agent/rustjail/src/configs/mod.rs
  src/agent/rustjail/src/configs/namespaces.rs
  src/agent/rustjail/src/configs/validator.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/validator.rs
Labels: area/agent, no-backport-needed, no-forward-port-needed

#1799 Open CONFIG_VIRTIO_MEM in x86_64 Linux kernel
  tools/packaging/kernel/configs/fragments/x86_64/virtio.conf
  tools/packaging/kernel/kata_config_version
Labels: needs-backport, no-forward-port-needed

#1813 [2.1.0] kernel: configs: Open CONFIG_VIRTIO_MEM in x86_64 Linux kernel
  tools/packaging/kernel/configs/fragments/x86_64/virtio.conf
  tools/packaging/kernel/kata_config_version
Labels: backport, no-forward-port-needed

#1814 [backport]runtime: use s.ctx instead ctx for checking cancellation
  src/runtime/containerd-shim-v2/wait.go
Labels: area/runtime, backport

#1811 Monitor cleanup
  src/runtime/cli/kata-exec.go
  src/runtime/containerd-shim-v2/shim_management.go
  src/runtime/pkg/kata-monitor/metrics.go
  src/runtime/pkg/kata-monitor/monitor.go
  src/runtime/pkg/kata-monitor/shim_client.go
Labels: missing-backport-to-stable-2.1.0, needs-backport, no-forward-port-needed

#1818 osbuilder: Upgrade alpine version to 3.13.5
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  versions.yaml
Labels: needs-backport, needs-review, no-forward-port-needed

#1590 Support TDx
  src/runtime/cli/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_amd64.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
Labels: area/security, feature

#1821 stable-2.1: First round of backports
  ci/install_yq.sh
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/agent/kata-agent.service.in
  src/runtime/cli/kata-check.go
  src/runtime/cli/kata-env.go
  src/runtime/cli/kata-exec.go
  src/runtime/cli/main.go
  src/runtime/cli/version.go
  src/runtime/containerd-shim-v2/shim_management.go
  src/runtime/pkg/kata-monitor/metrics.go
  src/runtime/pkg/kata-monitor/monitor.go
  src/runtime/pkg/kata-monitor/shim_client.go
Labels: backport

#1790 runtime: make dialing timeout configurable
  src/runtime/cli/config/configuration-acrn.toml.in
  src/runtime/cli/config/configuration-clh.toml.in
  src/runtime/cli/config/configuration-fc.toml.in
  src/runtime/cli/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
Labels: enhancement, needs-backport, no-forward-port-needed

#1803 packaging/kata-cleanup: add k3s containerd volume
  tools/packaging/kata-deploy/kata-cleanup/overlays/k3s/kustomization.yaml
  tools/packaging/kata-deploy/kata-cleanup/overlays/k3s/mount_k3s_conf.yaml
Labels: backport, release-gating

#1794 docs: Remove horizontal ruler markers that disable spell checks
  docs/Limitations.md
  tools/packaging/ccloudvm/README.md
Labels: no-backport-needed, no-forward-port-needed

#1824 docs: Document test repository changes when creating a stable branch
  docs/Release-Process.md
Labels: no-backport-needed, no-forward-port-needed

#1828 agent: move the dependency tempfile to the dev-dependencies section
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
Labels: no-backport-needed, no-forward-port-needed

#1829 agent: avoid reaping the exit signal of execute_hook in the reaper
  src/agent/rustjail/src/container.rs
  src/agent/src/signal.rs
Labels: needs-backport, no-forward-port-needed

#1833 stable-2.1 | Get sandbox metrics cli
  src/runtime/cli/kata-metrics.go
  src/runtime/cli/main.go
  src/runtime/pkg/kata-monitor/metrics.go
Labels: backport

#1830 stable-2.1 | agent: avoid reaping the exit signal of execute_hook in the reaper
  src/agent/rustjail/src/container.rs
  src/agent/src/signal.rs
Labels: backport

#1835 stable-2.1 | runtime: make dialing timeout configurable
  src/runtime/cli/config/configuration-acrn.toml.in
  src/runtime/cli/config/configuration-clh.toml.in
  src/runtime/cli/config/configuration-fc.toml.in
  src/runtime/cli/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
Labels: backport

#1840 back port: image_build: align image size to 128M for arm64
  tools/osbuilder/image-builder/image_builder.sh
Labels: backport

#1839 # Kata Containers 2.0.4
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: no-backport-needed, no-forward-port-needed

#1843 docs: add note for connecting debug console for old versions
  docs/Developer-Guide.md
Labels: no-backport-needed, no-forward-port-needed

#985 runtime: improve sandbox cleanup logic
  src/runtime/virtcontainers/sandbox.go
Labels: needs-backport, no-forward-port-needed

#1844 rustjail: separated the propagation flags from mount flags
  src/agent/rustjail/src/mount.rs
Labels: needs-backport, no-forward-port-needed

#1853 stable-2.1 | The last round of backports before releasing 2.1.0
  docs/Limitations.md
  src/agent/rustjail/src/mount.rs
  src/runtime/virtcontainers/sandbox.go
  tools/packaging/ccloudvm/README.md
Labels: backport

#1858 github: Run require porting labels only at main
  .github/workflows/require-pr-porting-labels.yaml
Labels: no-backport-needed, no-forward-port-needed

#1846 how-to-use-virtio-mem-with-kata.md: Update doc to make it clear
  docs/how-to/how-to-use-virtio-mem-with-kata.md
Labels: needs-backport, no-forward-port-needed

#1910 workflows: release kata 2.x snap through the stable channel
  .github/workflows/snap-release.yaml
  docs/install/snap-installation-guide.md
Labels: needs-backport

#1911 [backport-2.1] workflows: release kata 2.x snap through the stable channel
  .github/workflows/snap-release.yaml
  docs/install/snap-installation-guide.md
Labels: backport

#1908 docs: Add instructions for getting QEMU source
  docs/Developer-Guide.md
Labels: area/QEMU, area/documentation

#1915 agent: fix start container failed when dropping all capabilities
  src/agent/rustjail/src/container.rs
Labels: needs-backport

#1921 Weekly stable 2.1 backports may 24th
  src/agent/rustjail/src/container.rs
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  tools/packaging/qemu/patches/5.1.x/0013-qemu-align-before-memory-hotplug-on-arm64.patch
Labels: backport

#1934 runtime: and cgroup and SandboxCgroupOnly check for check sub-command
  src/runtime/cli/kata-check.go
Labels: needs-backport

#1932 virtiofsd: Fix file descriptors leak and return correct PID
  src/runtime/virtcontainers/virtiofsd.go
Labels: area/runtime, needs-backport

#1939 agent: re-enable the standard SIGPIPE behavior
  src/agent/src/main.rs
Labels: needs-backport

#1918 cgroup: fix the issue of set mem.limit and mem.swap
  src/agent/rustjail/src/cgroups/fs/mod.rs
Labels: needs-backport
