Repository kata-containers/kata-containers, pull requests merged in 2021-10, with the labels that each got.

#2769 Pass the host route IP family to the guest
  src/agent/protocols/protos/types.proto
  src/agent/src/netlink.rs
  src/runtime/cmd/netmon/netmon.go
  src/runtime/cmd/netmon/netmon_test.go
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/github.com/vishvananda/netlink/README.md
  src/runtime/vendor/github.com/vishvananda/netlink/addr_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/bpf_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/class_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/conntrack_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/devlink_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/filter_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/handle_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/handle_unspecified.go
  src/runtime/vendor/github.com/vishvananda/netlink/inet_diag.go
  src/runtime/vendor/github.com/vishvananda/netlink/ipset_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/link.go
  src/runtime/vendor/github.com/vishvananda/netlink/link_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/neigh_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/netlink_unspecified.go
  src/runtime/vendor/github.com/vishvananda/netlink/netns_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/nl/conntrack_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/nl/devlink_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/nl/link_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/nl/lwt_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/nl/nl_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/nl/parse_attr_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/nl/rdma_link_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/nl/seg6_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/nl/syscall.go
  src/runtime/vendor/github.com/vishvananda/netlink/nl/tc_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/qdisc.go
  src/runtime/vendor/github.com/vishvananda/netlink/qdisc_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/rdma_link_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/route.go
  src/runtime/vendor/github.com/vishvananda/netlink/route_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/route_unspecified.go
  src/runtime/vendor/github.com/vishvananda/netlink/rule.go
  src/runtime/vendor/github.com/vishvananda/netlink/rule_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/socket_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/tcp.go
  src/runtime/vendor/github.com/vishvananda/netlink/tcp_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/xfrm_policy.go
  src/runtime/vendor/github.com/vishvananda/netlink/xfrm_policy_linux.go
  src/runtime/vendor/github.com/vishvananda/netlink/xfrm_state.go
  src/runtime/vendor/github.com/vishvananda/netlink/xfrm_state_linux.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/network_test.go
  src/runtime/virtcontainers/physical_endpoint_test.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/health.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
  src/runtime/virtcontainers/tap_endpoint.go
  src/runtime/virtcontainers/tuntap_endpoint.go
Labels: needs-backport

#2774 runtime: Fix !x86 static checks
  src/runtime/cmd/kata-runtime/kata-check_s390x_test.go
  src/runtime/virtcontainers/hypervisor_arm64.go
  src/runtime/virtcontainers/hypervisor_arm64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_arm64_test.go
  src/runtime/virtcontainers/utils/utils_linux_ppc64le.go
Labels: needs-backport, area/runtime, area/s390x

#2037 agent: Make wording of error message match CRI-O test suite
  src/agent/rustjail/src/container.rs
Labels: no-backport-needed, no-forward-port-needed

#2435 Update k8s, critools, and CRI-O to their 1.22 release
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#2496 cli: Show available guest protection in env output
  src/runtime/cmd/kata-runtime/kata-env.go
  src/runtime/virtcontainers/qemu_arch_base.go
Labels: needs-rebase

#1998 runtime: add fast-test to let test exit on error
  src/runtime/Makefile
Labels: needs-rebase, no-backport-needed, area/runtime, area/debug
