Repository kata-containers/kata-containers, pull requests merged in 2021-06, with the labels that each got.

#1940 [backport]runtime: and cgroup and SandboxCgroupOnly check for check sub-command
  src/runtime/cli/kata-check.go
Labels: backport

#1859 tracing: Make runtime span attributes more consistent
  src/runtime/containerd-shim-v2/service.go
  src/runtime/pkg/katautils/create.go
  src/runtime/pkg/katautils/hook.go
  src/runtime/pkg/katautils/tracing.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/api.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/factory/factory.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/virtiofsd.go
Labels: area/runtime, area/tracing, no-backport-needed, no-forward-port-needed

#1946 [stable-2.1] Weekly backports to stable-2.1 branch, May 31st 2021
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/src/main.rs
  src/runtime/virtcontainers/virtiofsd.go
Labels: backport

#1948 runtime: fix some comments and logs
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/network_test.go
  src/runtime/virtcontainers/sandbox.go
Labels: area/runtime, no-backport-needed

#1930 metrics: Add virtiofsd exporter
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/mock_hypervisor.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox_metrics.go
Labels: needs-review

#1961 docs: Fix Release Process document
  docs/Release-Process.md
Labels: area/documentation

#1963 stable-2.1 | versions: Update kubernetes to 1.21.1
  versions.yaml
Labels: backport

#1967 runtime: add more traces for network
  src/runtime/virtcontainers/bridgedmacvlan_endpoint.go
  src/runtime/virtcontainers/ipvlan_endpoint.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/macvtap_endpoint.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/network_test.go
  src/runtime/virtcontainers/physical_endpoint.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/tap_endpoint.go
  src/runtime/virtcontainers/tuntap_endpoint.go
  src/runtime/virtcontainers/veth_endpoint.go
  src/runtime/virtcontainers/vhostuser_endpoint.go
Labels: area/runtime, area/tracing, no-forward-port-needed

#1978 stable-2.1 | week 23: weekly backports
  docs/Release-Process.md
  src/runtime/cli/main_test.go
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/github.com/dlespiau/covertool/LICENSE
  src/runtime/vendor/github.com/dlespiau/covertool/pkg/cover/cover.go
  src/runtime/vendor/modules.txt
  tools/packaging/static-build/qemu/Dockerfile
Labels: backport

#1877 docs: Update the stable branch strategy to what was proposed in our ML
  docs/Stable-Branch-Strategy.md
Labels: no-backport-needed

#1988 agent: Conform to the latest nix version (0.21.0)
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/container.rs
  src/agent/src/console.rs
Labels: no-backport-needed

#1981 runtime: remove the call to storeSandbox at the end of createSandboxFromConfig
  src/runtime/virtcontainers/api.go
Labels: needs-backport

#1995 docs: Remove old travis reference
  tools/osbuilder/README.md
Labels: area/documentation, no-backport-needed

#1993 versions: Upgrade to cloud-hypervisor v16.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: needs-backport

#1832 test: Add a unit test for ioCopy()
  src/runtime/containerd-shim-v2/stream_test.go
Labels: needs-backport, no-forward-port-needed

#2020 docs: Update README for runtime documentation
  src/runtime/README.md
Labels: area/documentation, no-backport-needed

#2030 docs: Remove docker support with kata 2.x and sysctls
  docs/how-to/how-to-use-sysctls-with-kata.md
Labels: area/documentation, no-backport-needed

#2032 docs: Update url for breaking compatibility
  tools/packaging/kernel/README.md
Labels: area/documentation, no-backport-needed

#2033 backport docs: Update README for runtime documentation
  src/runtime/README.md
Labels: no-backport-needed, no-forward-port-needed

#1990 osbuilder: fix log message that is not error but seems like an error
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: area/osbuilder, no-backport-needed

#2028 [backport stable-2.1] versions: Upgrade to cloud-hypervisor v16.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: backport

#2041 qemu: Add nvdimm read-only file support
  tools/packaging/qemu/patches/5.2.x/0010-Merge-remote-tracking-branch-remotes-ehabkost-gl-tag.patch
Labels: area/QEMU, needs-backport

#2049 runtime: using detail propertites instead of function name in log field
  src/runtime/virtcontainers/qemu_amd64.go
Labels: area/runtime, no-backport-needed

#2055 stable-2.1 | qemu: Add nvdimm read-only file support
  tools/packaging/qemu/patches/5.2.x/0010-Merge-remote-tracking-branch-remotes-ehabkost-gl-tag.patch
Labels: area/QEMU, backport

#2070 docs: Update url for installation guides
  src/runtime/README.md
Labels: area/documentation, needs-backport

#2073 docs: Update kata-deploy urls for installation document
  docs/install/minikube-installation-guide.md
Labels: area/documentation, needs-backport

#2076 backport stable-2.1
  docs/install/minikube-installation-guide.md
  src/runtime/README.md
Labels: no-backport-needed, no-forward-port-needed

#1954 Remove the pc machine
  docs/use-cases/Intel-GPU-passthrough-and-Kata.md
  docs/use-cases/Nvidia-GPU-passthrough-and-Kata.md
  src/runtime/cli/config/configuration-fc.toml.in
  src/runtime/cli/config/configuration-qemu.toml.in
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/vendor/github.com/kata-containers/govmm/qemu/qmp.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_test.go
Labels: no-backport-needed

#2095 docs: Update urls for Documentation Requirements document
  docs/Documentation-Requirements.md
Labels: area/documentation, needs-backport

#2089 shimv2: fix the issue of leaking wait goroutines
  src/runtime/containerd-shim-v2/start.go
Labels: needs-backport

#2093 docs: Set LIBC=gnu for s390x too
  docs/Developer-Guide.md
Labels: area/architecture/s390x, area/documentation

#2099 stable-2.1 | runtime: report finish time in containers stats
  src/runtime/containerd-shim-v2/service.go
Labels: backport

#2100 stable-2.1 | docs: Update urls for Documentation Requirements document
  docs/Documentation-Requirements.md
Labels: area/documentation, no-backport-needed, no-forward-port-needed

#2003 tracing: Make runHooks() span creation return context
  src/runtime/pkg/katautils/hook.go
Labels: no-backport-needed, no-forward-port-needed

#2135 docs: Fix url in virtiofs documentation
  docs/how-to/how-to-use-virtio-fs-with-kata.md
Labels: area/documentation, needs-backport, no-forward-port-needed

#2060 agent: delete some lint attributes
  src/agent/rustjail/src/cgroups/notifier.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/mount.rs
  src/agent/src/sandbox.rs
  src/agent/src/test_utils.rs
Labels: area/agent, no-backport-needed
