Repository kata-containers/kata-containers, pull requests merged in 2021-03, with the labels that each got.

#1452 shimv2: return the hypervisor's pid as the container pid
  src/runtime/containerd-shim-v2/create.go
  src/runtime/containerd-shim-v2/service.go
  src/runtime/virtcontainers/interfaces.go
  src/runtime/virtcontainers/sandbox.go
Labels: needs-backport, no-forward-port-needed

#1457 agent: don't error of virtiofs share is already mounted
  src/agent/src/mount.rs
Labels: needs-backport

#1480 runtime: Fix missing 'name' field on containerd-shim-v2 logs
  src/runtime/containerd-shim-v2/service.go
Labels: no-backport-needed, no-forward-port-needed

#1491 musl/arm64: decompression before use the tarball.
  tools/osbuilder/scripts/lib.sh
Labels: needs-backport, no-forward-port-needed

#1408 [backport] Fix Snap CI
  .github/workflows/snap.yaml
  snap/snapcraft.yaml
Labels: no-backport-needed, no-forward-port-needed

#1478 rustjail: fix the issue of bind mount device file from guest
  src/agent/rustjail/src/mount.rs
Labels: needs-backport, no-forward-port-needed

#1472 agent-ctl: Unbreak build
  .github/workflows/static-checks.yaml
  tools/agent-ctl/Cargo.lock
  tools/agent-ctl/Cargo.toml
  tools/agent-ctl/Makefile
  tools/agent-ctl/src/client.rs
Labels: no-backport-needed, no-forward-port-needed

#1495 rustjail: fix the issue of home_dir function
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/utils.rs
Labels: no-backport-needed, no-forward-port-needed

#1501 exec: ensure sup groups are added to agent request
  src/runtime/containerd-shim-v2/exec.go
Labels: needs-backport

#1489 agent: makefile: Add codecov target
  src/agent/.gitignore
  src/agent/Makefile
Labels: no-backport-needed

#1498 runtime: return hypervisor Pid in TaskExit event
  src/runtime/containerd-shim-v2/utils.go
Labels: needs-backport, no-forward-port-needed

#1496 Bump to QEMU 5.2.0 - respin
  snap/snapcraft.yaml
  tools/packaging/scripts/configure-hypervisor.sh
Labels: area/ci, area/packaging

#1514 [forwardport] Fixup systemd cgroup handling
  src/runtime/virtcontainers/pkg/cgroups/manager.go
  src/runtime/virtcontainers/pkg/cgroups/manager_test.go
  src/runtime/virtcontainers/pkg/cgroups/utils.go
  src/runtime/virtcontainers/pkg/cgroups/utils_test.go
Labels: needs-backport, no-forward-port-needed

#1508 agent: Fix unused import warning in unit tests
  src/agent/rustjail/src/utils.rs
Labels: no-backport-needed, no-forward-port-needed

#1506 agent: Update Cargo.lock for earlier dependency change
  src/agent/Cargo.lock
Labels: no-backport-needed, no-forward-port-needed

#1525 agent: disconnect rpc get_oom_event when destroy_sandbox.
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
Labels: no-backport-needed, no-forward-port-needed

#1522 [backport] Fixup systemd cgroup handling
  src/runtime/virtcontainers/pkg/cgroups/manager.go
  src/runtime/virtcontainers/pkg/cgroups/manager_test.go
  src/runtime/virtcontainers/pkg/cgroups/utils.go
  src/runtime/virtcontainers/pkg/cgroups/utils_test.go
Labels: backport

#1529 [backport] runtime: Fix missing 'name' field on containerd-shim-v2 logs
  src/runtime/containerd-shim-v2/service.go
Labels: backport

#1426 runtime: clh-config: add runtime hooks to the clh toml
  src/runtime/cli/config/configuration-acrn.toml.in
  src/runtime/cli/config/configuration-clh.toml.in
  src/runtime/cli/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
Labels: backport

#1528 [backport] shimv2: return the hypervisor's pid as the container pid
  src/runtime/containerd-shim-v2/create.go
  src/runtime/containerd-shim-v2/service.go
  src/runtime/containerd-shim-v2/utils.go
  src/runtime/virtcontainers/interfaces.go
  src/runtime/virtcontainers/pkg/vcmock/sandbox.go
  src/runtime/virtcontainers/sandbox.go
Labels: backport, no-forward-port-needed

#1517 agent: Allow server address to be specified on kernel command-line
  src/agent/src/config.rs
Labels: no-backport-needed, no-forward-port-needed

#1534 rustjail: rework execute_hook
  src/agent/rustjail/src/container.rs
Labels: no-backport-needed, no-forward-port-needed

#1521 Verify container ID
  src/agent/src/rpc.rs
  src/runtime/cli/kata-exec.go
  src/runtime/containerd-shim-v2/service.go
  src/runtime/containerd-shim-v2/service_test.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/utils.go
  src/runtime/pkg/katautils/utils_test.go
  src/runtime/virtcontainers/pkg/vcmock/sandbox.go
Labels: no-backport-needed, no-forward-port-needed

#1541 kata-deploy: Use the correct image for 2.0.2 release
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: no-backport-needed, no-forward-port-needed

#1542 kata-deploy: Use the correct tag for 2.1-alpha1 release
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: no-backport-needed, no-forward-port-needed

#1548 [backport] runtime: increase dial timeout
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
Labels: backport

#1551 runtime: Fix trace span ordering and static checks
  src/runtime/containerd-shim-v2/service.go
  src/runtime/containerd-shim-v2/service_test.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/api.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/factory/factory.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, no-forward-port-needed

#1460 runtime: update virtcontainers API documentation
  src/agent/src/device.rs
  src/runtime/virtcontainers/README.md
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/interfaces.go
  src/runtime/virtcontainers/persist/api/config.go
Labels: no-backport-needed, no-forward-port-needed

#1553 runtime: fix virtiofsd RO volume sharing
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mount.go
Labels: needs-backport, no-forward-port-needed

#1535 agent: Enable clean shutdown
  pkg/logging/src/lib.rs
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/config.rs
  src/agent/src/main.rs
  src/agent/src/signal.rs
  src/agent/src/uevent.rs
  src/agent/src/util.rs
  src/trace-forwarder/src/main.rs
  tools/agent-ctl/src/main.rs
Labels: no-backport-needed, no-forward-port-needed

#1560 container: on cleanup, rm container directory for mounts path
  src/runtime/virtcontainers/container.go
Labels: bug, needs-backport

#1537 cgroups: fix the issue of get wrong online cpus
  src/agent/rustjail/src/cgroups/fs/mod.rs
Labels: needs-backport, no-forward-port-needed

#1555 test: install mock hook binary before test
  src/runtime/Makefile
  src/runtime/pkg/katautils/hook_test.go
  src/runtime/virtcontainers/pkg/mock/mock.go
Labels: no-backport-needed, no-forward-port-needed

#1569 # Kata Containers 2.1-alpha1
  VERSION
Labels: no-backport-needed, no-forward-port-needed

#1549 runtime: makefile allow override DAX value
  src/runtime/Makefile
Labels: no-backport-needed

#1563 virtcontainers: Fix missing contexts in s390x
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_arm64_test.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_s390x_test.go
Labels: no-backport-needed, no-forward-port-needed

#1384 kernel: Enable OVERLAY_FS_{METACOPY,XINO_AUTO}
  tools/packaging/kernel/configs/fragments/common/fs.conf
Labels: needs-backport, needs-review, no-forward-port-needed

#1587 Remove installation guides for SLE and openSUSE
  docs/install/README.md
  docs/install/opensuse-installation-guide.md
  docs/install/opensuse-leap-15.1-installation-guide.md
  docs/install/sle-installation-guide.md
Labels: needs-backport, no-forward-port-needed

#1594 action: fix missing qemu tag
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#1595 kata-deploy: QEMU, for 2.x, already includes virtiofs
  .github/workflows/main.yaml
  .github/workflows/release.yaml
  docs/how-to/how-to-use-virtio-fs-with-kata.md
  src/runtime/.gitignore
  src/runtime/arch/amd64-options.mk
  tools/packaging/artifact-list.sh
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/README.md
  tools/packaging/kata-deploy/action/test-kata.sh
  tools/packaging/kata-deploy/examples/test-deploy-kata-qemu-virtiofs.yaml
  tools/packaging/kata-deploy/k8s-1.13/kata-qemu-virtiofs-runtimeClass.yaml
  tools/packaging/kata-deploy/k8s-1.14/kata-qemu-virtiofs-runtimeClass.yaml
  tools/packaging/release/kata-deploy-binaries.sh
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/static-build/qemu-virtiofs/Dockerfile
  tools/packaging/static-build/qemu-virtiofs/build-static-qemu-virtiofs.sh
Labels: no-backport-needed, no-forward-port-needed

#1584 Update install docs for Fedora and CentOS
  docs/install/README.md
  docs/install/centos-installation-guide.md
  docs/install/fedora-installation-guide.md
Labels: needs-backport, no-forward-port-needed

#1602 docs: Update snap install guide
  docs/install/snap-installation-guide.md
Labels: needs-backport, no-forward-port-needed

#1577 runtime: import runtime/v2/runc/options to decode request from Docker
  src/runtime/containerd-shim-v2/create.go
Labels: no-backport-needed, no-forward-port-needed

#1592 versions: Update cloud-hypervisor to release v0.14.1
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/configuration.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryZoneConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/RateLimiterConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/TokenBucket.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_balloon_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cmd_line_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_console_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpu_topology.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_node.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_initramfs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_kernel_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_zone_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_numa_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_numa_distance.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pci_device_info.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_rate_limiter_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_restore_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_rng_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_sgx_epc_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_token_bucket.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_add_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_info.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_remove_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize_zone.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_snapshot_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vmm_ping_response.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vsock_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: forward-port
