Repository kata-containers/kata-containers, pull requests merged in 2022-09, with the labels that each got.

#5059 versions: Upgrade rust supported version to 1.59.0 for 2.5 branch
  src/tools/agent-ctl/src/utils.rs
  versions.yaml
Labels: size/small

#5052 stable-2.5 | versions: Update kernel to 5.15.63
  tools/packaging/kernel/configs/fragments/x86_64/base.conf
  tools/packaging/kernel/kata_config_version
  versions.yaml
Labels: size/tiny

#5049 [stable-2.5] backport security related dependency commits
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/seccomp.rs
  src/tools/agent-ctl/Cargo.lock
  src/tools/runk/Cargo.lock
  src/tools/trace-forwarder/Cargo.lock
Labels: size/large

#5065 docs: Specify language in markdown for syntax highlight
  docs/Unit-Test-Advice.md
Labels: size/tiny

#5048 # Kata Containers 3.0.0-alpha1
  VERSION
Labels: size/tiny

#5047 # Kata Containers 2.5.1
  VERSION
  src/agent/src/rpc.rs
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/containerd-shim-v2/service.go
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kernel/configs/fragments/common/cgroup.conf
  tools/packaging/kernel/kata_config_version
Labels: size/tiny

#5076 docs: Update url in the Developer Guide
  docs/Developer-Guide.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4862 Address Memory hotplug limitation
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/mock_hypervisor.go
  src/runtime/virtcontainers/mock_hypervisor_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: needs-backport, size/large, backport-to-stable-2.5

#5013 config: Added SEV config
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-sev.toml.in
Labels: size/tiny

#5079 qemu: fix tdx qemu tarball directories
  tools/packaging/qemu/patches/tag_patches/SPR-BKC-QEMU-v2.5/no_patches.txt
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/qemu/build-base-qemu.sh
Labels: no-backport-needed, size/small

#5090 qemu: Keep passing BUILD_SUFFIX
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/qemu/build-base-qemu.sh
Labels: no-backport-needed, size/tiny

#4719 github-actions: Add cargo-deny
  .github/cargo-deny-composite-action/cargo-deny-generator.sh
  .github/cargo-deny-composite-action/cargo-deny-skeleton.yaml.in
  .github/workflows/cargo-deny-runner.yaml
  ci/lib.sh
  deny.toml
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/vsock-exporter/Cargo.toml
  src/libs/Cargo.lock
  src/libs/Cargo.toml
  src/libs/logging/Cargo.toml
  src/libs/oci/Cargo.toml
  src/libs/protocols/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/persist/Cargo.toml
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/tests/utils/Cargo.toml
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Cargo.toml
  src/tools/trace-forwarder/Cargo.lock
  src/tools/trace-forwarder/Cargo.toml
Labels: no-backport-needed, size/large

#4744 runtime-rs: support functionality of static resource management
  src/libs/kata-types/src/annotations/cri_containerd.rs
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/runtime.rs
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/src/static_resource.rs
Labels: runtime-rs, size/large

#5063 runtime-rs: split amend_spec function
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: runtime-rs, size/tiny

#5086 docs: fix unix socket address in agent-ctl doc
  src/tools/agent-ctl/README.md
Labels: size/tiny

#5045 CC | kata-deploy: Misc fixes related to building the payload
  docs/how-to/README.md
  docs/how-to/how-to-generate-a-kata-containers-payload-for-the-confidential-containers-operator.md
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
  tools/packaging/qemu/patches/tag_patches/SPR-BKC-QEMU-v2.5/no_patches.txt
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/qemu/build-base-qemu.sh
Labels: no-backport-needed, size/large

#5121 kata-deploy: Fix `containerd-shim-kata-v2` location
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: no-backport-needed, size/tiny

#5099 runtime-rs: add default agent/runtime/hypervisor for configuration
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/agent.rs
  src/libs/kata-types/src/config/default.rs
  src/libs/kata-types/src/config/mod.rs
  src/libs/kata-types/src/config/runtime.rs
Labels: runtime-rs, size/small

#5124 Revert arp neighbour api
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/netlink.rs
  tools/packaging/kata-deploy/action/test-kata.sh
Labels: no-backport-needed, size/large

#5058 gperf: point URL to mirror site
  versions.yaml
Labels: no-backport-needed, size/tiny

#5116 libs/kata-types: replace tabs by spaces in comments
  src/libs/kata-types/src/annotations/mod.rs
Labels: runtime-rs, size/small

#5129 kata-deploy-cc: Simplify cleanup
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: no-backport-needed, area/confidential-containers, size/small

#5095 kernel: fix kernel tarball name for SEV
  tools/packaging/kernel/build-kernel.sh
Labels: no-backport-needed, size/tiny

#5034 runk: Refactor container builder
  src/tools/runk/libcontainer/src/activated_builder.rs
  src/tools/runk/libcontainer/src/builder.rs
  src/tools/runk/libcontainer/src/container.rs
  src/tools/runk/libcontainer/src/init_builder.rs
  src/tools/runk/libcontainer/src/lib.rs
  src/tools/runk/libcontainer/src/utils.rs
  src/tools/runk/src/commands/create.rs
  src/tools/runk/src/commands/exec.rs
  src/tools/runk/src/commands/run.rs
Labels: size/huge

#5096 kernel: fix kernel tarball name for SEV for CCv0
  tools/packaging/kernel/build-kernel.sh
Labels: no-backport-needed, size/tiny

#5103 config: add "inline-virtio-fs" as a "shared_fs" type
  src/runtime-rs/config/configuration-dragonball.toml.in
Labels: runtime-rs, size/tiny

#5134 CCv0: Merge main into CCv0 branch
  .github/cargo-deny-composite-action/cargo-deny-generator.sh
  .github/cargo-deny-composite-action/cargo-deny-skeleton.yaml.in
  .github/workflows/cargo-deny-runner.yaml
  VERSION
  ci/lib.sh
  deny.toml
  docs/Developer-Guide.md
  docs/Unit-Test-Advice.md
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/src/netlink.rs
  src/agent/vsock-exporter/Cargo.toml
  src/libs/Cargo.lock
  src/libs/Cargo.toml
  src/libs/kata-types/src/annotations/cri_containerd.rs
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/agent.rs
  src/libs/kata-types/src/config/default.rs
  src/libs/kata-types/src/config/mod.rs
  src/libs/kata-types/src/config/runtime.rs
  src/libs/logging/Cargo.toml
  src/libs/oci/Cargo.toml
  src/libs/protocols/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/persist/Cargo.toml
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/src/static_resource.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/tests/utils/Cargo.toml
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/mock_hypervisor.go
  src/runtime/virtcontainers/mock_hypervisor_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Cargo.toml
  src/tools/agent-ctl/README.md
  src/tools/trace-forwarder/Cargo.lock
  src/tools/trace-forwarder/Cargo.toml
  tools/packaging/kata-deploy/action/test-kata.sh
  versions.yaml
Labels: no-backport-needed, area/confidential-containers, ignore-depends-on, size/huge

#4897 runk: Enable seccomp support by default
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
  src/tools/runk/Makefile
  src/tools/runk/README.md
Labels: size/medium

#5073 runtime-rs: update rust runtime roadmap
  docs/design/architecture_3.0/README.md
Labels: runtime-rs, size/tiny

#5151 runtime-rs: remove meaningless comment
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
Labels: runtime-rs, size/tiny

#5146 runtime-rs: fix host device check pattern
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
Labels: runtime-rs, size/tiny

#5101 kata-types: change return type of getting CPU period/quota function
  src/libs/kata-types/src/annotations/mod.rs
  src/runtime-rs/crates/runtimes/src/static_resource.rs
Labels: runtime-rs, size/small

#5105 kata-types: don't check virtio_fs_daemon for inline-virtio-fs
  src/libs/kata-types/src/config/hypervisor/mod.rs
Labels: runtime-rs, size/small

#3697 Support Peer Pod VMs
  src/agent/src/rpc.rs
  src/runtime/cmd/kata-runtime/kata-check_amd64.go
  src/runtime/cmd/kata-runtime/kata-check_arm64.go
  src/runtime/cmd/kata-runtime/kata-check_ppc64le.go
  src/runtime/cmd/kata-runtime/kata-check_s390x.go
  src/runtime/hack/update-generated-hypervisor-proto.sh
  src/runtime/pkg/katautils/config.go
  src/runtime/protocols/hypervisor/hypervisor.pb.go
  src/runtime/protocols/hypervisor/hypervisor.proto
  src/runtime/virtcontainers/fs_share_linux.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_config_darwin.go
  src/runtime/virtcontainers/hypervisor_config_linux.go
  src/runtime/virtcontainers/hypervisor_linux.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
  src/runtime/virtcontainers/remote.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/types/sandbox.go
Labels: area/confidential-containers, size/huge

#5026 CC| packaging: Add AmdSev OVMF target for use in payload images
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, size/small

#5120 CC, packaging: add sev-initrd target, and add efi_secret module to sev's initrd
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/scripts/lib.sh
Labels: area/confidential-containers, size/medium

#5130 CC, kata-deploy: add kata-qemu-sev runtimeclass
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: no-backport-needed, area/confidential-containers, size/tiny

#5165 runtime-rs: delete some allow(dead_code) attributes
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
  src/runtime-rs/crates/shim/src/config.rs.in
Labels: runtime-rs, size/small

#5174 # Kata Containers 3.0.0-rc0
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml
Labels: size/large

#5024 CC | rootfs builder: add agent config file to rootfs for offline_sev_kbc
  tools/osbuilder/rootfs-builder/agent-config.toml.in
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
Labels: no-backport-needed, size/tiny

#5038 CC | packaging: Build SEV capable kernel + efi_secret module
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/kernel/Dockerfile
Labels: size/small

#5127 CC use depmod in rootfs builder for kernel modules with docker support
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
Labels: area/confidential-containers, size/tiny

#5133 feat(Shimmgmt): Shim management server and client
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/mod.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/client.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/mod.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/server.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: runtime-rs, size/large

#5113 runtime-rs: call TomlConfig's validate function after load
  src/runtime-rs/Makefile
  src/runtime-rs/crates/runtimes/src/manager.rs
Labels: runtime-rs, size/tiny

#5167 kata-deploy: rename make target for sev initrd
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, size/tiny

#5082 dragonball: Fix problem that stdio console cannot connect to stdout
  src/dragonball/src/device_manager/console_manager.rs
  src/dragonball/src/device_manager/mod.rs
Labels: no-backport-needed, no-forward-port-needed, runtime-rs, size/small

#5204 docs: Update url in virtualization document
  docs/design/virtualization.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5195 Build-in Sandbox: update dragonball-sandbox dependencies
  src/dragonball/Cargo.toml
  src/dragonball/Makefile
  src/dragonball/src/address_space_manager.rs
  src/dragonball/src/device_manager/mod.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
Labels: size/large

#5159 kernel: Add crypto kernel config for s390
  tools/packaging/kernel/configs/fragments/s390/crypto.conf
Labels: size/small

#5188 runtime-rs: fix incorrect comments
  src/libs/kata-types/src/config/hypervisor/mod.rs
Labels: needs-backport, no-forward-port-needed, runtime-rs, size/tiny

#5202 packaging: Remove skopeo & umoci
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: area/confidential-containers, size/tiny

#5171 runtime-rs/resource: use macro to reduce duplicated code
  src/runtime-rs/crates/resource/src/network/utils/link/manager.rs
Labels: refactor, runtime-rs, size/large

#4924 runtime-rs: add unit tests for network resource
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
  src/runtime-rs/crates/resource/src/network/network_pair.rs
  src/runtime-rs/crates/resource/src/network/utils/address.rs
  src/runtime-rs/crates/resource/src/network/utils/link/create.rs
  src/runtime-rs/crates/resource/src/network/utils/link/mod.rs
  src/runtime-rs/crates/resource/src/network/utils/mod.rs
  src/runtime-rs/crates/resource/src/network/utils/netns.rs
Labels: runtime-rs, size/large

#5233 osbuilder: Export directory variables for libseccomp
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5186 runtime-rs: use Path.is_file to check regular files
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
Labels: runtime-rs, size/small

#5206 docs: add README for runtime-rs hypervisor crate
  src/runtime-rs/crates/hypervisor/README.md
  src/runtime-rs/docs/images/hypervisor-config.svg
  src/runtime-rs/docs/images/vm-start.svg
Labels: runtime-rs, size/large

#5230 runtime-rs: remove hardcoded string
  src/runtime-rs/crates/runtimes/src/shim_mgmt/server.rs
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5163 runtime-rs: add test for StaticResource
  src/runtime-rs/crates/runtimes/src/static_resource.rs
Labels: runtime-rs, size/large

#5238 osbuilder: don't pull in umoci with attestation
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: area/confidential-containers, size/tiny

#5175 release: Revert kata-deploy changes after 3.0.0-rc0 release
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml
Labels: size/large

#5161 packaging: fix typo in configure-hypervisor.sh
  tools/packaging/scripts/configure-hypervisor.sh
Labels: size/small

#4931 Added SNP-Support for Kata-Containers
  docs/Developer-Guide.md
  docs/how-to/README.md
  docs/how-to/containerd-kata.md
  docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md
  docs/how-to/images/SNP-stack.svg
  src/runtime/Makefile
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_linux_amd64.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arm64_test.go
  src/runtime/virtcontainers/qemu_ppc64le_test.go
  src/runtime/virtcontainers/qemu_s390x_test.go
  tools/packaging/kernel/README.md
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/x86_64/snp/snp.conf
  versions.yaml
Labels: size/huge

#5250 runtime-rs: set agent timeout to 0 for stream RPCs
  src/runtime-rs/crates/agent/src/kata/agent.rs
Labels: needs-backport, runtime-rs, size/tiny

#5190 runtime-rs: define VFIO unbind path as a const
  src/runtime-rs/crates/hypervisor/src/device/vfio.rs
Labels: no-backport-needed, no-forward-port-needed, runtime-rs, size/tiny

#5193 kata-deploy: ship the rustified runtime binary
  src/runtime-rs/Makefile
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  tools/packaging/kata-deploy/README.md
  tools/packaging/kata-deploy/action/test-kata.sh
  tools/packaging/kata-deploy/examples/nginx-deployment-dragonball.yaml
  tools/packaging/kata-deploy/examples/test-deploy-kata-dragonball.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
  tools/packaging/static-build/shim-v2/Dockerfile
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/shim-v2/install_go_rust.sh
Labels: runtime-rs, size/large

#5097 runtime-rs: debug console support in runtime
  src/libs/kata-types/src/config/default.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/src/config/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/kernel_param.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/src/manager.rs
Labels: runtime-rs, size/large

#5257 Last backport for 3.0-rc1
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, backport, size/medium

#5260 docs: Update urls in runk documentation
  src/tools/runk/README.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5252 modify virtio_net_dev_mgr.rs wrong code comments
  src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
Labels: runtime-rs, size/tiny

#5254 Dragonball: update linux_loader to 0.6.0
  src/dragonball/Cargo.toml
  src/dragonball/src/device_manager/blk_dev_mgr.rs
  src/dragonball/src/error.rs
  src/dragonball/src/vm/x86_64.rs
Labels: runtime-rs, size/small

#5263 kata-deploy: support runtime-rs for kata deploy
  src/runtime-rs/Makefile
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  tools/packaging/kata-deploy/README.md
  tools/packaging/kata-deploy/action/test-kata.sh
  tools/packaging/kata-deploy/examples/nginx-deployment-dragonball.yaml
  tools/packaging/kata-deploy/examples/test-deploy-kata-dragonball.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
  tools/packaging/static-build/shim-v2/Dockerfile
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/shim-v2/install_go_rust.sh
Labels: runtime-rs, size/large

#5262 stable-2.5: fix cargo vendor
  src/agent/Cargo.lock
Labels: size/small

#4387 workflow: trigger test-kata-deploy with pull_request and fix workflow_dispatch
  .github/workflows/kata-deploy-test.yaml
  docs/Release-Process.md
Labels: needs-backport, no-forward-port-needed, size/medium

#5258 Last backport for 2.5.2
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu.go
Labels: backport, size/small

#5273 osbuilder: Export directory variables for libseccomp
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: no-backport-needed, no-forward-port-needed, backport, size/tiny

#5198 runtime-rs: add comments for runtime-rs shared directory
  src/runtime-rs/crates/resource/src/share_fs/utils.rs
Labels: runtime-rs, size/small

#5271 runtime-rs: fix shim close_io call to support kubectl cp
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
  src/runtime-rs/crates/service/src/task_service.rs
Labels: runtime-rs, size/small

#5200 refactor(runtime-rs): Use RwLock in runtime-agent
  src/runtime-rs/crates/agent/src/kata/mod.rs
Labels: runtime-rs, size/small

#5281 runtime-rs: update Cargo.lock
  src/runtime-rs/Cargo.lock
Labels: runtime-rs, size/tiny

#5284 tools: release: fix bogus version check
  tools/packaging/release/update-repository-version.sh
Labels: needs-backport

#5286 tools: release: fix bogus version check
  tools/packaging/release/update-repository-version.sh
Labels: no-backport-needed, backport, size/tiny

#5289 tools: release: fix bogus version check
  tools/packaging/release/update-repository-version.sh
Labels: no-backport-needed, backport, size/tiny

#5288 dragonball: fix no "as_str" error on Arm
  src/dragonball/src/vm/aarch64.rs
Labels: no-backport-needed, size/tiny

#5292 versions: Update oci version
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5244 versions: Update gperf url to avoid libseccomp random failures
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5278 dragonball: update ut for kernel config
  src/dragonball/src/vm/kernel_config.rs
Labels: no-backport-needed, runtime-rs, size/tiny

#5290 # Kata Containers 3.0.0-rc1
  VERSION
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5293 # Kata Containers 2.5.2
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: size/tiny
