Repository kata-containers/kata-containers, pull requests merged in 2022-03, with the labels that each got.

#3794 back port:: runtime: make selinux configurable
  src/runtime/Makefile
  src/runtime/config/configuration-acrn.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu.go
Labels: backport

#3770 runtime: Gofmt fixes
  src/runtime/pkg/govmm/qemu/qemu_arch_base_test.go
  src/runtime/pkg/govmm/vmm_s390x.go
  src/runtime/pkg/resourcecontrol/cgroups.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/acrn_arch_base.go
  src/runtime/virtcontainers/acrn_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/fc_metrics.go
  src/runtime/virtcontainers/fc_test.go
  src/runtime/virtcontainers/ipvlan_endpoint.go
  src/runtime/virtcontainers/ipvlan_endpoint_test.go
  src/runtime/virtcontainers/macvlan_endpoint.go
  src/runtime/virtcontainers/macvlan_endpoint_test.go
  src/runtime/virtcontainers/macvtap_endpoint.go
  src/runtime/virtcontainers/macvtap_endpoint_test.go
  src/runtime/virtcontainers/physical_endpoint.go
  src/runtime/virtcontainers/physical_endpoint_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_arm64_test.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_ppc64le_test.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_s390x_test.go
  src/runtime/virtcontainers/qemu_test.go
  src/runtime/virtcontainers/tap_endpoint.go
  src/runtime/virtcontainers/tuntap_endpoint.go
  src/runtime/virtcontainers/veth_endpoint.go
  src/runtime/virtcontainers/veth_endpoint_test.go
  src/runtime/virtcontainers/vhostuser_endpoint.go
  src/runtime/virtcontainers/vhostuser_endpoint_test.go
Labels: needs-backport, no-forward-port-needed, area/govmm

#3728 snap: clh: Re-use kata-deploy script here
  snap/snapcraft.yaml
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3796 Fix monitor listen address
  src/runtime/Makefile
  src/runtime/cmd/kata-monitor/main.go
Labels: no-backport-needed, no-forward-port-needed

#3764 virtcontainers: Use available s390x hugepages
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/code.cloudfoundry.org/bytefmt/LICENSE
  src/runtime/vendor/code.cloudfoundry.org/bytefmt/NOTICE
  src/runtime/vendor/code.cloudfoundry.org/bytefmt/README.md
  src/runtime/vendor/code.cloudfoundry.org/bytefmt/bytes.go
  src/runtime/vendor/code.cloudfoundry.org/bytefmt/go.mod
  src/runtime/vendor/code.cloudfoundry.org/bytefmt/go.sum
  src/runtime/vendor/code.cloudfoundry.org/bytefmt/package.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/kata_agent_test.go
Labels: no-backport-needed, no-forward-port-needed, area/runtime, area/s390x

#3812 snap: Don't build cloud-hypevisor on ppc64le
  snap/snapcraft.yaml
Labels: no-backport-needed, no-forward-port-needed

#3811 clh: tdx: Don't use sharedFS with Confidential Guests
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_ppc64le.go
Labels: no-backport-needed, no-forward-port-needed, area/cloud-hypervisor, area/tdx

#3823 clh: stop virtofsd if clh fails to boot up the vm
  src/runtime/virtcontainers/clh.go
Labels: needs-backport, no-forward-port-needed

#3814 Minor fixes for the `disable_block_device_use` comments
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
Labels: no-backport-needed, no-forward-port-needed

#3826 versions: Upgrade to Cloud Hypervisor v22.0
  versions.yaml
Labels: needs-backport, no-forward-port-needed

#3281 experimentally enable vcpu hotplug and virtio-mem on arm64 in kernel part
  src/runtime/virtcontainers/qemu.go
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/arm64/base.conf
  tools/packaging/kernel/configs/fragments/build-type/arm-experimental/no.conf
  tools/packaging/kernel/configs/fragments/common/fs.conf
  tools/packaging/kernel/patches/5.15.x/arm-experimental/0001-arm64-kernel-Handle-disabled-present-cpus-in-MADT-GI.patch
  tools/packaging/kernel/patches/5.15.x/arm-experimental/0002-arm64-kernel-Bound-the-total-present-disabled-cpus-w.patch
  tools/packaging/kernel/patches/5.15.x/arm-experimental/0003-arm64-kernel-Init-cpu-operations-for-all-possible-vc.patch
  tools/packaging/kernel/patches/5.15.x/arm-experimental/0004-arm64-kernel-Arch-specific-ACPI-hooks-like-logical-c.patch
  tools/packaging/kernel/patches/5.15.x/arm-experimental/0005-cpu-numa-fix-failure-when-hot-remove-cpu.patch
  tools/packaging/kernel/patches/5.15.x/arm-experimental/0006-arm64-mm-avoid-fixmap-race-condition-when-create-pud.patch
  tools/packaging/kernel/patches/5.15.x/arm-experimental/0007-virtio-mem-enable-virtio-mem-on-arm64.patch
  versions.yaml
Labels: needs-review, no-backport-needed, no-forward-port-needed

#3836 Enhancement: fix comments/logs and delete not used function
  src/agent/rustjail/src/container.rs
  src/agent/src/sandbox.rs
  src/runtime/pkg/resourcecontrol/controller.go
  src/runtime/pkg/resourcecontrol/utils_linux.go
Labels: enhancement, no-backport-needed, no-forward-port-needed

#3842 CI: Create GHA to add PR sizing label
  .github/workflows/add-pr-sizing-label.yaml
Labels: force-skip-ci

#3766 Improve error checking of hugepage allocation
  src/agent/src/mount.rs
Labels: no-backport-needed, no-forward-port-needed

#3855 docs: Update contact link in runtime README
  src/runtime/README.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3853 kernel: fix cve-2022-0847
  tools/packaging/kernel/kata_config_version
  versions.yaml
Labels: needs-backport, no-forward-port-needed

#3828 CCv0: Update AA's launch command
  src/agent/src/image_rpc.rs
Labels: area/confidential-containers

#3838 agent: add tests for get_memory_info function
  src/agent/src/rpc.rs
Labels: no-backport-needed, no-forward-port-needed, size/large

#3865 scripts: Change here document delimiters
  src/libs/protocols/hack/update-generated-proto.sh
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/initrd-builder/initrd_builder.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/scripts/lib.sh
  tools/osbuilder/tests/test_images.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/release/publish-kata-image.sh
  tools/packaging/release/release-notes.sh
  tools/packaging/release/tag_repos.sh
  tools/packaging/release/update-repository-version.sh
  tools/packaging/scripts/apply_patches.sh
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/scripts/gen_versions_txt.sh
  tools/packaging/static-build/shim-v2/install_go.sh
Labels: no-backport-needed, size/large

#3858 Add debug and self-test control options to Kata Manager
  utils/kata-manager.sh
Labels: size/large

#3786 runtime-rs: shim part
  Makefile
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/rpc.rs
  src/libs/kata-sys-util/src/fs.rs
  src/libs/kata-sys-util/src/lib.rs
  src/libs/kata-sys-util/src/validate.rs
  src/libs/kata-types/.gitignore
  src/libs/kata-types/src/container.rs
  src/libs/kata-types/src/k8s.rs
  src/libs/protocols/.gitignore
  src/runtime-rs/.gitignore
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/runtime-rs/Makefile
  src/runtime-rs/VERSION
  src/runtime-rs/crates/shim/Cargo.toml
  src/runtime-rs/crates/shim/build.rs
  src/runtime-rs/crates/shim/src/args.rs
  src/runtime-rs/crates/shim/src/bin/main.rs
  src/runtime-rs/crates/shim/src/config.rs.in
  src/runtime-rs/crates/shim/src/error.rs
  src/runtime-rs/crates/shim/src/lib.rs
  src/runtime-rs/crates/shim/src/logger.rs
  src/runtime-rs/crates/shim/src/panic_hook.rs
  src/runtime-rs/crates/shim/src/shim.rs
  src/runtime-rs/crates/shim/src/shim_delete.rs
  src/runtime-rs/crates/shim/src/shim_run.rs
  src/runtime-rs/crates/shim/src/shim_start.rs
  src/runtime-rs/tests/texture/image-bundle/config.json
  src/runtime-rs/tests/texture/kata-containers-configuration.toml
  src/runtime-rs/tests/utils/Cargo.toml
  src/runtime-rs/tests/utils/src/lib.rs
Labels: runtime-rs, size/huge

#3873 versions: Upgrade to Cloud Hypervisor v22.1
  versions.yaml
Labels: needs-backport, no-forward-port-needed

#3877 runtime-rs: modify the review suggestion for shim-part
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/shim/Cargo.toml
  src/runtime-rs/crates/shim/src/bin/main.rs
  src/runtime-rs/crates/shim/src/shim.rs
  src/runtime-rs/crates/shim/src/shim_start.rs
Labels: runtime-rs

#3880 doc: fix kata-deploy README typo
  tools/packaging/kata-deploy/README.md
Labels: size/tiny

#3867 rustjail: optimization, merged several writelns into one
  src/agent/rustjail/src/utils.rs
Labels: size/small

#3868 docs: Update k8s documentation
  docs/how-to/run-kata-with-k8s.md
Labels: needs-backport, size/medium

#3875 runtime: properly handle ESRCH error when signaling container
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/utils/utils.go
Labels: needs-backport, area/runtime, size/small

#3892 runtime: Properly handle ESRCH error when signaling container
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/utils/utils.go
Labels: backport

#3893 runtime: Properly handle ESRCH error when signaling container
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/utils/utils.go
Labels: backport

#3861 image: Enable image-rs crate to pull image inside guest
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/lib.rs
  src/agent/src/device.rs
  src/agent/src/image_rpc.rs
  src/libs/oci/src/lib.rs
  src/tools/agent-ctl/src/utils.rs
Labels: size/huge

#3903 tools: update QEMU to 6.2
  tools/packaging/qemu/patches/6.2.x/Revert-target-ppc-Move-SPR_DSISR-setting-to-powerpc_excp.patch
  tools/packaging/qemu/patches/tag_patches/v6.2.0/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/large

#3912 doc: update Intel SGX use cases document
  docs/use-cases/using-Intel-SGX-and-kata.md
Labels: no-backport-needed, no-forward-port-needed, size/small

#3322 device: using const strings for block-driver option instead of hard coding
  src/runtime/virtcontainers/container_test.go
  src/runtime/virtcontainers/device/config/config.go
  src/runtime/virtcontainers/device/config/pmem.go
  src/runtime/virtcontainers/device/drivers/block.go
  src/runtime/virtcontainers/device/drivers/vhost_user_blk.go
  src/runtime/virtcontainers/device/manager/manager.go
  src/runtime/virtcontainers/device/manager/manager_linux_test.go
  src/runtime/virtcontainers/device/manager/manager_test.go
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/persist/api/device.go
  src/runtime/virtcontainers/persist_test.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: enhancement, area/runtime, size/large

#3682 Multistrap Ubuntu & enable cross-building guest
  ci/install_libseccomp.sh
  ci/install_musl.sh
  tools/osbuilder/dracut/Dockerfile.in
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile.in
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/template/Dockerfile.template
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
  tools/osbuilder/scripts/lib.sh
  tools/osbuilder/tests/test_images.sh
  utils.mk
  versions.yaml
Labels: architecture-specific, no-backport-needed, no-forward-port-needed, area/osbuilder, size/large

#3927 stable-2.4: Bump QEMU to 6.2 (bringing then SGX support in)
  docs/use-cases/using-Intel-SGX-and-kata.md
  tools/packaging/qemu/patches/6.2.x/Revert-target-ppc-Move-SPR_DSISR-setting-to-powerpc_excp.patch
  tools/packaging/qemu/patches/tag_patches/v6.2.0/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  versions.yaml
Labels: backport, area/QEMU

#3942 Don't use a globally installed mock hook for hook tests
  src/runtime/Makefile
  src/runtime/pkg/katautils/hook_test.go
  src/runtime/pkg/katautils/mockhook/.gitignore
  src/runtime/pkg/katautils/mockhook/Makefile
  src/runtime/pkg/katautils/mockhook/hook.go
  src/runtime/virtcontainers/Makefile
Labels: no-backport-needed, size/medium

#3909 static-build,clh: Add the ability to build from a PR
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Labels: no-backport-needed, area/cloud-hypervisor, size/small

#3934 Agent: fix unneeded late initialization lint
  src/agent/rustjail/src/cgroups/notifier.rs
  src/agent/rustjail/src/lib.rs
  src/agent/src/main.rs
  src/agent/src/mount.rs
  src/agent/src/signal.rs
  src/agent/src/util.rs
  src/agent/vsock-exporter/src/lib.rs
Labels: no-backport-needed, size/medium

#3951 docs: Update vcpu handling document
  docs/design/vcpu-handling.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation, size/medium

#3948 CCv0: Merge main into CCv0 branch
  .github/workflows/commit-message-check.yaml
  docs/how-to/run-kata-with-k8s.md
  docs/use-cases/using-Intel-SGX-and-kata.md
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/container_test.go
  src/runtime/virtcontainers/device/config/config.go
  src/runtime/virtcontainers/device/config/pmem.go
  src/runtime/virtcontainers/device/drivers/block.go
  src/runtime/virtcontainers/device/drivers/vhost_user_blk.go
  src/runtime/virtcontainers/device/manager/manager.go
  src/runtime/virtcontainers/device/manager/manager_linux_test.go
  src/runtime/virtcontainers/device/manager/manager_test.go
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/persist/api/device.go
  src/runtime/virtcontainers/persist_test.go
  src/runtime/virtcontainers/sandbox_test.go
  src/runtime/virtcontainers/utils/utils.go
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/qemu/patches/6.2.x/Revert-target-ppc-Move-SPR_DSISR-setting-to-powerpc_excp.patch
  tools/packaging/qemu/patches/tag_patches/v6.2.0/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  versions.yaml
Labels: area/confidential-containers, size/large

#3952 osbuilder/qat: use centos as base OS
  tools/osbuilder/dockerfiles/QAT/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#3919 runtime-rs: agent implements:
  src/libs/kata-types/src/config/agent.rs
  src/libs/kata-types/src/config/mod.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/mod.rs
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/agent/src/log_forwarder.rs
  src/runtime-rs/crates/agent/src/sock/hybrid_vsock.rs
  src/runtime-rs/crates/agent/src/sock/mod.rs
  src/runtime-rs/crates/agent/src/sock/vsock.rs
  src/runtime-rs/crates/agent/src/types.rs
Labels: runtime-rs, size/huge

#3921 CCv0 | github: Use `/etc/kata-containers/agent.toml`
  .github/workflows/deploy-ccv0-demo.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: area/github, area/confidential-containers, size/tiny

#3930 docs: fix markdown issues in how-to-run-docker-with-kata.md
  docs/how-to/how-to-run-docker-with-kata.md
Labels: no-backport-needed, force-skip-ci, size/tiny

#3966 osbuilder/qat: don't pull kata sources if exist
  tools/osbuilder/dockerfiles/QAT/run.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#3955 agent: Signal the whole process group
  src/agent/src/rpc.rs
  src/runtime/pkg/containerd-shim-v2/service.go
  src/runtime/pkg/containerd-shim-v2/start.go
  src/runtime/pkg/containerd-shim-v2/stream.go
  src/runtime/pkg/containerd-shim-v2/stream_test.go
  src/runtime/pkg/containerd-shim-v2/wait.go
Labels: needs-backport, size/large

#3977 stable-2.4 | tools: release: Do not consider release candidates as stable releases
  tools/packaging/release/update-repository-version.sh
Labels: backport

#3981 docs: Remove kata-proxy references in documentation
  docs/design/VSocks.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation, size/tiny

#3969 tools/packaging/kata-deploy: Copy install_yq.sh before starting parallel builds
  .github/workflows/release.yaml
  .gitignore
  tools/packaging/kata-deploy/local-build/.gitignore
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-copy-yq-installer.sh
Labels: no-backport-needed, size/small

#3962 runtime: Remove the explicit VirtioMem set and fix the comment
  src/runtime/virtcontainers/qemu.go
Labels: size/tiny

#3974 release: Include all the rust vendored code into the vendored tarball
  .github/workflows/release.yaml
  tools/packaging/release/generate_vendor.sh
Labels: needs-backport, size/medium

#3993 stable-2.4: release: Include all the rust vendored code into the vendored tarball
  .github/workflows/release.yaml
  tools/packaging/release/generate_vendor.sh
Labels: backport

#3987 kata-deploy: fix version bump from -rc to stable
  tools/packaging/release/update-repository-version.sh
Labels: needs-backport, size/small

#3991 tools/packaging: Fix error path in `kata-deploy-binaries.sh -s`
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: needs-backport, size/small

#3988 kata-deploy: fix version bump from -rc to stable
  tools/packaging/release/update-repository-version.sh
Labels: no-backport-needed

#3989 Stop getting OOM events from agent for "ttrpc closed" error
  src/runtime/pkg/containerd-shim-v2/wait.go
  src/runtime/virtcontainers/monitor.go
Labels: needs-backport, size/small

#3945 docs: Update to reflect logging changes
  docs/how-to/ccv0.sh
  docs/how-to/how-to-build-and-test-ccv0.md
Labels: area/confidential-containers, size/small

#3997 stable-2.4 | runtime: Stop getting OOM events from agent for "ttrpc closed" error
  src/runtime/pkg/containerd-shim-v2/wait.go
  src/runtime/virtcontainers/monitor.go
Labels: backport

#4003 stable-2.4 | kata-monitor: fix duplicated output when printing usage
  src/runtime/cmd/kata-monitor/main.go
Labels: backport

#4014 docs: Remove kata-proxy reference
  docs/how-to/how-to-use-kata-containers-with-acrn.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation, size/tiny

#3944 doc: Improve kata-deploy README.md by changing sh blocks to bash blocks
  tools/packaging/kata-deploy/README.md
Labels: no-backport-needed, area/documentation, size/small
