Repository kata-containers/kata-containers, pull requests merged in 2022-04, with the labels that each got.

#3995 agent: fix container stop error with signal SIGRTMIN+3
  src/agent/rustjail/src/process.rs
  src/agent/src/rpc.rs
Labels: needs-backport, size/small

#4000 CCv0: Refactor image verification doc and tests
  docs/how-to/ccv0.sh
  docs/how-to/how-to-build-and-test-ccv0.md
Labels: area/confidential-containers, size/large

#4011 versions: Bump firecracker to v0.23.4
  versions.yaml
Labels: needs-backport, size/tiny

#3957 CCv0: agent: Support https_proxy config for image download in guest
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/config.rs
  src/agent/src/image_rpc.rs
Labels: size/medium

#4024 # Kata Containers 2.4.0
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: no-backport-needed

#4025 # Kata Containers 2.5.0-alpha0
  VERSION
Labels: size/tiny

#4023 clh: Expose service offload configuration
  src/runtime/config/configuration-clh.toml.in
Labels: needs-backport, size/small

#3915 test: use `T.TempDir` to create temporary test directory
  docs/Unit-Test-Advice.md
  src/runtime/cmd/kata-runtime/factory_test.go
  src/runtime/cmd/kata-runtime/kata-check_amd64_test.go
  src/runtime/cmd/kata-runtime/kata-check_arm64_test.go
  src/runtime/cmd/kata-runtime/kata-check_generic_test.go
  src/runtime/cmd/kata-runtime/kata-check_ppc64le_test.go
  src/runtime/cmd/kata-runtime/kata-check_s390x_test.go
  src/runtime/cmd/kata-runtime/kata-check_test.go
  src/runtime/cmd/kata-runtime/kata-env_amd64_test.go
  src/runtime/cmd/kata-runtime/kata-env_generic_test.go
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/cmd/kata-runtime/main_test.go
  src/runtime/cmd/kata-runtime/utils_test.go
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/containerd-shim-v2/stream_test.go
  src/runtime/pkg/direct-volume/utils_test.go
  src/runtime/pkg/katatestutils/constraints_test.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/katautils/create_test.go
  src/runtime/pkg/katautils/network_test.go
  src/runtime/pkg/katautils/utils_test.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/pkg/utils/utils_test.go
  src/runtime/virtcontainers/container_test.go
  src/runtime/virtcontainers/device/config/config_test.go
  src/runtime/virtcontainers/device/manager/manager_linux_test.go
  src/runtime/virtcontainers/device/manager/manager_test.go
  src/runtime/virtcontainers/fs_share_linux_test.go
  src/runtime/virtcontainers/hypervisor_test.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mount_test.go
  src/runtime/virtcontainers/nydusd_test.go
  src/runtime/virtcontainers/qemu_test.go
  src/runtime/virtcontainers/sandbox_test.go
  src/runtime/virtcontainers/utils/utils_test.go
  src/runtime/virtcontainers/virtiofsd_test.go
  src/runtime/virtcontainers/vm_test.go
Labels: size/huge

#3923 runtime: Allow and require no initrd for SE
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_test.go
  src/runtime/virtcontainers/qemu.go
Labels: area/confidential-containers, area/s390x, size/small

#4012 docs: Add a firecracker installation guide
  docs/how-to/README.md
  docs/how-to/how-to-use-kata-containers-with-firecracker.md
Labels: no-backport-needed, no-forward-port-needed, size/large

#3696 kata-runtime enable hugepage support
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
Labels: size/tiny

#4039 CCv0 | ccv0.sh: Expand to also using Cloud Hypervisor
  docs/how-to/ccv0.sh
  docs/how-to/how-to-build-and-test-ccv0.md
Labels: size/small

#3926 CCv0 | Multistrap & enable cross-building guest
  ci/install_libseccomp.sh
  ci/install_musl.sh
  tools/osbuilder/dracut/Dockerfile.in
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile.in
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/template/Dockerfile.template
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
  tools/osbuilder/scripts/lib.sh
  tools/osbuilder/tests/test_images.sh
  utils.mk
  versions.yaml
Labels: area/osbuilder, area/confidential-containers, size/huge

#3879 Runtime rs service part
  src/agent/src/rpc.rs
  src/libs/kata-sys-util/src/validate.rs
  src/libs/kata-types/src/config/runtime.rs
  src/libs/logging/src/lib.rs
  src/libs/oci/src/lib.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/src/sock/mod.rs
  src/runtime-rs/crates/agent/src/sock/vsock.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/common/src/container_manager.rs
  src/runtime-rs/crates/runtimes/common/src/error.rs
  src/runtime-rs/crates/runtimes/common/src/lib.rs
  src/runtime-rs/crates/runtimes/common/src/message.rs
  src/runtime-rs/crates/runtimes/common/src/runtime_handler.rs
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_into_shim.rs
  src/runtime-rs/crates/runtimes/linux_container/Cargo.toml
  src/runtime-rs/crates/runtimes/linux_container/src/lib.rs
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml
  src/runtime-rs/crates/runtimes/wasm_container/src/lib.rs
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/service/src/lib.rs
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/service/src/task_service.rs
  src/runtime-rs/crates/shim/Cargo.toml
  src/runtime-rs/crates/shim/src/args.rs
  src/runtime-rs/crates/shim/src/lib.rs
  src/runtime-rs/crates/shim/src/shim.rs
  src/runtime-rs/crates/shim/src/shim_delete.rs
  src/runtime-rs/crates/shim/src/shim_run.rs
Labels: runtime-rs, size/huge

#4007 protocols: add src/csi.rs to .gitignore
  src/libs/protocols/.gitignore
Labels: no-backport-needed, size/tiny

#4059 rustjail: add test coverage for process_grpc_to_oci function
  src/agent/rustjail/src/lib.rs
Labels: size/large

#4048 runtime: delete debug option in virtiofsd
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/virtiofsd.go
  src/runtime/virtcontainers/virtiofsd_test.go
Labels: area/runtime, size/small

#3985 agent: add tests for do_write_stream function
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
Labels: size/large

#4057 agent: add test coverage for parse_mount_flags_and_options function
  src/agent/src/mount.rs
Labels: size/medium

#3994 Runtime rs resource part
  src/libs/kata-sys-util/src/cgroup.rs
  src/libs/kata-sys-util/src/lib.rs
  src/libs/kata-sys-util/src/spec.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/device/block.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/network.rs
  src/runtime-rs/crates/hypervisor/src/device/share_fs_device.rs
  src/runtime-rs/crates/hypervisor/src/device/share_fs_mount.rs
  src/runtime-rs/crates/hypervisor/src/device/vfio.rs
  src/runtime-rs/crates/hypervisor/src/device/vsock.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/cgroups/mod.rs
  src/runtime-rs/crates/resource/src/cgroups/utils.rs
  src/runtime-rs/crates/resource/src/lib.rs
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
  src/runtime-rs/crates/resource/src/rootfs/share_fs_rootfs.rs
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_inline.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
  src/runtime-rs/crates/resource/src/share_fs/utils.rs
  src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/default_volume.rs
  src/runtime-rs/crates/resource/src/volume/mod.rs
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
  src/runtime-rs/crates/resource/src/volume/shm_volume.rs
Labels: runtime-rs

#4069 agent: add tests for mount_storage
  src/agent/src/mount.rs
Labels: size/large

#4071 docs: Update link to contributions guide
  docs/Limitations.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation, size/tiny

#4078 agent: Avoid agent panic when reading empty stats
  src/agent/rustjail/src/cgroups/fs/mod.rs
Labels: needs-backport, area/agent

#4062 kata-monitor: add some links when generating pages for browsers
  src/runtime/cmd/kata-monitor/main.go
  src/runtime/pkg/kata-monitor/metrics.go
  src/runtime/pkg/kata-monitor/monitor.go
  src/runtime/pkg/kata-monitor/pprof.go
Labels: enhancement, no-backport-needed, size/medium

#4064 runtime: no need to write virtiofsd error to log
  src/runtime/virtcontainers/virtiofsd.go
Labels: no-backport-needed, size/small

#4021 runtime: Base64 encode the direct volume mountInfo path
  src/runtime/cmd/kata-runtime/kata-volume.go
  src/runtime/pkg/direct-volume/utils.go
  src/runtime/pkg/direct-volume/utils_test.go
  src/runtime/virtcontainers/kata_agent.go
Labels: needs-backport, size/medium

#4055 kata-monitor: update the hrefs in the debug/pprof index page
  src/runtime/pkg/kata-monitor/pprof.go
  src/runtime/pkg/kata-monitor/pprof_test.go
Labels: needs-backport, size/large

#4094 kata-monitor: add the README file
  docs/design/kata-2-0-metrics.md
  src/runtime/README.md
  src/runtime/cmd/kata-monitor/README.md
Labels: no-backport-needed, size/medium

#4042 fsGroup support for direct-assigned volume
  src/agent/src/mount.rs
  src/libs/protocols/protos/agent.proto
  src/libs/protocols/protos/types.proto
  src/runtime/pkg/direct-volume/utils.go
  src/runtime/pkg/direct-volume/utils_test.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
Labels: size/large

#4086 test: Fix golangci-lint error for s390x
  src/runtime/cmd/kata-runtime/kata-check_s390x_test.go
Labels: size/tiny

#4072 agent: best-effort removing mount point
  src/agent/src/sandbox.rs
Labels: needs-backport, size/small

#4102 Upgrade to Cloud Hypervisor v23.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpuFeatures.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VdpaConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpu_features.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vdpa_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: needs-backport, no-forward-port-needed, size/huge

#4092 CCv0: Merge main into CCv0 branch
  docs/Limitations.md
  src/agent/Makefile
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/lib.rs
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/libs/protocols/.gitignore
  src/runtime/cmd/kata-monitor/main.go
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/kata-monitor/metrics.go
  src/runtime/pkg/kata-monitor/monitor.go
  src/runtime/pkg/kata-monitor/pprof.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/virtiofsd.go
  src/runtime/virtcontainers/virtiofsd_test.go
Labels: area/confidential-containers, ignore-depends-on, size/huge

#3940 agent: add tests for is_signal_handled function
  src/agent/src/rpc.rs
Labels: size/large

#4035 agent: add tests for update_container_namespaces
  src/agent/src/rpc.rs
Labels: no-backport-needed, size/large

#4074 agent: add tests for mount_to_rootfs function
  src/agent/src/mount.rs
Labels: size/large

#4096 rustjail: Add tests for root_grpc_to_oci
  src/agent/rustjail/src/lib.rs
Labels: no-backport-needed, size/medium

#4116 CCv0: Merge main into CCv0 branch
  docs/design/kata-2-0-metrics.md
  src/agent/rustjail/src/lib.rs
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/libs/protocols/protos/agent.proto
  src/libs/protocols/protos/types.proto
  src/runtime/README.md
  src/runtime/cmd/kata-monitor/README.md
  src/runtime/cmd/kata-runtime/kata-check_s390x_test.go
  src/runtime/cmd/kata-runtime/kata-volume.go
  src/runtime/pkg/direct-volume/utils.go
  src/runtime/pkg/direct-volume/utils_test.go
  src/runtime/pkg/kata-monitor/pprof.go
  src/runtime/pkg/kata-monitor/pprof_test.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpuFeatures.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VdpaConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpu_features.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vdpa_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  src/runtime/virtcontainers/virtiofsd.go
  versions.yaml
Labels: area/confidential-containers, ignore-depends-on, size/huge

#4104 agent: move assert_result macro to test_utils file
  src/agent/src/config.rs
  src/agent/src/rpc.rs
  src/agent/src/test_utils.rs
Labels: no-backport-needed, size/medium

#3462 libs/safe-path: add crate to safely resolve fs paths
  README.md
  src/libs/Cargo.lock
  src/libs/Cargo.toml
  src/libs/README.md
  src/libs/safe-path/Cargo.toml
  src/libs/safe-path/README.md
  src/libs/safe-path/src/lib.rs
  src/libs/safe-path/src/pinned_path_buf.rs
  src/libs/safe-path/src/scoped_dir_builder.rs
  src/libs/safe-path/src/scoped_path_resolver.rs
Labels: no-backport-needed, size/huge

#4098 stable-2.4 | runtime: Base64 encode the direct volume mountInfo path
  src/runtime/cmd/kata-runtime/kata-volume.go
  src/runtime/pkg/direct-volume/utils.go
  src/runtime/pkg/direct-volume/utils_test.go
  src/runtime/virtcontainers/kata_agent.go
Labels: backport

#4120 stable-2.4 | versions: Upgrade to Cloud Hypervisor v23.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpuFeatures.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VdpaConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpu_features.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vdpa_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: backport

#4114 agent: modify the type of swappiness to u64
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/lib.rs
  src/libs/oci/src/lib.rs
  src/tools/agent-ctl/src/utils.rs
Labels: size/tiny

#4143 rustjail: Add tests for hooks_grpc_to_oci
  src/agent/rustjail/src/lib.rs
Labels: no-backport-needed, size/large

#4122 rustjail: add tests for mount_from function
  src/agent/rustjail/src/mount.rs
Labels: no-backport-needed, size/large

#4097 Rund new runtime impl
  src/agent/Cargo.lock
  src/libs/Cargo.lock
  src/libs/kata-sys-util/Cargo.toml
  src/libs/kata-sys-util/src/lib.rs
  src/libs/kata-sys-util/src/mount.rs
  src/libs/kata-sys-util/src/rand/mod.rs
  src/libs/kata-sys-util/src/rand/random_bytes.rs
  src/libs/kata-sys-util/src/rand/uuid.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/src/config/hypervisor/vendor.rs
  src/libs/kata-types/src/config/runtime.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/mod.rs
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/agent/src/sock/hybrid_vsock.rs
  src/runtime-rs/crates/agent/src/sock/mod.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/common/src/container_manager.rs
  src/runtime-rs/crates/runtimes/common/src/message.rs
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_from_agent.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_into_agent.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/container_io.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/mod.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/shim_io.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/mod.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
  src/runtime-rs/crates/runtimes/virt_container/src/health_check.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/shim/src/shim.rs
  src/runtime-rs/crates/shim/src/shim_delete.rs
  src/runtime-rs/crates/shim/src/shim_run.rs
  src/runtime-rs/crates/shim/src/shim_start.rs
Labels: runtime-rs

#4141 Fix Go unit tests to clean up /tmp after themselves
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/containerd-shim-v2/delete_test.go
  src/runtime/pkg/containerd-shim-v2/service_test.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/create_test.go
  src/runtime/pkg/katautils/hook_test.go
  src/runtime/virtcontainers/factory/cache/cache_test.go
  src/runtime/virtcontainers/factory/direct/direct_test.go
  src/runtime/virtcontainers/factory/factory_test.go
  src/runtime/virtcontainers/factory/template/template_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mount_test.go
  src/runtime/virtcontainers/persist/fs/fs.go
  src/runtime/virtcontainers/persist/fs/fs_test.go
  src/runtime/virtcontainers/persist/fs/mockfs.go
  src/runtime/virtcontainers/persist/fs/mockfs_test.go
  src/runtime/virtcontainers/persist/manager.go
  src/runtime/virtcontainers/persist/manager_test.go
  src/runtime/virtcontainers/virtcontainers_test.go
Labels: no-backport-needed, size/large

#4152 packaging: Fix broken path in `build-static-clh.sh`
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Labels: needs-backport, size/tiny

#4107 rustjail: Add tests for mount_grpc_to_oci
  src/agent/rustjail/src/lib.rs
Labels: size/medium

#3910 Agent: Unit tests for random.rs
  src/agent/src/random.rs
Labels: force-skip-ci, size/medium

#4156 docs: remove pc machine type supports
  docs/design/virtualization.md
Labels: size/tiny

#4163 docs: Update containerd link to installation guide
  docs/install/container-manager/containerd/containerd-install.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4161 kata-deploy: Add support to RKE2
  tools/packaging/kata-deploy/README.md
  tools/packaging/kata-deploy/kata-cleanup/overlays/rke2/kustomization.yaml
  tools/packaging/kata-deploy/kata-cleanup/overlays/rke2/mount_rke2_conf.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/rke2/kustomization.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/rke2/mount_rke2_conf.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: enhancement, no-backport-needed, area/kata-deploy, size/large

#4135 Implement network and disk rate limiter for Cloud Hypervisor
  src/runtime/config/configuration-clh.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/fc_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/utils/utils.go
  src/runtime/virtcontainers/utils/utils_test.go
Labels: needs-review, no-backport-needed, area/cloud-hypervisor, size/huge

#4166 agent-ctl: Fix abstract socket connections
  src/tools/agent-ctl/README.md
  src/tools/agent-ctl/src/client.rs
Labels: size/small

#3907 doc: Update for NVIDIA GPUs
  docs/use-cases/GPU-passthrough-and-Kata.md
  docs/use-cases/NVIDIA-GPU-passthrough-and-Kata.md
  docs/use-cases/Nvidia-GPU-passthrough-and-Kata.md
Labels: size/huge

#3248 docs: repropose direct-assigned volume
  docs/design/README.md
  docs/design/direct-blk-device-assignment.md
Labels: size/large

#4031 Virtcontainers: Enable hot plugging vhost-user-blk device on ARM
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, no-forward-port-needed, size/medium

#4178 runk: set BinaryName for runk for containerd
  src/tools/runk/README.md
Labels: no-backport-needed, size/tiny

#4119 agent: add tests for create_logger_task function
  src/agent/src/main.rs
  src/agent/src/mount.rs
  src/agent/src/test_utils.rs
Labels: size/medium
