Repository kata-containers/kata-containers, pull requests merged in 2022-10, with the labels that each got.

#5106 microvm: Remove kernel_irqchip=on option
  src/runtime/virtcontainers/qemu_amd64.go
Labels: needs-backport, size/tiny

#5311 Upgrade to Cloud Hypervisor v27.0
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PayloadConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/TdxConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_payload_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_tdx_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: size/huge

#5322 Stable-2.5 | Upgrade to Cloud Hypervisor v27.0
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PayloadConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/TdxConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_payload_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_tdx_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: size/huge

#5323 packaging: Mount $HOME/.docker in the 1st layer container
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
Labels: no-backport-needed, size/small

#5324 CC | packaging: Mount $HOME/.docker in the 1st layer container
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
Labels: size/small

#5319 CCv0: Add image_ttrpc_async.rs to .gitignore
  src/libs/protocols/.gitignore
Labels: no-backport-needed, area/confidential-containers, size/tiny

#5372 backport fix for 3.0.0 release
  src/libs/kata-sys-util/src/spec.rs
  versions.yaml
Labels: no-backport-needed, size/tiny

#5304 kata-sys-util: delete duplicated get_bundle_path
  src/libs/kata-sys-util/src/fs.rs
Labels: size/tiny

#5367 agent: don't exit early if signal fails due to ESRCH
  src/agent/Cargo.lock
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/console.rs
  src/agent/src/rpc.rs
Labels: needs-backport, size/small

#5365 agent: reduce reference count for failed mount
  src/agent/src/mount.rs
Labels: needs-backport, size/small, backport-to-stable-2.5

#5015 Enable ACRN hypervisor support for Kata 2.x release
  src/runtime/Makefile
  src/runtime/cmd/kata-runtime/kata-check_amd64.go
  src/runtime/pkg/device/drivers/block.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/acrn_arch_base.go
  src/runtime/virtcontainers/acrn_test.go
  src/runtime/virtcontainers/fs_share_linux.go
Labels: no-backport-needed, size/large

#5305 runtime-rs: delete duplicated PASSTHROUGH_FS_DIR const
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_inline.rs
Labels: runtime-rs, size/tiny

#5377 stable-3.0: backport agent fixes
  src/agent/Cargo.lock
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/console.rs
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
Labels: no-backport-needed, size/medium

#5111 libs/kata-types: adjust default_vcpus correctly
  src/libs/kata-types/src/config/hypervisor/mod.rs
Labels: runtime-rs, size/large

#5235 virtcontainers: add warn log record for qmp hotplug cpu error
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, size/tiny

#5302 runtime: fix incorrect comment for SetFsSharingSupport function
  src/runtime/virtcontainers/types/capabilities.go
Labels: size/tiny

#5380 # Kata Containers 3.1.0-alpha0
  .github/workflows/kata-deploy-test.yaml
  VERSION
  docs/Release-Process.md
Labels: size/small

#5379 # Kata Containers 3.0.0
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: size/tiny

#5276 readme: remove libraries mentioning
  README.md
  src/runtime-rs/README.md
Labels: no-backport-needed, size/tiny

#4961 Built-in Sandbox: add more unit tests for dragonball
  .github/workflows/static-checks.yaml
  Makefile
  src/dragonball/Cargo.toml
  src/dragonball/Makefile
  src/dragonball/src/address_space_manager.rs
  src/dragonball/src/api/v1/boot_source.rs
  src/dragonball/src/api/v1/instance_info.rs
  src/dragonball/src/api/v1/machine_config.rs
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/config_manager.rs
  src/dragonball/src/device_manager/blk_dev_mgr.rs
  src/dragonball/src/device_manager/fs_dev_mgr.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
  src/dragonball/src/device_manager/vsock_dev_mgr.rs
  src/dragonball/src/kvm_context.rs
  src/dragonball/src/resource_manager.rs
  src/dragonball/src/vcpu/vcpu_impl.rs
  src/dragonball/src/vm/mod.rs
  src/dragonball/src/vmm.rs
Labels: runtime-rs, size/huge

#5393 docs: fix a typo in rust-runtime-installation-guide
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
Labels: runtime-rs, size/tiny

#5282 runtime-rs: support ephemeral storage for emptydir
  src/libs/kata-sys-util/src/k8s.rs
  src/libs/kata-types/src/mount.rs
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: runtime-rs, size/medium

#5388 kata-ctl: Move development to main branch
  Makefile
  README.md
  src/tools/kata-ctl/.gitignore
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/Makefile
  src/tools/kata-ctl/README.md
  src/tools/kata-ctl/VERSION
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
  src/tools/kata-ctl/src/arch/mod.rs
  src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/ops.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/ops/version.rs.in
Labels: size/huge

#5397 Dragonball: delete redundant comments in blk_dev_mgr
  src/dragonball/src/device_manager/blk_dev_mgr.rs
Labels: runtime-rs

#5395 ci: skip s390x for dragonball.
  .github/workflows/static-checks.yaml
  src/dragonball/Makefile
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/vcpu/aarch64.rs
  src/dragonball/src/vcpu/vcpu_impl.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/dragonball/src/vm/aarch64.rs
  utils.mk
Labels: size/small

#5404 versions: Update TDX kernel
  tools/packaging/kernel/patches/5.15-plus-TDX.x/no_patches.txt
  versions.yaml
Labels: no-backport-needed, size/tiny

#5088 runtime-rs: force shutdown shim process in it can't exit
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/shim/src/shim_delete.rs
Labels: runtime-rs, size/small

#5412 kata-ctl: improve command descriptions for consistency
  src/tools/kata-ctl/src/args.rs
Labels: size/small

#5417 runtime-rs: fix typo get_contaier_type to get_container_type
  src/libs/kata-sys-util/src/spec.rs
  src/runtime-rs/crates/shim/src/shim_delete.rs
Labels: size/tiny

#5169 config: Add root hash value and measure config to kernel params
  src/runtime/Makefile
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small

#5400 image_rpc: avoid double and triple indirections
  src/agent/src/image_rpc.rs
Labels: no-backport-needed, size/small

#5407 image_rpc: Make `init_attestation_agent` fail gracefully
  src/agent/src/image_rpc.rs
Labels: no-backport-needed, size/small

#5383 Dragonball: remove redundant comments in event manager
  src/dragonball/src/event_manager.rs
Labels: runtime-rs, size/tiny

#5427 CC | backport TDX kernel and qemu repo updates
  tools/packaging/kernel/patches/5.15-plus-TDX.x/no_patches.txt
  tools/packaging/qemu/patches/tag_patches/TDX-v3.1/no_patches.txt
  versions.yaml
Labels: no-backport-needed, size/tiny

#5422 image_rpc: always call `verify_cid` after determining the cid
  src/agent/src/image_rpc.rs
Labels: no-backport-needed, size/large

#5426 virtiofsd: Build inside a container
  snap/snapcraft.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
  tools/packaging/static-build/virtiofsd/build.sh
  tools/packaging/static-build/virtiofsd/gnu/Dockerfile
  tools/packaging/static-build/virtiofsd/musl/Dockerfile
Labels: no-backport-needed, size/large

#5439 kata-ctl: Disable network check on s390x
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/arch/mod.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
Labels: size/medium

#5437 CC | backport | virtiofsd: Build inside a container
  snap/snapcraft.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
  tools/packaging/static-build/virtiofsd/build.sh
  tools/packaging/static-build/virtiofsd/gnu/Dockerfile
  tools/packaging/static-build/virtiofsd/musl/Dockerfile
Labels: size/large

#5414 runtime-rs: regulate the comment in runtime-rs makefile
  src/runtime-rs/Makefile
Labels: runtime-rs, size/small

#5461 CC | actions: Publish a payload on every CCv0 push
  .github/workflows/cc-payload-after-push.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: size/large

#5459 CC | action: Automate CC payload release
  .github/workflows/cc-payload.yaml
Labels: size/medium

#5219 Modify agent-url return value in runtime-rs
  src/runtime-rs/crates/agent/src/kata/mod.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: runtime-rs, size/small

#5466 CC | actions: Fix runtime-payload-ci registry address
  .github/workflows/cc-payload-after-push.yaml
Labels: size/tiny

#5465 qemu: Re-work static-build Dockerfile
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/qemu/build-base-qemu.sh
  tools/packaging/static-build/qemu/build-qemu.sh
Labels: no-backport-needed, size/medium

#5453 Makefile: fix an typo in runtime-rs makefile
  src/runtime-rs/Makefile
Labels: runtime-rs, size/tiny

#5314 CCv0: Optimize integrity device creation by avoiding a full device clear
  tools/osbuilder/rootfs-builder/init_trusted_storage.sh
Labels: size/medium

#5483 CC | packaging: Don't build runtime-rs if no RUST_VERSION is provided
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/shim-v2/install_go_rust.sh
Labels: size/small

#5455 agent: validate hugepage size is supported
  src/agent/rustjail/src/cgroups/fs/mod.rs
Labels: no-backport-needed, forward-port, size/small

#5192 CCv0: agent: validate hugepage size is supported
  src/agent/rustjail/src/cgroups/fs/mod.rs
Labels: size/small, auto-backport

#5089 agent: use NLM_F_REPLACE replace NLM_F_EXCL in rtnetlink
  src/agent/src/netlink.rs
Labels: runtime-rs, size/tiny

#5447 kata-ctl: Re-enable network tests on s390x (fixes 5438)
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
Labels: no-backport-needed, size/large

#5317 shim: Ensure pagesize is set when reporting hugetlb stats
  src/runtime/pkg/containerd-shim-v2/metrics.go
Labels: needs-backport, size/tiny

#5497 agent: remove redundant checks
  src/agent/src/sandbox.rs
Labels: area/agent, size/tiny

#5474 makefile: remove sudo when create symbolic link
  src/runtime-rs/Makefile
Labels: runtime-rs, size/tiny

#5488 rustjail: Upgrade libseccomp crate to v0.3.0
  src/agent/Cargo.lock
  src/agent/rustjail/Cargo.toml
Labels: no-backport-needed, area/agent, size/tiny

#5501 docs: update rust runtime installation guide
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
  tools/packaging/kata-deploy/README.md
Labels: no-backport-needed, no-forward-port-needed, runtime-rs, size/tiny

#5493 versions: Update Cloud Hypervisor to b4e39427080
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmAddDevice.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_add_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: no-backport-needed, size/huge

#5482 CC | Avoid rebuilding the containers used for building the artefacts
  .github/workflows/cc-payload-after-push.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/initramfs/build.sh
  tools/packaging/static-build/kernel/build.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/qemu/build-base-qemu.sh
  tools/packaging/static-build/qemu/build-qemu.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/td-shim/build.sh
  tools/packaging/static-build/virtiofsd/build.sh
  tools/packaging/static-build/virtiofsd/gnu/Dockerfile
  tools/packaging/static-build/virtiofsd/musl/Dockerfile
  versions.yaml
Labels: size/large

#5508 CC | Fix up issues with cached images
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/initramfs/Dockerfile
  tools/packaging/static-build/initramfs/build-initramfs.sh
  tools/packaging/static-build/initramfs/build.sh
  tools/packaging/static-build/kernel/build.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/qemu/build-base-qemu.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/td-shim/build.sh
  tools/packaging/static-build/virtiofsd/build.sh
Labels: no-backport-needed, size/large

#5458 CCv0: Merge main into CCv0 branch
  .github/workflows/static-checks.yaml
  Makefile
  README.md
  docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
  src/dragonball/Cargo.toml
  src/dragonball/Makefile
  src/dragonball/src/address_space_manager.rs
  src/dragonball/src/api/v1/boot_source.rs
  src/dragonball/src/api/v1/instance_info.rs
  src/dragonball/src/api/v1/machine_config.rs
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/config_manager.rs
  src/dragonball/src/device_manager/blk_dev_mgr.rs
  src/dragonball/src/device_manager/fs_dev_mgr.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
  src/dragonball/src/device_manager/vsock_dev_mgr.rs
  src/dragonball/src/event_manager.rs
  src/dragonball/src/kvm_context.rs
  src/dragonball/src/resource_manager.rs
  src/dragonball/src/vcpu/aarch64.rs
  src/dragonball/src/vcpu/vcpu_impl.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/dragonball/src/vm/aarch64.rs
  src/dragonball/src/vm/mod.rs
  src/dragonball/src/vmm.rs
  src/libs/kata-sys-util/src/k8s.rs
  src/libs/kata-sys-util/src/spec.rs
  src/libs/kata-types/src/mount.rs
  src/runtime-rs/Makefile
  src/runtime-rs/README.md
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
  src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/shim/src/shim_delete.rs
  src/tools/kata-ctl/.gitignore
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/Makefile
  src/tools/kata-ctl/README.md
  src/tools/kata-ctl/VERSION
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
  src/tools/kata-ctl/src/arch/mod.rs
  src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/ops.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/ops/version.rs.in
  utils.mk
Labels: no-backport-needed, area/confidential-containers, ignore-depends-on, size/huge

#5515 docs: Fix volumeMounts in SGX usage example
  docs/use-cases/using-Intel-SGX-and-kata.md
Labels: no-backport-needed, size/tiny

#5513 versions: bump golangci-lint version
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5436 Kata ctl drop privs
  src/tools/kata-ctl/.gitignore
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/utils.rs
Labels: size/huge

#5518 CC | packaging: Allow passing a container builder to the scripts
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/static-build/initramfs/build.sh
  tools/packaging/static-build/kernel/build.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/qemu/build-base-qemu.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/td-shim/build.sh
  tools/packaging/static-build/virtiofsd/build.sh
Labels: size/small

#5523 virtiofsd: Not use "link-self-contained=yes" on s390x
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
Labels: size/tiny

#5530 tools: Fix indentation of build static clh script
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Labels: needs-backport, no-forward-port-needed, size/medium

#5434 add EnterNetNS in virtcontainers
  src/runtime/pkg/katautils/network_linux.go
  src/runtime/virtcontainers/network_linux.go
Labels: size/small

#5398 CCv0: Use cached cc qemu tarball
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/cache_components.sh
  tools/packaging/static-build/qemu/build-static-qemu-cc.sh
Labels: no-backport-needed, no-forward-port-needed, size/large

#5533 CC | config: Export aa_kbc_params to be set in guest kernel command line
  src/agent/src/config.rs
Labels: size/small
