Repository kata-containers/kata-containers, pull requests merged in 2022-01, with the labels that each got.

#2840 use-cases: clarify SPDK vhost-user-nvme target status in using-spdk-v…
  docs/use-cases/using-SPDK-vhostuser-and-kata.md
Labels: stale

#3354 agent: return detail error message for RPC calls from shim
  src/agent/src/rpc.rs
Labels: no-backport-needed, no-forward-port-needed, area/agent

#3368 stable-2.3 Missing backports
  ci/openshift-ci/images/Dockerfile.buildroot
  pkg/logging/Cargo.toml
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/oci/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/src/metrics.rs
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
  src/trace-forwarder/Cargo.toml
  tools/agent-ctl/Cargo.toml
  tools/agent-ctl/src/utils.rs
  tools/osbuilder/Makefile
  tools/osbuilder/dockerfiles/QAT/Dockerfile
  tools/osbuilder/dracut/Dockerfile.in
  tools/osbuilder/image-builder/Dockerfile
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  tools/osbuilder/rootfs-builder/centos/Dockerfile.in
  tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
  tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
  tools/osbuilder/rootfs-builder/gentoo/Dockerfile.in
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/suse/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/action/Dockerfile
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
  tools/packaging/kata-monitor/Dockerfile
  tools/packaging/static-build/kernel/Dockerfile
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/shim-v2/Dockerfile
  tools/packaging/tests/Dockerfile/FedoraDockerfile.in
  utils/kata-manager.sh
Labels: needs-review, backport

#3366 runtime: fix a typo in kata-collect-data.sh
  src/runtime/data/kata-collect-data.sh.in
Labels: no-backport-needed, no-forward-port-needed

#3382 docs: Remove word duplication
  docs/Upgrading.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3253 agent: Refactor command line parsing to use a framework
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/main.rs
Labels: no-backport-needed, no-forward-port-needed

#3384 versions: Upgrade to Cloud Hypervisor v20.2
  versions.yaml
Labels: needs-backport, no-forward-port-needed

#3395 kata-deploy: fix tar command in dockerfile
  tools/packaging/kata-deploy/action/Dockerfile
Labels: needs-backport, no-forward-port-needed

#3397 stable-2.3 | versions: Upgrade to Cloud Hypervisor v20.2
  versions.yaml
Labels: backport

#3398 # Kata Containers 2.4.0-alpha1
  VERSION
Labels: needs-review, no-backport-needed, no-forward-port-needed

#3401 runtime: Remove docker comments for kata 2.0 configuration.tomls
  src/runtime/config/configuration-acrn.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
Labels: no-backport-needed, no-forward-port-needed

#3396 stable-2.3 | kata-deploy: fix tar command in dockerfile
  tools/packaging/kata-deploy/action/Dockerfile
Labels: backport

#3405 packaging: Remove obs packages testing for kata 2.0
  tools/packaging/tests/Dockerfile/Dockerfile.in
  tools/packaging/tests/Dockerfile/FedoraDockerfile.in
  tools/packaging/tests/run_obs_testing.sh
  tools/packaging/tests/run_packages_testing.sh
Labels: no-backport-needed, no-forward-port-needed, area/packaging

#3402 # Kata Containers 2.3.1
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: no-backport-needed, no-forward-port-needed

#3415 agent: fix the broken protobuf generation code
  src/agent/Makefile
  src/libs/protocols/hack/update-generated-proto.sh
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/health.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/healthpb_test.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/ocipb_test.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
Labels: no-backport-needed, no-forward-port-needed

#3421 CI: Revert "CI: Switch to a mirror as gnu.org is down"
  ci/install_libseccomp.sh
Labels: no-backport-needed, no-forward-port-needed

#3428 packaging: Remove ccloudvm instructions and script
  tools/packaging/ccloudvm/README.md
  tools/packaging/ccloudvm/kata-docker-xenial.yaml
Labels: no-backport-needed, no-forward-port-needed

#3425 runtime: close span before return from function in case of error
  src/runtime/virtcontainers/container.go
Labels: needs-backport, no-forward-port-needed

#3423 libs: add some generated files to .gitignore
  src/libs/oci/.gitignore
  src/libs/protocols/.gitignore
Labels: enhancement, no-backport-needed, no-forward-port-needed

#3433 kata-deploy: validate conf file can be created
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: needs-backport, no-forward-port-needed

#3441 runtime: Provide protection for shared data
  src/runtime/virtcontainers/kata_agent.go
Labels: needs-backport, no-forward-port-needed

#3449 docs: Remove ccloudvm reference
  tools/packaging/README.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3420 Remove all the non-tested rootfs
  tools/osbuilder/Makefile
  tools/osbuilder/README.md
  tools/osbuilder/dockerfiles/QAT/README.md
  tools/osbuilder/rootfs-builder/README.md
  tools/osbuilder/rootfs-builder/centos/Dockerfile.in
  tools/osbuilder/rootfs-builder/centos/config.sh
  tools/osbuilder/rootfs-builder/centos/config_aarch64.sh
  tools/osbuilder/rootfs-builder/centos/config_ppc64le.sh
  tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
  tools/osbuilder/rootfs-builder/fedora/config.sh
  tools/osbuilder/rootfs-builder/fedora/config_aarch64.sh
  tools/osbuilder/rootfs-builder/gentoo/Dockerfile.in
  tools/osbuilder/rootfs-builder/gentoo/config.sh
  tools/osbuilder/rootfs-builder/gentoo/rootfs_lib.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/suse/Dockerfile.in
  tools/osbuilder/rootfs-builder/suse/config.sh
  tools/osbuilder/rootfs-builder/suse/config.xml
  tools/osbuilder/rootfs-builder/suse/install-packages.sh
  tools/osbuilder/rootfs-builder/suse/rootfs_lib.sh
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3432 docs: fix a typo in host-cgroups.md doc
  docs/design/host-cgroups.md
Labels: force-skip-ci

#3446 packaging: Make kernel config accessible to guest
  tools/packaging/kernel/configs/fragments/common/debug.conf
Labels: no-backport-needed, no-forward-port-needed

#3188 update apiVersion
  docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
Labels: no-backport-needed, no-forward-port-needed

#3463 workflows: Use the correct branch ref on test kata-deploy
  .github/workflows/kata-deploy-test.yaml
Labels: needs-backport, no-forward-port-needed

#3470 runtime: -Wl,--s390-pgste for s390x
  src/runtime/Makefile
Labels: needs-backport, no-forward-port-needed, area/runtime, area/s390x

#3460 vendor: update govmm
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/runtime/Makefile
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go
  src/runtime/vendor/github.com/kata-containers/govmm/qemu/qmp.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/factory/factory_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, no-forward-port-needed

#3478 version: bump to kubernetes 1.23
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3468 govmm: Bring the project in
  src/runtime/pkg/govmm/.github/workflows/main.yml
  src/runtime/pkg/govmm/.gitignore
  src/runtime/pkg/govmm/.golangci.yml
  src/runtime/pkg/govmm/.travis.yml
  src/runtime/pkg/govmm/CONTRIBUTING.md
  src/runtime/pkg/govmm/COPYING
  src/runtime/pkg/govmm/README.md
  src/runtime/pkg/govmm/go.mod
  src/runtime/pkg/govmm/qemu/examples_test.go
  src/runtime/pkg/govmm/qemu/image.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_arch_base_test.go
  src/runtime/pkg/govmm/qemu/qemu_s390x_test.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
  src/runtime/pkg/govmm/qemu/qmp.go
  src/runtime/pkg/govmm/qemu/qmp_test.go
Labels: no-backport-needed, no-forward-port-needed, force-skip-ci

#3488 release: Escape backticks in Libseccomp Notices
  tools/packaging/release/release-notes.sh
Labels: no-backport-needed, no-forward-port-needed

#3486 workflows: Fix typo in kata-deploy-push action
  .github/workflows/kata-deploy-push.yaml
Labels: no-backport-needed, no-forward-port-needed

#3496 govmm: Use it from our own repo
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/pkg/govmm/CONTRIBUTING.md
  src/runtime/pkg/govmm/COPYING
  src/runtime/pkg/govmm/README.md
  src/runtime/pkg/govmm/go.mod
  src/runtime/pkg/govmm/qemu/examples_test.go
  src/runtime/pkg/govmm/qemu/image.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_arch_base_test.go
  src/runtime/pkg/govmm/qemu/qemu_s390x_test.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
  src/runtime/pkg/govmm/qemu/qmp.go
  src/runtime/pkg/govmm/qemu/qmp_test.go
  src/runtime/pkg/katautils/config.go
  src/runtime/vendor/github.com/kata-containers/govmm/COPYING
  src/runtime/vendor/github.com/kata-containers/govmm/qemu/image.go
  src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go
  src/runtime/vendor/github.com/kata-containers/govmm/qemu/qmp.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_arm64_test.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_ppc64le_test.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_s390x_test.go
  src/runtime/virtcontainers/qemu_test.go
Labels: no-backport-needed, no-forward-port-needed

#3503 workflows: Use base instead of head ref for kata-deploy-test
  .github/workflows/kata-deploy-test.yaml
Labels: no-backport-needed, no-forward-port-needed

#3506 docs: Redirect glossary to the wiki
  Glossary.md
Labels: force-skip-ci

#3514 docs: Remove kata-pkgsync reference
  tools/packaging/Makefile
  tools/packaging/README.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3370 agent: fix the issue of creating new namespaces for agent
  src/agent/src/namespace.rs
Labels: needs-backport, no-forward-port-needed

#3509 osbuilder: Remove libseccomp from Dockerfile
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
Labels: no-backport-needed, no-forward-port-needed

#3522 runtime: rectify passing empty options to -ldflags
  src/runtime/Makefile
Labels: needs-backport, no-forward-port-needed

#3520 Upgrade to Cloud Hypervisor v21.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/ReceiveMigrationData.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/SendMigrationData.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_receive_migration_data.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_send_migration_data.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: needs-backport, no-forward-port-needed

#3531 agent: resolve unused variables in tests
  src/agent/rustjail/src/mount.rs
  src/agent/src/util.rs
Labels: needs-backport, no-forward-port-needed

#3526 stable-2.3 | ci: Pass function arguments in static-checks.sh
  ci/lib.sh
  ci/static-checks.sh
Labels: needs-forward-port, no-backport-needed, area/ci

#3528 stable-2.3 | runtime: -Wl,--s390-pgste for s390x
  src/runtime/Makefile
Labels: no-forward-port-needed, backport, area/runtime

#3476 runtime: update runc and image-spec dependencies
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
  src/runtime/vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
  src/runtime/vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  src/runtime/vendor/github.com/opencontainers/image-spec/specs-go/version.go
  src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go
  src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/hugetlb.go
  src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/common.go
  src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/dbus.go
  src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v1.go
  src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v2.go
  src/runtime/vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
  src/runtime/vendor/modules.txt
Labels: no-backport-needed, no-forward-port-needed

#3546 docs: Remove docker run and sysctl limitation
  docs/Limitations.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3543 ci: Pass function arguments in static-checks.sh
  ci/lib.sh
  ci/static-checks.sh
Labels: forward-port, area/ci

#3532 stable-2.3: backport lint fixes from main
  src/agent/rustjail/src/mount.rs
  src/agent/src/network.rs
  src/agent/src/uevent.rs
  src/agent/src/util.rs
Labels: no-forward-port-needed, backport

#3504 Fix and re-enable s390x GoVMM tests
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_arch_base_test.go
  src/runtime/pkg/govmm/qemu/qemu_s390x_test.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
Labels: no-backport-needed, no-forward-port-needed, area/s390x, area/govmm

#3548 docs: Update networking details in the architecture doc
  docs/design/architecture/networking.md
Labels: no-backport-needed, no-forward-port-needed

#3560 kata-deploy: Fix the tag replacement logic
  tools/packaging/kata-deploy/action/test-kata.sh
Labels: no-backport-needed, no-forward-port-needed

#3561 stable-2.3 - kata-deploy: validate conf file can be created
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: backport

#2941 Sandbox sizing feature
  docs/design/vcpu-handling.md
  src/runtime/Makefile
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/sandbox.go
Labels: area/runtime

#3517 CCv0 | doc: Add crictl e2e cc doc
  docs/how-to/ccv0.sh
  docs/how-to/how-to-build-and-test-ccv0.md
Labels: area/confidential-containers

#3571 versions: update Rust to 1.58.1
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/mount.rs
  src/agent/src/namespace.rs
  src/agent/src/sandbox.rs
  src/agent/src/watcher.rs
  versions.yaml
Labels: security

#3567 virtcontainers: Enable initrd for Cloud Hypervisor
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/virtcontainers_test.go
Labels: no-backport-needed, no-forward-port-needed

#3575 stable-2.3-backports
  .github/workflows/PR-wip-checks.yaml
  .github/workflows/commit-message-check.yaml
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/move-issues-to-in-progress.yaml
  .github/workflows/require-pr-porting-labels.yaml
  .github/workflows/snap.yaml
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/kata_agent.go
  tools/packaging/static-build/qemu/build-base-qemu.sh
Labels: backport
