Repository kata-containers/kata-containers, pull requests merged in 2022-11, with the labels that each got.

#5544 CC | osbuilder: Install rats-tls-tdx
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
Labels: size/small

#5542 CC | agent: Bump pinned version of image-rs to support cosign signature verification
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/signal.rs
Labels: area/confidential-containers, size/huge

#5554 CCv0: Merge main into CCv0 branch
  docs/design/architecture_3.0/README.md
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
  docs/use-cases/using-Intel-SGX-and-kata.md
  src/agent/Cargo.lock
  src/agent/rustjail/Cargo.toml
  src/agent/src/netlink.rs
  src/agent/src/sandbox.rs
  src/runtime-rs/Makefile
  src/runtime-rs/crates/agent/src/kata/mod.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime/pkg/containerd-shim-v2/metrics.go
  src/runtime/pkg/katautils/network_linux.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/network_linux.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmAddDevice.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_add_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  src/tools/kata-ctl/.gitignore
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/utils.rs
  tools/packaging/kata-deploy/README.md
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
  versions.yaml
Labels: no-backport-needed, area/confidential-containers, ignore-depends-on, size/huge

#5374 osbuilder: specify Attestation Agent tag for rootfs build
  tools/osbuilder/rootfs-builder/rootfs.sh
  versions.yaml
Labels: size/tiny

#5562 CC | Agent: Allow agent config to be overwritten
  src/agent/src/config.rs
Labels: no-backport-needed, area/confidential-containers, size/medium

#5574 CC | clh: Increase the timeouts when using Conf Guests
  src/runtime/virtcontainers/clh.go
Labels: no-backport-needed, size/tiny

#5552 Sig ver param
  src/agent/src/config.rs
  src/agent/src/image_rpc.rs
  src/runtime/Makefile
Labels: area/confidential-containers, size/medium

#5571 snap: Unbreak docker install
  snap/snapcraft.yaml
Labels: needs-backport, size/tiny

#5557 runk: Upgrade libseccomp crate to v0.3.0 in Cargo.lock
  src/tools/runk/Cargo.lock
Labels: no-backport-needed, size/tiny

#5556 runk: Ignore an error when calling kill cmd with --all option
  src/tools/runk/libcontainer/src/container.rs
  src/tools/runk/libcontainer/src/status.rs
Labels: needs-backport, size/small

#5546 CC | runtime: Enable kernel hashes for all SEV guests
  src/runtime/virtcontainers/qemu_amd64.go
Labels: size/tiny

#5580 CC | config: Add specific config for TDX + EAA KBC
  .github/workflows/cc-payload-after-push.yaml
  .github/workflows/cc-payload.yaml
  src/runtime/Makefile
  src/runtime/config/configuration-clh-tdx-eaa-kbc.toml.in
  src/runtime/config/configuration-qemu-tdx-eaa-kbc.toml.in
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/huge

#5548 runtime-rs: fix shared volume permission issue
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
Labels: no-backport-needed, runtime-rs, size/tiny

#4476 vCPUs pinning support for Kata Containers
  docs/design/README.md
  docs/design/arch-images/vcpus-pinning-process.png
  docs/design/vcpu-threads-pinning.md
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/oci/utils.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/sandbox.go
Labels: size/large, soc

#5573 runtime-rs: blanks filled & fixes made to virtiofsd launch
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
Labels: runtime-rs, size/small

#5586 github: Parallelise static checks
  .github/workflows/static-checks.yaml
Labels: size/large

#5584 cloud-hypervisor: Fix GetThreadIDs function
  src/runtime/virtcontainers/clh.go
Labels: size/small

#5592 CC | github: Parallelise static checks
  .github/workflows/static-checks.yaml
  snap/snapcraft.yaml
Labels: no-backport-needed, size/large

#5570 runtime-rs:add hypervisor interface capabilities
  src/agent/Cargo.lock
  src/libs/Cargo.lock
  src/libs/kata-types/Cargo.toml
  src/libs/kata-types/src/capabilities.rs
  src/libs/kata-types/src/lib.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
Labels: runtime-rs, size/large

#5567 Dragonball: enable mem_file_path config into hugetlbfs process
  src/dragonball/src/vm/mod.rs
Labels: runtime-rs, size/tiny

#5600 CC: Make agent build differently for image-rs on s390x
  src/agent/Makefile
Labels: size/tiny

#5431 Built-in Sandbox: add more unit tests for dragonball. Part 3
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/lib.rs
  src/dragonball/src/test_utils.rs
  src/dragonball/src/vm/mod.rs
Labels: size/large

#5613 feat(shim-mgmt): iptables handler
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/client.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: size/large

#5615 runtime-rs: delete all cargo patches
  src/dragonball/Cargo.toml
  src/runtime-rs/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
Labels: runtime-rs, size/small

#5637 versions: update vmm-sys-util and related crates to v0.11.0
  src/dragonball/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
Labels: size/large

#5536 runtime-rs : fix the shim source in the documentation test is ambiguous
  src/runtime-rs/crates/shim/src/lib.rs
Labels: runtime-rs, size/tiny

#5505 docs: Fix configuration path
  docs/how-to/how-to-use-kata-containers-with-firecracker.md
Labels: size/tiny

#5631 tools: Fix indentation of build static virtiofsd script
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
Labels: needs-backport, size/large

#5597 clh: avoid race condition when stopping clh
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/qemu.go
Labels: needs-backport, size/small

#5679 docs: update doc "Setup swap device in guest kernel"
  docs/how-to/how-to-setup-swap-devices-in-guest-kernel.md
Labels: size/tiny

#5684 Upgrade to Cloud Hypervisor v28.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/TpmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_tpm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: needs-backport, size/large, backport-to-stable-3.0

#5638 versions: update nydusd version
  src/runtime/virtcontainers/nydusd.go
  src/runtime/virtcontainers/nydusd_test.go
  versions.yaml
Labels: size/tiny

#5689 utils: Add utility function to fetch the kernel version.
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/utils.rs
Labels: size/large

#5691 runtime-rs: support vhost-vsock
  src/libs/kata-types/src/config/agent.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/agent/src/sock/mod.rs
  src/runtime-rs/crates/agent/src/sock/vsock.rs
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/vsock.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
Labels: runtime-rs, size/large

#5709 docs: update doc "NVIDIA GPU passthrough"
  docs/use-cases/NVIDIA-GPU-passthrough-and-Kata.md
Labels: size/tiny

#5695 runtime: Support virtiofs queue size for qemu and make it configurable
  src/runtime/Makefile
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/device/config/config.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_arch_base.go
Labels: size/small

#5727 package: add nydus to release artifacts
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/nydus/build.sh
Labels: size/medium

#5720 runtime: add log record to the qemu config method `appendDevices` for…
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
Labels: needs-backport, size/small

#5707 Refactor(runtime-rs): add conditional compile for virt-sandbox persist
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox_persist.rs
Labels: runtime-rs, size/small

#5671 tools: Improve cached artifacts for qemu
  tools/packaging/static-build/cache_components.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5746 CC | runtime: Revendor containerd to v1.6.8
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/github.com/Microsoft/hcsshim/internal/jobobject/iocp.go
  src/runtime/vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
  src/runtime/vendor/github.com/Microsoft/hcsshim/internal/jobobject/limits.go
  src/runtime/vendor/github.com/Microsoft/hcsshim/internal/queue/mq.go
  src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
  src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go
  src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/system.go
  src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
  src/runtime/vendor/github.com/containerd/containerd/version/version.go
  src/runtime/vendor/modules.txt
Labels: size/small

#5729 runtime-rs: block on the current thread when setup the network to avoid be take over by other task
  src/runtime-rs/crates/resource/src/manager_inner.rs
Labels: bug, runtime-rs, size/small

#5742 kernel: add CONFIG_X86_SGX into whitelist
  tools/packaging/kernel/configs/fragments/whitelist.conf
Labels: size/tiny

#5714 runtime: don't fail mkdir if the folder is already created by another process
  src/runtime/virtcontainers/utils/utils.go
Labels: needs-backport, size/tiny

#5711 CC: Fix errors on building cc-builders on s390x
  tools/packaging/static-build/initramfs/Dockerfile
  tools/packaging/static-build/shim-v2/build.sh
Labels: size/small

#5618 CCv0: Use cached kernel
  tools/packaging/static-build/cache_components.sh
  tools/packaging/static-build/kernel/build.sh
Labels: area/confidential-containers, size/large

#5771 CC | build: export kernel_version to be used with its build script
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/kernel/build.sh
Labels: size/tiny

#5758 doc: update runtime-rs "Build and Install"
  src/runtime-rs/README.md
Labels: size/tiny

#5752 runtime: go fix code for 1.19
  src/runtime/cmd/kata-runtime/kata-check_generic_test.go
  src/runtime/cmd/kata-runtime/kata-env_generic_test.go
  src/runtime/go.mod
  src/runtime/pkg/govmm/qemu/qemu_arch_base_test.go
  src/runtime/pkg/resourcecontrol/cgroups.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/acrn_arch_base.go
  src/runtime/virtcontainers/acrn_test.go
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/fc_metrics.go
  src/runtime/virtcontainers/fc_test.go
  src/runtime/virtcontainers/ipvlan_endpoint.go
  src/runtime/virtcontainers/ipvlan_endpoint_test.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/macvlan_endpoint.go
  src/runtime/virtcontainers/macvlan_endpoint_test.go
  src/runtime/virtcontainers/macvtap_endpoint.go
  src/runtime/virtcontainers/macvtap_endpoint_test.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/physical_endpoint.go
  src/runtime/virtcontainers/physical_endpoint_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_arm64_test.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_ppc64le_test.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_s390x_test.go
  src/runtime/virtcontainers/qemu_test.go
  src/runtime/virtcontainers/tap_endpoint.go
  src/runtime/virtcontainers/tuntap_endpoint.go
  src/runtime/virtcontainers/utils/utils_linux_generic.go
  src/runtime/virtcontainers/veth_endpoint.go
  src/runtime/virtcontainers/veth_endpoint_test.go
  src/runtime/virtcontainers/vhostuser_endpoint.go
  src/runtime/virtcontainers/vhostuser_endpoint_test.go
Labels: size/small

#5699 Stable-3.0 | Upgrade to Cloud Hypervisor v28.0
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PayloadConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/TdxConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/TpmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmAddDevice.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_payload_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_tdx_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_tpm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_add_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: backport, size/huge

#5762 actions: skip some jobs using "paths-ignore" filter
  .github/workflows/cargo-deny-runner.yaml
  .github/workflows/darwin-tests.yaml
  .github/workflows/snap.yaml
Labels: area/ci, size/small

#5154 agent: support systemd cgroup for kata agent.
  docs/design/README.md
  docs/design/agent-systemd-cgroup.md
  src/agent/Cargo.lock
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/mock.rs
  src/agent/rustjail/src/cgroups/mod.rs
  src/agent/rustjail/src/cgroups/systemd.rs
  src/agent/rustjail/src/cgroups/systemd/cgroups_path.rs
  src/agent/rustjail/src/cgroups/systemd/common.rs
  src/agent/rustjail/src/cgroups/systemd/dbus_client.rs
  src/agent/rustjail/src/cgroups/systemd/interface/mod.rs
  src/agent/rustjail/src/cgroups/systemd/interface/session.rs
  src/agent/rustjail/src/cgroups/systemd/interface/system.rs
  src/agent/rustjail/src/cgroups/systemd/manager.rs
  src/agent/rustjail/src/cgroups/systemd/mod.rs
  src/agent/rustjail/src/cgroups/systemd/subsystem/cpu.rs
  src/agent/rustjail/src/cgroups/systemd/subsystem/cpuset.rs
  src/agent/rustjail/src/cgroups/systemd/subsystem/memory.rs
  src/agent/rustjail/src/cgroups/systemd/subsystem/mod.rs
  src/agent/rustjail/src/cgroups/systemd/subsystem/pids.rs
  src/agent/rustjail/src/cgroups/systemd/subsystem/transformer.rs
  src/agent/rustjail/src/container.rs
  src/agent/src/rpc.rs
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/tools/agent-ctl/Cargo.lock
  src/tools/runk/Cargo.lock
  src/tools/runk/libcontainer/src/container.rs
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
Labels: size/huge, soc

#5744 CC | agent: Update the merge_oci_process to properly manage the env variables
  src/agent/src/rpc.rs
Labels: no-backport-needed, area/confidential-containers, size/medium

#5776 ci: let static checks don't depend on build
  Makefile
  src/agent/Makefile
  src/dragonball/Makefile
  src/libs/Makefile
  src/runtime-rs/Makefile
  src/runtime/Makefile
  src/tools/agent-ctl/Makefile
  src/tools/kata-ctl/Makefile
  src/tools/log-parser/Makefile
  src/tools/runk/Makefile
  src/tools/trace-forwarder/Makefile
  utils.mk
Labels: no-backport-needed, area/ci, size/small

#5748 tools: Remove extra tab spaces from kata deploy binaries script
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5761 runtime-rs: moving only vCPU threads into sandbox controller
  src/runtime-rs/crates/resource/src/cgroups/mod.rs
Labels: size/tiny

#5612 fix(agent): fix iptables binary path in guest
  src/agent/src/rpc.rs
Labels: size/medium

#5781 snap: Fix snapcraft setup (unbreak snap releases)
  .github/workflows/snap-release.yaml
  .github/workflows/snap.yaml
Labels: size/small

#5774 build: update golang version to 1.19.3
  .github/workflows/darwin-tests.yaml
  .github/workflows/docs-url-alive-check.yaml
  .github/workflows/static-checks.yaml
  versions.yaml
Labels: needs-backport, size/small, backport-to-stable-3.0

#5649 runk: Re-implement start operation using the agent codes
  src/tools/runk/libcontainer/src/activated_builder.rs
  src/tools/runk/libcontainer/src/container.rs
  src/tools/runk/libcontainer/src/created_builder.rs
  src/tools/runk/libcontainer/src/lib.rs
  src/tools/runk/src/commands/start.rs
  src/tools/runk/src/main.rs
Labels: no-backport-needed, size/large

#5680 CC | agent: Add auth reg support to the agent
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/image_rpc.rs
Labels: size/large

#5767 CC: Merge main into CCv0 branch
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
  docs/design/direct-blk-device-assignment.md
  docs/use-cases/NVIDIA-GPU-passthrough-and-Kata.md
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/rpc.rs
  src/libs/kata-types/src/config/agent.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/agent/src/sock/mod.rs
  src/runtime-rs/crates/agent/src/sock/vsock.rs
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/vsock.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox_persist.rs
  src/runtime/Makefile
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/go.mod
  src/runtime/pkg/device/config/config.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
  src/runtime/pkg/katautils/config.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/nydusd.go
  src/runtime/virtcontainers/nydusd_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/utils.rs
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/static-build/firecracker/build-static-firecracker.sh
  tools/packaging/static-build/nydus/build.sh
  versions.yaml
Labels: no-backport-needed, area/confidential-containers, ignore-depends-on, size/huge

#5733 CC | agent: Update the merge_oci_process function to change cwd
  src/agent/src/rpc.rs
Labels: no-backport-needed, area/confidential-containers, size/medium
