Repository kata-containers/kata-containers, pull requests merged in 2022-05, with the labels that each got.

#4158 CCv0: Merge main into CCv0 branch
  README.md
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/mount.rs
  src/agent/src/config.rs
  src/agent/src/random.rs
  src/agent/src/rpc.rs
  src/agent/src/test_utils.rs
  src/libs/Cargo.lock
  src/libs/Cargo.toml
  src/libs/README.md
  src/libs/oci/src/lib.rs
  src/libs/safe-path/Cargo.toml
  src/libs/safe-path/README.md
  src/libs/safe-path/src/lib.rs
  src/libs/safe-path/src/pinned_path_buf.rs
  src/libs/safe-path/src/scoped_dir_builder.rs
  src/libs/safe-path/src/scoped_path_resolver.rs
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/containerd-shim-v2/delete_test.go
  src/runtime/pkg/containerd-shim-v2/service_test.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/create_test.go
  src/runtime/pkg/katautils/hook_test.go
  src/runtime/virtcontainers/factory/cache/cache_test.go
  src/runtime/virtcontainers/factory/direct/direct_test.go
  src/runtime/virtcontainers/factory/factory_test.go
  src/runtime/virtcontainers/factory/template/template_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mount_test.go
  src/runtime/virtcontainers/persist/fs/fs.go
  src/runtime/virtcontainers/persist/fs/fs_test.go
  src/runtime/virtcontainers/persist/fs/mockfs.go
  src/runtime/virtcontainers/persist/fs/mockfs_test.go
  src/runtime/virtcontainers/persist/manager.go
  src/runtime/virtcontainers/persist/manager_test.go
  src/runtime/virtcontainers/virtcontainers_test.go
  src/tools/agent-ctl/src/utils.rs
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Labels: area/confidential-containers, ignore-depends-on, size/huge

#4197 clh: Rely on Cloud Hypervisor for generating the device ID
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
Labels: needs-backport, area/cloud-hypervisor, size/small

#4189 agent watchers: ensure uid/gid is preserved on copy/mkdir
  src/agent/src/watcher.rs
Labels: needs-backport, size/medium

#4203 # Kata Containers 2.5.0-alpha1
  VERSION
Labels: size/tiny

#4187 rustjail: Add tests for hook_grpc_to_oci
  src/agent/rustjail/src/lib.rs
Labels: no-backport-needed, size/medium

#4137 agent: add test coverage for functions find_process and online_resources
  src/agent/src/sandbox.rs
Labels: no-backport-needed, size/large

#4184 runk: use custom Kill command to support --all option
  src/tools/runk/src/commands/kill.rs
  src/tools/runk/src/main.rs
Labels: no-backport-needed, size/small

#4186 agent: Add a macro to skip a loop easier
  src/agent/src/mount.rs
  src/agent/src/test_utils.rs
Labels: no-backport-needed, size/small

#4223 versions: Upgrade to Cloud Hypervisor v23.1
  versions.yaml
Labels: needs-backport, no-forward-port-needed, size/tiny

#4229 stable-2.4 | versions: Upgrade to Cloud Hypervisor v23.1
  versions.yaml
Labels: backport

#4242 doc: Allow ccv0 to run as non-root user
  docs/how-to/ccv0.sh
Labels: area/confidential-containers, size/small

#4233 Build and distribute the rust version of virtiofsd
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
  versions.yaml
Labels: no-backport-needed, area/virtiofs, size/medium

#4221 CCv0: Refactored ccv0.sh to use new shared library
  docs/how-to/ccv0.sh
Labels: area/confidential-containers, size/medium

#4264 docs: Update runc containerd runtime
  docs/how-to/privileged.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation, size/tiny

#4255 tools: Add QEMU patches for SGX numa support
  tools/packaging/qemu/patches/6.2.x/0001-numa-Enable-numa-for-SGX-EPC-sections.patch
  tools/packaging/qemu/patches/6.2.x/0002-numa-Support-SGX-numa-in-the-monitor-and-Libvirt-int.patch
  tools/packaging/qemu/patches/6.2.x/0003-doc-Add-the-SGX-numa-description.patch
Labels: needs-backport, size/huge

#4268 stable-2.4 | tools: Add QEMU patches for SGX numa support
  tools/packaging/qemu/patches/6.2.x/0001-numa-Enable-numa-for-SGX-EPC-sections.patch
  tools/packaging/qemu/patches/6.2.x/0002-numa-Support-SGX-numa-in-the-monitor-and-Libvirt-int.patch
  tools/packaging/qemu/patches/6.2.x/0003-doc-Add-the-SGX-numa-description.patch
Labels: backport

#4220 ci: Don't run Docs URL Alive Check workflow on forks
  .github/workflows/docs-url-alive-check.yaml
Labels: no-backport-needed

#4267 packaging: Add kernel config option for SGX in Gramine
  tools/packaging/kernel/configs/fragments/x86_64/sgx.conf
  tools/packaging/kernel/kata_config_version
Labels: no-backport-needed, size/tiny

#4191 Improve Go unit test script
  ci/go-test.sh
  ci/lib.sh
  src/runtime/.gitignore
  src/runtime/Makefile
  src/runtime/go-test.sh
Labels: no-backport-needed, size/large

#4252 agent: Fix is_signal_handled failing parsing str to u64
  src/agent/src/rpc.rs
Labels: needs-backport, size/small

#4269 tools: delete unused param from get_from_kata_deps callers
  tools/packaging/scripts/gen_versions_txt.sh
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
  tools/packaging/static-build/firecracker/build-static-firecracker.sh
Labels: no-backport-needed, size/small

#4273 kernel: Remove nemu.conf from packaging
  tools/packaging/kernel/configs/fragments/x86_64/nemu.conf
  tools/packaging/kernel/kata_config_version
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4271 runtime: do not check for EOF error in console watcher
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, size/small

#4279 docs: Remove clear containers reference in README
  tools/osbuilder/rootfs-builder/README.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4277 CCv0: Merge main into CCv0 branch
  .github/workflows/docs-url-alive-check.yaml
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
  ci/go-test.sh
  ci/lib.sh
  docs/how-to/privileged.md
  src/agent/src/rpc.rs
  src/runtime/.gitignore
  src/runtime/Makefile
  src/runtime/go-test.sh
  src/runtime/virtcontainers/sandbox.go
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/configs/fragments/x86_64/nemu.conf
  tools/packaging/kernel/configs/fragments/x86_64/sgx.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/qemu/patches/6.2.x/0001-numa-Enable-numa-for-SGX-EPC-sections.patch
  tools/packaging/qemu/patches/6.2.x/0002-numa-Support-SGX-numa-in-the-monitor-and-Libvirt-int.patch
  tools/packaging/qemu/patches/6.2.x/0003-doc-Add-the-SGX-numa-description.patch
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/scripts/gen_versions_txt.sh
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
  tools/packaging/static-build/firecracker/build-static-firecracker.sh
  tools/packaging/static-build/scripts/qemu-build-post.sh
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
  versions.yaml
Labels: area/confidential-containers, ignore-depends-on, size/huge

#4238 qemu: allow using legacy serial device for the console
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_s390x.go
Labels: no-backport-needed, no-forward-port-needed, size/large

#4281 runtime: sync docstrings with function names
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, size/small

#4282 runtime: remove duplicate 'types' import
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, size/large

#4213 runtime: Adding the correct detection of mediated PCIe devices
  src/runtime/virtcontainers/device/drivers/utils.go
  src/runtime/virtcontainers/device/drivers/vfio.go
  src/runtime/virtcontainers/device/drivers/vfio_test.go
Labels: needs-backport, area/runtime, size/small

#4287 CCv0: Fix ccv0.sh to install virtiofsd
  docs/how-to/ccv0.sh
Labels: area/confidential-containers, size/tiny

#4294 runtime: fix incorrect Action function for direct-volume stats
  src/runtime/cmd/kata-runtime/kata-volume.go
Labels: needs-backport, size/small

#4298 Fix issues with direct-volume stats feature
  src/agent/src/rpc.rs
  src/runtime/cmd/kata-runtime/kata-volume.go
  src/runtime/pkg/containerd-shim-v2/shim_management.go
Labels: needs-backport, size/large

#4290 runk: merge oci-kata-agent into runk
  src/agent/Cargo.toml
  src/agent/rustjail/src/container.rs
  src/tools/runk/Makefile
  src/tools/runk/README.md
  src/tools/runk/src/main.rs
Labels: no-backport-needed, no-forward-port-needed, size/medium

#4105 runtime-rs: support network resource
  src/libs/Cargo.lock
  src/libs/kata-sys-util/Cargo.toml
  src/libs/kata-sys-util/src/rand/random_bytes.rs
  src/libs/kata-sys-util/src/rand/uuid.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/lib.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
  src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/veth_endpoint.rs
  src/runtime-rs/crates/resource/src/network/mod.rs
  src/runtime-rs/crates/resource/src/network/network_entity.rs
  src/runtime-rs/crates/resource/src/network/network_info/mod.rs
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs
  src/runtime-rs/crates/resource/src/network/network_model/mod.rs
  src/runtime-rs/crates/resource/src/network/network_model/none_model.rs
  src/runtime-rs/crates/resource/src/network/network_model/route_model.rs
  src/runtime-rs/crates/resource/src/network/network_model/tc_filter_model.rs
  src/runtime-rs/crates/resource/src/network/network_pair.rs
  src/runtime-rs/crates/resource/src/network/network_with_netns.rs
  src/runtime-rs/crates/resource/src/network/utils/address.rs
  src/runtime-rs/crates/resource/src/network/utils/link/create.rs
  src/runtime-rs/crates/resource/src/network/utils/link/driver_info.rs
  src/runtime-rs/crates/resource/src/network/utils/link/macros.rs
  src/runtime-rs/crates/resource/src/network/utils/link/manager.rs
  src/runtime-rs/crates/resource/src/network/utils/link/mod.rs
  src/runtime-rs/crates/resource/src/network/utils/mod.rs
  src/runtime-rs/crates/resource/src/network/utils/netns.rs
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
Labels: runtime-rs, size/huge

#4301 snap: Build and package rust version of virtiofsd
  snap/snapcraft.yaml
Labels: size/medium

#4318 clh: Update to v24.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: needs-backport, size/medium

#3871 Update containerd docs
  docs/how-to/containerd-kata.md
Labels: size/large

#4274 stable-2.4: backport agent fixes
  src/agent/src/config.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/test_utils.rs
Labels: backport

#4353 agent, runk: Enable test for the agent built with standard-oci-runtime feature
  src/agent/rustjail/src/console.rs
  src/tools/runk/Makefile
Labels: size/small
