Repository kata-containers/kata-containers, pull requests merged in 2022-07, with the labels that each got.

#4527 runtime-rs:refactor network model with netlink
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/network/network_model/mod.rs
  src/runtime-rs/crates/resource/src/network/network_model/tc_filter_model.rs
  src/runtime-rs/crates/resource/src/network/network_model/test_network_model.rs
Labels: runtime-rs, size/large

#4380 runtime-rs: makefile for dragonball
  src/runtime-rs/.gitignore
  src/runtime-rs/Makefile
  src/runtime-rs/arch/x86_64-options.mk
  src/runtime-rs/config/configuration-dragonball.toml.in
  utils.mk
Labels: runtime-rs, size/huge

#4571 stable-2.4 | shim: set a non-zero return code if the wait process call failed.
  src/runtime/pkg/containerd-shim-v2/wait.go
  src/runtime/virtcontainers/sandbox.go
Labels: backport

#4570 CC | packaging: Add a build target for all the "unmodified" components
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/qemu/build-static-qemu-cc.sh
Labels: size/large

#4560 ci/cd: update check-commit-message
  .github/workflows/commit-message-check.yaml
Labels: no-backport-needed, size/tiny

#4573 build: Set safe.directory for runtime repo
  tools/packaging/static-build/shim-v2/build.sh
Labels: size/tiny

#4550 runtime: overwrite mount type to bind for bind mounts
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
Labels: size/medium

#4576 agent: Run OCI poststart hooks after a container is launched
  src/agent/rustjail/src/container.rs
  src/agent/src/rpc.rs
Labels: size/medium

#4574 oci: fix serde skip serializing condition
  src/libs/oci/src/lib.rs
Labels: size/tiny

#4479 agent: enhance get handled signal
  src/agent/src/rpc.rs
Labels: no-backport-needed

#4543 runtime-rs: Dragonball sandbox - add Vcpu::configure() function for aarch64
  src/dragonball/Cargo.toml
  src/dragonball/src/vcpu/aarch64.rs
  src/dragonball/src/vcpu/vcpu_impl.rs
Labels: runtime-rs, size/large

#4109 Drop in cfg files support
  src/runtime/README.md
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
Labels: size/large

#4591 # Kata Containers 2.5.0-rc0
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml
Labels: force-skip-ci, size/large

#4597 action: revert commit message limit to 150 bytes
  .github/workflows/commit-message-check.yaml
Labels: size/tiny

#4533 tools/snap: simplify nproc
  docs/Developer-Guide.md
  docs/use-cases/using-Intel-QAT-and-kata.md
  snap/snapcraft.yaml
  tools/osbuilder/dockerfiles/QAT/run.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/static-build/qemu/Dockerfile
Labels: size/small

#4616 docs: Update URL links for containerd documentation
  docs/how-to/containerd-kata.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4600 runtime: Fix DisableSelinux config
  src/runtime/config/configuration-acrn.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
Labels: needs-backport, size/small

#4515 runtime-rs: built-in Dragonball sandbox part III - virtio-blk, virtio-fs, virtio-net and VMM API support
  src/dragonball/Cargo.toml
  src/dragonball/docs/api.md
  src/dragonball/src/address_space_manager.rs
  src/dragonball/src/api/v1/boot_source.rs
  src/dragonball/src/api/v1/instance_info.rs
  src/dragonball/src/api/v1/machine_config.rs
  src/dragonball/src/api/v1/mod.rs
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/config_manager.rs
  src/dragonball/src/device_manager/blk_dev_mgr.rs
  src/dragonball/src/device_manager/console_manager.rs
  src/dragonball/src/device_manager/fs_dev_mgr.rs
  src/dragonball/src/device_manager/memory_region_handler.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
  src/dragonball/src/device_manager/vsock_dev_mgr.rs
  src/dragonball/src/error.rs
  src/dragonball/src/event_manager.rs
  src/dragonball/src/lib.rs
  src/dragonball/src/vcpu/aarch64.rs
  src/dragonball/src/vcpu/mod.rs
  src/dragonball/src/vcpu/vcpu_impl.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/dragonball/src/vm/aarch64.rs
  src/dragonball/src/vm/kernel_config.rs
  src/dragonball/src/vm/mod.rs
  src/dragonball/src/vm/x86_64.rs
  src/dragonball/src/vmm.rs
Labels: runtime-rs, size/huge

#4595 Fix clh tarball build
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Labels: needs-backport, size/small

#4192 kata 3.0 Architecture
  README.md
  docs/design/architecture_3.0/README.md
  docs/design/architecture_3.0/images/architecture.png
  docs/design/architecture_3.0/images/built_in_vmm.png
  docs/design/architecture_3.0/images/framework.png
  docs/design/architecture_3.0/images/not_built_in_vmm.png
  docs/design/architecture_3.0/images/resourceManager.png
  docs/design/architecture_3.0/images/source_code/kata_3.0_images.drawio
  docs/hypervisors.md
Labels: runtime-rs, size/large

#4617 build: save lines for repository_owner check
  .github/workflows/docs-url-alive-check.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4609 packaging: Simplify config path handling
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: no-backport-needed, size/tiny

#4544 runtime-rs: Dragonball-sandbox - add virtio device feature support for aarch64
  src/dragonball/src/device_manager/legacy.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/error.rs
  src/dragonball/src/vm/aarch64.rs
  src/dragonball/src/vm/mod.rs
Labels: runtime-rs, size/large

#4631 CC | packaging: Allow building a TDX capable kernel
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
Labels: size/medium

#4642 versions: Update Cloud Hypervisor to v25.0
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PmemConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmCoredumpData.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_coredump_data.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: needs-backport, size/huge

#4643 stable-2.5 | versions: Update Cloud Hypervisor to v25.0
  .github/workflows/commit-message-check.yaml
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PmemConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmCoredumpData.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_coredump_data.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: size/huge

#4640 cc | packaging: Allow building a TDX capable QEMU
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/qemu/build-static-qemu-cc.sh
  tools/packaging/static-build/qemu/build-static-qemu-experimental.sh
  tools/packaging/static-build/scripts/qemu-build-post.sh
Labels: size/small

#4647 clh: Don't crash if no network device is set by the upper layer
  src/runtime/virtcontainers/clh.go
Labels: needs-backport, size/tiny

#4506 runk: Support `exec` sub-command
  src/agent/rustjail/src/container.rs
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
  src/tools/runk/libcontainer/Cargo.toml
  src/tools/runk/libcontainer/src/builder.rs
  src/tools/runk/libcontainer/src/container.rs
  src/tools/runk/libcontainer/src/utils.rs
  src/tools/runk/src/commands/create.rs
  src/tools/runk/src/commands/exec.rs
  src/tools/runk/src/commands/mod.rs
  src/tools/runk/src/commands/run.rs
  src/tools/runk/src/main.rs
Labels: size/huge, soc

#4676 runtime-rs: fix some bugs to make runtime-rs on aarch64
  src/dragonball/src/vm/aarch64.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/runtime-rs/arch/aarch64-options.mk
  src/runtime-rs/crates/hypervisor/src/device/vfio.rs
Labels: runtime-rs, size/medium

#4671 kata-sys-util: upgrade nix version
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/console.rs
  src/agent/src/main.rs
  src/libs/kata-sys-util/Cargo.toml
  src/libs/kata-sys-util/src/mount.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/shim/Cargo.toml
Labels: runtime-rs, size/medium

#4678 runtime-rs: remove the value of hypervisor path in DB config
  src/runtime-rs/Makefile
Labels: runtime-rs, size/tiny

#4656 runtime-rs: support functionalities of ipvlan endpoint
  src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
  src/runtime-rs/crates/resource/src/network/endpoint/ipvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
  src/runtime-rs/crates/resource/src/network/network_model/mod.rs
  src/runtime-rs/crates/resource/src/network/network_pair.rs
  src/runtime-rs/crates/resource/src/network/network_with_netns.rs
  src/runtime/virtcontainers/ipvlan_endpoint.go
Labels: runtime-rs, size/large

#4662 docs: add installation guide for kata 3.0
  docs/install/README.md
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
Labels: runtime-rs, size/medium

#4684 runtime-rs: fix ctr exit failed
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
Labels: runtime-rs, size/tiny

#4688 runtime-rs: fix sandbox_cgroup_only=false panic
  src/runtime-rs/crates/resource/src/cgroups/utils.rs
Labels: runtime-rs, size/tiny

#4686 kata-monitor: fix can't monitor /run/vc/sbs
  docs/how-to/data/kata-monitor-daemonset.yml
Labels: size/tiny

#4682 doc: Remove skopeo requirement from doc
  docs/how-to/how-to-build-and-test-ccv0.md
Labels: area/confidential-containers, size/tiny

#4697 CCv0: Merge main into CCv0 branch
  docs/how-to/data/kata-monitor-daemonset.yml
  src/agent/rustjail/src/container.rs
  src/runtime/virtcontainers/clh.go
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
  src/tools/runk/libcontainer/Cargo.toml
  src/tools/runk/libcontainer/src/builder.rs
  src/tools/runk/libcontainer/src/container.rs
  src/tools/runk/libcontainer/src/utils.rs
  src/tools/runk/src/commands/create.rs
  src/tools/runk/src/commands/exec.rs
  src/tools/runk/src/commands/mod.rs
  src/tools/runk/src/commands/run.rs
  src/tools/runk/src/main.rs
Labels: area/confidential-containers, ignore-depends-on, size/huge

#4718 versions: Update firecracker version
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4644 cgroups: remove unnecessary get_paths()
  src/agent/rustjail/src/cgroups/fs/mod.rs
Labels: size/tiny

#4692 support disable_guest_seccomp
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/runtimes/common/src/runtime_handler.rs
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/linux_container/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/runtimes/wasm_container/src/lib.rs
Labels: runtime-rs, size/medium

#4695 upgrade nydus version
  versions.yaml
Labels: no-backport-needed, size/tiny

#4709 rustjail: check result to let it return early
  src/agent/rustjail/src/mount.rs
  src/agent/src/main.rs
  src/agent/src/netlink.rs
Labels: size/small

#4721 Docs: add rust environment setup for kata 3.0
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
Labels: runtime-rs, size/small

#4702 runtime-rs: add functionalities support for macvlan and vlan endpoints
  src/libs/Cargo.lock
  src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
  src/runtime-rs/crates/resource/src/network/endpoint/macvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
  src/runtime-rs/crates/resource/src/network/endpoint/vlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/network_with_netns.rs
  src/runtime-rs/crates/resource/src/network/utils/link/manager.rs
Labels: runtime-rs, size/huge

#4715 agent: fix fd-double-close problem in ut test_do_write_stream
  src/agent/src/rpc.rs
Labels: size/tiny

#4713 runtime-rs: handle default_vcpus greator than default_maxvcpu
  src/libs/kata-types/src/config/hypervisor/dragonball.rs
Labels: runtime-rs, size/tiny

#4727 fix network failed for kata ci
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs
  src/runtime-rs/crates/resource/src/network/network_model/tc_filter_model.rs
Labels: runtime-rs, size/small

#4664 container: kill all of the processes in a container when it terminated
  src/agent/rustjail/src/container.rs
Labels: needs-backport

#4753 agent: Fix stream fd's double close
  src/agent/rustjail/src/process.rs
Labels: size/tiny

#4724 Docs: fix tables format error
  src/libs/README.md
Labels: size/tiny

#4681 runtime-rs: fix set share sandbox pid namespace
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: runtime-rs, size/medium

#4646 qemu: Add liburing to qemu build
  tools/packaging/static-build/qemu/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4758 versions: Update runc version
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4397 runtime: Support for host cgroupv2
  docs/design/host-cgroups.md
  docs/install/container-manager/containerd/containerd-install.md
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/pkg/resourcecontrol/cgroups.go
  src/runtime/pkg/resourcecontrol/controller.go
  src/runtime/pkg/resourcecontrol/utils.go
  src/runtime/pkg/resourcecontrol/utils_linux.go
  src/runtime/pkg/resourcecontrol/utils_linux_test.go
  src/runtime/vendor/github.com/containerd/cgroups/README.md
  src/runtime/vendor/github.com/containerd/cgroups/Vagrantfile
  src/runtime/vendor/github.com/containerd/cgroups/go.mod
  src/runtime/vendor/github.com/containerd/cgroups/go.sum
  src/runtime/vendor/github.com/containerd/cgroups/utils.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/cpu.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/devicefilter.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/ebpf.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/errors.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/hugetlb.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/io.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/manager.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/memory.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/paths.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/pids.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/rdma.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/state.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/stats/doc.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/stats/metrics.pb.go
  src/runtime/vendor/github.com/containerd/cgroups/v2/stats/metrics.pb.txt
  src/runtime/vendor/github.com/containerd/cgroups/v2/stats/metrics.proto
  src/runtime/vendor/github.com/containerd/cgroups/v2/utils.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, no-forward-port-needed, size/large, soc

#4170 Add support AmdSev build of OVMF
  tools/packaging/static-build/ovmf/Dockerfile
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/ovmf/build.sh
  versions.yaml
Labels: area/confidential-containers, size/large

#4741 runtime-rs: fix stop failed in azure
  src/runtime-rs/crates/resource/src/cgroups/mod.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/shim_io.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: runtime-rs, size/small

#4739 agent: log RPC calls for debugging
  src/agent/src/tracer.rs
Labels: no-backport-needed, size/tiny
