Repository kata-containers/kata-containers, pull requests merged in 2022-12, with the labels that each got.

#5784 Re-work the way we cache components for the CCv0 branch
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/cache_components.sh
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
  tools/packaging/static-build/initramfs/build.sh
  tools/packaging/static-build/kernel/build.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/qemu/build-base-qemu.sh
  tools/packaging/static-build/qemu/build-static-qemu-cc.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/td-shim/build.sh
  tools/packaging/static-build/virtiofsd/build.sh
Labels: no-backport-needed, size/huge

#5814 workflow: call cargo in user's $PATH
  .github/workflows/static-checks-dragonball.yaml
Labels: size/tiny

#5809 workflow: fix cargo-deny-runner.yaml syntax error
  .github/workflows/cargo-deny-runner.yaml
Labels: size/tiny

#5823 CC | packaging: Fix the cloud hypervisor cached logic
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components.sh
Labels: no-backport-needed, size/small

#5834 agent: Fix s390x agent build
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/Makefile
Labels: no-backport-needed, area/confidential-containers, size/small

#5827 CCv0: use virtiofsd cache
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components.sh
Labels: size/tiny

#5811 kata-ctl: fix dependency version conflict
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
Labels: size/huge

#5769 kata-ctl: add host check for aarch64
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
Labels: no-backport-needed, size/small

#5822 runtime-rs: fix some variable names and typos
  src/agent/src/rpc.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/service/src/task_service.rs
Labels: runtime-rs, size/small

#5846 kernel: Export KATA_BUILD_CC in install_cc_tee_kernel()
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny

#5842 docs: Update the rust version in the installation documentation
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
Labels: size/tiny

#5607 runtime-rs: bind mount volumes in sandbox level
  .gitignore
  src/libs/kata-sys-util/src/mount.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_inline.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
  src/runtime-rs/crates/resource/src/share_fs/utils.rs
  src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/default_volume.rs
  src/runtime-rs/crates/resource/src/volume/mod.rs
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
  src/runtime-rs/crates/resource/src/volume/shm_volume.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
Labels: size/large

#5844 agent: remove `sysinfo` dependency
  src/agent/Cargo.lock
  src/agent/Cargo.toml
Labels: no-backport-needed, size/medium

#5830 runtime-rs: fix high cpu
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/shim_io.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
Labels: no-backport-needed, runtime-rs, size/small

#5610 runtime: prevent waiting 50 ms minimum for a process exit
  src/runtime/virtcontainers/utils/utils.go
  src/runtime/virtcontainers/utils/utils_darwin.go
  src/runtime/virtcontainers/utils/utils_linux.go
Labels: bug, enhancement, needs-backport, size/large

#5855 CC: Merge main into CCv0 branch
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
  src/agent/src/rpc.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/service/src/task_service.rs
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
Labels: no-backport-needed, area/confidential-containers, ignore-depends-on, size/huge

#5863 CC | Rework TDX runtime configuration files
  src/runtime/Makefile
  src/runtime/config/configuration-clh-tdx-eaa-kbc.toml.in
  src/runtime/config/configuration-qemu-tdx-eaa-kbc.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: size/huge

#5852 CC: Fix issues on cc-payload-ci workflow for s390x
  .github/workflows/cc-payload-after-push-s390x.yaml
Labels: size/tiny

#5865 tools: Fix indentation for ovmf script
  tools/packaging/static-build/ovmf/build-ovmf.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5829 fix kata deploy error after node reboot.
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: needs-backport, size/tiny

#5876 Rework how we build the payload so measured boot can be used with the Operator
  .github/workflows/cc-payload-after-push-amd64.yaml
  .github/workflows/cc-payload-after-push-s390x.yaml
  .github/workflows/cc-payload.yaml
  src/runtime/Makefile
  src/runtime/config/configuration-clh-tdx.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, size/large

#5886 actions: Fix pushing the shim-v2 build image to quay.io
  .github/workflows/cc-payload-after-push-amd64.yaml
  .github/workflows/cc-payload-after-push-s390x.yaml
Labels: no-backport-needed, size/small

#5853 dragonball: enable kata3.0/dragonball CI on Arm
  tools/packaging/kernel/configs/fragments/arm64/base.conf
  tools/packaging/kernel/kata_config_version
Labels: needs-backport, size/tiny, backport-to-stable-3.0

#5848 agent: Drop the Option for LinuxContainer.cgroup_manager
  src/agent/rustjail/src/container.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/tools/runk/libcontainer/src/container.rs
Labels: size/large

#5873 kata-sys-util: fix issues where umount2 couldn't get the correct path
  src/libs/Cargo.lock
  src/libs/kata-sys-util/src/mount.rs
Labels: no-backport-needed, no-forward-port-needed, size/small

#5882 runtime-rs: fix sandbox_pidns calculation and oci spec amending
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: runtime-rs, size/small

#5690 runtime-rs: fix standalone share fs
  src/libs/kata-types/src/config/default.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
Labels: runtime-rs, size/medium

#5835 CC | Cache and use rootfs whenever it's possible
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components.sh
  tools/packaging/static-build/shim-v2/build.sh
Labels: no-backport-needed, size/large

#5884 tools: Fix indentation on build kernel script
  tools/packaging/kernel/build-kernel.sh
Labels: no-backport-needed, no-forward-port-needed, size/small

#5798 basic framework for QEMU support in runtime-rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/runtime-rs/README.md
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/shim-ctl/Cargo.toml
  src/runtime-rs/crates/shim-ctl/README.md
  src/runtime-rs/crates/shim-ctl/src/main.rs
Labels: runtime-rs, size/large

#5786 kata-ctl: check: only-list-releases and include-all-releases options
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
Labels: no-backport-needed, size/large, outreach, kata-ctl

#5735 kata-ctl: Add --list option
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/arch/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/types.rs
Labels: size/large

#5875 refactor(shim-mgmt): move client side to libs
  src/libs/Cargo.lock
  src/libs/Cargo.toml
  src/libs/shim-interface/Cargo.toml
  src/libs/shim-interface/src/lib.rs
  src/libs/shim-interface/src/shim_mgmt/client.rs
  src/libs/shim-interface/src/shim_mgmt/mod.rs
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/persist/Cargo.toml
  src/runtime-rs/crates/persist/src/lib.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/mod.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/server.rs
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/service/src/manager.rs
Labels: runtime-rs, size/large

#5712 Dragonball: introduce upcall
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/build-type/dragonball-experimental/upcall.conf
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0001-upcall-establish-upcall-server.patch
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0002-upcall-introduce-device-manager-upcall-service.patch
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0003-upcall-add-cpu-hotplug-hot-unplug-into-device-manage.patch
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0004-upcall-add-virtio-mmio-hotplug-hot-unplug-into-devic.patch
  versions.yaml
Labels: runtime-rs, size/huge

#5899 shim: return hypervisor's pid not shim's pid
  src/runtime/pkg/containerd-shim-v2/service.go
Labels: size/tiny

#5897 CC: Enable multi-arch build for runtime-payload image
  .github/workflows/cc-payload-amd64.yaml
  .github/workflows/cc-payload-s390x.yaml
  .github/workflows/cc-payload.yaml
Labels: size/large

#5902 tools: Add some new gitignore items
  .gitignore
  tools/osbuilder/.gitignore
  tools/packaging/.gitignore
Labels: size/small

#5913 stable-3.0 | kata-deploy: Fix the pod of kata deploy starts to occur an error
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: backport, size/tiny

#5581 CCv0: runtime: pkg/sev: Support SEV-ES launch digest calculation
  src/runtime/pkg/sev/ovmf.go
  src/runtime/pkg/sev/sev.go
  src/runtime/pkg/sev/sev_test.go
  src/runtime/pkg/sev/vcpu_sigs.go
  src/runtime/pkg/sev/vmsa.go
Labels: size/large

#5893 CC: static build switching sev ovmf to CC fork
  tools/packaging/static-build/ovmf/Dockerfile
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/ovmf/build.sh
  versions.yaml
Labels: no-backport-needed, area/confidential-containers, size/small

#5867 kernel building: Add module unload to SEV kernel config
  tools/packaging/kernel/configs/fragments/x86_64/sev/sev.conf
  tools/packaging/kernel/kata_config_version
Labels: size/tiny

#5877 runtime-rs: enable start container from bundle
  docs/how-to/containerd-kata.md
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
  src/runtime-rs/crates/resource/src/rootfs/share_fs_rootfs.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: runtime-rs, size/large

#5915 dragonball: refactor legacy device initialization
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/device_manager/mod.rs
Labels: size/small

#5861 docs: Update virtiofsd build script in the developer guide
  docs/Developer-Guide.md
Labels: no-backport-needed, size/tiny

#5925 docs: Remove duplicate sentences
  docs/use-cases/using-SPDK-vhostuser-and-kata.md
Labels: size/tiny

#5929 version: Fix formatting
  versions.yaml
Labels: bug, no-backport-needed, size/tiny

#5921 # Kata Containers 3.1.0-alpha1
  VERSION
Labels: size/tiny

#5922 # Kata Containers 3.0.1
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
  VERSION
  src/runtime/virtcontainers/nydusd.go
  src/runtime/virtcontainers/nydusd_test.go
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/nydus/build.sh
  versions.yaml
Labels: size/medium

#5924 kata-ctl: fix checkcpu bug in non-x86 arches
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
  src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
Labels: size/medium

#5901 runtime-rs: Clean up mount points shared to guest
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
  src/runtime-rs/crates/resource/src/rootfs/nydus_rootfs.rs
  src/runtime-rs/crates/resource/src/rootfs/share_fs_rootfs.rs
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/default_volume.rs
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
  src/runtime-rs/crates/resource/src/volume/shm_volume.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
Labels: runtime-rs, size/large

#5937 runtime: Update the remote hypervisor config
  src/runtime/pkg/katautils/config.go
Labels: no-backport-needed, area/confidential-containers, size/tiny

#5933 CC: Merge main into CCv0 branch
  .gitignore
  VERSION
  docs/Developer-Guide.md
  docs/how-to/containerd-kata.md
  docs/use-cases/using-SPDK-vhostuser-and-kata.md
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/device_manager/mod.rs
  src/libs/Cargo.lock
  src/libs/Cargo.toml
  src/libs/shim-interface/Cargo.toml
  src/libs/shim-interface/src/lib.rs
  src/libs/shim-interface/src/shim_mgmt/client.rs
  src/libs/shim-interface/src/shim_mgmt/mod.rs
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/persist/Cargo.toml
  src/runtime-rs/crates/persist/src/lib.rs
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
  src/runtime-rs/crates/resource/src/rootfs/share_fs_rootfs.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/mod.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/server.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime/pkg/containerd-shim-v2/service.go
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/arch/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/types.rs
  tools/osbuilder/.gitignore
  tools/packaging/.gitignore
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/build-type/dragonball-experimental/upcall.conf
  tools/packaging/kernel/configs/fragments/x86_64/sev/sev.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0001-upcall-establish-upcall-server.patch
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0002-upcall-introduce-device-manager-upcall-service.patch
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0003-upcall-add-cpu-hotplug-hot-unplug-into-device-manage.patch
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0004-upcall-add-virtio-mmio-hotplug-hot-unplug-into-devic.patch
  versions.yaml
Labels: no-backport-needed, area/confidential-containers, ignore-depends-on, size/huge
