Repository kata-containers/kata-containers, pull requests merged in 2022-06, with the labels that each got.

#4328 agent: Pass standard I/O to container launched by runk
  src/agent/rustjail/src/process.rs
Labels: size/small

#4339 runk: Add Podman guide in README
  src/tools/runk/README.md
Labels: size/small

#4325 runk: Return error when tty is used without console socket
  src/tools/runk/libcontainer/src/builder.rs
Labels: size/small

#4326 for rust context with_context is better, because it is evaluated lazily.
  src/runtime-rs/crates/hypervisor/src/device/vfio.rs
  src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
  src/runtime-rs/crates/resource/src/network/network_model/route_model.rs
  src/runtime-rs/crates/resource/src/network/utils/netns.rs
  src/runtime-rs/crates/resource/src/share_fs/utils.rs
  src/runtime-rs/crates/resource/src/volume/mod.rs
  versions.yaml
Labels: runtime-rs

#4357 osbuilder: add iptables package
  tools/osbuilder/rootfs-builder/alpine/config.sh
  tools/osbuilder/rootfs-builder/centos/config.sh
  tools/osbuilder/rootfs-builder/clearlinux/config.sh
  tools/osbuilder/rootfs-builder/debian/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
Labels: no-backport-needed, size/small

#4348 CCv0: Merge main into CCv0 branch
  docs/how-to/containerd-kata.md
  snap/snapcraft.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  src/tools/runk/libcontainer/src/builder.rs
  src/tools/runk/libcontainer/src/container.rs
  src/tools/runk/libcontainer/src/status.rs
  src/tools/runk/libcontainer/src/utils.rs
  versions.yaml
Labels: area/confidential-containers, ignore-depends-on, size/large

#4375 docs: Update Intel QAT documentation links
  docs/use-cases/using-Intel-QAT-and-kata.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4355 agent: return mount file content if parse mountinfo failed
  src/agent/src/mount.rs
Labels: no-backport-needed, size/tiny

#4159 feature: add ability to interact with IPTables within the guest
  src/agent/src/rpc.rs
  src/libs/Cargo.lock
  src/libs/Cargo.toml
  src/libs/protocols/protos/agent.proto
  src/runtime/cmd/kata-runtime/kata-iptables.go
  src/runtime/cmd/kata-runtime/kata-volume.go
  src/runtime/cmd/kata-runtime/main.go
  src/runtime/pkg/containerd-shim-v2/shim_management.go
  src/runtime/pkg/kata-monitor/metrics.go
  src/runtime/pkg/utils/shimclient/shim_management_client.go
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/interfaces.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/mock/mock.go
  src/runtime/virtcontainers/pkg/vcmock/sandbox.go
  src/runtime/virtcontainers/sandbox.go
  src/tools/agent-ctl/src/client.rs
Labels: feature, no-backport-needed, size/huge

#4322 snap: Use helper script and cleanup
  README.md
  snap/local/README.md
  snap/local/snap-common.sh
  snap/snapcraft.yaml
  tools/packaging/Makefile
  tools/packaging/README.md
Labels: no-backport-needed, size/large

#4350 workflows: add workflow_dispatch triggering to test-kata-deploy
  .github/workflows/kata-deploy-test.yaml
  docs/Release-Process.md
Labels: needs-backport, no-forward-port-needed, size/tiny

#4352 backport-2.4 | workflows: add workflow_dispatch triggering to test-kata-deploy
  .github/workflows/kata-deploy-test.yaml
  docs/Release-Process.md
Labels: backport

#4360 runtime: ignore ESRCH error from stop container
  src/agent/rustjail/src/container.rs
  src/runtime/pkg/containerd-shim-v2/wait.go
Labels: needs-backport, size/small

#4344 docs: Update vGPU use-case
  docs/use-cases/NVIDIA-GPU-passthrough-and-Kata.md
Labels: size/large

#4383 runk: Support `list` sub-command
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
  src/tools/runk/src/commands/list.rs
  src/tools/runk/src/commands/mod.rs
  src/tools/runk/src/main.rs
Labels: no-backport-needed, size/medium, soc

#4300 rustjail: get home dir using nix crate
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/utils.rs
Labels: size/large

#4384 # Kata Containers 2.5.0-alpha2
  VERSION
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4415 docs: Add agent-ctl examples section
  src/tools/agent-ctl/README.md
Labels: no-backport-needed, size/medium

#4413 tools: Enable extra detail on error
  src/tools/agent-ctl/src/main.rs
  src/tools/trace-forwarder/src/main.rs
Labels: no-backport-needed, size/tiny

#4378 docs: Update source for cri-tools
  docs/how-to/containerd-kata.md
  src/tools/runk/README.md
Labels: no-backport-needed, size/tiny

#4431 docs: Add storage limits to arch doc
  docs/design/architecture/storage.md
Labels: force-skip-ci, size/small

#4434 versions: Bump virtiofsd to v1.3.0
  versions.yaml
Labels: no-backport-needed, size/tiny

#4331 Allow io.katacontainers.config.hypervisor.enable_iommu annotation by …
  src/runtime/Makefile
Labels: needs-backport, size/tiny

#4265 runtime-rs: built-in Dragonball sandbox part I - resource and device managers
  README.md
  src/dragonball/.gitignore
  src/dragonball/Cargo.toml
  src/dragonball/LICENSE
  src/dragonball/Makefile
  src/dragonball/README.md
  src/dragonball/THIRD-PARTY
  src/dragonball/docs/device.md
  src/dragonball/src/address_space_manager.rs
  src/dragonball/src/config_manager.rs
  src/dragonball/src/device_manager/console_manager.rs
  src/dragonball/src/device_manager/legacy.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/device_manager/vsock_dev_mgr.rs
  src/dragonball/src/error.rs
  src/dragonball/src/lib.rs
  src/dragonball/src/resource_manager.rs
  src/dragonball/src/vm/kernel_config.rs
  src/dragonball/src/vm/mod.rs
  src/libs/safe-path/src/pinned_path_buf.rs
  src/libs/safe-path/src/scoped_dir_builder.rs
Labels: runtime-rs, size/huge

#4417 docs: Add more kata monitor details
  src/runtime/cmd/kata-monitor/README.md
Labels: force-skip-ci, size/tiny

#4425 shim: change the log level for GetOOMEvent call failures
  src/runtime/pkg/containerd-shim-v2/wait.go
Labels: no-backport-needed

#4308 runtime: Switch to using the rust version of virtiofsd (all arches but powerpc)
  snap/snapcraft.yaml
  src/runtime/Makefile
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
Labels: size/medium

#4426 CCv0: Merge main into CCv0 branch
  .github/workflows/kata-deploy-test.yaml
  README.md
  docs/Release-Process.md
  docs/design/architecture/storage.md
  docs/use-cases/NVIDIA-GPU-passthrough-and-Kata.md
  docs/use-cases/using-Intel-QAT-and-kata.md
  snap/local/README.md
  snap/local/snap-common.sh
  snap/snapcraft.yaml
  src/agent/rustjail/src/console.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/process.rs
  src/agent/rustjail/src/utils.rs
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
  src/libs/Cargo.lock
  src/libs/Cargo.toml
  src/libs/protocols/protos/agent.proto
  src/runtime/cmd/kata-runtime/kata-iptables.go
  src/runtime/cmd/kata-runtime/kata-volume.go
  src/runtime/cmd/kata-runtime/main.go
  src/runtime/pkg/containerd-shim-v2/shim_management.go
  src/runtime/pkg/containerd-shim-v2/wait.go
  src/runtime/pkg/kata-monitor/metrics.go
  src/runtime/pkg/utils/shimclient/shim_management_client.go
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/interfaces.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/mock/mock.go
  src/runtime/virtcontainers/pkg/vcmock/sandbox.go
  src/runtime/virtcontainers/sandbox.go
  src/tools/agent-ctl/src/client.rs
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
  src/tools/runk/Makefile
  src/tools/runk/README.md
  src/tools/runk/libcontainer/src/builder.rs
  src/tools/runk/src/commands/list.rs
  src/tools/runk/src/commands/mod.rs
  src/tools/runk/src/main.rs
  tools/osbuilder/rootfs-builder/alpine/config.sh
  tools/osbuilder/rootfs-builder/centos/config.sh
  tools/osbuilder/rootfs-builder/clearlinux/config.sh
  tools/osbuilder/rootfs-builder/debian/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/packaging/Makefile
  tools/packaging/README.md
Labels: area/confidential-containers, ignore-depends-on, size/huge

#4180 kernel building: efi_secret module
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/x86_64/sev/sev.conf
  tools/packaging/kernel/patches/efi-secret-v5.17-rc6.x/no_patches.txt
  versions.yaml
Labels: size/small

#4442 safe-path: fix clippy warning
  src/libs/safe-path/src/pinned_path_buf.rs
  src/libs/safe-path/src/scoped_dir_builder.rs
Labels: size/tiny

#4441 agent: refactor reading file timing for debugging
  src/agent/src/mount.rs
Labels: no-backport-needed

#4452 docs: Update containerd url link
  docs/Developer-Guide.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4312 Allow Cloud Hypervisor to run under the `container_kvm_t`
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/network_linux.go
Labels: no-backport-needed, size/large

#4436 runtime: fix error when trying to parse sandbox sizing annotations
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
Labels: size/small

#4461 CCv0: Merge main into CCv0 branch
  .github/workflows/snap-release.yaml
  .github/workflows/snap.yaml
  VERSION
  docs/Developer-Guide.md
  docs/Unit-Test-Advice.md
  docs/code-pr-advice.md
  docs/design/README.md
  docs/design/architecture/kubernetes.md
  docs/design/architecture/storage.md
  docs/design/core-scheduling.md
  docs/how-to/containerd-kata.md
  docs/how-to/how-to-import-kata-logs-with-fluentd.md
  snap/snapcraft.yaml
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/src/mount.rs
  src/libs/Cargo.lock
  src/libs/safe-path/src/pinned_path_buf.rs
  src/libs/safe-path/src/scoped_dir_builder.rs
  src/runtime/Makefile
  src/runtime/README.md
  src/runtime/cmd/kata-monitor/README.md
  src/runtime/pkg/containerd-shim-v2/service.go
  src/runtime/pkg/containerd-shim-v2/wait.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/pkg/utils/schedcore.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/network_linux.go
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/README.md
  src/tools/agent-ctl/src/main.rs
  src/tools/runk/README.md
  src/tools/trace-forwarder/Cargo.lock
  src/tools/trace-forwarder/src/main.rs
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/x86_64/sev/sev.conf
  tools/packaging/kernel/patches/efi-secret-v5.17-rc6.x/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
  versions.yaml
Labels: area/confidential-containers, ignore-depends-on, size/huge

#4466 osbuilder: Fix attestation-agent build
  docs/how-to/how-to-build-and-test-ccv0.md
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: area/confidential-containers, size/tiny

#4481 workflow: Removing man-db, workflow kept failing
  .github/workflows/add-pr-sizing-label.yaml
  .github/workflows/snap-release.yaml
Labels: needs-backport, size/tiny

#4484 tracing: Remove whitespace from root span
  src/runtime/pkg/containerd-shim-v2/create.go
Labels: no-backport-needed, size/tiny

#4168 rootfs: Fix chronyd.service failing on boot
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: needs-backport, area/osbuilder, size/tiny

#4497 packaging: Remove unused publish kata image script
  tools/packaging/release/publish-kata-image.sh
Labels: no-backport-needed, no-forward-port-needed, size/medium

#4288 runtime: enable sandbox feature on qemu
  src/runtime/Makefile
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, size/medium

#4358 runtime: Add heuristic to get the right value(s) for mem-reserve
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/LICENSE
  src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/bytes/bytes.go
  src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/bytes/native.go
  src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/bytes/swapbo.go
  src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/config.go
  src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/mmio/mmio.go
  src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/mmio/mock.go
  src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/mock.go
  src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/nvpci.go
  src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/resources.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_arch_base.go
Labels: size/medium

#4501 stable-2.4 | rootfs: Fix chronyd.service failing on boot
  .github/workflows/snap-release.yaml
  .github/workflows/snap.yaml
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: backport

#4508 CCv0: Merge main into CCv0 branch
  .github/workflows/add-pr-sizing-label.yaml
  .github/workflows/snap-release.yaml
  snap/snapcraft.yaml
  src/runtime/Makefile
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/qemu.go
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/release/publish-kata-image.sh
Labels: area/confidential-containers, ignore-depends-on, size/large

#4511 kernel: Add CONFIG_EFI=y as part of the TDX fragments
  tools/packaging/kernel/configs/fragments/x86_64/tdx/tdx.conf
  tools/packaging/kernel/kata_config_version
Labels: size/tiny

#4503 block: Leverage multiqueue for virtio-block
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, size/tiny

#4514 doc: Update crictl pod-config
  docs/how-to/ccv0.sh
  docs/how-to/how-to-setup-swap-devices-in-guest-kernel.md
  docs/how-to/how-to-use-virtio-fs-nydus-with-kata.md
  docs/how-to/how-to-use-virtio-mem-with-kata.md
Labels: area/confidential-containers, size/small

#4526 Fix clippy warnings and update agent's vendored code
  src/agent/Cargo.lock
  src/agent/src/netlink.rs
  src/agent/src/random.rs
Labels: no-backport-needed, size/huge

#4439 versions: Update kernel to latest LTS version 5.15.48
  tools/packaging/kernel/README.md
  tools/packaging/scripts/apply_patches.sh
  versions.yaml
Labels: no-backport-needed, size/tiny

#4532 CCv0: Fix PS1 unbound error
  docs/how-to/ccv0.sh
Labels: size/tiny

#4518 CCv0 | agent: Pin a specific version of image-rs
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/image_rpc.rs
  src/agent/src/netlink.rs
  src/agent/src/random.rs
Labels: size/huge

#4529 CCv0: Refactor ccv0.sh to use bats test
  docs/how-to/ccv0.sh
Labels: size/small

#4432 shim: support shim v2 logging plugin
  src/runtime/pkg/containerd-shim-v2/service.go
  src/runtime/pkg/containerd-shim-v2/shim_io_binary.go
  src/runtime/pkg/containerd-shim-v2/shim_io_file.go
  src/runtime/pkg/containerd-shim-v2/shim_io_pipe.go
  src/runtime/pkg/containerd-shim-v2/start.go
  src/runtime/pkg/containerd-shim-v2/stream.go
  src/runtime/pkg/containerd-shim-v2/stream_test.go
  src/runtime/vendor/github.com/containerd/containerd/pkg/ioutil/read_closer.go
  src/runtime/vendor/github.com/containerd/containerd/pkg/ioutil/write_closer.go
  src/runtime/vendor/github.com/containerd/containerd/pkg/ioutil/writer_group.go
  src/runtime/vendor/modules.txt
Labels: size/huge

#4130 kata-with-k8s: Add cgroupDriver for containerd
  docs/how-to/run-kata-with-k8s.md
Labels: size/small

#4547 packaging: Remove unused kata docker configure script
  tools/packaging/static-build/scripts/kata-configure-docker.sh
Labels: no-backport-needed, no-forward-port-needed, size/large

#4537 CCv0: Refactor ccv0.sh to remove duplicate code
  docs/how-to/ccv0.sh
  docs/how-to/how-to-build-and-test-ccv0.md
Labels: area/confidential-containers, size/small

#4552 CC | versions: Always use ubuntu as rootfs for CC
  versions.yaml
Labels: size/tiny

#4549 shim: set a non-zero return code if the wait process call failed.
  src/runtime/pkg/containerd-shim-v2/wait.go
  src/runtime/virtcontainers/sandbox.go
Labels: needs-backport, size/tiny

#4558 CC | Build the rootfs image with skopeo, umoci, and using an offline_fs_kbc
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small

#4540 Add `default_maxmemory` config option
  src/runtime/Makefile
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/vendor/github.com/pbnjay/memory/LICENSE
  src/runtime/vendor/github.com/pbnjay/memory/README.md
  src/runtime/vendor/github.com/pbnjay/memory/doc.go
  src/runtime/vendor/github.com/pbnjay/memory/go.mod
  src/runtime/vendor/github.com/pbnjay/memory/memory_bsd.go
  src/runtime/vendor/github.com/pbnjay/memory/memory_darwin.go
  src/runtime/vendor/github.com/pbnjay/memory/memory_linux.go
  src/runtime/vendor/github.com/pbnjay/memory/memory_windows.go
  src/runtime/vendor/github.com/pbnjay/memory/memsysctl.go
  src/runtime/vendor/github.com/pbnjay/memory/stub.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_test.go
Labels: size/large

#4554 runtime: delete Console from Cmd type
  src/runtime/cmd/kata-runtime/factory_test.go
  src/runtime/cmd/kata-runtime/main_test.go
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/containerd-shim-v2/utils_test.go
  src/runtime/pkg/katautils/create.go
  src/runtime/pkg/katautils/create_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/types/sandbox.go
Labels: no-backport-needed, no-forward-port-needed, size/medium

#4565 CC | Build the shim-v2 with the needed configurations for Confidential Containers usage
  src/runtime/Makefile
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/shim-v2/build.sh
Labels: size/small

#4562 Set safe.directory against tests repository
  ci/lib.sh
Labels: size/tiny
