Repository kata-containers/kata-containers, pull requests merged in 2022-08, with the labels that each got.

#4783 versions: Track and add support for building TD-shim
  tools/packaging/static-build/td-shim/Dockerfile
  tools/packaging/static-build/td-shim/build-td-shim.sh
  tools/packaging/static-build/td-shim/build.sh
  versions.yaml
Labels: no-backport-needed, size/large

#4773 packaging: Add support for building TDVF
  tools/packaging/static-build/ovmf/Dockerfile
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/ovmf/build.sh
  versions.yaml
Labels: no-backport-needed, size/medium

#4791 runtime-rs: merge main to runtime-rs
  src/agent/rustjail/src/mount.rs
  src/agent/src/main.rs
  src/libs/kata-sys-util/src/mount.rs
  src/libs/logging/src/lib.rs
  src/runtime-rs/crates/shim/src/logger.rs
  src/tools/agent-ctl/src/main.rs
  src/tools/agent-ctl/src/utils.rs
  src/tools/runk/src/commands/delete.rs
  src/tools/runk/src/commands/list.rs
  tools/packaging/static-build/td-shim/Dockerfile
  tools/packaging/static-build/td-shim/build-td-shim.sh
  tools/packaging/static-build/td-shim/build.sh
  versions.yaml
Labels: runtime-rs, size/large

#4784 libs: fix CI error for protocols
  src/libs/protocols/src/agent_ttrpc_async.rs
  src/libs/protocols/src/health_ttrpc_async.rs
Labels: runtime-rs, size/tiny

#4801 CCv0: Merge main into CCv0 branch
  tools/packaging/static-build/ovmf/Dockerfile
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/td-shim/Dockerfile
  tools/packaging/static-build/td-shim/build-td-shim.sh
  tools/packaging/static-build/td-shim/build.sh
  versions.yaml
Labels: area/confidential-containers, ignore-depends-on, size/large

#4810 OVMF / td-shim: Adjust final tarball location
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/td-shim/build-td-shim.sh
Labels: no-backport-needed, size/tiny

#4805 Bump TDX dependencies (QEMU and Kernel)
  tools/packaging/kernel/configs/fragments/x86_64/tdx/tdx.conf
  tools/packaging/kernel/kata_config_version
  versions.yaml
Labels: no-backport-needed, size/small

#4811 CC | packaging: Build and ship TDVF and TD-shim
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/td-shim/build-td-shim.sh
Labels: size/large

#4770 agent: Use rtnetlink's neighbours API to add neighbors
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/netlink.rs
Labels: size/large

#4820 docs: Improve SGX documentation
  docs/use-cases/using-Intel-SGX-and-kata.md
Labels: no-backport-needed, size/tiny

#4817 runtime-rs:skip the build process when the arch is s390x
  src/runtime-rs/Makefile
  src/runtime-rs/arch/s390x-options.mk
Labels: runtime-rs, size/small

#4826 runtime-rs:update rtnetlink version
  src/runtime-rs/crates/resource/Cargo.toml
Labels: runtime-rs, size/tiny

#4823 Runtime-rs:merge main runtime rs
  docs/use-cases/using-Intel-SGX-and-kata.md
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/netlink.rs
  tools/packaging/kernel/configs/fragments/x86_64/tdx/tdx.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/static-build/ovmf/Dockerfile
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/td-shim/build-td-shim.sh
  versions.yaml
Labels: runtime-rs, size/large

#4763 runk: add ps sub-command
  src/tools/runk/libcontainer/src/builder.rs
  src/tools/runk/libcontainer/src/container.rs
  src/tools/runk/src/commands/kill.rs
  src/tools/runk/src/commands/mod.rs
  src/tools/runk/src/commands/ps.rs
  src/tools/runk/src/main.rs
Labels: size/large, soc

#4795 docs: add back host network limitation
  docs/Limitations.md
Labels: no-backport-needed

#4829 runtime: add unlock before return in sendReq
  src/runtime/virtcontainers/kata_agent.go
Labels: needs-backport, size/tiny

#4746 runtime: explicitly mark the source of the log is from qemu.log
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, size/tiny

#4658 runtime-rs: persist file
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/hypervisor_persist.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/persist/Cargo.toml
  src/runtime-rs/crates/persist/src/lib.rs
  src/runtime-rs/crates/persist/src/sandbox_persist.rs
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/cgroups/cgroup_persist.rs
  src/runtime-rs/crates/resource/src/cgroups/mod.rs
  src/runtime-rs/crates/resource/src/lib.rs
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/network/endpoint/endpoint_persist.rs
  src/runtime-rs/crates/resource/src/network/endpoint/ipvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/macvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
  src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/veth_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/vlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/mod.rs
  src/runtime-rs/crates/resource/src/network/network_with_netns.rs
  src/runtime-rs/crates/resource/src/resource_persist.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox_persist.rs
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/shim/src/bin/main.rs
  src/runtime-rs/crates/shim/src/shim_delete.rs
Labels: runtime-rs, size/huge

#4842 packaging: Create no_patches.txt for the SPR-BKC-PC-v9.6.x
  tools/packaging/kernel/patches/SPR-BKC-PC-v9.6.x/no_patches.txt
Labels: no-backport-needed, size/tiny

#4844 agent-ctl: Add an empty [workspace]
  src/tools/agent-ctl/Cargo.toml
Labels: no-backport-needed, size/tiny

#4846 versions: Update TD-shim due to build breakage
  versions.yaml
Labels: no-backport-needed, size/tiny

#4711 nydus: wait nydusd API server ready before mounting share fs
  src/runtime/virtcontainers/nydusd.go
  src/runtime/virtcontainers/nydusd_test.go
Labels: size/medium

#4839 CC | Build and ship QEMU TDX (and all the needed artefacts)
  src/runtime/Makefile
  src/runtime/arch/amd64-options.mk
  src/runtime/config/configuration-qemu-tdx.toml.in
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
  tools/packaging/kata-deploy/local-build/Makefile
Labels: area/confidential-containers, size/huge

#4270 runtime: Add support for SEV pre-attestation
  src/runtime/Makefile
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/go.mod
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qmp.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/pkg/sev/sev.go
  src/runtime/protocols/simple-kbs/keybroker.pb.go
  src/runtime/protocols/simple-kbs/keybroker.proto
  src/runtime/protocols/simple-kbs/keybroker_grpc.pb.go
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mock_hypervisor.go
  src/runtime/virtcontainers/monitor.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/sandbox.go
Labels: area/confidential-containers, size/huge

#4859 versions: Update libseccomp version
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4868 agent: Update pinned verison of image-rs
  src/agent/Cargo.lock
  src/agent/Cargo.toml
Labels: area/confidential-containers, size/large

#4872 Fix some GitHub actions workflow issues
  .github/workflows/commit-message-check.yaml
  .github/workflows/move-issues-to-in-progress.yaml
Labels: size/tiny

#4876 runtime-rs: update Cargo.lock
  src/runtime-rs/Cargo.lock
Labels: no-backport-needed, runtime-rs, size/tiny

#4881 docs: use curl as default downloader for runtime-rs
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
Labels: no-backport-needed, runtime-rs, size/tiny

#4898 runtime-rs: fix design doc's typo
  docs/design/architecture_3.0/images/architecture.png
  docs/design/architecture_3.0/images/source_code/kata_3.0_images.drawio
Labels: no-backport-needed, runtime-rs, size/tiny

#4854 runtime-rs: delete route model
  docs/design/architecture_3.0/README.md
  src/runtime-rs/crates/resource/src/network/network_model/mod.rs
  src/runtime-rs/crates/resource/src/network/network_model/route_model.rs
Labels: runtime-rs, size/medium

#4911 # Kata Containers 3.0.0-alpha0
  VERSION
Labels: size/tiny

#4916 docs: Update url in containerd documentation
  docs/how-to/containerd-kata.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#4893 Runtime-rs: support persist file
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/hypervisor_persist.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/persist/Cargo.toml
  src/runtime-rs/crates/persist/src/lib.rs
  src/runtime-rs/crates/persist/src/sandbox_persist.rs
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/cgroups/cgroup_persist.rs
  src/runtime-rs/crates/resource/src/cgroups/mod.rs
  src/runtime-rs/crates/resource/src/lib.rs
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/network/endpoint/endpoint_persist.rs
  src/runtime-rs/crates/resource/src/network/endpoint/ipvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/macvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
  src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/veth_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/vlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/mod.rs
  src/runtime-rs/crates/resource/src/network/network_with_netns.rs
  src/runtime-rs/crates/resource/src/resource_persist.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox_persist.rs
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/shim/src/bin/main.rs
  src/runtime-rs/crates/shim/src/shim_delete.rs
Labels: runtime-rs, size/huge

#4927 CC | runtime: Fix TDVF configuration with QEMU TDX
  src/runtime/Makefile
Labels: area/confidential-containers, size/tiny

#4769 CC | Integrate pause image inside rootfs
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  versions.yaml
Labels: area/confidential-containers, size/small

#4922 workflow: trigger release for 3.x releases
  .github/workflows/release.yaml
  .github/workflows/snap-release.yaml
Labels: size/tiny

#4910 # Kata Containers 2.5.0
  VERSION
  src/agent/rustjail/src/container.rs
  src/runtime/config/configuration-acrn.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/kata_agent.go
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  versions.yaml
Labels: size/medium

#4921 runtime-rs: delete vergen dependency
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/shim/Cargo.toml
  src/runtime-rs/crates/shim/build.rs
Labels: runtime-rs, size/large

#4869 Updated the link target of CRI-O
  docs/install/minikube-installation-guide.md
Labels: no-backport-needed, size/tiny

#4930 dep: update nix dependency
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/seccomp.rs
  src/agent/vsock-exporter/Cargo.toml
  src/dragonball/Cargo.toml
  src/libs/kata-sys-util/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/shim/Cargo.toml
Labels: needs-backport, size/large

#4940 ci: Update libseccomp version
  ci/install_libseccomp.sh
Labels: size/tiny

#4903 runtime: tracing: End root span at end of trace
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/containerd-shim-v2/service.go
Labels: needs-backport, size/tiny

#4933 Upgrade to Cloud Hypervisor v26.0
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CmdLineConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/InitramfsConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/KernelConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PayloadConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cmd_line_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_initramfs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_kernel_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_payload_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: size/huge

#4955 Stable-2.5 | Upgrade to Cloud Hypervisor v26.0
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CmdLineConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/InitramfsConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/KernelConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PayloadConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cmd_line_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_initramfs_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_kernel_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_payload_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: size/huge

#4937 network: Fix error message for setting hardware address on TAP interface
  src/runtime/virtcontainers/network_linux.go
Labels: size/tiny

#4754 agent: do some rollback works if case of do_create_container failed
  src/agent/src/rpc.rs
Labels: needs-backport, size/medium

#4772 Drop-in cfg files support in runtime-rs
  src/libs/Cargo.lock
  src/libs/kata-types/Cargo.toml
  src/libs/kata-types/src/config/drop_in.rs
  src/libs/kata-types/src/config/mod.rs
Labels: no-backport-needed, runtime-rs, size/large

#4861 kernel: upgrade guest kernel support to 5.19
  snap/snapcraft.yaml
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/common/dax.conf
  tools/packaging/kernel/configs/fragments/s390/network.conf
  tools/packaging/kernel/configs/fragments/x86_64/base.conf
  tools/packaging/kernel/configs/fragments/x86_64/sev/sev.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/5.19.x/no_patches.txt
  versions.yaml
Labels: needs-backport, size/small

#4960 CCv0 | kata-deploy: allow to build the image without skopeo
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, area/kata-deploy, area/confidential-containers, size/tiny

#4870 runk: add pause/resume commands
  src/agent/Cargo.lock
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/mount.rs
  src/agent/rustjail/src/seccomp.rs
  src/tools/runk/Cargo.lock
  src/tools/runk/libcontainer/Cargo.toml
  src/tools/runk/libcontainer/src/builder.rs
  src/tools/runk/libcontainer/src/cgroup.rs
  src/tools/runk/libcontainer/src/container.rs
  src/tools/runk/libcontainer/src/status.rs
  src/tools/runk/libcontainer/src/utils.rs
  src/tools/runk/src/commands/delete.rs
  src/tools/runk/src/commands/list.rs
  src/tools/runk/src/commands/mod.rs
  src/tools/runk/src/commands/pause.rs
  src/tools/runk/src/commands/resume.rs
  src/tools/runk/src/commands/start.rs
  src/tools/runk/src/commands/state.rs
  src/tools/runk/src/main.rs
Labels: size/huge

#4051 enable vmx for vm factory
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_ppc64le.go
Labels: no-backport-needed, size/small

#4705 UT: test_load_kernel_module needs root
  src/agent/rustjail/src/container.rs
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
Labels: no-backport-needed, size/small

#4969 Fix depbot reported rust crates dependency security issues
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/libs/kata-types/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/tools/agent-ctl/Cargo.lock
  src/tools/runk/Cargo.lock
  src/tools/trace-forwarder/Cargo.lock
Labels: needs-backport

#4976 runk: Move delete logic to libcontainer
  src/tools/runk/libcontainer/src/container.rs
  src/tools/runk/src/commands/delete.rs
Labels: no-backport-needed, size/large

#4982 TDX: Get TDX working again with Cloud Hypervisor + a minor change on QEMU's code
  src/runtime/config/configuration-clh.toml.in
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/qemu_amd64.go
Labels: no-backport-needed, area/confidential-containers, size/large

#4892 runtime-rs: support loading kernel modules in guest vm
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/config.rs
  src/libs/kata-types/src/config/agent.rs
  src/libs/kata-types/src/config/default.rs
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/mod.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/tools/agent-ctl/src/utils.rs
Labels: runtime-rs, size/large

#4997 CC | Backport fixes for Cloud Hypervisor + TDX
  src/runtime/config/configuration-clh.toml.in
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/qemu_amd64.go
Labels: area/confidential-containers, size/large

#4986 CC | config: Drop `force_tdx_guest` unneeded parameter
  src/runtime/Makefile
Labels: area/confidential-containers, size/tiny

#4999 kernel: Ignore CONFIG_SPECULATION_MITIGATIONS for older kernels
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/kernel/kata_config_version
Labels: no-backport-needed, area/confidential-containers, size/tiny

#4815 logging: Replace nix::Error::EINVAL with more descriptive msgs
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/mount.rs
  src/agent/rustjail/src/validator.rs
  src/agent/src/netlink.rs
  src/agent/src/rpc.rs
Labels: area/agent, size/large

#5002 CC | kernel: Ignore CONFIG_SPECULATION_MITIGATIONS for older kernels
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/kernel/kata_config_version
Labels: size/tiny

#4798 Use iouring for qemu block devices
  src/runtime/Makefile
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/device/config/config.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qmp.go
  src/runtime/pkg/govmm/qemu/qmp_test.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/qemu.go
Labels: size/large

#4984 CC | Build and ship CLH TDX (and all the needed artefacts)
  src/runtime/Makefile
  src/runtime/config/configuration-clh-tdx.toml.in
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: area/confidential-containers, size/large

#5011 agent: add some logs for mount operation
  src/agent/src/mount.rs
Labels: no-backport-needed, size/small

#4983 runk: Add cli message for init command
  src/tools/runk/src/main.rs
Labels: no-backport-needed, size/tiny

#4942 ci: Use versions.yaml for the libseccomp
  ci/install_libseccomp.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/scripts/lib.sh
Labels: size/medium

#4797 runtime-rs: add support for core scheduling
  src/runtime-rs/crates/shim/src/core_sched.rs
  src/runtime-rs/crates/shim/src/lib.rs
  src/runtime-rs/crates/shim/src/shim_run.rs
Labels: runtime-rs, size/large

#4775 github-actions: Auto-backporting
  .github/workflows/add-backport-label.yaml
  .github/workflows/auto-backport.yaml
Labels: size/large

#4951 Fix kata-deploy to work on CI context
  tools/packaging/kata-deploy/local-build/.gitignore
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
Labels: no-backport-needed, area/ci, area/kata-deploy, size/tiny

#4987 Initrd fixes for ubuntu systemd
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: size/small

#5021 CC | docs: Add https_proxy to confidential agent config
  docs/how-to/data/confidential-agent-config.toml.in
Labels: area/confidential-containers, size/tiny

#4900 Built-in Sandbox: add more unit tests for dragonball.
  src/dragonball/src/config_manager.rs
Labels: size/medium

#4996 runtime-rs: delete socket from shim command-line options
  src/runtime-rs/crates/runtimes/virt_container/src/health_check.rs
  src/runtime-rs/crates/shim/src/args.rs
  src/runtime-rs/crates/shim/src/bin/main.rs
  src/runtime-rs/crates/shim/src/shim.rs
  src/runtime-rs/crates/shim/src/shim_start.rs
Labels: no-backport-needed, runtime-rs, size/small

#5036 kernel: Whitelist cleanup
  tools/packaging/kernel/configs/fragments/whitelist.conf
Labels: no-backport-needed, size/tiny

#5046 kernel: Re-work get_tee_kernel()
  tools/packaging/kernel/build-kernel.sh
  versions.yaml
Labels: no-backport-needed, size/small

#4967 CC | image-build: generate root hash as an separate partition for rootfs
  tools/osbuilder/image-builder/Dockerfile
  tools/osbuilder/image-builder/image_builder.sh
Labels: area/confidential-containers, size/small
