Repository kata-containers/kata-containers, pull requests merged in 2022-02, with the labels that each got.

#3578 # Kata Containers 2.4.0-alpha2
  VERSION
Labels: no-backport-needed, no-forward-port-needed

#3580 stable-2.3 | workflows: Use base instead of head ref for kata-deploy-test
  .github/workflows/kata-deploy-test.yaml
Labels: backport

#3565 workflows: stop checking revert commit
  .github/workflows/commit-message-check.yaml
Labels: no-backport-needed, no-forward-port-needed

#3582 docs: Remove Zun documentation with kata containers
  docs/README.md
  docs/use-cases/images/kata-zun1.png
  docs/use-cases/images/kata-zun2.png
  docs/use-cases/images/kata-zun3.png
  docs/use-cases/images/kata-zun4.png
  docs/use-cases/images/kata-zun5.png
  docs/use-cases/zun_kata.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3587 kata-deploy: for testing, make sure we use the PR branch
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
Labels: no-backport-needed, no-forward-port-needed

#3585 # Kata Containers 2.3.2
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: no-backport-needed, no-forward-port-needed

#3584 runtime: suppport split firmware
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/runtime/Makefile
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_test.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_arm64_test.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_ppc64le_test.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_s390x_test.go
  src/runtime/virtcontainers/types/asset.go
  src/runtime/virtcontainers/types/asset_test.go
Labels: no-backport-needed, no-forward-port-needed

#3620 Revert "workflows: Ensure a label change re-triggers the actions"
  .github/workflows/commit-message-check.yaml
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/move-issues-to-in-progress.yaml
  .github/workflows/snap.yaml
  .github/workflows/static-checks.yaml
Labels: no-backport-needed, no-forward-port-needed

#3564 CCv0 | doc: Improve ccv0.sh and CCv0 how-to document
  docs/how-to/ccv0.sh
  docs/how-to/how-to-build-and-test-ccv0.md
Labels: area/confidential-containers

#3223 runtime: also check kvm module `sev` parameter as bool
  src/runtime/virtcontainers/hypervisor_amd64.go
Labels: no-backport-needed, no-forward-port-needed, area/runtime, area/confidential-containers

#3606 openshift-ci: switch to CentOS Stream
  ci/openshift-ci/images/Dockerfile.buildroot
Labels: no-backport-needed, no-forward-port-needed, area/ci

#3612 Release process related fixes
  docs/Release-Process.md
  tools/packaging/scripts/lib.sh
Labels: no-backport-needed, no-forward-port-needed

#3628 snap: update qemu version to 6.1.0 for arm
  snap/snapcraft.yaml
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3619 runtime: support QEMU SGX
  src/runtime/virtcontainers/qemu_amd64.go
Labels: no-backport-needed, no-forward-port-needed

#3617 docs: Update link to EFK stack docs
  docs/how-to/how-to-import-kata-logs-with-fluentd.md
Labels: no-backport-needed, no-forward-port-needed

#3643 device: Actually update PCIDEVICE_ environment variables for the guest
  src/agent/src/device.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
Labels: no-backport-needed, no-forward-port-needed

#3651 kernel: support TDx
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/patches/tdx-guest-v5.15-4.x/no_patches.txt
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3613 docs: Fix relative links in Markdown
  docs/Release-Process.md
  docs/Unit-Test-Advice.md
  docs/code-pr-advice.md
  docs/how-to/how-to-import-kata-logs-with-fluentd.md
  docs/how-to/how-to-run-docker-with-kata.md
  docs/how-to/how-to-use-virtio-fs-with-kata.md
  docs/install/minikube-installation-guide.md
  docs/install/snap-installation-guide.md
  docs/tracing.md
  docs/use-cases/using-Intel-QAT-and-kata.md
  docs/use-cases/using-Intel-SGX-and-kata.md
  src/runtime/README.md
  tools/osbuilder/rootfs-builder/README.md
Labels: no-backport-needed, no-forward-port-needed

#2977 feature(nydusd): add nydusd support to introduce lazyload ability
  docs/design/README.md
  docs/design/arch-images/kata-nydus.drawio
  docs/design/arch-images/kata-nydus.png
  docs/design/arch-images/nydus-performance.png
  docs/design/arch-images/nydusd-arch.png
  docs/design/arch-images/rafs-format.png
  docs/design/kata-nydus-design.md
  docs/how-to/README.md
  docs/how-to/how-to-use-virtio-fs-nydus-with-kata.md
  src/agent/src/device.rs
  src/agent/src/mount.rs
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/hypervisors/hypervisor_state.go
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/create.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/device/config/config.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/nydusd.go
  src/runtime/virtcontainers/nydusd_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_test.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/utils/retry/retry.go
  src/runtime/virtcontainers/virtiofsd.go
  tools/osbuilder/scripts/lib.sh
  versions.yaml
Labels: feature, needs-review, no-backport-needed, no-forward-port-needed, area/agent, area/runtime

#3483 versions: bump CRI-O to its 1.23 release
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3636 scripts: fix a typo while to check build_type
  tools/packaging/kernel/build-kernel.sh
Labels: no-backport-needed, no-forward-port-needed

#3660 kernel: add missing config fragment for TDx
  tools/packaging/kernel/configs/fragments/x86_64/tdx/tdx.conf
Labels: no-backport-needed, no-forward-port-needed

#3664 versions: Udpate Cloud Hypervisor to 55479a64d237
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/BalloonConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/TdxConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_balloon_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_tdx_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3668 agent: fix hook execution issues
  src/agent/rustjail/src/container.rs
Labels: needs-backport, no-forward-port-needed

#3677 docs: Remove docker run and shared memory from limitations
  docs/Limitations.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3673 tools: clh: Allow to set when to build from sources and the build flags passed down to cargo
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Labels: no-backport-needed, no-forward-port-needed

#3344 feature: hugepages support
  src/agent/src/device.rs
  src/agent/src/mount.rs
  src/runtime/go.mod
  src/runtime/vendor/modules.txt
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/device/config/pmem.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
  src/runtime/virtcontainers/utils/utils_linux.go
  src/runtime/virtcontainers/utils/utils_linux_test.go
Labels: feature, no-backport-needed, no-forward-port-needed

#3669 virtiofsd: Use "-o announce_submounts"
  src/runtime/Makefile
Labels: no-backport-needed, no-forward-port-needed

#3689 tools: Build cloud-hypervisor with "--features tdx"
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, no-forward-port-needed

#3558 docs: Improve top-level README
  README.md
  src/runtime/README.md
Labels: no-backport-needed, no-forward-port-needed

#3657 trace-forwarder/agent-ctl: run cargo fmt/clippy in make check
  src/agent/Makefile
  src/tools/agent-ctl/Makefile
  src/tools/agent-ctl/src/client.rs
  src/tools/agent-ctl/src/main.rs
  src/tools/agent-ctl/src/utils.rs
  src/tools/trace-forwarder/Makefile
  src/tools/trace-forwarder/src/handler.rs
  utils.mk
Labels: no-backport-needed, no-forward-port-needed

#3684 versions: Linux 5.15.x
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/kernel/patches/5.15.x/no_patches.txt
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3110 container: Remove VFIO lazy attach handling
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/device/manager/utils.go
  src/runtime/virtcontainers/device/manager/utils_test.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: no-backport-needed, no-forward-port-needed, area/darwin

#3638 doc: Add doc and script for ssh-demo sample
  docs/how-to/ccv0.sh
  docs/how-to/how-to-build-and-test-ccv0.md
Labels: area/confidential-containers

#3707 packaging: support qemu-tdx
  tools/packaging/qemu/patches/tag_patches/tdx-qemu-2021.11.29-v6.0.0-rc1-mvp/no_patches.txt
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3542 Runtime-rs: load, parse, access kata configuration and optionally modify them by annotations
  .github/workflows/move-issues-to-in-progress.yaml
  src/libs/Cargo.lock
  src/libs/kata-types/Cargo.toml
  src/libs/kata-types/src/annotations/dockershim.rs
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/annotations/thirdparty.rs
  src/libs/kata-types/src/config/agent.rs
  src/libs/kata-types/src/config/agent_vendor.rs
  src/libs/kata-types/src/config/default.rs
  src/libs/kata-types/src/config/hypervisor/dragonball.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/src/config/hypervisor/qemu.rs
  src/libs/kata-types/src/config/hypervisor/vendor.rs
  src/libs/kata-types/src/config/mod.rs
  src/libs/kata-types/src/config/runtime.rs
  src/libs/kata-types/src/config/runtime_vendor.rs
  src/libs/kata-types/src/lib.rs
  src/libs/kata-types/tests/test_config.rs
  src/libs/kata-types/tests/texture/configuration-anno-0.toml
  src/libs/kata-types/tests/texture/configuration-anno-1.toml
Labels: runtime-rs

#3710 docs: Update limitations document
  docs/Limitations.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3711 runtime: Always add network endpoints from the pod netns
  src/runtime/virtcontainers/network_linux.go
Labels: no-backport-needed, no-forward-port-needed

#3725 stable-2.3 | packaging: Use `patch` for applying patches
  tools/packaging/scripts/apply_patches.sh
  tools/packaging/static-build/kernel/Dockerfile
  tools/packaging/static-build/qemu/Dockerfile
Labels: no-forward-port-needed, backport, area/packaging

#3716 stable-2.3 | agent: fix invalid hooks env issues
  src/agent/rustjail/src/container.rs
Labels: backport

#3721 kernel: remove SYS_SUPPORTS_HUGETLBFS from powerpc fragments
  tools/packaging/kernel/configs/fragments/powerpc/base.conf
Labels: no-backport-needed, no-forward-port-needed

#3553 kata-monitor: simplify sandbox cache management and attach kubernetes POD metadata to metrics
  src/runtime/pkg/kata-monitor/cri.go
  src/runtime/pkg/kata-monitor/metrics.go
  src/runtime/pkg/kata-monitor/metrics_test.go
  src/runtime/pkg/kata-monitor/monitor.go
  src/runtime/pkg/kata-monitor/sandbox_cache.go
  src/runtime/pkg/kata-monitor/sandbox_cache_test.go
  src/runtime/pkg/kata-monitor/shim_client.go
Labels: no-backport-needed, no-forward-port-needed

#3735 kata-deploy: Use (kata with) qemu as the default shim-v2 binary
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: needs-backport, no-forward-port-needed

#3306 runtime-rs: Introduce kata-sys-util library crate
  src/libs/Cargo.lock
  src/libs/Cargo.toml
  src/libs/README.md
  src/libs/kata-sys-util/Cargo.toml
  src/libs/kata-sys-util/README.md
  src/libs/kata-sys-util/src/cgroup.rs
  src/libs/kata-sys-util/src/device.rs
  src/libs/kata-sys-util/src/fs.rs
  src/libs/kata-sys-util/src/hooks.rs
  src/libs/kata-sys-util/src/k8s.rs
  src/libs/kata-sys-util/src/lib.rs
  src/libs/kata-sys-util/src/mount.rs
  src/libs/kata-sys-util/src/numa.rs
  src/libs/kata-sys-util/test/texture/sys/devices/system/cpu/cpu0/node0/cpulist
  src/libs/kata-sys-util/test/texture/sys/devices/system/cpu/cpu0/node0/cpumap
  src/libs/kata-sys-util/test/texture/sys/devices/system/cpu/cpu1/node0/cpulist
  src/libs/kata-sys-util/test/texture/sys/devices/system/cpu/cpu64/node1/cpulist
  src/libs/kata-sys-util/test/texture/sys/devices/system/node/node0/cpulist
  src/libs/kata-sys-util/test/texture/sys/devices/system/node/node0/cpumap
  src/libs/kata-sys-util/test/texture/sys/devices/system/node/node1/cpulist
  src/libs/kata-sys-util/test/texture/sys/devices/system/node/node1/cpumap
  src/libs/kata-types/src/cpu.rs
  src/libs/kata-types/src/lib.rs
  src/libs/kata-types/src/utils/mod.rs
  src/libs/kata-types/src/utils/u32_set.rs
Labels: runtime-rs

#3741 docs: Update contributing link
  CONTRIBUTING.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3736 shim: log events for CRI-O
  src/runtime/pkg/containerd-shim-v2/event_forwarder.go
  src/runtime/pkg/containerd-shim-v2/event_forwarder_test.go
  src/runtime/pkg/containerd-shim-v2/service.go
  src/runtime/virtcontainers/container.go
Labels: needs-backport, no-forward-port-needed

#3744 stable-2.3 | shim: log events for CRI-O
  src/runtime/pkg/containerd-shim-v2/event_forwarder.go
  src/runtime/pkg/containerd-shim-v2/event_forwarder_test.go
  src/runtime/pkg/containerd-shim-v2/service.go
  src/runtime/virtcontainers/container.go
Labels: no-forward-port-needed, backport

#3745 stable-2.3 | kata-deploy: Use (kata with) qemu as the default shim-v2 binary
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: no-forward-port-needed, backport

#3670 Support nerdctl OCI hooks
  src/runtime/pkg/katautils/create.go
  src/runtime/pkg/katautils/create_test.go
  src/runtime/pkg/katautils/hook.go
  src/runtime/pkg/katautils/hook_test.go
Labels: no-backport-needed, no-forward-port-needed

#3724 kata-deploy: Simplify Dockerfile and support s390x
  tools/packaging/kata-deploy/Dockerfile
Labels: needs-backport, no-forward-port-needed, area/kata-deploy

#3615 Make the hypervisor framework not Linux specific
  src/runtime/pkg/govmm/vmm_amd64.go
  src/runtime/pkg/govmm/vmm_arm64.go
  src/runtime/pkg/govmm/vmm_ppc64le.go
  src/runtime/pkg/govmm/vmm_s390x.go
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/acrn_arch_base.go
  src/runtime/virtcontainers/acrn_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/fc_metrics.go
  src/runtime/virtcontainers/fc_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_linux.go
  src/runtime/virtcontainers/hypervisor_linux_amd64.go
  src/runtime/virtcontainers/hypervisor_linux_arm64.go
  src/runtime/virtcontainers/hypervisor_linux_arm64_test.go
  src/runtime/virtcontainers/hypervisor_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_arm64_test.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_ppc64le_test.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_s390x_test.go
  src/runtime/virtcontainers/qemu_test.go
Labels: no-backport-needed, no-forward-port-needed, area/darwin

#3747 agent-protocol support async
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/src/rpc.rs
  src/libs/Cargo.lock
  src/libs/Cargo.toml
  src/libs/kata-sys-util/Cargo.toml
  src/libs/kata-types/Cargo.toml
  src/libs/protocols/Cargo.toml
  src/libs/protocols/build.rs
  src/libs/protocols/src/lib.rs
  src/libs/protocols/src/trans.rs
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Cargo.toml
  src/tools/agent-ctl/src/client.rs
  src/tools/agent-ctl/src/main.rs
  src/tools/agent-ctl/src/utils.rs
Labels: runtime-rs

#3762 runtime: fix package declaration for ppc64le
  src/runtime/pkg/govmm/vmm_ppc64le.go
Labels: no-backport-needed, no-forward-port-needed

#3751 kata-monitor: fix collecting metrics for sandboxes not started through CRI
  src/runtime/cmd/kata-monitor/main.go
  src/runtime/pkg/kata-monitor/cri.go
  src/runtime/pkg/kata-monitor/metrics.go
  src/runtime/pkg/kata-monitor/metrics_test.go
  src/runtime/pkg/kata-monitor/monitor.go
  src/runtime/pkg/kata-monitor/sandbox_cache.go
  src/runtime/pkg/kata-monitor/sandbox_cache_test.go
Labels: no-backport-needed, no-forward-port-needed

#3599 virtcontainers: Do not add a virtio-rng-ccw device
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, no-forward-port-needed, area/runtime, area/s390x

#3771 clh: Add TDX support
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DeviceNode.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/ReceiveMigrationData.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/SendMigrationData.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_node.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_receive_migration_data.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_send_migration_data.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_s390x.go
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, area/cloud-hypervisor, area/tdx

#3776 Fix unbound variable / typo on error mesage
  src/runtime/virtcontainers/clh.go
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Labels: no-backport-needed, no-forward-port-needed

#3767 runtime, config: make selinux configurable
  src/runtime/Makefile
  src/runtime/config/configuration-acrn.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu.go
Labels: needs-backport

#3732 docs: Developer-Guide build a custom Kata agent with musl
  docs/Developer-Guide.md
Labels: no-backport-needed, no-forward-port-needed

#3792 docs: Update Readme document
  docs/README.md
Labels: no-backport-needed, no-forward-port-needed, area/documentation

#3788 Update `confidential_guest` comments
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
Labels: no-backport-needed, no-forward-port-needed
