Repository kata-containers/kata-containers, pull requests merged in 2023-08, with the labels that each got.

#7504 release: Fix upload-versions-yaml
  .github/workflows/release.yaml
Labels: force-skip-ci, size/tiny

#7480 Simplify implementation of runtime-rs/service
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/service/src/task_service.rs
  src/runtime-rs/crates/shim-ctl/src/main.rs
  src/runtime-rs/crates/shim/src/shim_run.rs
Labels: no-backport-needed, no-forward-port-needed, runtime-rs, size/large

#7486 metrics: Add sysbench performance test
  tests/metrics/density/README.md
  tests/metrics/density/k8s-sysbench.sh
  tests/metrics/density/runtimeclass_workloads/sysbench-pod.yaml
  tests/metrics/density/sysbench-dockerfile/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, size/large

#7508 release: release-note.sh: Fix typos and reference to images
  tools/packaging/release/release-notes.sh
Labels: force-skip-ci, size/tiny

#6672 kata-ctl: add monitor subcommand for runtime-rs
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/monitor/http_server.rs
  src/tools/kata-ctl/src/monitor/metrics.rs
  src/tools/kata-ctl/src/monitor/mod.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/ops/exec_ops.rs
  src/tools/kata-ctl/src/ops/volume_ops.rs
  src/tools/kata-ctl/src/utils.rs
Labels: no-backport-needed, no-forward-port-needed, size/tiny, kata-ctl

#5797 runtime-rs: add support for gather metrics in runtime-rs
  docs/design/README.md
  docs/design/kata-metrics-in-runtime-rs.md
  src/dragonball/Cargo.lock
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/hypervisor_metrics.rs
  src/dragonball/src/lib.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/shim_metrics.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: runtime-rs, size/huge

#6586 kata-deploy: enable cross build for non-x86
  ci/install_libseccomp.sh
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/kernel/Dockerfile
  tools/packaging/static-build/kernel/build.sh
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/qemu/build-base-qemu.sh
  tools/packaging/static-build/qemu/build-qemu.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
  tools/packaging/static-build/virtiofsd/build.sh
  utils.mk
Labels: size/large, ok-to-test

#7510 ci: k8s: Do not fail when gathering info on AKS nodes
  tests/integration/kubernetes/gha-run.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#7519 ci-on-push: Make the CI also run for the stable-* branches
  .github/workflows/ci-on-push.yaml
Labels: force-skip-ci, size/tiny

#7516 metrics: Add iperf3 network test
  tests/metrics/README.md
  tests/metrics/network/README.md
  tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
  tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-daemonset.yaml
  tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-deployment.yaml
  tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-service.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7503 metrics: Add FIO test to gha for kata metrics CI
  .github/workflows/run-metrics.yaml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/gha-run.sh
  tests/metrics/storage/README.md
  tests/metrics/storage/fio-k8s/README.md
  tests/metrics/storage/fio-k8s/fio-test-ci.sh
  tests/metrics/storage/fio-k8s/scripts/dax-compare-test/Makefile
  tests/metrics/storage/fio-k8s/scripts/dax-compare-test/README.md
  tests/metrics/storage/fio-k8s/scripts/dax-compare-test/compare-virtiofsd-dax.sh
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#7494 vfio: Fix vfio device ordering
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/sandbox.go
Labels: size/small, ok-to-test

#7523 # Kata Containers 3.2.0-rc0
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml
Labels: ok-to-test

#7530 metrics: stop kata components before start a metric test.
  tests/common.bash
  tests/metrics/lib/common.bash
  tests/metrics/time/launch_times.sh
Labels: no-backport-needed, no-forward-port-needed, area/metrics, size/tiny, ok-to-test

#7524 release: Revert kata-deploy changes after 3.2.0-rc0 release
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml
Labels: size/large

#7520 kata-deploy: Use host's systemctl
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: needs-backport, size/small, ok-to-test, backport-to-sable-3.2

#7542 Use version 0.10.4 of `fuse-backend-rs`
  src/dragonball/Cargo.toml
Labels: size/tiny

#7106 Image pulling on the host
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/device/config/config.go
  src/runtime/pkg/device/manager/manager.go
  src/runtime/pkg/govmm/qemu/qmp.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/fs_share_linux.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
Labels: size/tiny, ok-to-test

#7527 metrics: Add network latency test
  tests/metrics/network/README.md
  tests/metrics/network/latency_kubernetes/latency-client.yaml
  tests/metrics/network/latency_kubernetes/latency-network.sh
  tests/metrics/network/latency_kubernetes/latency-server.yaml
Labels: no-backport-needed, no-forward-port-needed, size/large

#7191 agent: avoid unnecessary calls to `Arc::clone`
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
Labels: size/tiny, ok-to-test

#7467 docs: Use control-plane term instead of master
  docs/design/architecture/kubernetes.md
  docs/how-to/how-to-use-k8s-with-containerd-and-kata.md
  docs/how-to/run-kata-with-k8s.md
  docs/install/minikube-installation-guide.md
Labels: no-backport-needed, area/documentation, size/tiny

#7549 CC | Add missing runtime classes
  tools/packaging/kata-deploy/runtimeclasses/kata-clh-tdx.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-qemu-se.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-remote.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
Labels: size/medium

#7562 3.2 backport | dragonball: use version 0.10.4 of `fuse-backend-rs`
  src/dragonball/Cargo.toml
Labels: size/tiny

#7572 metrics: General improvements to mobilenet tensorflow test
  tests/metrics/machine_learning/mobilenet_v1_bfloat16_fp32_dockerfile/Dockerfile
  tests/metrics/machine_learning/tensorflow_mobilenet_v1_bfloat16_fp32.sh
Labels: no-backport-needed, no-forward-port-needed, size/small

#7383 runtime-rs: Introduce directly attachable network
  src/libs/kata-types/src/config/runtime.rs
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/resource/src/network/dan.rs
  src/runtime-rs/crates/resource/src/network/endpoint/endpoint_persist.rs
  src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
  src/runtime-rs/crates/resource/src/network/endpoint/tap_endpoint.rs
  src/runtime-rs/crates/resource/src/network/mod.rs
  src/runtime-rs/crates/resource/src/network/network_info/mod.rs
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_dan.rs
  src/runtime-rs/crates/resource/src/network/utils/address.rs
  src/runtime-rs/crates/resource/src/network/utils/mod.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: runtime-rs, size/huge

#7500 fix number of queues handling in dragonball share fs device
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
Labels: runtime-rs, size/tiny

#7581 deps: Bump dependent crate versions
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/dbs_address_space/Cargo.toml
  src/dragonball/src/dbs_arch/Cargo.toml
  src/dragonball/src/dbs_boot/Cargo.toml
  src/dragonball/src/dbs_virtio_devices/Cargo.toml
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/test_utils.rs
  src/dragonball/src/vm/kernel_config.rs
  src/dragonball/src/vm/mod.rs
  src/runtime-rs/Cargo.lock
Labels: size/tiny

#7552 Fix mimor bugs and improve coding stype of agent rpc/sandbox/mount
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
Labels: area/agent, size/tiny, ok-to-test

#7598 tests: upgrade bats version
  tests/integration/kubernetes/gha-run.sh
Labels: size/tiny, ok-to-test

#7492 kata-deploy: Ensure we cover SHIMS / DEFAULT_SHIM as part of our tests
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/kata-deploy-ensure-runtimec-classes-created.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/setup.sh
Labels: force-skip-ci, size/small, ok-to-test

#7596 tests: Create image that will be used in the unencrypted confidential tests
  .github/workflows/ci.yaml
  tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/Dockerfile
  tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/ssh/unencrypted
  tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/ssh/unencrypted.pub
Labels: size/medium

#7604 Follow up fixes for https://github.com/kata-containers/kata-containers/pull/7596
  .github/workflows/ci.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
Labels: force-skip-ci, size/small

#7607 ci: create-confidential-image: Add dependent actions
  .github/workflows/ci.yaml
Labels: force-skip-ci, size/small

#7608 ci: unencrypted-image: Fix build context
  .github/workflows/ci.yaml
  tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/Dockerfile
Labels: force-skip-ci, size/tiny

#7579 metrics: install kata once and run multiple checks
  .github/workflows/run-metrics.yaml
  tests/common.bash
  tests/metrics/gha-run.sh
Labels: needs-backport, no-backport-needed, area/metrics, size/small, ok-to-test

#7606 metrics: Add network nginx benchmark
  tests/metrics/network/README.md
  tests/metrics/network/nginx_kubernetes/nginx-network.sh
  tests/metrics/network/nginx_kubernetes/runtimeclass_workloads/nginx-networking.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7609 metrics: compute tensorflow statistics
  tests/metrics/machine_learning/tensorflow.sh
Labels: no-backport-needed, no-forward-port-needed, area/metrics, size/large, ok-to-test

#7589 Re-added hypervisor annotations
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/dbs_address_space/Cargo.toml
  src/dragonball/src/dbs_arch/Cargo.toml
  src/dragonball/src/dbs_boot/Cargo.toml
  src/dragonball/src/dbs_virtio_devices/Cargo.toml
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/test_utils.rs
  src/dragonball/src/vm/kernel_config.rs
  src/dragonball/src/vm/mod.rs
  src/runtime-rs/Cargo.lock
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, size/tiny

#7557 agent: avoid creating new `Vec` instances when easily avoidable
  src/agent/src/mount.rs
  src/agent/src/network.rs
  src/agent/src/rpc.rs
Labels: size/medium, ok-to-test

#7535 agent: Allow clippy::redundant_clone in the unit tests
  src/agent/src/device.rs
Labels: size/tiny

#7447 gha: static-checks: Move to the Azure instances
  .github/workflows/static-checks.yaml
Labels: size/tiny

#7547 kata-deploy: Preliminary k0s support
  tools/packaging/kata-deploy/README.md
  tools/packaging/kata-deploy/kata-deploy/overlays/k0s/kustomization.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/k0s/mount_k0s_conf.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#7211 Propogate secrets, config maps etc into guest if sharedFS not available
  src/agent/src/rpc.rs
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
  src/runtime/config/configuration-qemu-sev.toml.in
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/virtcontainers/fs_share.go
  src/runtime/virtcontainers/fs_share_darwin.go
  src/runtime/virtcontainers/fs_share_linux.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, size/huge, ok-to-test

#7638 docs: Remove installation step in virtcontainers doc
  src/runtime/virtcontainers/documentation/Developers.md
Labels: size/tiny

#7629 metrics: fix the loop used to stop kata components
  tests/common.bash
Labels: no-backport-needed, no-forward-port-needed, area/metrics, size/small, ok-to-test

#7618 metrics: Add common functions to the common script
  tests/metrics/lib/common.bash
  tests/metrics/machine_learning/tensorflow.sh
  tests/metrics/machine_learning/tensorflow_mobilenet_v1_bfloat16_fp32.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7626 metrics: Add Cassandra Kubernetes benchmark for kata metrics
  tests/metrics/disk/cassandra_kubernetes/cassandra.sh
  tests/metrics/disk/cassandra_kubernetes/runtimeclass_workloads/cassandra-service.yaml
  tests/metrics/disk/cassandra_kubernetes/runtimeclass_workloads/cassandra-statefulset.yaml
  tests/metrics/disk/cassandra_kubernetes/volume/block-local-storage.yaml
  tests/metrics/disk/cassandra_kubernetes/volume/block-loop-pv.yaml
  tests/metrics/disk/cassandra_kubernetes/volume/block-loop-pvc.yaml
Labels: no-backport-needed, no-forward-port-needed, size/large

#7169 runk: Support without pid ns
  src/agent/rustjail/src/container.rs
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7574 agent: runtime: add Agent Policy feature
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/Makefile
  src/agent/src/main.rs
  src/agent/src/policy.rs
  src/agent/src/rpc.rs
  src/kata-opa/allow-all.rego
  src/kata-opa/kata-opa.service.in
  src/libs/protocols/protos/agent.proto
  src/runtime/pkg/katautils/create.go
  src/runtime/pkg/oci/utils.go
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/pkg/mock/mock.go
  tools/osbuilder/rootfs-builder/cbl-mariner/config.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  versions.yaml
Labels: area/confidential-containers, size/tiny, ok-to-test

#7643 gha: tests: Add kata-deploy functional tests -- Part 1
  .github/workflows/run-kata-deploy-tests-on-aks.yaml
  .github/workflows/run-kata-deploy-tests-on-tdx.yaml
  tests/functional/kata-deploy/gha-run.sh
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/gha-run.sh
Labels: size/large, ok-to-test

#7644 metrics: Rename tensorflow scripts
  tests/metrics/machine_learning/tensorflow_nhwc.sh
  tests/metrics/machine_learning/tensorflow_nhwc_dockerfile/Dockerfile
Labels: no-backport-needed, no-forward-port-needed

#7640 gha: cri-containerd: Enable tests
  tests/integration/cri-containerd/gha-run.sh
  tests/integration/cri-containerd/integration-tests.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#7558 runtime-rs: add driver option
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
  src/runtime-rs/tests/texture/configuration-qemu.toml
  src/runtime-rs/tests/texture/kata-containers-configuration.toml
  src/runtime-rs/tests/utils/Cargo.toml
  src/runtime-rs/tests/utils/src/lib.rs
Labels: no-backport-needed, runtime-rs, size/large

#7651 runk: Modify kill command's error message for containerd tests
  src/tools/runk/Cargo.lock
  src/tools/runk/libcontainer/src/container.rs
Labels: size/medium

#7660 gha: ci: Start running kata-deploy tests
  .github/workflows/ci.yaml
Labels: force-skip-ci, size/small

#7662 metrics: Fix MobileNet help me description
  tests/metrics/machine_learning/tensorflow_mobilenet_v1_bfloat16_fp32.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7627 agent: simplify error handling
  src/agent/src/rpc.rs
Labels: size/large, ok-to-test

#7653 metrics: Add Tensorflow ResNet50 int8 benchmark
  tests/metrics/machine_learning/README.md
  tests/metrics/machine_learning/resnet50_int8_dockerfile/Dockerfile
  tests/metrics/machine_learning/tensorflow_resnet50_int8.sh
Labels: no-backport-needed, no-forward-port-needed, size/large

#7685 metrics: Fix check results for tensorflow benchmark
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7649 gha: k8s: kata-deploy: Move kata-deploy specific tests from integration/kubernetes to functional/kata-deploy
  tests/common.bash
  tests/functional/kata-deploy/gha-run.sh
  tests/functional/kata-deploy/kata-deploy.bats
  tests/functional/kata-deploy/run-kata-deploy-tests.sh
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/kata-deploy-ensure-runtimec-classes-created.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: force-skip-ci, size/large, ok-to-test

#7682 CC | kata-deploy: Properly create default runtime class
  tests/common.bash
  tests/integration/kubernetes/kata-deploy-ensure-runtimec-classes-created.bats
  tests/integration/kubernetes/setup.sh
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#7664 rootfs: agent: Policy support with AGENT_INIT=yes
  src/agent/src/main.rs
  src/agent/src/policy.rs
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7635 CC | move image service related code into image-rpc.rs
  src/agent/src/image_rpc.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
Labels: no-backport-needed, area/agent, area/confidential-containers, size/tiny, ok-to-test

#7680 metrics: Remove unused variable in tensorflow mobilenet script
  tests/metrics/machine_learning/tensorflow_mobilenet_v1_bfloat16_fp32.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7690 metrics: Fix README for pytorch
  tests/metrics/machine_learning/README.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7666 metrics: Enable kata runtime in K8s for FIO test.
  tests/metrics/gha-run.sh
  tests/metrics/storage/fio-k8s/Makefile
  tests/metrics/storage/fio-k8s/cmd/fiotest/Makefile
  tests/metrics/storage/fio-k8s/configs/example-config/kata-clh.yaml
  tests/metrics/storage/fio-k8s/configs/example-config/kata-qemu.yaml
  tests/metrics/storage/fio-k8s/fio-test-ci.sh
Labels: no-backport-needed, area/metrics, size/tiny, ok-to-test

#7710 metrics: Use function from metrics common in pytorch script
  tests/metrics/machine_learning/pytorch.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7708 gha: capture additional kata-deploy output
  tests/integration/kubernetes/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, force-skip-ci, size/tiny, ok-to-test

#7712 metrics: Fix FIO path
  tests/metrics/storage/fio-k8s/fio-test-ci.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7722 metrics: Add disk link to README
  tests/metrics/README.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7737 local-build: Remove GID before creating group
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Labels: size/tiny, ok-to-test

#7728 libs,tests: fix typo disable_guest_seccomp in configuration-anno-1.toml
  src/libs/kata-types/tests/texture/configuration-anno-1.toml
Labels: size/tiny

#7698 kata-types: introduce KataVirtualVolume to support nydus, direct volume and image pull
  src/libs/kata-types/src/mount.rs
Labels: no-backport-needed, area/runtime, size/large, ok-to-test

#7576 Update AA, image-rs td-shim
  .github/workflows/static-checks.yaml
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  versions.yaml
Labels: no-backport-needed, size/large, ok-to-test

#7744 CC | cherry-pick PR #7698 into CCv0
  src/libs/kata-types/src/mount.rs
Labels: no-backport-needed, area/confidential-containers, size/large

#7718 kata-agent: use default filemode for block device when it is set to 0
  src/agent/rustjail/src/lib.rs
Labels: needs-backport, size/tiny

#7745 gha: vfio: Run on Ubuntu 23.04 runner
  .github/workflows/run-vfio-tests.yaml
Labels: force-skip-ci, size/tiny

#7748 CC | backport | kata-deploy: Don't try to remove /opt/kata
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: force-skip-ci, size/tiny

#7749 CC | Backport | local-build: Remove GID before creating group
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Labels: size/tiny

#7736 metrics: Add TensorFlow ResNet50 FP32 benchmark
  tests/metrics/machine_learning/resnet50_fp32_dockerfile/Dockerfile
  tests/metrics/machine_learning/tensorflow_resnet50_fp32.sh
Labels: no-backport-needed, no-forward-port-needed, size/large

#7747 kata-deploy: Don't try to remove /opt/kata
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#7751 metrics: Remove unused variable in tensorflow nhwc script
  tests/metrics/machine_learning/tensorflow_nhwc.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7602 Refine storage device management for kata-agent
  src/agent/src/device.rs
  src/agent/src/main.rs
  src/agent/src/mount.rs
  src/agent/src/namespace.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/storage/bind_watcher_handler.rs
  src/agent/src/storage/block_handler.rs
  src/agent/src/storage/ephemeral_handler.rs
  src/agent/src/storage/fs_handler.rs
  src/agent/src/storage/local_handler.rs
  src/agent/src/storage/mod.rs
  src/libs/kata-sys-util/src/mount.rs
  src/libs/kata-types/src/mount.rs
Labels: no-backport-needed, area/agent, size/huge, ok-to-test

#7758 gha: Avoid "fail-fast" in tests that are known to be flaky
  .github/workflows/run-cri-containerd-tests.yaml
  .github/workflows/run-metrics.yaml
  .github/workflows/run-nydus-tests.yaml
  .github/workflows/static-checks.yaml
Labels: force-skip-ci, size/small

#7742 runtime-rs: check peer close in log_forwarder
  src/runtime-rs/crates/agent/src/log_forwarder.rs
Labels: no-backport-needed, runtime-rs, size/small

#7755 tests: use unique test name
  tests/integration/kubernetes/k8s-kill-all-process-in-container.bats
Labels: force-skip-ci, size/tiny

#7754 tests: delete k8s deployment at the test's end
  tests/integration/kubernetes/k8s-pod-quota.bats
Labels: force-skip-ci, size/tiny, ok-to-test

#7763 CC | cherry-pick #7602 from main branch
  src/agent/src/mount.rs
Labels: no-backport-needed, size/small

#7767 CC | cherry pick #7602 from main into CCv0
  src/agent/src/device.rs
  src/agent/src/main.rs
  src/agent/src/mount.rs
  src/agent/src/namespace.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/storage/bind_watcher_handler.rs
  src/agent/src/storage/block_handler.rs
  src/agent/src/storage/ephemeral_handler.rs
  src/agent/src/storage/fs_handler.rs
  src/agent/src/storage/local_handler.rs
  src/agent/src/storage/mod.rs
  src/libs/kata-sys-util/src/mount.rs
  src/libs/kata-types/src/mount.rs
Labels: area/confidential-containers, size/huge

#7185 tests: Add confidential test
  tests/integration/kubernetes/confidential_common.sh
  tests/integration/kubernetes/k8s-confidential.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/pod-confidential-unencrypted.yaml
Labels: force-skip-ci, size/large, ok-to-test

#7585 dragonball: vsock add fifo/pipe stream support for passed fd hybridSt…
  src/dragonball/src/dbs_virtio_devices/src/vsock/backend/hybrid_stream.rs
  src/dragonball/src/dbs_virtio_devices/src/vsock/backend/mod.rs
  src/dragonball/src/dbs_virtio_devices/src/vsock/backend/unix_stream.rs
  src/dragonball/src/dbs_virtio_devices/src/vsock/muxer/mod.rs
  src/dragonball/src/dbs_virtio_devices/src/vsock/muxer/muxer_impl.rs
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7775 metrics: fix parsing issue on memory-usage test
  tests/metrics/density/memory_usage.sh
Labels: no-backport-needed, area/metrics, size/medium, ok-to-test

#7787 metrics: Fix memory inside limits for kata metrics
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7783 metrics: Add metrics report script
  tests/metrics/report/makereport.sh
  tests/metrics/report/report_dockerfile/Dockerfile
  tests/metrics/report/report_dockerfile/dut-details.R
  tests/metrics/report/report_dockerfile/fio-reads.R
  tests/metrics/report/report_dockerfile/fio-writes.R
  tests/metrics/report/report_dockerfile/footprint-density.R
  tests/metrics/report/report_dockerfile/genreport.sh
  tests/metrics/report/report_dockerfile/html.Rmd
  tests/metrics/report/report_dockerfile/lifecycle-time.R
  tests/metrics/report/report_dockerfile/mem-in-cont.R
  tests/metrics/report/report_dockerfile/memory-footprint.R
  tests/metrics/report/report_dockerfile/metrics_report.Rmd
  tests/metrics/report/report_dockerfile/network-cpu.R
Labels: no-backport-needed, no-forward-port-needed, size/huge

#7797 versions: Bump guest-components
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  versions.yaml
Labels: no-backport-needed, size/large

#7772 metrics: Enable FIO limits for kata metrics
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#7789 Fixes tests on AMD machines
  src/runtime/cmd/kata-runtime/kata-check_amd64_test.go
  src/runtime/cmd/kata-runtime/kata-env_amd64_test.go
Labels: no-backport-needed, size/small, ok-to-test

#7813 metrics: Add grabdata script for metrics report
  tests/metrics/report/grabdata.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny
