Repository kata-containers/kata-containers, pull requests merged in 2023-02, with the labels that each got.

#6149 runtime:fix stat uds path
  src/runtime/pkg/containerd-shim-v2/shim_management.go
Labels: size/tiny

#6140 virtiofsd: fix the build on ppc64le
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
Labels: no-forward-port-needed, size/tiny, backport-to-stable-3.0

#6212 CI: Make docker version stick to v20.10 in ubuntu:20.04 for s390x|ppc64le
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Labels: needs-backport, size/tiny

#6056 arm64/CI: fix unit test failure on arm64
  src/agent/src/watcher.rs
  src/runtime/pkg/containerd-shim-v2/stream_test.go
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/ops/volume_ops.rs
  src/tools/kata-ctl/src/utils.rs
Labels: size/tiny

#6215 Backport CI fixes for s390x and ppc64le to stable-3.0
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
Labels: no-backport-needed, backport, size/tiny

#6009 Dragonball: add cpu resize ability
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/error.rs
  src/dragonball/src/vcpu/mod.rs
  src/dragonball/src/vcpu/vcpu_impl.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/dragonball/src/vm/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
Labels: high-priority, runtime-rs, size/large

#6208 improvement: Fix naming conventions for span name and log subsystem
  src/runtime/virtcontainers/fs_share_linux.go
Labels: size/tiny

#6175 Qemu logs for stable 3.0
  src/runtime/pkg/govmm/qemu/examples_test.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
  src/runtime/pkg/govmm/qemu/qmp.go
  src/runtime/pkg/govmm/qemu/qmp_test.go
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, backport, size/tiny

#6217 CI: Set docker version to v20.10 in ubuntu:20.04 for s390x|ppc64le
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Labels: no-backport-needed, area/confidential-containers, size/tiny

#6158 CC | Take runtime-rs into consideration when building and caching the shim-v2 tarball
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/shim-v2/install_go_rust.sh
Labels: runtime-rs, size/small

#6182 CCv0: Merge main into CCv0 branch
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
  docs/Developer-Guide.md
  docs/use-cases/using-Intel-QAT-and-kata.md
  src/dragonball/README.md
  src/dragonball/docs/images/upcall-architecture.svg
  src/dragonball/docs/upcall.md
  src/dragonball/src/address_space_manager.rs
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/vm/mod.rs
  src/dragonball/src/vmm.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/govmm/qemu/examples_test.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
  src/runtime/pkg/govmm/qemu/qmp.go
  src/runtime/pkg/govmm/qemu/qmp_test.go
  src/runtime/virtcontainers/qemu.go
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  versions.yaml
Labels: no-backport-needed, area/confidential-containers, ignore-depends-on, size/huge

#6223 runtime: remove not used shim configurations
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/katatestutils/utils.go
Labels: size/tiny

#6163 kernel: Add console kernel config for s390
  tools/packaging/kernel/configs/fragments/s390/console.conf
  tools/packaging/kernel/kata_config_version
Labels: size/tiny

#6193 runtime-rs: ignor "no such process" error when delete cgroup for a thread to let it go
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/libs/Cargo.lock
  src/libs/kata-sys-util/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/cgroups/mod.rs
  src/tools/runk/Cargo.lock
  src/tools/runk/libcontainer/Cargo.toml
Labels: runtime-rs, size/medium

#6152 virtiofsd: change cache mod to const
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/virtiofsd.go
Labels: size/small

#6234 clh: Enforce API timeout only for vm.boot request
  src/runtime/virtcontainers/clh.go
Labels: size/tiny

#6209 Action check kernel config version
  .github/workflows/static-checks.yaml
  tools/packaging/kernel/README.md
Labels: no-backport-needed, size/small

#6183 main | docs: Fix missing critical steps in how-to-hotplug-memory-arm64.md
  docs/how-to/how-to-hotplug-memory-arm64.md
Labels: size/small

#5796 CCv0: Enable 'policy' for SNP container
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu_amd64.go
Labels: no-backport-needed, area/confidential-containers, size/tiny

#6166 Minor cleanups in make file
  Makefile
  src/tools/agent-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.lock
  tools/packaging/kata-deploy/local-build/Makefile
Labels: no-backport-needed, size/tiny

#6233 osbuilder: remove duplicate KATA_BUILD_CC entry
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: size/tiny

#6200 runtime: Improve documentation of appendFDs
  src/runtime/pkg/govmm/qemu/qemu.go
Labels: enhancement, no-backport-needed, size/tiny

#6196 stable-3.0 | docs: Fix missing critical steps in how-to-hotplug-memory-arm64.md
  docs/how-to/how-to-hotplug-memory-arm64.md
Labels: size/tiny

#6064 rootfs: support EROFS filesystem
  docs/how-to/README.md
  docs/how-to/how-to-use-erofs-build-rootfs.md
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/kernel_param.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime/Makefile
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/config/configuration-acrn.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/acrn_arch_base.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_test.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_s390x.go
  tools/osbuilder/image-builder/image_builder.sh
  tools/packaging/kernel/configs/fragments/common/fs.conf
  tools/packaging/kernel/kata_config_version
Labels: no-backport-needed, no-forward-port-needed, area/runtime, area/osbuilder, runtime-rs, size/tiny, kernel

#5999 runtime: support cgroup v2 metrics marshal guest metrics
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/runtime/pkg/containerd-shim-v2/metrics.go
  src/runtime/pkg/containerd-shim-v2/metrics_test.go
  src/runtime/pkg/resourcecontrol/utils.go
  src/runtime/pkg/resourcecontrol/utils_linux.go
Labels: size/large

#6245 CCv0: install protobuf-compiler explicitly in shim-v2 Dockerfile
  tools/packaging/static-build/shim-v2/Dockerfile
Labels: size/tiny

#5920 kata-ctl: Expand unit tests for CPU check
  src/tools/kata-ctl/src/check.rs
Labels: no-backport-needed, no-forward-port-needed, size/large

#6143 shim-v2/build.sh: Only build runtime-rs for the supported arches
  src/runtime-rs/Makefile
Labels: needs-backport, size/tiny

#5007 SEV: Update ReducedPhysBits
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
Labels: needs-backport, size/tiny

#6076 runtime: add reconnect timeout for vhost user block
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/device/config/config.go
  src/runtime/pkg/device/drivers/vhost_user_blk.go
  src/runtime/pkg/device/manager/manager.go
  src/runtime/pkg/device/manager/manager_test.go
  src/runtime/pkg/govmm/qemu/qmp.go
  src/runtime/pkg/govmm/qemu/qmp_test.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/oci/utils.go
  src/runtime/virtcontainers/container_linux_test.go
  src/runtime/virtcontainers/container_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/persist_test.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_linux_test.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: size/large

#6274 CCv0: shim-v2: Only build runtime-rs for the supported arches
  src/runtime-rs/Makefile
Labels: runtime-rs, size/tiny

#6243 CC | Dragonball: add confidential_vm_type for TDX
  src/dragonball/src/api/v1/instance_info.rs
  src/dragonball/src/api/v1/mod.rs
  src/dragonball/src/error.rs
  src/dragonball/src/kvm_context.rs
  src/dragonball/src/vm/mod.rs
Labels: runtime-rs, size/tiny

#6272 runtime: tracing: Fix missing ctx return
  src/runtime/virtcontainers/clh.go
Labels: no-backport-needed

#6279 CC|action: Place permission adjustment for s390x kata-payload
  .github/workflows/cc-payload-after-push-s390x.yaml
Labels: no-backport-needed, area/github, size/tiny

#6273 kata-deploy: Install protobuf-compiler explicitly in shim-v2 Dockerfile
  tools/packaging/static-build/shim-v2/Dockerfile
Labels: size/tiny

#6275 stable-3.0: Stable 3.0 backports
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/rpc.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime/pkg/containerd-shim-v2/wait.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
Labels: size/tiny

#6285 Assisted PR | docs: Update how-to-use-kata-containers-with-firecracker.md
  docs/how-to/how-to-use-kata-containers-with-firecracker.md
Labels: no-backport-needed, size/tiny

#6283 # Kata Containers 3.1.0-rc0
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml
Labels: size/tiny

#6282 # Kata Containers 3.0.2
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: size/tiny

#6201 runtime-rs: Add basic CH implementation
  src/libs/kata-types/src/config/default.rs
  src/libs/kata-types/src/config/hypervisor/ch.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/src/config/mod.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/README.md
  src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
  src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/net_util.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/virtio_devices.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/ch/utils.rs
  src/runtime-rs/crates/hypervisor/src/hypervisor_persist.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
Labels: runtime-rs, size/huge

#6277 CC | Dragonball TDX: add is_tdx_enabled to identify tdx VM type
  src/dragonball/src/api/v1/instance_info.rs
  src/dragonball/src/vm/mod.rs
Labels: runtime-rs, size/small

#6294 packaging/shim-v2: Only change the config if the file exists
  tools/packaging/static-build/shim-v2/build.sh
Labels: no-backport-needed, size/tiny

#6287 sandbox: set the dns for the sandbox
  src/agent/src/network.rs
  src/libs/kata-types/src/config/default.rs
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: no-backport-needed, no-forward-port-needed, runtime-rs, size/tiny

#6300 runtime-rs: handle sys_dir bind volume
  src/runtime-rs/crates/resource/src/volume/mod.rs
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
Labels: runtime-rs, size/tiny

#6296 runtime-rs: Don't build on Power, don't break on Power.
  src/runtime-rs/arch/powerpc64le-options.mk
  tools/packaging/static-build/shim-v2/install_go_rust.sh
Labels: runtime-rs, size/tiny

#6308 runtime-rs: remove unnecessary Send/Sync trait implement
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/runtimes/linux_container/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/runtimes/wasm_container/src/lib.rs
Labels: no-backport-needed, size/tiny

#6298 docs: Change the order of release step
  docs/Release-Process.md
Labels: force-skip-ci, size/small

#6267 github-action: Replace deprecated command with environment file
  .github/workflows/add-backport-label.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
Labels: size/tiny

#6304 versions: Use ubuntu as the default distro for the rootfs-image
  versions.yaml
Labels: no-backport-needed, size/tiny

#6309 utils: always check some dependencies.
  utils/kata-manager.sh
Labels: size/tiny

#6310 packaging: Cache the container used to build the kata-deploy artefacts
  .github/workflows/kata-deploy-push.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/kernel/build.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/qemu/build-base-qemu.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/td-shim/build.sh
  tools/packaging/static-build/virtiofsd/build.sh
  tools/packaging/static-build/virtiofsd/gnu/Dockerfile
  tools/packaging/static-build/virtiofsd/musl/Dockerfile
  versions.yaml
Labels: no-backport-needed, size/large

#6323 shim-v2: Bump Ubuntu container image to 22.04
  tools/packaging/static-build/shim-v2/Dockerfile
Labels: needs-backport, size/tiny

#6319 kata-deploy: Fix building the kata static firecracker arm64 package occurred an error
  tools/packaging/static-build/firecracker/build-static-firecracker.sh
Labels: needs-backport, size/tiny

#6322 Remove all remaining unsafe impl
  src/dragonball/Cargo.lock
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/vmm_action.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/src/sock/hybrid_vsock.rs
  src/runtime-rs/crates/agent/src/sock/vsock.rs
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/runtimes/common/src/message.rs
Labels: no-backport-needed, size/medium

#6334 Revert "workflows: Push the builder image to quay.io"
  .github/workflows/kata-deploy-push.yaml
Labels: size/tiny

#6325 dragonball: config_manager: preserve device when update
  src/dragonball/src/config_manager.rs
Labels: no-backport-needed, runtime-rs, size/tiny

#6340 kata-deploy: Ensure go binaries can run on Ubuntu 20.04
  tools/packaging/static-build/shim-v2/Dockerfile
  tools/packaging/static-build/shim-v2/install_go_rust.sh
Labels: needs-backport, size/tiny

#6330 devguide: Add link to the contribution guidelines
  docs/Developer-Guide.md
Labels: no-backport-needed, no-forward-port-needed, size/small

#6236 osbuilder: fix default build target in makefile
  tools/osbuilder/Makefile
Labels: size/tiny

#6080 runtime-rs: cleanup kata host share path
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/utils.rs
  src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: runtime-rs, size/tiny

#6312 virtiofsd: update to a valid path on ppc64le
  src/runtime/Makefile
Labels: size/tiny

#6332 runtime-rs: Improve Cloud Hypervisor config handling
  src/libs/kata-types/src/config/default.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
  src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Labels: area/cloud-hypervisor, runtime-rs, size/tiny

#6124 kernel: Add CONFIG_SEV_GUEST to SEV kernel config
  tools/packaging/kernel/configs/fragments/x86_64/sev/sev.conf
  tools/packaging/kernel/kata_config_version
Labels: no-backport-needed, size/tiny

#5958 kata-ctl/exec: add new command exec to enter guest VM.
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/ops.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/ops/exec_ops.rs
Labels: runtime-rs, size/huge, kata-ctl

#6338 CC: Rename SEV firmware to AMDSEV.fd
  src/runtime/Makefile
  tools/packaging/static-build/ovmf/build-ovmf.sh
Labels: size/tiny

#6262 osbuilder: Include minimal set of device nodes in ubuntu initrd
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
Labels: needs-backport, size/tiny

#6177 Adding caching capability for SEV kernel and initrd
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components.sh
Labels: size/medium

#6314 feat(runtime): make static resource management consistent with 2.0
  src/libs/kata-types/src/config/runtime.rs
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/runtimes/src/manager.rs
Labels: size/tiny

#6363 packaging: Fix sev cache kernel issue
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/cache_components.sh
Labels: size/small

#6376 Upgrade to Cloud Hypervisor v30.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpuAffinity.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpu_affinity.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: no-backport-needed, size/medium

#6369 runtime: use filepath.Clean() to clean the mount path
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/mount_linux_test.go
  src/runtime/virtcontainers/mount_test.go
Labels: needs-backport, size/tiny

#6360 CCv0: update deps for 0.4.0
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  versions.yaml
Labels: size/huge

#6368 agent: don't set permission of existing directory in copy_file
  src/agent/src/rpc.rs
Labels: no-backport-needed, size/tiny
