Repository kata-containers/kata-containers, pull requests merged in 2023-06, with the labels that each got.

#6929 kubernetes: add agnhost command in pod yaml
  tests/integration/kubernetes/runtimeclass_workloads/pod-empty-dir-fsgroup.yaml
  tests/integration/kubernetes/runtimeclass_workloads/pod-http-liveness.yaml
  tests/integration/kubernetes/runtimeclass_workloads/pod-tcp-liveness.yaml
Labels: size/tiny

#7002 gha: aks: Ensure host_os is used everywhere needed
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: size/tiny

#7007 kata-deploy: Change how we get the Ubuntu k8s key
  tools/packaging/kata-deploy/Dockerfile
Labels: needs-backport, size/tiny

#7009 README: Display badge for the "Publish Artefacts" job and update the Kata Containers logo
  README.md
Labels: size/tiny

#7011 gha: aks: Use short SHA in cluster name
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: size/small

#7013 runtime-rs: bugfix: update Cargo.lock
  src/runtime-rs/Cargo.lock
Labels: size/tiny

#4748 agent: fix the issue of exec hang with a backgroud process
  src/agent/rustjail/src/process.rs
  src/agent/src/rpc.rs
Labels: needs-backport, size/tiny

#7023 CCv0: update dependencies for CoCo release 0.6.0
  versions.yaml
Labels: size/tiny

#7033 agent-ctl: fix the compile error
  src/agent/Cargo.lock
  src/libs/Cargo.lock
  src/libs/kata-sys-util/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/tools/agent-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.lock
  src/tools/runk/Cargo.lock
Labels: size/huge

#6980 runtime-rs: handle copy files when share_fs is not available
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/volume/mod.rs
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
  versions.yaml
Labels: area/storage, no-backport-needed, lang/rust, runtime-rs, size/medium, rust

#6972 gha: aks: Extract `run` commands to a script
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
  tests/integration/gha-run.sh
Labels: size/large

#7037 CCv0: Update dependencies to v0.6.0 for release
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  versions.yaml
Labels: no-backport-needed

#7035 log-parser: Update log parser link at README
  src/tools/log-parser-rs/README.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6764 kata-ctl: Switch to slog logging; add --log-level and --json-logging arguments
  src/agent/Cargo.lock
  src/libs/logging/Cargo.toml
  src/libs/logging/src/lib.rs
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/ops/exec_ops.rs
  src/tools/kata-ctl/src/ops/volume_ops.rs
Labels: size/large, kata-ctl, hackathon

#7048 gha: Fix gha-run.sh and unbreak CI
  .github/workflows/run-k8s-tests-on-aks.yaml
  tests/integration/gha-run.sh
Labels: size/tiny

#7060 local-build: Fix qemu build for SNP
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, size/tiny

#6973 add support direct volume and refactor device manager
  docs/how-to/README.md
  docs/how-to/how-to-run-kata-containers-with-kinds-of-Block-Volumes.md
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/mod.rs
  src/runtime-rs/crates/resource/src/volume/utils.rs
Labels: runtime-rs, size/huge

#6756 Port Measured rootfs feature from CCv0 branch to main
  .github/workflows/build-kata-static-tarball-amd64.yaml
  src/runtime/Makefile
  tools/osbuilder/image-builder/Dockerfile
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/common/confidential_containers/cryptsetup.conf
  tools/packaging/kernel/configs/fragments/common/confidential_containers/initramfs.conf
  tools/packaging/kernel/configs/fragments/x86_64/crypto.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/static-build/initramfs/Dockerfile
  tools/packaging/static-build/initramfs/build-initramfs.sh
  tools/packaging/static-build/initramfs/build.sh
  tools/packaging/static-build/initramfs/init.sh
  tools/packaging/static-build/initramfs/initramfs.list
  tools/packaging/static-build/kernel/build.sh
  tools/packaging/static-build/shim-v2/build.sh
  versions.yaml
Labels: no-backport-needed, size/large

#6998 Dragonball: support resize memory
  src/dragonball/Cargo.lock
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/device_manager/balloon_dev_mgr.rs
  src/dragonball/src/device_manager/blk_dev_mgr.rs
  src/dragonball/src/device_manager/mem_dev_mgr.rs
  src/dragonball/src/device_manager/memory_region_handler.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/error.rs
  src/dragonball/src/vm/mod.rs
Labels: runtime-rs, size/huge

#6970 CCv0: kata-deploy-cc: Ignore pod annotations in kata-remote
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: no-backport-needed

#7082 packaging: Remove snap package
  .github/workflows/snap-release.yaml
  .github/workflows/snap.yaml
  README.md
  docs/install/README.md
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
  docs/install/snap-installation-guide.md
  snap/local/README.md
  snap/local/snap-common.sh
  snap/snapcraft.yaml
  src/runtime/README.md
  tools/packaging/.gitignore
  tools/packaging/Makefile
  tools/packaging/README.md
  tools/packaging/kernel/README.md
Labels: size/huge

#6289 feat(runtime): vcpu resize capability
  docs/Limitations.md
  docs/design/README.md
  docs/design/VSocks.md
  docs/design/vcpu-handling-runtime-go.md
  docs/design/vcpu-handling-runtime-rs.md
  src/agent/src/linux_abi.rs
  src/agent/src/sandbox.rs
  src/libs/kata-types/src/cpu.rs
  src/libs/kata-types/src/utils/u32_set.rs
  src/libs/protocols/protos/agent.proto
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/cgroups/mod.rs
  src/runtime-rs/crates/resource/src/cpu_mem/cpu.rs
  src/runtime-rs/crates/resource/src/cpu_mem/initial_size.rs
  src/runtime-rs/crates/resource/src/cpu_mem/mod.rs
  src/runtime-rs/crates/resource/src/lib.rs
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/runtimes/common/src/runtime_handler.rs
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/vm.go
Labels: high-priority, runtime-rs, size/huge

#7087 gha: Fix `stage` definition in matrix
  .github/workflows/build-kata-static-tarball-amd64.yaml
Labels: size/tiny

#7099 tools: Fix no-op builds
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny

#7090 versions: Update firecracker version to 1.3.3
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#7092 runtime-rs: Enhance flexibility of virtio-fs config
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_fs.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
Labels: size/small

#7095 docs: Update Developer Guide
  docs/Developer-Guide.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7117 gha: Add base branch on SHA on pull requst
  .github/workflows/run-launchtimes-metrics.yaml
Labels: no-backport-needed, area/metrics, size/tiny

#7122 CC: Set default value for AA_KBC for cc_rootfs_initrd_tarball
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, size/tiny

#7112 Fix deprecated virtiofsd args (go shim only)
  src/runtime/Makefile
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/virtcontainers/virtiofsd.go
  src/runtime/virtcontainers/virtiofsd_test.go
Labels: bug, needs-backport, size/small, backport-to-stable-3.1

#7114 tests: Add tests lib common script
  tests/metrics/lib/common.bash
Labels: no-backport-needed, no-forward-port-needed, size/large

#7131 gha: Fix format for run launchtimes metrics yaml
  .github/workflows/run-launchtimes-metrics.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7124 [stable-3.1] backport: versions: Use ubuntu as the default distro for the rootfs-image
  versions.yaml
Labels: size/tiny

#7129 tests: Add json script for metrics tests
  tests/metrics/lib/json.bash
Labels: no-backport-needed, no-forward-port-needed, size/large

#7109 tests: Move tests helper script to this repo
  tests/common.bash
Labels: no-backport-needed, area/metrics, size/large

#7138 metrics: install kata and launch-times test
  .github/workflows/ci-on-push.yaml
  .github/workflows/run-launchtimes-metrics.yaml
  .github/workflows/run-metrics.yaml
  tests/metrics/gha-run.sh
Labels: no-backport-needed, size/large

#7150 gha: Fix gha actions
  .github/workflows/run-metrics.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7148 packaging: Fix indentation in init.sh script
  tools/packaging/static-build/initramfs/init.sh
Labels: no-backport-needed, no-forward-port-needed, size/small

#7154 docs: fix spelling of "crate"
  src/runtime-rs/docs/images/crate-overview.drawio
  src/runtime-rs/docs/images/crate-overview.svg
Labels: size/large

#6800 kata-ctl: Check for vm capability
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
  src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/env_ops.rs
  src/tools/kata-ctl/src/types.rs
Labels: no-backport-needed, size/tiny

#7155 [stable-3.1] Fix deprecated virtiofsd args (go shim only)
  src/runtime/Makefile
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/virtcontainers/virtiofsd.go
  src/runtime/virtcontainers/virtiofsd_test.go
Labels: backport, size/small

#7162 gha: Don't automatically trigger CI
  .github/workflows/ci-on-push.yaml
Labels: no-backport-needed, size/small

#7058 add support vfio device manager
  docs/how-to/how-to-run-kata-containers-with-kinds-of-Block-Volumes.md
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
  src/runtime-rs/crates/hypervisor/src/device/util.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
  src/runtime-rs/crates/resource/src/volume/mod.rs
  src/runtime-rs/crates/resource/src/volume/vfio_volume.rs
Labels: runtime-rs, size/huge

#7158 docs: Add general metrics documentation
  README.md
  tests/metrics/README.md
Labels: no-backport-needed, no-forward-port-needed, size/large

#7159 metrics: enable launch-times test on gha-run metrics script
  tests/metrics/gha-run.sh
  tests/metrics/lib/common.bash
  tests/metrics/time/launch_times.sh
Labels: no-backport-needed, area/metrics, size/huge, ok-to-test

#7056 dragonball: avoid obtaining lock twice in create_stdio_console
  src/dragonball/src/device_manager/console_manager.rs
Labels: size/small

#7141 runtime: Add support for key annotations to remote hyp
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/remote.go
Labels: no-backport-needed, size/tiny

#7097 static-build: Remove kata-version parameter
  tools/packaging/static-build/initramfs/build.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/td-shim/build.sh
Labels: no-backport-needed, size/small

#7171 docs: Add boot time metrics documentation
  tests/metrics/README.md
  tests/metrics/time/README.md
Labels: no-backport-needed, no-forward-port-needed, size/small

#7173 checkmetrics: Add checkmetrics makefile and documentation
  tests/metrics/README.md
  tests/metrics/cmd/checkmetrics/Makefile
  tests/metrics/cmd/checkmetrics/README.md
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#7192 # Kata Containers 3.1.3
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: size/tiny

#7188 runtime-rs: fix build error on AArch64
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
Labels: size/small

#7180 metrics: Fix retrieving hypervisor version on metrics
  tests/common.bash
Labels: size/tiny

#7189 runtime-rs: bugfix for direct volume path's validation.
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/utils.rs
Labels: size/small

#7104 runtime-rs: support physical endpoint using device manager
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
  src/runtime-rs/crates/resource/src/network/mod.rs
  src/runtime-rs/crates/resource/src/network/network_with_netns.rs
Labels: runtime-rs, size/medium

#7193 stable-3.1: A bunch of kata-deploy fixes and a switch to using ubuntu as the base image
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/large

#7197 metrics: Uniformity across function names in gha-run.sh
  tests/metrics/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7200 runtime: Add "none" as a shared_fs option
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
  src/runtime/config/configuration-qemu-sev.toml.in
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/device/config/config.go
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/acrn_arch_base.go
  src/runtime/virtcontainers/acrn_arch_base_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_ppc64le.go
Labels: size/large, ok-to-test

#7174 metrics: Add memory footprint tests
  .github/workflows/run-metrics.yaml
  tests/metrics/README.md
  tests/metrics/density/README.md
  tests/metrics/density/fast_footprint.sh
  tests/metrics/density/footprint_data.md
  tests/metrics/density/footprint_data.sh
  tests/metrics/density/memory_usage.sh
  tests/metrics/density/memory_usage_inside_container.sh
  tests/metrics/gha-run.sh
Labels: no-backport-needed, area/metrics, size/tiny, ok-to-test
