Repository kata-containers/kata-containers, pull requests merged in 2023-07, with the labels that each got.

#4492 runtime: fix PCIe topology for GPUDirect use-case
  src/runtime/cmd/kata-runtime/kata-env.go
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/device/config/config.go
  src/runtime/pkg/device/drivers/utils.go
  src/runtime/pkg/device/drivers/vfio.go
  src/runtime/pkg/device/drivers/vfio_test.go
  src/runtime/pkg/device/manager/manager.go
  src/runtime/pkg/device/manager/manager_test.go
  src/runtime/pkg/device/manager/utils.go
  src/runtime/pkg/device/manager/utils_test.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/hypervisors/hypervisor_state.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_test.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: size/huge, area/gpu

#6949 gpu: Update kernel building to the latest changes
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/gpu/nvidia.arm64.conf.in
  tools/packaging/kernel/configs/fragments/gpu/nvidia.conf
  tools/packaging/kernel/configs/fragments/gpu/nvidia.x86_64.conf.in
  tools/packaging/kernel/kata_config_version
Labels: size/tiny, area/gpu

#5444 doc: Add documentation for the virtualization reference architecture
  docs/design/README.md
  docs/design/kata-vra.md
Labels: size/large, area/gpu

#7209 packaging: Fix indentation of build.sh script at ovmf
  tools/packaging/static-build/ovmf/build.sh
Labels: no-backport-needed, no-forward-port-needed, size/small

#7199 metrics: Add checkmetrics to gha-run.sh for metrics CI
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#7224 gha: release: Use a specific release of hub
  .github/workflows/release.yaml
Labels: needs-backport, size/tiny

#7225 stable-3.1 | gha: release: Use a specific release of hub
  .github/workflows/release.yaml
Labels: size/tiny

#7202 Convert `is_allowed`, `ttrpc_error` and `sl` to functions
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/notifier.rs
  src/agent/rustjail/src/container.rs
  src/agent/src/device.rs
  src/agent/src/main.rs
  src/agent/src/metrics.rs
  src/agent/src/rpc.rs
  src/agent/src/tracer.rs
  src/agent/src/uevent.rs
Labels: size/huge, ok-to-test

#7217 versions: Upgrade to Cloud Hypervisor v33.0
  versions.yaml
Labels: no-forward-port-needed, size/tiny, ok-to-test

#7222 gha: dragonball: Correctly propagate PATH update
  .github/workflows/static-checks-dragonball.yaml
Labels: size/tiny

#7228 Update dependencies after guest-components repo updates
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  tools/osbuilder/rootfs-builder/rootfs.sh
  versions.yaml
Labels: no-backport-needed, size/tiny

#7234 cc: kata-deploy: Adapt the SNP's QEMU name
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: size/tiny

#7237 cc: gha: Pass MEASURED_ROOTFS to the artefacts build
  .github/workflows/cc-payload-after-push-amd64.yaml
  .github/workflows/cc-payload-after-push-s390x.yaml
  .github/workflows/cc-payload-amd64.yaml
  .github/workflows/cc-payload-s390x.yaml
Labels: size/small

#7241 cc: gha: Matrix "include" cannot be a list
  .github/workflows/cc-payload-after-push-amd64.yaml
  .github/workflows/cc-payload-after-push-s390x.yaml
  .github/workflows/cc-payload-amd64.yaml
  .github/workflows/cc-payload-s390x.yaml
Labels: size/tiny

#7181 metrics: Adds blogbench and webtool metrics tests
  .github/workflows/run-metrics.yaml
  tests/metrics/gha-run.sh
  tests/metrics/storage/blogbench.sh
  tests/metrics/storage/blogbench_dockerfile/Dockerfile
  tests/metrics/storage/web-tooling-dockerfile/Dockerfile.in
  tests/metrics/storage/webtooling.sh
Labels: no-backport-needed, area/metrics, size/large, ok-to-test

#7244 cc: gha: Export MEASURE_ROOTFS=yes for rootfs-image builds
  .github/workflows/cc-payload-after-push-amd64.yaml
  .github/workflows/cc-payload-after-push-s390x.yaml
  .github/workflows/cc-payload-amd64.yaml
  .github/workflows/cc-payload-s390x.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small

#7246 cc: gha: Avoid building twice the components set as "include"
  .github/workflows/cc-payload-after-push-amd64.yaml
  .github/workflows/cc-payload-after-push-s390x.yaml
  .github/workflows/cc-payload-amd64.yaml
  .github/workflows/cc-payload-s390x.yaml
Labels: size/small

#7238 gha: k8s: Ensure tests are running on a specific namespace
  tests/integration/gha-run.sh
  tests/integration/kubernetes/k8s-pod-quota.bats
  tests/integration/kubernetes/runtimeclass_workloads/pod-custom-dns.yaml
  tests/integration/kubernetes/runtimeclass_workloads/pod-oom.yaml
  tests/integration/kubernetes/runtimeclass_workloads/pod-quota-deployment.yaml
  tests/integration/kubernetes/runtimeclass_workloads/resource-quota.yaml
  tests/integration/kubernetes/runtimeclass_workloads/tests-namespace.yaml
Labels: size/small, ok-to-test

#7240 metrics: storing metrics workflow artifacts
  .github/workflows/run-metrics.yaml
  tests/common.bash
  tests/metrics/gha-run.sh
  tests/metrics/lib/common.bash
Labels: no-backport-needed, area/ci, area/metrics, size/large, ok-to-test

#6953 gha: Add nightly jobs
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/ci-nightly.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/ci.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/publish-kata-deploy-payload-amd64.yaml
  .github/workflows/publish-kata-deploy-payload-arm64.yaml
  .github/workflows/publish-kata-deploy-payload-s390x.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
  .github/workflows/run-metrics.yaml
Labels: size/large

#7230 tests: Enable memory usage metrics tests
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/density/memory_usage.sh
  tests/metrics/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7260 gha: ci: Follow up fixes for the nightly jobs
  .github/workflows/ci-nightly.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/ci.yaml
  .github/workflows/payload-after-push.yaml
Labels: size/small

#7261 gha: ci: Avoid using env unless it's really needed
  .github/workflows/ci-nightly.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/payload-after-push.yaml
Labels: size/small

#7257 config: Update remote hypervisor config
  src/runtime/config/configuration-remote.toml.in
Labels: no-backport-needed, area/confidential-containers, size/tiny

#6839 tests: Enable running k8s tests on Mariner
  .github/workflows/build-kata-static-tarball-amd64.yaml
  tests/integration/gha-run.sh
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/setup.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
  versions.yaml
Labels: size/large, ok-to-test

#7263 gha: ci: More follow up fixes after adding a nightly CI
  .github/workflows/ci-nightly.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/ci.yaml
Labels: size/tiny

#7243 gha: k8s: Ensure cluster doesn't exist before creating it
  tests/integration/gha-run.sh
Labels: size/tiny

#7264 gha: ci: Avoid using env also in the ci-nightly and payload-after-push
  .github/workflows/ci-nightly.yaml
  .github/workflows/payload-after-push.yaml
Labels: force-skip-ci, size/tiny

#7266 kata-deploy: Remove remote annotation logic
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: no-backport-needed, size/tiny

#7267 gha: ci: Fix refernce passed to checkout@v3
  .github/workflows/ci-on-push.yaml
Labels: force-skip-ci, size/tiny

#7272 dragonball: Don't fail if a request asks for more CPUs than allowed
  src/agent/rustjail/src/process.rs
  src/agent/src/rpc.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  tests/integration/kubernetes/k8s-oom.bats
Labels: size/tiny, ok-to-test

#7277 gha: ci: Use github.sha to get the last commit reference
  .github/workflows/ci-nightly.yaml
  .github/workflows/payload-after-push.yaml
Labels: force-skip-ci, size/tiny

#7280 README: Add badge for our Nightly CI
  README.md
Labels: size/tiny, ok-to-test

#7288 gha: nightly: Fix long name of AKS clusters issue and make the CI easier to test
  .github/workflows/ci-nightly.yaml
Labels: force-skip-ci, size/tiny

#7299 gha: Cancel previous jobs if a PR is updated
  .github/workflows/PR-wip-checks.yaml
  .github/workflows/add-backport-label.yaml
  .github/workflows/add-issues-to-project.yaml
  .github/workflows/add-pr-sizing-label.yaml
  .github/workflows/auto-backport.yaml
  .github/workflows/cargo-deny-runner.yaml
  .github/workflows/ci-nightly.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/commit-message-check.yaml
  .github/workflows/darwin-tests.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/release.yaml
  .github/workflows/require-pr-porting-labels.yaml
  .github/workflows/static-checks-dragonball.yaml
  .github/workflows/static-checks.yaml
Labels: force-skip-ci, size/tiny

#7303 metrics: Update memory usage script
  tests/metrics/density/memory_usage.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7308 gha: k8s: tdx: Temporarily disable TDX tests
  .github/workflows/ci.yaml
Labels: force-skip-ci, size/small

#7306 runtime-rs: Do not scan network if network model is "none"
  src/runtime-rs/crates/resource/src/network/network_with_netns.rs
Labels: runtime-rs, size/tiny, ok-to-test

#7276 gha: ci: Gather info about the node / pods
  tests/integration/gha-run.sh
Labels: size/tiny, ok-to-test

#7297 tools: Use a consistent target name when building mariner initrd
  tests/integration/kubernetes/setup.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  versions.yaml
Labels: size/tiny, ok-to-test

#7287 CCv0 | Update guest components dependency version
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  versions.yaml
Labels: no-backport-needed, size/small

#7255 metrics: Enable memory inside container metrics
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/density/memory_usage_inside_container.sh
  tests/metrics/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#7314 tests: gha: ci: Add cri-containerd tests skeleton
  .github/workflows/ci.yaml
  .github/workflows/run-cri-containerd-tests.yaml
  tests/common.bash
  tests/integration/cri-containerd/gha-run.sh
  tests/metrics/gha-run.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#7315 tests: Add machine learning performance tests
  tests/metrics/README.md
  tests/metrics/machine_learning/README.md
  tests/metrics/machine_learning/pytorch.sh
  tests/metrics/machine_learning/pytorch_dockerfile/Dockerfile
  tests/metrics/machine_learning/tensorflow.sh
  tests/metrics/machine_learning/tensorflow_dockerfile/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, size/large

#7322 gha: ci: Add cri-containerd tests skeleton -- follow up 1
  .github/workflows/run-cri-containerd-tests.yaml
  tests/integration/cri-containerd/gha-run.sh
  versions.yaml
Labels: force-skip-ci, size/tiny

#7330 tests: Add metrics storage documentation
  tests/metrics/README.md
  tests/metrics/storage/README.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7328 tests: Add function before function name in common.bash for metrics
  tests/metrics/lib/common.bash
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7236 kata-ctl: Move GuestProtection code to kata-sys-util
  src/agent/Cargo.lock
  src/libs/Cargo.lock
  src/libs/kata-sys-util/Cargo.toml
  src/libs/kata-sys-util/src/cpu.rs
  src/libs/kata-sys-util/src/lib.rs
  src/libs/kata-sys-util/src/protection.rs
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
  src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/env_ops.rs
  src/tools/kata-ctl/src/utils.rs
Labels: size/huge

#7018 runtime-rs: add parameter for propagation of (u)mount events
  src/libs/kata-sys-util/src/mount.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/resource/src/share_fs/sandbox_bind_mounts.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
  src/runtime-rs/crates/resource/src/share_fs/utils.rs
Labels: area/storage, no-backport-needed, runtime-rs, size/tiny, rust

#7344 kata-deploy: Add a debug option to kata-deploy (and also use it as part of our CI)
  tests/integration/gha-run.sh
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#7333 kernel: Update kernel config name
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
Labels: size/tiny, ok-to-test

#7337 metrics: use rm -f to remove the oldest continerd config file.
  tests/common.bash
Labels: no-backport-needed, area/metrics, size/tiny, ok-to-test

#7349 metrics: Stop running kata-env before kata is properly installed.
  tests/metrics/density/memory_usage.sh
  tests/metrics/lib/common.bash
  tests/metrics/lib/json.bash
Labels: no-backport-needed, area/metrics, size/small, ok-to-test

#7021 runtime-rs: ignore unconfigured network interfaces
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs
  src/runtime-rs/crates/resource/src/network/network_with_netns.rs
Labels: area/networking, no-backport-needed, runtime-rs, size/tiny

#5450 feat(Tracing): tracing in Rust runtime
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/mod.rs
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/src/tracer.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/shim/Cargo.toml
  src/runtime-rs/crates/shim/src/bin/main.rs
  src/runtime-rs/crates/shim/src/shim.rs
Labels: no-backport-needed, runtime-rs, size/huge

#7351 local-build: always use DEFSERVICEOFFLOAD for CoCo
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, size/tiny

#7320 metrics: replace backslashes used to escape double quoted jq key expr.
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: no-backport-needed, area/metrics, size/small, ok-to-test

#7335 tests: Add MobileNet Tensorflow performance benchmark
  tests/metrics/machine_learning/README.md
  tests/metrics/machine_learning/tensorflow_mobilenet_benchmark.sh
  tests/metrics/machine_learning/tensorflow_mobilenet_dockerfile/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, size/large

#7361 gha: ci: cri-containerd: Fix KATA_HYPERVSIOR typo
  .github/workflows/run-cri-containerd-tests.yaml
Labels: force-skip-ci, size/tiny

#7360 metrics: Update machine learning documentation
  tests/metrics/machine_learning/README.md
Labels: no-backport-needed, no-forward-port-needed, size/small

#7369 ci: k8s: Bring TDX tests back
  .github/workflows/ci.yaml
Labels: force-skip-ci, size/small, ok-to-test

#6993 agent: Ignore already mounted dev/fs/pseudo-fs
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/mount.rs
Labels: size/medium, ok-to-test, area/gpu

#7352 agent: Fix exec hang issues with a backgroud process
  src/agent/rustjail/src/process.rs
  src/agent/src/rpc.rs
Labels: size/small, ok-to-test

#6788 versions: Update kernel to version v6.1.x
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/6.1.x/no_patches.txt
  versions.yaml
Labels: size/tiny, ok-to-test

#7374 ci: Move `tests/integration/gha-run.sh` to `tests/integration/kuberentes/` ... and also remove KUBECONFIG from the tdx envs
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: force-skip-ci, size/small

#7378 ci: k8s: Adapt "source ..." to the new location of gha-run.sh
  tests/integration/kubernetes/gha-run.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#7377 metrics: stop hypervirsor and shim at init_env stage
  tests/common.bash
  tests/metrics/lib/common.bash
  tests/metrics/storage/blogbench.sh
Labels: no-backport-needed, area/metrics, size/tiny, ok-to-test

#7372 versions: Bump virtiofsd to v1.7.0
  versions.yaml
Labels: size/tiny, ok-to-test

#7354 CC | Update deps 0.7.0 (rc)
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  tests/integration/kubernetes/tests_common.sh
  tools/packaging/kata-deploy/examples/test-deploy-kata-clh.yaml
  tools/packaging/kata-deploy/examples/test-deploy-kata-dragonball.yaml
  tools/packaging/kata-deploy/examples/test-deploy-kata-fc.yaml
  tools/packaging/kata-deploy/examples/test-deploy-kata-qemu.yaml
  tools/packaging/kata-deploy/examples/test-deploy-runc.yaml
  versions.yaml
Labels: size/tiny, ok-to-test

#7388 Revert "metrics: Replace backslashes used to escape double quoted key in jq expr"
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7387 metrics: Add function to memory inside container script
  tests/metrics/density/memory_usage_inside_container.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7391 gha: ci: cc-payload-after-push: Add workflow_dispatch trigger
  .github/workflows/cc-payload-after-push.yaml
Labels: force-skip-ci, size/tiny

#7363 metrics: enable TensorFlow benchmark to be run on gha
  .github/workflows/run-metrics.yaml
  tests/metrics/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7376 metrics: Add C-Ray performance test
  tests/metrics/README.md
  tests/metrics/cpu/README.md
  tests/metrics/cpu/c-ray/Dockerfile
  tests/metrics/cpu/c-ray/cray.sh
Labels: no-backport-needed, no-forward-port-needed, area/metrics, size/medium

#7394 kata-deploy: Add VERSION and versions.yaml to the final tarball
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/release.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
  versions.yaml
Labels: size/tiny, ok-to-test

#7406 kata-deploy: Properly get the path of the versions.yaml file
  tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#7404 cache: kernel: Consider changes in tools/packaging/kernel
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components_main.sh
Labels: size/tiny

#7399 packaging/tools: Add kata-debug and use it as part of our CI
  Makefile
  README.md
  tests/integration/kubernetes/gha-run.sh
  tools/packaging/kata-debug/Dockerfile
  tools/packaging/kata-debug/README.md
  tools/packaging/kata-debug/debug.sh
  tools/packaging/kata-debug/kata-debug-build-and-upload-payload.sh
Labels: force-skip-ci, area/kata-deploy, size/tiny, ok-to-test

#7418 workflows: fix malformed CC payload s390x yaml
  .github/workflows/cc-payload-s390x.yaml
Labels: no-backport-needed, force-skip-ci, size/tiny

#7426 gha: ci: Add no-op nydus tests to our CI
  .github/workflows/ci.yaml
  .github/workflows/run-nydus-tests.yaml
  tests/integration/nydus/gha-run.sh
  tests/integration/nydus/nydus-container.yaml
  tests/integration/nydus/nydus-sandbox.yaml
  tests/integration/nydus/nydus_tests.sh
  tests/integration/nydus/nydusd-config.json
Labels: force-skip-ci, size/tiny

#7427 ci: nydus: Fix typo in "source"
  tests/integration/nydus/gha-run.sh
Labels: force-skip-ci, size/tiny

#7417 kata-deploy-binaries: kernel_cache: Take module_dir into account
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny

#7413 release: Mention the container images used to build the project
  tools/packaging/release/release-notes.sh
Labels: size/small

#7382 s390x: Fixing device.Bus assignment
  src/runtime/cmd/kata-runtime/kata-env.go
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/device/drivers/utils.go
  src/runtime/pkg/device/drivers/vfio.go
  src/runtime/pkg/device/manager/manager.go
  src/runtime/pkg/device/manager/manager_test.go
  src/runtime/pkg/device/manager/utils.go
  src/runtime/pkg/device/manager/utils_test.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qmp.go
  src/runtime/pkg/govmm/qemu/qmp_test.go
  src/runtime/pkg/hypervisors/hypervisor_state.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: no-backport-needed, size/huge

#7402 CCv0 | Ensure kata-deploy scripts from CCv0 are as close to main as possible
  .github/workflows/cc-payload-after-push-amd64.yaml
  .github/workflows/cc-payload-after-push-s390x.yaml
  .github/workflows/cc-payload-amd64.yaml
  .github/workflows/cc-payload-s390x.yaml
  src/runtime/arch/amd64-options.mk
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy-cc/Dockerfile
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
  tools/packaging/static-build/qemu/build-static-qemu-cc.sh
  tools/packaging/static-build/qemu/build-static-qemu-experimental-cc.sh
  versions.yaml
Labels: size/tiny

#7436 gha: ci: Add skeleton of vfio job
  .github/workflows/ci.yaml
  .github/workflows/run-vfio-tests.yaml
  tests/functional/vfio/gha-run.sh
Labels: force-ci, size/medium, ok-to-test

#7408 kata-deploy: Allow shim creation based on what's passed to the daemonset
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#7430 metrics: General improvements to json.bash script
  tests/metrics/lib/json.bash
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7432 runk: Add Docker guide to README
  src/tools/runk/README.md
Labels: size/small

#7437 cache: kernel: Fix kernel caching
  tools/packaging/static-build/cache_components_main.sh
Labels: size/tiny, ok-to-test

#7440 CC | Adjust cache URL for TDX components
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small

#7365 agent: exclude symlinks from recursive ownership change
  src/agent/src/mount.rs
Labels: bug, needs-backport, size/tiny

#7443 CC| cc: cache: Enable more cached components back and ensure shim-v2 can be properly cached
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny

#7450 CCv0: fix a prefix to kata for IBM SE image build
  tools/packaging/guest-image/build_se_image.sh
Labels: no-backport-needed, size/tiny

#7448 cc: cache: shim-v2: Re-enable cached artefact
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny

#7461 CC | kata-deploy: Add executable bit to script
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny

#7455 tests: QoL improvements for running tests locally
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
  tests/.gitignore
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/setup.sh
  tests/integration/kubernetes/tests_common.sh
Labels: force-skip-ci, size/medium, ok-to-test

#7425 runtime-rs: remove unneeded 'mut' keywords
  src/runtime-rs/crates/resource/src/cpu_mem/initial_size.rs
  src/runtime-rs/crates/resource/src/volume/spdk_volume.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: size/tiny

#7439 agent,libs: Remove unused 'mut' keywords
  src/agent/src/signal.rs
  src/libs/kata-types/src/annotations/mod.rs
Labels: size/tiny

#7453 tests: Fix `k8s-job` test
  .github/workflows/run-k8s-tests-on-aks.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#7465 gha: dragonball: Run only on the dragonball labeled machine
  .github/workflows/static-checks-dragonball.yaml
Labels: no-backport-needed, size/tiny

#7471 CC | kata-deploy: Add the runtime-classes that are not yet on main
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny

#7442 metrics: Add FIO benchmark for metrics tests
  tests/metrics/storage/fio-k8s/.gitignore
  tests/metrics/storage/fio-k8s/Makefile
  tests/metrics/storage/fio-k8s/cmd/fiotest/Makefile
  tests/metrics/storage/fio-k8s/cmd/fiotest/go.mod
  tests/metrics/storage/fio-k8s/cmd/fiotest/go.sum
  tests/metrics/storage/fio-k8s/cmd/fiotest/main.go
  tests/metrics/storage/fio-k8s/configs/example-config/fio-jobs/randrw-async.job
  tests/metrics/storage/fio-k8s/configs/example-config/fio-jobs/randrw-libaio.job
  tests/metrics/storage/fio-k8s/configs/example-config/fio-jobs/randrw-sync.job
  tests/metrics/storage/fio-k8s/configs/example-config/kata.yaml
  tests/metrics/storage/fio-k8s/configs/example-config/runc.yaml
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/randread-libaio.job
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/randread-mmpap.job
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/randrw-libaio.job
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/randrw-mmap.job
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/randwrite-libaio.job
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/randwrite-mmap.job
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/seqread-libaio.job
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/seqread-mmap.job
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/seqread-psync.job
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/seqwrite-libaio.job
  tests/metrics/storage/fio-k8s/configs/test-config/fio-jobs/seqwrite-mmap.job
  tests/metrics/storage/fio-k8s/configs/test-config/kata.yaml
  tests/metrics/storage/fio-k8s/configs/test-config/runc.yaml
  tests/metrics/storage/fio-k8s/pkg/env/Makefile
  tests/metrics/storage/fio-k8s/pkg/env/env.go
  tests/metrics/storage/fio-k8s/pkg/env/go.mod
  tests/metrics/storage/fio-k8s/pkg/env/go.sum
  tests/metrics/storage/fio-k8s/pkg/exec/Exec.go
  tests/metrics/storage/fio-k8s/pkg/exec/go.mod
  tests/metrics/storage/fio-k8s/pkg/exec/go.sum
  tests/metrics/storage/fio-k8s/pkg/k8s/Makefile
  tests/metrics/storage/fio-k8s/pkg/k8s/exec.go
  tests/metrics/storage/fio-k8s/pkg/k8s/go.mod
  tests/metrics/storage/fio-k8s/pkg/k8s/go.sum
  tests/metrics/storage/fio-k8s/pkg/k8s/k8s.go
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7456 agent: fix typo in constant
  src/agent/src/sandbox.rs
Labels: size/tiny, ok-to-test

#7477 CC | kata-deploy: Use different shim arrays for different arches
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny

#7139 runtime-rs: change block index to 0
  src/libs/kata-types/src/config/default.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/kernel_param.rs
  src/runtime-rs/crates/resource/src/lib.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/spdk_volume.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: no-backport-needed, runtime-rs, size/large

#7482 kata-deploy: Fix if-elif-else-statement
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny

#7484 kata-deploy: We need shim to an array, not a string
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny

#7473 metrics: Add FIO report files for kata metrics
  tests/metrics/storage/fio-k8s/cmd/fiotest/Makefile
  tests/metrics/storage/fio-k8s/cmd/fiotest/main.go
  tests/metrics/storage/fio-k8s/pkg/env/Makefile
  tests/metrics/storage/fio-k8s/pkg/env/env.go
  tests/metrics/storage/fio-k8s/pkg/exec/Exec.go
  tests/metrics/storage/fio-k8s/pkg/k8s/Makefile
  tests/metrics/storage/fio-k8s/pkg/k8s/exec.go
  tests/metrics/storage/fio-k8s/pkg/k8s/k8s.go
  tests/metrics/storage/fio-k8s/scripts/Makefile
  tests/metrics/storage/fio-k8s/scripts/compare-virtiofsd-dax.sh
  tests/metrics/storage/fio-k8s/scripts/dax-compare-test/report/fio.ipynb
  tests/metrics/storage/fio-k8s/scripts/dax-compare-test/report/fio.py
  tests/metrics/storage/fio-k8s/scripts/dax-compare-test/report/gen-html-fio-report.sh
  tests/metrics/storage/fio-k8s/scripts/dax-compare-test/report/run-docker-jupyter-server.sh
Labels: no-backport-needed, no-forward-port-needed, size/large

#7132 tests: Add `k8s-volume` and `k8s-file-volume` tests to GHA CI
  tests/integration/kubernetes/k8s-file-volume.bats
  tests/integration/kubernetes/k8s-volume.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/pv-pod.yaml
  tests/integration/kubernetes/runtimeclass_workloads/pv-volume.yaml
  tests/integration/kubernetes/runtimeclass_workloads/volume-claim.yaml
  tests/integration/kubernetes/tests_common.sh
Labels: force-skip-ci, size/large, ok-to-test

#7390 runtime: Configure the image request timeout to handle large workloads
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/runtime/Makefile
  src/runtime/config/configuration-clh-tdx.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
  src/runtime/config/configuration-qemu-se.toml.in
  src/runtime/config/configuration-qemu-sev.toml.in
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/config/configuration-remote.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, size/medium

#7490 # Kata Containers 3.2.0-alpha4
  VERSION
Labels: size/tiny, ok-to-test

#7498 gha: release: `stage` must be a string
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-s390x.yaml
Labels: force-skip-ci, size/tiny

#7496 k8s: Rely on the USING_NFD environment variable passed by the jobs
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
Labels: force-skip-ci, size/tiny

#7488 docs: Update links for pods and kubelet
  docs/design/architecture/kubernetes.md
Labels: no-backport-needed, area/documentation, size/tiny

#7499 gha: release: `stage` must be defined for arm64 / s390x yamls
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-s390x.yaml
Labels: force-skip-ci, size/tiny

#7396 metrics: Enable Tensorflow metrics for kata CI
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/gha-run.sh
  tests/metrics/machine_learning/tensorflow.sh
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test
