Repository kata-containers/kata-containers, pull requests merged in 2023-05, with the labels that each got.

#6759 gha: sev: fix for kata-deploy error
  .github/workflows/run-k8s-tests-on-sev.yaml
Labels: no-backport-needed, size/tiny

#6723 gha: Also run k8s tests on qemu-snp
  .github/workflows/ci-on-push.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: size/tiny

#6749 virtcontainers/factory: Improved test coverage
  src/runtime/virtcontainers/factory/factory_test.go
Labels: size/large, hackathon

#6774 CC | runtime: Add configurable context timeout for StopVM
  src/runtime/virtcontainers/remote.go
Labels: no-backport-needed, size/small

#6729 virtcontainers/persist: Improved test coverage 65% to 87.5%
  src/runtime/virtcontainers/persist/manager_test.go
Labels: size/small, hackathon

#6728 pkg/signals: Improved test coverage 60% to 100%
  src/runtime/pkg/signals/signals_test.go
Labels: size/tiny, hackathon

#6699 gpu: cold plug VFIO devices
  src/runtime/cmd/kata-runtime/kata-env.go
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/device/drivers/utils.go
  src/runtime/pkg/device/drivers/vfio.go
  src/runtime/pkg/device/manager/manager.go
  src/runtime/pkg/device/manager/utils.go
  src/runtime/pkg/device/manager/utils_test.go
  src/runtime/pkg/hypervisors/hypervisor_state.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
Labels: size/huge

#6738 runtime: Fix virtiofs fd leak
  src/agent/rustjail/src/mount.rs
  src/agent/src/rpc.rs
  src/libs/protocols/protos/agent.proto
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/container_linux_test.go
  src/runtime/virtcontainers/container_test.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/mock/mock.go
Labels: size/large

#6753 cross-compile: Include documentation and configuration for cross-compile
  src/tools/kata-ctl/Cross.toml
  src/tools/kata-ctl/README.md
Labels: size/small

#6594 warning_fix: fix warnings when build with cargo-1.68.0
  src/libs/kata-types/src/annotations/mod.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/resource/src/network/utils/address.rs
  src/runtime-rs/crates/resource/src/network/utils/mod.rs
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
  src/runtime-rs/crates/runtimes/virt_container/src/health_check.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/tools/agent-ctl/src/main.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/ops/exec_ops.rs
  src/tools/kata-ctl/src/ops/volume_ops.rs
  src/tools/kata-ctl/src/utils.rs
  src/tools/runk/Cargo.lock
  src/tools/runk/libcontainer/src/cgroup.rs
  src/tools/runk/src/main.rs
  versions.yaml
Labels: runtime-rs, size/tiny

#6512 Log-parser-rs
  Makefile
  README.md
  src/tools/log-parser-rs/Cargo.lock
  src/tools/log-parser-rs/Cargo.toml
  src/tools/log-parser-rs/Makefile
  src/tools/log-parser-rs/README.md
  src/tools/log-parser-rs/src/args.rs
  src/tools/log-parser-rs/src/log_message.rs
  src/tools/log-parser-rs/src/log_parser_error.rs
  src/tools/log-parser-rs/src/main.rs
  src/tools/log-parser-rs/src/output_file.rs
  src/tools/log-parser-rs/src/parse_file.rs
  src/tools/log-parser-rs/src/process_logs.rs
Labels: area/logging, no-backport-needed, size/huge, outreach, rust

#6379 kata-ctl: add generic kvm check & unit test
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/types.rs
Labels: no-backport-needed, size/medium

#6591 packaging: Add sev artifacts to main
  .github/workflows/build-kata-static-tarball-amd64.yaml
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-sev.toml.in
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
  tools/packaging/static-build/cache_components_main.sh
  tools/packaging/static-build/ovmf/build-ovmf.sh
  versions.yaml
Labels: no-backport-needed, size/huge

#6794 docs: Mark snap installation method as unmaintained
  docs/install/README.md
  docs/install/snap-installation-guide.md
Labels: force-skip-ci, size/medium

#6700 packaging: Add SEV-SNP artifacts to main
  .github/workflows/build-kata-static-tarball-amd64.yaml
  docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md
  src/runtime/Makefile
  src/runtime/arch/amd64-options.mk
  src/runtime/config/configuration-qemu-snp.toml.in
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
  tools/packaging/qemu/patches/tag_patches/3b6a2b6b7466f6dea53243900b7516c3f29027b7/no_patches.txt
  tools/packaging/static-build/cache_components_main.sh
  versions.yaml
Labels: no-backport-needed, size/huge

#6778 cache: Update the KERNEL_FLAVOUR list to include nvidia-gpu
  .github/workflows/build-kata-static-tarball-amd64.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components_main.sh
Labels: size/tiny

#6807 cache: Fix nvidia-gpu version
  tools/packaging/static-build/cache_components_main.sh
Labels: size/tiny

#6748 gha: Fix snap creation workflow
  .github/workflows/snap-release.yaml
  .github/workflows/snap.yaml
Labels: size/tiny, hackathon

#6739 gha: Fix Body Line Length action flagging empty body commit messages
  .github/workflows/commit-message-check.yaml
Labels: size/tiny

#6742 runtime: remove overriding ARCH value by default for ppc64le
  src/agent/Makefile
  src/runtime-rs/Makefile
  src/tools/agent-ctl/Makefile
  src/tools/runk/Makefile
  src/tools/trace-forwarder/Makefile
  utils.mk
Labels: no-backport-needed, size/tiny

#6811 cache: More fixes to nvidia-gpu kernels caching
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components_main.sh
Labels: size/small

#6815 actions: multi-arch runtime-payload
  .github/workflows/cc-payload-after-push.yaml
  .github/workflows/cc-payload.yaml
Labels: size/tiny

#6450 main | release: Fix multi-arch publishing is not supported
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/release.yaml
Labels: size/large

#6763 virtcontainers: Improved test coverage for fc.go from 4.6% to 18.5%
  src/runtime/virtcontainers/fc_test.go
Labels: size/large, hackathon

#6817 # Kata Containers 3.1.1
  VERSION
  src/agent/src/main.rs
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: size/tiny

#6825 kata-deploy: Build improvements
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
  tools/packaging/static-build/firecracker/build-static-firecracker.sh
Labels: size/medium

#6835 kata-deploy: Add http_proxy as part of the docker build
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6812 Dragonball: use LinuxBootConfigurator::write_bootparams
  src/dragonball/src/vm/x86_64.rs
Labels: runtime-rs, size/small

#6804 runtime-rs: fix building instructions to use correct required Rust ve…
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
Labels: runtime-rs, size/tiny

#6767 kata-ctl: Add the option to install kata-ctl to a user specified directory
  src/tools/kata-ctl/Makefile
  src/tools/kata-ctl/README.md
Labels: no-backport-needed, size/tiny, hackathon

#6823 kata-manager: Fix '-o' syntax and logic error
  utils/kata-manager.sh
Labels: size/tiny

#6832 deploy: Fix arch in image tag
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: no-backport-needed, size/tiny

#6735 virtcontainers/pkg/compatoci/: Improved coverage for for Kata 2.0
  src/runtime/virtcontainers/pkg/compatoci/utils.go
  src/runtime/virtcontainers/pkg/compatoci/utils_test.go
Labels: size/tiny, hackathon

#6773 agent: Add context to errors that may occur when AgentConfig file is …
  src/agent/src/config.rs
Labels: size/tiny

#6849 osbuilder: Fix indentation in rootfs.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6780 ppc64le: switch virtiofsd from C to rust version
  src/runtime/Makefile
  tools/packaging/scripts/configure-hypervisor.sh
  versions.yaml
Labels: no-backport-needed, size/small

#6852 deploy: fix shell script error
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: no-backport-needed, size/tiny

#6845 gpu: Rename the last bits from `gpu` to `nvidia-gpu`
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny

#6789 runtime: Port sev package to main
  src/runtime/pkg/README.md
  src/runtime/pkg/sev/README.md
  src/runtime/pkg/sev/kbs/kbs.go
  src/runtime/pkg/sev/ovmf.go
  src/runtime/pkg/sev/sev.go
  src/runtime/pkg/sev/sev_test.go
  src/runtime/pkg/sev/testdata/README.md
  src/runtime/pkg/sev/testdata/ovmf_suffix.bin
  src/runtime/pkg/sev/vcpu_sigs.go
  src/runtime/pkg/sev/vcpu_sigs_test.go
  src/runtime/pkg/sev/vmsa.go
Labels: no-backport-needed, size/huge

#6858 gha: tdx: Use the k3s overlay for kata-cleanup
  .github/workflows/run-k8s-tests-on-tdx.yaml
Labels: no-backport-needed, size/tiny

#6810 gha: Enable SEV-SNP tests on main
  src/runtime/Makefile
  tests/integration/kubernetes/k8s-cpu-ns.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/small

#6866 gha: k8s: Make the tests more reliable
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
Labels: no-backport-needed, size/tiny

#6838 runtime: use enable_vcpus_pinning from toml
  src/runtime/pkg/oci/utils.go
Labels: size/tiny

#6833 resource-control: fix setting CPU affinities on Linux
  src/runtime/pkg/resourcecontrol/utils_linux.go
Labels: needs-backport, size/tiny

#6862 deploy: fix shell script error
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: no-backport-needed, size/tiny

#6882 update tokio dependency
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/src/signal.rs
  src/agent/vsock-exporter/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/linux_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/shim-ctl/Cargo.toml
  src/runtime-rs/crates/shim/Cargo.toml
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
Labels: needs-backport, size/huge

#6819 runtime: Use static_sandbox_resource_mgmt=true for TEEs
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-sev.toml.in
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
Labels: needs-backport, size/tiny

#6888 stable-3.1 | update tokio dependency
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/src/signal.rs
  src/agent/vsock-exporter/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/linux_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/shim-ctl/Cargo.toml
  src/runtime-rs/crates/shim/Cargo.toml
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
Labels: size/tiny

#6869 CC | runtime: Use static_sandbox_resource_mgmt=true for TEEs
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-sev.toml.in
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
Labels: size/tiny

#6886 CC: tdx: Stick to the 2022ww44 TDX stack for the CCv0 branch
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/virtcontainers/hypervisor_linux_amd64.go
  src/runtime/virtcontainers/qemu_amd64.go
  tools/packaging/kernel/configs/fragments/x86_64/tdx/tdx.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/5.19-TDX-v2.x/no_patches.txt
  tools/packaging/qemu/patches/tag_patches/ad4c7f529a279685da84297773b4ec8080153c2d-plus-TDX-v1.3/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/ovmf/build.sh
  versions.yaml
Labels: size/medium

#6892 # Kata Containers 3.2.0-alpha1
  VERSION
Labels: size/tiny

#6896 tools: Fix arch bug
  tools/packaging/static-build/firecracker/build-static-firecracker.sh
Labels: no-backport-needed, size/tiny

#6900 gha: payload-after-push: Pass secrets down
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/payload-after-push.yaml
Labels: no-backport-needed, size/tiny

#6902 CC | local-build: Bring back root_hash logic
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny

#6898 cache: Fix OVMF caching
  tools/packaging/static-build/cache_components_main.sh
Labels: no-backport-needed, size/tiny

#6906 gha: aks: Wait a little bit more before run the tests
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: no-backport-needed, size/tiny

#6913 local-build: Standardise what's set for the local build scripts
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-copy-yq-installer.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
Labels: needs-forward-port, size/small

#6924 osbuilder: Bump fedora image version
  tools/osbuilder/dockerfiles/QAT/Dockerfile
  tools/osbuilder/image-builder/Dockerfile
Labels: needs-backport, size/tiny

#6918 Fix cache for OVMF and rootfs-initrd (both x86_64)
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components_main.sh
Labels: size/tiny

#6919 runtime: Fix QEMU cmdline for TDX
  src/runtime/arch/amd64-options.mk
Labels: size/tiny

#5441 runtime-rs: device manager for runtime-rs
  src/agent/src/device.rs
  src/agent/src/mount.rs
  src/libs/kata-types/src/config/hypervisor/dragonball.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Makefile
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/block.rs
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_fs.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_vsock.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/share_fs_device.rs
  src/runtime-rs/crates/hypervisor/src/device/util.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/kernel_param.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/network/endpoint/ipvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/macvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/veth_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/vlan_endpoint.rs
  src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
  src/runtime-rs/crates/resource/src/rootfs/nydus_rootfs.rs
  src/runtime-rs/crates/resource/src/rootfs/share_fs_rootfs.rs
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
  src/runtime-rs/crates/resource/src/share_fs/utils.rs
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/default_volume.rs
  src/runtime-rs/crates/resource/src/volume/hugepage.rs
  src/runtime-rs/crates/resource/src/volume/mod.rs
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
  src/runtime-rs/crates/resource/src/volume/shm_volume.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
Labels: no-backport-needed, no-forward-port-needed, runtime-rs, size/tiny

#6930 # Kata Containers 3.2.0-alpha2
  VERSION
Labels: size/tiny

#6935 release: Fix `docker/login-action` version
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/release.yaml
Labels: no-backport-needed, size/tiny

#6941 # Kata Containers 3.2.0-alpha3
  VERSION
Labels: no-backport-needed, size/tiny

#6939 versions: Update nydus version to 2.2.1
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6943 gha: release: login-action: Don't specify docker.io registry
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/release.yaml
Labels: no-backport-needed, size/tiny

#6947 gha: release: Simplify the process for tagging the payload
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-s390x.yaml
Labels: no-backport-needed, size/tiny

#6933 CC | runtime: config: Fix image path for QEMU TDX
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-tdx.toml.in
Labels: size/tiny

#6926 kata-deploy: Fix indentation on kata deploy merge script
  tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6952 doc: Update git commands
  tools/packaging/kata-deploy/README.md
  tools/packaging/kernel/README.md
Labels: no-backport-needed, size/tiny

#6958 kata-deploy: Improve shim backup / restore
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/medium

#6872 dragonball: Remove virtio-net and vsock devices gracefully
  src/dragonball/src/config_manager.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
  src/dragonball/src/device_manager/vsock_dev_mgr.rs
Labels: runtime-rs, size/tiny

#6956 kata-deploy-cc: Port fixes
  tools/packaging/kata-deploy-cc/Dockerfile
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: size/tiny

#6846 dragonball: convert BlockDeviceMgr and VirtioNetDeviceMgr functions to methods
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/device_manager/blk_dev_mgr.rs
  src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
Labels: runtime-rs, size/tiny

#6959 runtime: sending SIGKILL to qemu
  src/runtime/virtcontainers/qemu.go
Labels: needs-backport, size/tiny, backport-to-stable-3.1

#6963 kata-deploy: Remove trailing and leading white spaces in kata-deploy-binaries.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny

#6860 netlink: Fix the issue of update_interface
  src/agent/src/netlink.rs
Labels: needs-backport, size/tiny

#6686 gha: Create Mariner host as part of k8s tests
  .github/workflows/run-k8s-tests-on-aks.yaml
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/setup.sh
Labels: no-backport-needed, size/tiny

#6702 runtime-rs/kata-ctl: Enhancement of DirectVolumeMount.
  src/agent/Cargo.lock
  src/libs/Cargo.lock
  src/libs/kata-types/Cargo.toml
  src/libs/kata-types/src/mount.rs
  src/runtime-rs/Cargo.lock
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/src/ops/volume_ops.rs
Labels: runtime-rs, size/tiny

#6598 runtime-rs/sandbox_bindmounts: add support for sandbox bindmounts
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/runtime.rs
  src/libs/kata-types/src/mount.rs
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/sandbox_bind_mounts.rs
  src/runtime-rs/crates/resource/src/share_fs/utils.rs
  src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
Labels: runtime-rs, size/large

#6806 Dragonball: support vcpu hotplug on aarch64
  src/dragonball/Cargo.lock
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/dragonball/src/vm/aarch64.rs
  src/dragonball/src/vm/mod.rs
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0005-upcall-dragonball-devmgr-suppots-cpu-hotplug-on-arm6.patch
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0006-msi-control-msi-irq-number-activated.patch
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0007-smp-update-bringup_nonboot_cpus-parameters.patch
Labels: runtime-rs, size/huge

#6983 gha: Unbreak CI and fix cluster creation step
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: size/tiny

#6967 runtime: sending SIGKILL to qemu (backport to 3.1)
  src/runtime/virtcontainers/qemu.go
Labels: backport, size/small

#6995 gha: Fix Mariner cluster creation
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: size/tiny

#6985 kernel: Modify build-kernel.sh to accomodate for changes in version.yaml
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
Labels: size/small

#7000 gha: aks: Add the host_os as part of the aks cluster's name
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: size/tiny

#6989 packaging: make BUILDER_REGISTRY configurable
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/scripts/lib.sh
Labels: no-backport-needed, size/tiny

#6997 main | release: Standardize kata static file name
  .github/workflows/release.yaml
Labels: size/tiny
