Repository kata-containers/kata-containers, pull requests merged in 2023-12, with the labels that each got.

#8547 libs:logging: Fix logger
  src/libs/logging/src/lib.rs
Labels: safe-to-test, size/small, ok-to-test

#8480 dragonball: init dbs-pci lib with pci bus & pci conf
  src/dragonball/.gitignore
  src/dragonball/README.md
  src/dragonball/src/dbs_pci/Cargo.toml
  src/dragonball/src/dbs_pci/README.md
  src/dragonball/src/dbs_pci/src/bus.rs
  src/dragonball/src/dbs_pci/src/configuration.rs
  src/dragonball/src/dbs_pci/src/device.rs
  src/dragonball/src/dbs_pci/src/lib.rs
Labels: runtime-rs, size/huge, ok-to-test

#8549 libs: protection: x86_64: drop root requirement for querying
  src/libs/kata-sys-util/src/protection.rs
  src/tools/kata-ctl/src/ops/env_ops.rs
Labels: safe-to-test, size/small, ok-to-test

#8556 kernel: Add CONFIG_TDX_GUEST_DRIVER to the tdx.conf
  tools/packaging/kernel/configs/fragments/x86_64/tdx/tdx.conf
  tools/packaging/kernel/kata_config_version
Labels: needs-backport, size/tiny, ok-to-test

#8550 gha: Add cloud runtime rs as part of the stability tests
  .github/workflows/basic-ci-amd64.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8540 docs: Update cri installation url link
  docs/how-to/containerd-kata.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8551 runtime-rs: Launch cloud-hypervisor in given netns
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Labels: size/small, ok-to-test

#8516 move vsock device into device manager
  src/libs/kata-types/src/capabilities.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_vsock.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/resource/src/lib.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: no-backport-needed, runtime-rs, size/large, ok-to-test

#8558 runtime-rs: Show config files attempted on config load failure
  src/libs/kata-types/src/config/mod.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/service/src/task_service.rs
Labels: safe-to-test, size/small, ok-to-test

#4743 mount: support checking multiple kinds of block device driver
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/mount_linux_test.go
Labels: no-backport-needed, size/small, ok-to-test

#8570 gha: dragonball: Enable, but do not run, cri-containerd, stability, and devmapper tests
  .github/workflows/basic-ci-amd64.yaml
  .github/workflows/run-k8s-tests-on-garm.yaml
  tests/integration/cri-containerd/gha-run.sh
  tests/integration/kubernetes/gha-run.sh
  tests/stability/gha-run.sh
Labels: size/small, ok-to-test

#8573 gha: basic-ci: Add a timeout for the tests
  .github/workflows/basic-ci-amd64.yaml
Labels: size/tiny, ok-to-test

#8436 image-builder: bugfix incorrect partition location
  tools/osbuilder/image-builder/image_builder.sh
Labels: size/small, ok-to-test

#8578 docs: Update config containerd url link
  docs/how-to/containerd-kata.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8509 deployment: Add stable overlay for kata-deploy.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/stable/env_stable_conf.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/stable/kustomization.yaml
Labels: no-backport-needed, size/small, ok-to-test

#8601 GHA: remove GITHUB_WORKSPACE when workflow fails due to merge conflict
  tests/git-helper.sh
Labels: no-backport-needed, size/small, ok-to-test

#8594 metrics: Update TensorFlow ResNet FP32 dockerfile
  tests/metrics/machine_learning/resnet50_fp32_dockerfile/Dockerfile
  tests/metrics/machine_learning/tensorflow_resnet50_fp32.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8604 gha: nerdctl: Enable cloud hypervisor runtime-rs for nerdctl CI
  .github/workflows/basic-ci-amd64.yaml
  tests/integration/nerdctl/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8582 Implement and use try_from for DiskConfig
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
Labels: size/small, ok-to-test

#6755 packaging: Add IBM Z SE artifacts to main
  .github/workflows/build-kata-static-tarball-s390x.yaml
  ci/lib.sh
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-se.toml.in
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/guest-image/build_se_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
Labels: no-backport-needed, safe-to-test, size/huge, ok-to-test

#8429 dragonball: introduce vhost-user-fs device
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/dbs_virtio_devices/Cargo.toml
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/fs.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/mod.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/test_utils.rs
  src/dragonball/src/device_manager/fs_dev_mgr.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/error.rs
Labels: size/huge, ok-to-test

#8566 runtime-rs: fix panic when hypervisor mismatches with configuration
  src/libs/kata-types/src/annotations/mod.rs
Labels: runtime-rs, size/small, ok-to-test

#8622 GHA: Use --client=true for k3s kubectl version
  tests/gha-run-k8s-common.sh
Labels: no-backport-needed, size/tiny, ok-to-test

#8592 CI: static-checks: Try multiple user agents
  docs/install/azure-installation-guide.md
  tests/static-checks.sh
Labels: no-backport-needed, no-forward-port-needed, safe-to-test, size/large, ok-to-test

#8624 GHA: Fix kata-deploy-runtime-classes-check for kata-qemu-se
  tools/packaging/kata-deploy/runtimeclasses/kata-qemu-se.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
Labels: no-backport-needed, size/small, ok-to-test

#7769 rootfs: build OPA binary from source for ppc64le and s390x
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: no-backport-needed, safe-to-test, size/small, ok-to-test

#8599 dragonball: add --all for fmt ci
  src/dragonball/Makefile
  src/dragonball/src/dbs_pci/src/bus.rs
  src/dragonball/src/dbs_pci/src/lib.rs
  src/dragonball/src/dbs_virtio_devices/src/lib.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_kern/net.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/test_utils.rs
Labels: no-backport-needed, size/small, ok-to-test

#8542 metrics: cleans k8s iperf deployment when the test finishes.
  tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
  tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-deployment.yaml
  tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-service.yaml
Labels: no-backport-needed, no-forward-port-needed, area/metrics, size/large, ok-to-test

#8617 tests: nerdctl: Enable nerdctl tests for cloud hypervisor runtime-rs
  tests/common.bash
  tests/integration/nerdctl/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8634 dragonball: Disable packed virtqueue for vhost-user devices
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
Labels: no-backport-needed, size/tiny, ok-to-test

#8630 runtime-rs: ch: Change state when VM stopped
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Labels: size/small, ok-to-test

#8564 dragonball: add pci root bus and root device
  src/dragonball/src/dbs_pci/README.md
  src/dragonball/src/dbs_pci/src/device.rs
  src/dragonball/src/dbs_pci/src/lib.rs
  src/dragonball/src/dbs_pci/src/root_bus.rs
  src/dragonball/src/dbs_pci/src/root_device.rs
Labels: runtime-rs, size/huge, ok-to-test

#8639 kata-deploy: Use `tomlq` to configure containerd
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/medium, ok-to-test

#8649 GHA: Put all the preliminary steps into pre-action for s390x
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/ci-nightly-s390x.yaml
  .github/workflows/publish-kata-deploy-payload-s390x.yaml
  .github/workflows/run-cri-containerd-tests-s390x.yaml
  .github/workflows/run-k8s-tests-on-zvsi.yaml
Labels: no-backport-needed, size/small, ok-to-test

#8609 dragonball: Use vhost-net device by default
  src/dragonball/src/api/v1/virtio_net.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/resource/src/network/endpoint/ipvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/macvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/tap_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/veth_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/vlan_endpoint.rs
Labels: no-backport-needed, runtime-rs, size/large, ok-to-test

#8620 runtime-rs: Enhancement of DirectVolume when using a dedicated CSI
  src/libs/kata-types/src/mount.rs
  src/runtime-rs/crates/resource/src/volume/direct_volumes/mod.rs
Labels: no-backport-needed, runtime-rs, size/small, ok-to-test

#8667 gha: add a post cleanup script for cri-containerd ppc64le workflow
  .github/workflows/run-cri-containerd-tests-ppc64le.yaml
Labels: no-backport-needed, no-forward-port-needed, ok-to-test

#8589 Remove warning for cgroupsv2 only operating systems
  utils/README.md
Labels: force-skip-ci, size/tiny, ok-to-test

#8674 static-checks: Add some dependencies to static checks for CoCo features
  .github/workflows/static-checks.yaml
Labels: no-backport-needed, force-skip-ci, size/tiny, ok-to-test

#8644 metrics: Update TensorFlow ResNet50 Int8 Dockerfile
  tests/metrics/machine_learning/resnet50_int8_dockerfile/Dockerfile
  tests/metrics/machine_learning/tensorflow_resnet50_int8.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8659 metrics: Improve latency network cleanup
  tests/metrics/network/latency_kubernetes/latency-network.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8676 tests: k8s: Fix indentation in setup script
  tests/integration/kubernetes/setup.sh
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#6876 runtime-rs: support Memory hotplug
  src/libs/kata-types/Cargo.toml
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/capabilities.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/resource/src/cpu_mem/cpu.rs
  src/runtime-rs/crates/resource/src/cpu_mem/initial_size.rs
  src/runtime-rs/crates/resource/src/cpu_mem/mem.rs
  src/runtime-rs/crates/resource/src/cpu_mem/mod.rs
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/common/src/runtime_handler.rs
  src/runtime-rs/crates/runtimes/linux_container/Cargo.toml
  src/runtime-rs/crates/runtimes/linux_container/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml
  src/runtime-rs/crates/runtimes/wasm_container/src/lib.rs
Labels: no-backport-needed, runtime-rs, size/huge, ok-to-test

#8664 github-actions: Remove ignore paths for required CI checks
  .github/workflows/cargo-deny-runner.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/darwin-tests.yaml
Labels: size/tiny, ok-to-test

#8641 kata-ctl: Add option to dump config files
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/main.rs
Labels: safe-to-test, size/medium, ok-to-test

#8341 agent: correct CPUShares and CPUWeight value
  src/agent/rustjail/src/cgroups/systemd/subsystem/cpu.rs
Labels: backport, size/small, ok-to-test

#8682 ci: Use static checks from kata repo for lib functions
  ci/lib.sh
  docs/Licensing-strategy.md
  docs/presentations/unit-testing/kata-containers-unit-testing.md
Labels: no-backport-needed, no-forward-port-needed, ok-to-test

#8672 runtime-rs: Separate init_config() from new() for struct VsockDevice
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_vsock.rs
Labels: no-backport-needed, runtime-rs, size/small, ok-to-test

#8700 dragonball: Trigger unit tests of dbs_* subcrates by `make test`
  src/dragonball/Makefile
  src/dragonball/src/dbs_legacy_devices/src/i8042.rs
  src/dragonball/src/dbs_virtio_devices/src/device.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/fs.rs
Labels: no-backport-needed, size/small, ok-to-test

#8697 tests: additional run-runk logging
  tests/integration/runk/runk-tests.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8670 Bump image-rs rev to include image-layer-ordering fix
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/rpc.rs
  src/libs/Cargo.lock
  src/libs/protocols/Cargo.toml
  src/runtime/virtcontainers/kata_agent.go
Labels: no-backport-needed, size/huge

#8699 tests: k8s: Fix indentation in confidential common script
  tests/integration/kubernetes/confidential_common.sh
Labels: no-backport-needed, no-forward-port-needed, ok-to-test

#8588 runtime-rs: Update readme to indicate cloud-hypervisor support
  src/runtime-rs/README.md
Labels: no-backport-needed, size/tiny, ok-to-test

#8679 gha: kata-deploy: Revert containerd config break
  tests/functional/kata-deploy/kata-deploy.bats
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: no-backport-needed, size/medium, ok-to-test

#8709 kata-deploy: Update `jq` as part of the kata-deploy daemonset
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/medium, ok-to-test

#8688 tests: retry connection to pod SSH server
  tests/integration/kubernetes/k8s-confidential.bats
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8714 tests: Use function from Kata repo
  ci/lib.sh
Labels: no-backport-needed, size/tiny, ok-to-test

#8718 tests: Load vhost modules explicitly while Kata installing
  tests/common.bash
Labels: no-backport-needed, size/tiny, ok-to-test

#8655 kata-deploy: Allow setting up snapshotters per runtime handler
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: force-skip-ci, size/medium, ok-to-test

#8662 dragonball: introduce pci msi/msix interrupt
  src/dragonball/src/dbs_interrupt/src/lib.rs
  src/dragonball/src/dbs_pci/Cargo.toml
  src/dragonball/src/dbs_pci/README.md
  src/dragonball/src/dbs_pci/src/lib.rs
  src/dragonball/src/dbs_pci/src/msi.rs
  src/dragonball/src/dbs_pci/src/msix.rs
Labels: runtime-rs, size/huge, ok-to-test

#8721 kata-deploy: snapshotter typo fixes
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#8668 runtime-rs: Refactor the code related to PCI paths and VFIO device driver initialize in DM.
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/pci_path.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
Labels: no-backport-needed, runtime-rs, size/large, ok-to-test

#8503 dragonball: Support vhost-user-net device
  src/dragonball/Cargo.lock
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/mod.rs
  src/dragonball/src/api/v1/virtio_net.rs
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/dbs_virtio_devices/Cargo.toml
  src/dragonball/src/dbs_virtio_devices/src/balloon.rs
  src/dragonball/src/dbs_virtio_devices/src/block/device.rs
  src/dragonball/src/dbs_virtio_devices/src/device.rs
  src/dragonball/src/dbs_virtio_devices/src/fs/device.rs
  src/dragonball/src/dbs_virtio_devices/src/lib.rs
  src/dragonball/src/dbs_virtio_devices/src/mem.rs
  src/dragonball/src/dbs_virtio_devices/src/mmio/mmio_state.rs
  src/dragonball/src/dbs_virtio_devices/src/mmio/mmio_v2.rs
  src/dragonball/src/dbs_virtio_devices/src/net.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/mod.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/net.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_kern/net.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/fs.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/mod.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/net.rs
  src/dragonball/src/dbs_virtio_devices/src/vsock/device.rs
  src/dragonball/src/dbs_virtio_devices/src/vsock/mod.rs
  src/dragonball/src/device_manager/balloon_dev_mgr.rs
  src/dragonball/src/device_manager/blk_dev_mgr.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/device_manager/vhost_net_dev_mgr.rs
  src/dragonball/src/device_manager/vhost_user_net_dev_mgr.rs
  src/dragonball/src/error.rs
  src/runtime-rs/Cargo.lock
Labels: no-backport-needed, no-forward-port-needed, size/huge, ok-to-test

#8626 runtime-rs: Support vhost-user-net device
  src/dragonball/src/api/v1/mod.rs
  src/dragonball/src/api/v1/virtio_net.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_net.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/resource/src/network/dan.rs
  src/runtime-rs/crates/resource/src/network/endpoint/endpoint_persist.rs
  src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
  src/runtime-rs/crates/resource/src/network/endpoint/tap_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/vhost_user_endpoint.rs
  src/runtime-rs/crates/resource/src/volume/direct_volumes/spdk_volume.rs
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#8729 kata-monitor: fix Dockerfile to build image
  tools/packaging/kata-monitor/Dockerfile
Labels: no-backport-needed, size/tiny, ok-to-test

#8632 dragonball: introduce vhost-user-blk device
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/dbs_virtio_devices/Cargo.toml
  src/dragonball/src/dbs_virtio_devices/src/lib.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/block.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/mod.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/test_utils.rs
  src/dragonball/src/device_manager/blk_dev_mgr.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/error.rs
Labels: no-backport-needed, size/huge, ok-to-test

#8724 dragonball: introduce vfio support
  src/dragonball/src/dbs_pci/Cargo.toml
  src/dragonball/src/dbs_pci/README.md
  src/dragonball/src/dbs_pci/src/configuration.rs
  src/dragonball/src/dbs_pci/src/lib.rs
  src/dragonball/src/dbs_pci/src/msi.rs
  src/dragonball/src/dbs_pci/src/msix.rs
  src/dragonball/src/dbs_pci/src/vfio.rs
Labels: runtime-rs, size/huge, ok-to-test

#8733 kata-deploy: Fix shim check for snapshotter configuration
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#7489 runtime-rs: add pci topology for pci devices
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_blk.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_net.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_fs.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_vsock.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/topology.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
Labels: no-backport-needed, runtime-rs, size/huge, ok-to-test, area/gpu

#8618 runtime-rs: Add dedicated CSI driver for DirectVolume support in Kata
  docs/how-to/how-to-run-kata-containers-with-kinds-of-Block-Volumes.md
  src/tools/csi-kata-directvolume/Makefile
  src/tools/csi-kata-directvolume/README.md
  src/tools/csi-kata-directvolume/cmd/directvolplugin/main.go
  src/tools/csi-kata-directvolume/deploy/deploy.sh
  src/tools/csi-kata-directvolume/deploy/directvol-deploy.sh
  src/tools/csi-kata-directvolume/deploy/directvol-destroy.sh
  src/tools/csi-kata-directvolume/deploy/kata-directvolume/csi-directvol-driverinfo.yaml
  src/tools/csi-kata-directvolume/deploy/kata-directvolume/csi-directvol-plugin.yaml
  src/tools/csi-kata-directvolume/deploy/rbac-deploy.sh
  src/tools/csi-kata-directvolume/docs/deploy-csi-kata-directvol.md
  src/tools/csi-kata-directvolume/examples/pod-apply.sh
  src/tools/csi-kata-directvolume/examples/pod-delete.sh
  src/tools/csi-kata-directvolume/examples/pod-with-directvol/csi-app.yaml
  src/tools/csi-kata-directvolume/examples/pod-with-directvol/csi-pvc.yaml
  src/tools/csi-kata-directvolume/examples/pod-with-directvol/csi-storageclass.yaml
  src/tools/csi-kata-directvolume/examples/pod-with-directvol/runtimeclass.yaml
  src/tools/csi-kata-directvolume/go.mod
  src/tools/csi-kata-directvolume/go.sum
  src/tools/csi-kata-directvolume/internal/endpoint.go
  src/tools/csi-kata-directvolume/pkg/directvolume/controllerserver.go
  src/tools/csi-kata-directvolume/pkg/directvolume/directvolume.go
  src/tools/csi-kata-directvolume/pkg/directvolume/identityserver.go
  src/tools/csi-kata-directvolume/pkg/directvolume/nodeserver.go
  src/tools/csi-kata-directvolume/pkg/directvolume/server.go
  src/tools/csi-kata-directvolume/pkg/state/state.go
  src/tools/csi-kata-directvolume/pkg/state/state_test.go
  src/tools/csi-kata-directvolume/pkg/state/strings.go
  src/tools/csi-kata-directvolume/pkg/utils/capacity.go
  src/tools/csi-kata-directvolume/pkg/utils/direct_volume.go
  src/tools/csi-kata-directvolume/pkg/utils/safe_formater.go
  src/tools/csi-kata-directvolume/pkg/utils/utils.go
  src/tools/csi-kata-directvolume/release-tools/build.make
  src/tools/csi-kata-directvolume/release-tools/verify-go-version.sh
Labels: no-backport-needed, size/huge, ok-to-test

#8740 Dragonball: add pci vfio passthrough, hot(un)plug support
  src/agent/Cargo.lock
  src/dragonball/Cargo.lock
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/dbs_device/src/resources.rs
  src/dragonball/src/dbs_pci/src/lib.rs
  src/dragonball/src/dbs_pci/src/vfio.rs
  src/dragonball/src/dbs_upcall/src/dev_mgr_service.rs
  src/dragonball/src/dbs_upcall/src/lib.rs
  src/dragonball/src/dbs_virtio_devices/src/mmio/mmio_v2.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/device_manager/vfio_dev_mgr/mod.rs
  src/dragonball/src/device_manager/vfio_dev_mgr/pci_vfio.rs
  src/dragonball/src/error.rs
  src/dragonball/src/resource_manager.rs
  src/dragonball/src/test_utils.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/dragonball/src/vm/mod.rs
  src/dragonball/src/vm/x86_64.rs
  src/libs/kata-types/src/annotations/mod.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  tools/packaging/kernel/configs/fragments/build-type/dragonball-experimental/upcall.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/5.10.x/dragonball-experimental/0008-upcall-add-pci-hotplug-hot-unplug-support.patch
Labels: no-backport-needed, runtime-rs, size/huge, ok-to-test
