Repository kata-containers/kata-containers, pull requests merged in 2023-03, with the labels that each got.

#6392 CC | workflows: Do not install docker
  .github/workflows/deploy-ccv0-demo.yaml
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
Labels: size/tiny

#6389 packaging: fix initrd build
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny

#6397 kata-deploy-cc: Cleanup runtime-rs
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: size/tiny

#6382 CCv0: set dependencies to v0.4.0 tag
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  versions.yaml
Labels: size/small

#6305 actions: Use `git-diff` to get changes in kernel dir
  .github/workflows/static-checks.yaml
Labels: backport, size/tiny

#6380 src: Fixed typo mod.rs
  src/runtime-rs/crates/resource/src/cgroups/mod.rs
Labels: runtime-rs, size/tiny

#6344 workflows: Publish kata-deploy payload after a merge
  .github/workflows/payload-after-push-amd64.yaml
  .github/workflows/payload-after-push-arm64.yaml
  .github/workflows/payload-after-push-s390x.yaml
  .github/workflows/payload-after-push.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: size/tiny

#6391 workflows: Do not install docker
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
Labels: needs-backport, size/small

#6269 Dragonball: update dependencies
  src/dragonball/Cargo.lock
  src/dragonball/Cargo.toml
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/vcpu/vcpu_impl.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/dragonball/src/vm/aarch64.rs
  src/dragonball/src/vm/mod.rs
  src/runtime-rs/Cargo.lock
Labels: runtime-rs, size/huge

#6377 utils: Remove kata-manager.sh cgroups v2 check
  utils/kata-manager.sh
Labels: no-backport-needed, size/small

#5788 runtime-rs: add oci hook support
  docs/design/README.md
  docs/design/hooks-handling.md
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/dragonball/src/api/v1/instance_info.rs
  src/libs/oci/src/lib.rs
  src/libs/protocols/protos/oci.proto
  src/libs/protocols/src/trans.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/resource/src/network/mod.rs
  src/runtime-rs/crates/resource/src/network/utils/netns.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: runtime-rs, size/large

#6399 fix(runtime-rs): add exited state to ensure cleanup
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_into_shim.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
Labels: no-backport-needed, runtime-rs, size/tiny

#6355 fix wrong notes for func GetSandboxesStoragePathRust()
  src/runtime/pkg/containerd-shim-v2/shim_management.go
Labels: no-backport-needed, size/tiny

#6361 runtime/Makefile: Fix install-containerd-shim-v2 dependency
  src/runtime/Makefile
Labels: no-backport-needed, size/tiny

#6331 rustjail: fix cgroup handling in agent-init mode
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/mock.rs
  src/agent/rustjail/src/cgroups/mod.rs
  src/agent/rustjail/src/cgroups/systemd/manager.rs
  src/agent/rustjail/src/container.rs
  src/agent/src/main.rs
  src/agent/src/rpc.rs
Labels: needs-backport, size/tiny

#6402 workflows: Yet more fixes for publishing the kata-deploy payload after every PR merged
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: size/tiny

#6359 main | kata-deploy: Fix kata deploy arm64 image build error
  .github/workflows/payload-after-push-amd64.yaml
  .github/workflows/payload-after-push-arm64.yaml
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: needs-backport, size/tiny

#6409 docs: fix typo in key filename in AWS installation guide
  docs/install/aws-installation-guide.md
Labels: no-backport-needed, size/tiny

#6413 dragonball: support pmu on aarch64
  src/dragonball/src/error.rs
  src/dragonball/src/vcpu/aarch64.rs
  src/dragonball/src/vcpu/mod.rs
  src/dragonball/src/vcpu/vcpu_impl.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/dragonball/src/vm/aarch64.rs
  src/dragonball/src/vm/mod.rs
Labels: runtime-rs, size/medium

#6410 utils: Make kata-manager.sh runs checks
  utils/kata-manager.sh
Labels: size/tiny

#6432 packaging: Simplify get_last_modification()
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/kernel/build.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/qemu/build-base-qemu.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/td-shim/build.sh
  tools/packaging/static-build/virtiofsd/build.sh
Labels: size/tiny

#6416 packaging: fix sev kernel build
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, size/tiny

#5578 runtime-rs: add the missing default trait
  src/libs/kata-types/src/config/agent.rs
  src/libs/kata-types/src/config/default.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/shim/src/args.rs
  src/runtime-rs/crates/shim/src/shim.rs
  src/runtime-rs/crates/shim/src/shim_start.rs
Labels: needs-backport, no-forward-port-needed, runtime-rs, size/medium

#6443 bugfix: add get_ns_path API for Hypervisor
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
Labels: area/QEMU, area/cloud-hypervisor, runtime-rs, size/medium

#6426 bugfix: modify tty_win info in runtime when handling ResizePtyRequest
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: runtime-rs, size/tiny

#5840 Implement direct-volume commands handler for shim-mgmt
  src/libs/shim-interface/src/shim_mgmt/client.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: size/tiny, outreach, kata-ctl

#6292 runtime-rs: fix default kernel location and add more default config paths
  src/runtime-rs/Makefile
Labels: runtime-rs, size/tiny

#6447 kata-deploy-cc: Switch to using an ubuntu image
  tools/packaging/kata-deploy-cc/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: size/small

#6411 Add support for ephemeral mounts to occupy entire sandbox's memory
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
  src/libs/protocols/protos/agent.proto
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go
  src/runtime/virtcontainers/pkg/mock/mock.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: no-backport-needed, size/tiny

#5665 CC | runtime: Add online-kbs to kernel params
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-sev.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/sev/kbs/kbs.go
  src/runtime/pkg/sev/sev.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, area/confidential-containers, size/huge

#6458 runtime-rs: update load_config comment
  src/runtime-rs/crates/runtimes/src/manager.rs
Labels: runtime-rs, size/tiny

#6207 CC: Prepare secure execution image tarball for s390x
  ci/lib.sh
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-se.toml.in
  tools/packaging/guest-image/build_se_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, size/huge

#6463 runtime: add support for Hyper-V
  src/runtime/pkg/resourcecontrol/cgroups.go
Labels: size/tiny

#6186 Built-in Sandbox: add more unit tests for dragonball. Part 6
  src/dragonball/src/device_manager/blk_dev_mgr.rs
Labels: runtime-rs, size/huge

#6471 dependency: update cgroups-rs
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/libs/Cargo.lock
  src/libs/kata-sys-util/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/resource/Cargo.toml
  src/tools/agent-ctl/Cargo.lock
  src/tools/runk/Cargo.lock
  src/tools/runk/libcontainer/Cargo.toml
Labels: needs-backport, size/tiny

#6476 dependency: update cgroups-rs
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/libs/Cargo.lock
  src/libs/kata-sys-util/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/resource/Cargo.toml
  src/tools/agent-ctl/Cargo.lock
  src/tools/runk/Cargo.lock
  src/tools/runk/libcontainer/Cargo.toml
Labels: backport, size/small

#6486 CC | kernel: Ensure `kata_config_version` is taken into account
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components.sh
Labels: size/small

#6481 packaging / kata-deploy builds: Add the ability to cache and consume cached components
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/cache_components_main.sh
  tools/packaging/static-build/kernel/build.sh
  tools/packaging/static-build/qemu/build-base-qemu.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/virtiofsd/build.sh
  versions.yaml
Labels: size/large

#6474 packaging: fix sev kernel caching
  tools/packaging/static-build/cache_components.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6477 bugfix: set hostname in CreateSandboxRequest
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: runtime-rs, size/tiny

#6498 cache_components: Switch back the permission to 755
  tools/packaging/static-build/cache_components.sh
Labels: size/tiny

#6491 CC | kata-deploy-push more space
  .github/workflows/kata-deploy-push.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
Labels: no-backport-needed, size/tiny

#4582 agent: Bring in VFIO-AP device handling again
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/ap.rs
  src/agent/src/device.rs
  src/agent/src/linux_abi.rs
  src/agent/src/main.rs
  src/runtime/pkg/device/config/config.go
  src/runtime/pkg/device/drivers/utils.go
  src/runtime/pkg/device/drivers/vfio.go
  src/runtime/pkg/device/drivers/vfio_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/utils/utils_linux.go
  src/runtime/virtcontainers/utils/utils_linux_test.go
Labels: no-backport-needed, size/huge

#6495 A couple of kata-deploy fixes
  .github/workflows/payload-after-push-amd64.yaml
  .github/workflows/payload-after-push-arm64.yaml
  .github/workflows/payload-after-push-s390x.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: no-backport-needed, area/kata-deploy, size/tiny

#6406 static checks workflow improvements
  .github/workflows/static-checks.yaml
  tools/osbuilder/tests/test_images.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6503 CC | static checks workflow improvements
  .github/workflows/static-checks.yaml
  tools/osbuilder/tests/test_images.sh
Labels: no-backport-needed, area/confidential-containers, size/small

#6352 kata-deploy: Add cri-o support
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: area/confidential-containers, size/tiny

#6350 config: Add initial remote hypervisor config
  src/runtime/Makefile
  src/runtime/config/configuration-remote.toml.in
Labels: size/tiny

#6467 qemu/arm64: disable image nvdimm once no firmware offered
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
Labels: size/tiny

#6507 Backports for 3.1
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/mock.rs
  src/agent/rustjail/src/cgroups/mod.rs
  src/agent/rustjail/src/cgroups/systemd/manager.rs
  src/agent/rustjail/src/container.rs
  src/agent/src/main.rs
  src/agent/src/rpc.rs
  src/runtime-rs/arch/powerpc64le-options.mk
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/mount_linux_test.go
  src/runtime/virtcontainers/mount_test.go
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
  tools/packaging/static-build/firecracker/build-static-firecracker.sh
  tools/packaging/static-build/shim-v2/install_go_rust.sh
Labels: size/large

#6517 # Kata Containers 3.1.0
  VERSION
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: size/tiny

#6419 make only_kata work without -f
  utils/kata-manager.sh
Labels: size/small

#6532 rootfs: Ensure we use a compatible version of dcap with rats-tls
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
Labels: size/tiny

#6408 nydus: upgrad to v2.2.0
  src/runtime/virtcontainers/nydusd.go
  src/runtime/virtcontainers/nydusd_test.go
  versions.yaml
Labels: size/tiny

#6457 image_rpc: Add container_count for containers without cid
  src/agent/src/image_rpc.rs
Labels: no-backport-needed, area/confidential-containers, size/small

#6513 snap: Build the artefacts using kata-deploy
  snap/snapcraft.yaml
Labels: no-backport-needed, size/large

#6536 # Kata Containers 3.2.0-alpha0
  VERSION
Labels: size/tiny

#6552 CC|kata-deploy: Add kata-qemu-se runtimeclass
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Labels: no-backport-needed, size/tiny

#6342 runtime: propagate configmap, secrets, downward-api etc changes for remote-hyp
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/fs_share.go
  src/runtime/virtcontainers/fs_share_darwin.go
  src/runtime/virtcontainers/fs_share_linux.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, size/tiny

#6545 CC: Introduce secure image in payload image
  .github/workflows/cc-payload-after-push-s390x.yaml
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Labels: no-backport-needed, size/small

#5850 CC: kata-deploy add x86 ovmf build for SNP
  .github/workflows/cc-payload-after-push-amd64.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/ovmf/build-ovmf.sh
Labels: no-backport-needed, size/small

#6564 docs: Update CNM url in networking document
  docs/design/architecture/networking.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6062 kata-deploy: SNP version of Qemu
  src/runtime/Makefile
  src/runtime/arch/amd64-options.mk
  tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/qemu/patches/tag_patches/3b6a2b6b7466f6dea53243900b7516c3f29027b7/no_patches.txt
  tools/packaging/static-build/cache_components.sh
  versions.yaml
Labels: area/confidential-containers, size/small
