Repository kata-containers/kata-containers, pull requests merged in 2023-01, with the labels that each got.

#5891 agent: unset `CC` for cross-build
  utils.mk
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5910 osbuilder: fix kernel module copy logic in rootfs builder
  tools/packaging/guest-image/build_image.sh
Labels: no-backport-needed, size/tiny

#5951 kata-ctl: skip test if access GitHub.com fail
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/src/check.rs
Labels: size/small

#5967 versions: Update the rust toolchain to 1.66.0
  src/agent/rustjail/src/mount.rs
  src/agent/rustjail/src/seccomp.rs
  src/agent/src/device.rs
  src/agent/src/mount.rs
  src/agent/src/namespace.rs
  src/agent/src/netlink.rs
  src/agent/src/network.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/watcher.rs
  src/dragonball/src/address_space_manager.rs
  src/dragonball/src/resource_manager.rs
  src/dragonball/src/signal_handler.rs
  src/dragonball/src/vcpu/x86_64.rs
  src/dragonball/src/vm/x86_64.rs
  src/libs/kata-sys-util/src/fs.rs
  src/libs/kata-sys-util/src/mount.rs
  src/libs/kata-sys-util/src/numa.rs
  src/libs/kata-sys-util/src/validate.rs
  src/libs/kata-types/src/config/drop_in.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/tests/test_config.rs
  src/libs/logging/src/file_rotate.rs
  src/libs/logging/src/lib.rs
  src/libs/protocols/build.rs
  src/libs/protocols/src/trans.rs
  src/libs/safe-path/src/pinned_path_buf.rs
  src/libs/safe-path/src/scoped_dir_builder.rs
  src/libs/safe-path/src/scoped_path_resolver.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/resource/src/network/utils/link/create.rs
  src/runtime-rs/crates/resource/src/network/utils/link/manager.rs
  src/runtime-rs/crates/resource/src/network/utils/netns.rs
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/utils.rs
  src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/shim/src/shim_delete.rs
  src/tools/runk/src/main.rs
  versions.yaml
Labels: no-backport-needed, size/large

#5908 kernel: adding kmod to do docker env
  tools/packaging/static-build/kernel/Dockerfile
Labels: no-backport-needed, size/tiny

#5939 CC | config: Add sev suffix to initrd
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-sev.toml.in
Labels: no-backport-needed, area/confidential-containers, size/tiny

#5969 CC | agent: Update image-rs to bring stream pulling support
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/src/mount.rs
  src/agent/rustjail/src/seccomp.rs
  src/agent/src/device.rs
  src/agent/src/image_rpc.rs
  src/agent/src/mount.rs
  src/agent/src/namespace.rs
  src/agent/src/netlink.rs
  src/agent/src/network.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/watcher.rs
  src/dragonball/src/address_space_manager.rs
  src/dragonball/src/resource_manager.rs
  src/dragonball/src/signal_handler.rs
  src/dragonball/src/vcpu/x86_64.rs
  src/dragonball/src/vm/x86_64.rs
  src/libs/kata-sys-util/src/fs.rs
  src/libs/kata-sys-util/src/mount.rs
  src/libs/kata-sys-util/src/numa.rs
  src/libs/kata-sys-util/src/validate.rs
  src/libs/kata-types/src/config/drop_in.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/tests/test_config.rs
  src/libs/logging/src/file_rotate.rs
  src/libs/logging/src/lib.rs
  src/libs/protocols/build.rs
  src/libs/protocols/src/trans.rs
  src/libs/safe-path/src/pinned_path_buf.rs
  src/libs/safe-path/src/scoped_dir_builder.rs
  src/libs/safe-path/src/scoped_path_resolver.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/resource/src/network/utils/link/create.rs
  src/runtime-rs/crates/resource/src/network/utils/link/manager.rs
  src/runtime-rs/crates/resource/src/network/utils/netns.rs
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/utils.rs
  src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/shim/src/shim_delete.rs
  src/tools/runk/src/main.rs
  versions.yaml
Labels: no-backport-needed, size/huge

#5945 packaging: fix indents in build-kernel.sh
  tools/packaging/kernel/build-kernel.sh
Labels: no-backport-needed, no-forward-port-needed, size/small

#5943 docs: remove old and misleading instructions for minikube
  docs/install/minikube-installation-guide.md
Labels: no-backport-needed, no-forward-port-needed, size/small

#5947 runtime/Makefile: Get some bits happy on darwin
  ci/install_yq.sh
  src/runtime/Makefile
Labels: size/small

#5950 runtime-rs: add dbs-upcall feature
  src/dragonball/src/vm/mod.rs
  src/dragonball/src/vmm.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
Labels: runtime-rs, size/small

#5927 CCv0: runtime: Support launching SEV-ES guests
  src/runtime/pkg/sev/vcpu_sigs.go
  src/runtime/pkg/sev/vcpu_sigs_test.go
  src/runtime/virtcontainers/qemu_amd64.go
Labels: no-backport-needed, area/confidential-containers, size/medium

#5651 osbuilder: Switch to online_sev_kbc
  src/runtime/Makefile
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: area/confidential-containers, size/small

#5977 CC | agent: unset `CC` for cross-build
  utils.mk
Labels: no-backport-needed, area/confidential-containers, size/tiny

#5974 versions: Upgrade to Cloud Hypervisor v28.1
  versions.yaml
Labels: needs-backport, size/tiny

#5964 kata-runtime: add rust runtime path for kata-runtime exec
  src/runtime/pkg/containerd-shim-v2/shim_management.go
Labels: size/small

#5946 Runtime: Clarify mutability of global var
  src/runtime/virtcontainers/vm.go
Labels: size/tiny

#5467 Feat: implementation of kata-ctl direct-volume operations
  src/libs/kata-types/src/mount.rs
  src/libs/shim-interface/src/shim_mgmt/client.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/ops.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/ops/volume_ops.rs
Labels: size/huge, outreach, kata-ctl

#5976 runtime-rs: cleanup the run dir of hypervisor when shut down
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: runtime-rs, size/tiny

#5611 Built-in Sandbox: add more unit tests for dragonball. Part 4
  src/dragonball/src/kvm_context.rs
  src/dragonball/src/vcpu/vcpu_impl.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
Labels: size/large

#5984 schedcore: Make buildable on !linux
  src/runtime/pkg/utils/schedcore.go
  src/runtime/pkg/utils/schedcore_linux.go
  src/runtime/pkg/utils/schedcore_other.go
Labels: size/medium

#6001 clh: Ensure it works with Docker / Moby
  src/runtime/virtcontainers/clh.go
Labels: size/small

#5986 nydus: net-ns handling needs to be only executed on Linux hosts
  src/runtime/virtcontainers/nydusd.go
  src/runtime/virtcontainers/nydusd_linux.go
  src/runtime/virtcontainers/nydusd_other.go
Labels: size/small

#5991 runtime: Define Darwin handled signals list
  src/runtime/pkg/signals/signals.go
  src/runtime/pkg/signals/signals_darwin.go
  src/runtime/pkg/signals/signals_linux.go
Labels: no-backport-needed, no-forward-port-needed, size/medium

#5996 virtcontainers: Introduce hypervisor_darwin
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_darwin.go
  src/runtime/virtcontainers/hypervisor_linux.go
Labels: no-backport-needed, no-forward-port-needed, size/small

#5992 kata-ctl: fix build error on s390x
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
Labels: size/small

#5982 kata-ctl: remove get_kata_version_by_url function
  src/tools/kata-ctl/Makefile
  src/tools/kata-ctl/src/check.rs
Labels: size/medium

#6005 virtcontainers: Add a Virtualization.framework skeleton
  src/runtime/virtcontainers/virtframework.go
Labels: no-backport-needed, no-forward-port-needed, size/large

#6003 virtcontainers: fs_share: Add Darwin skeleton
  src/runtime/virtcontainers/fs_share_darwin.go
Labels: no-backport-needed, no-forward-port-needed, size/medium

#6014 tools: Fix indentation for setup aks script
  tools/packaging/kata-deploy/action/setup-aks.sh
Labels: no-backport-needed, no-forward-port-needed, size/small

#6025 osbuilder: copy efi_secret module for online_sev_kbc
  tools/packaging/guest-image/build_image.sh
Labels: size/tiny

#6019 Change cache mode from none to never
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/virtiofsd.go
  src/runtime/virtcontainers/virtiofsd_test.go
Labels: size/large

#5994 virtcontainers: tests: Ensure Linux specific tests are just run on Linux
  src/runtime/virtcontainers/acrn_arch_base_test.go
  src/runtime/virtcontainers/container_linux_test.go
  src/runtime/virtcontainers/container_test.go
  src/runtime/virtcontainers/hypervisor_linux_test.go
  src/runtime/virtcontainers/hypervisor_test.go
  src/runtime/virtcontainers/kata_agent_linux_test.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/sandbox_linux_test.go
  src/runtime/virtcontainers/sandbox_test.go
  src/runtime/virtcontainers/virtcontainers_darwin_test.go
  src/runtime/virtcontainers/virtcontainers_linux_test.go
  src/runtime/virtcontainers/virtcontainers_test.go
  src/runtime/virtcontainers/vm_linux_test.go
  src/runtime/virtcontainers/vm_test.go
Labels: size/huge

#6007 runtime-rs: add Single Container support
  src/libs/kata-sys-util/src/spec.rs
  src/libs/kata-types/src/container.rs
  src/libs/kata-types/src/k8s.rs
  src/runtime-rs/crates/shim/src/shim_start.rs
Labels: runtime-rs, size/small

#6035 tools: add --locked option for cargo install
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Makefile
  src/tools/kata-ctl/Makefile
Labels: size/large

#6038 CC: Support s390x for target cc-payload in Makefile
  tools/packaging/kata-deploy/local-build/Makefile
Labels: size/small

#6034 CC | packaging: Take toolchain version when using the td-shim builder image
  tools/packaging/scripts/lib.sh
Labels: size/tiny

#5837 docs: add hint of probing loop module
  docs/Developer-Guide.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6032 runtime: add test generated file to .gitignore
  src/runtime/.gitignore
Labels: size/tiny

#6066 CC | Update dependencies for the v0.3.0 release
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  versions.yaml
Labels: no-backport-needed, size/small

#6043 virtcontainers: Fix misspelling in error message
  src/runtime/virtcontainers/clh.go
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6052 Add darwin skeletons
  src/runtime/pkg/resourcecontrol/cgroups_darwin.go
  src/runtime/pkg/resourcecontrol/controller.go
  src/runtime/pkg/resourcecontrol/utils.go
  src/runtime/pkg/resourcecontrol/utils_linux.go
  src/runtime/virtcontainers/network_darwin.go
Labels: no-backport-needed, no-forward-port-needed, area/darwin, size/large

#6050 virtcontainers: split out linux-specific bits for mount, factory
  src/runtime/virtcontainers/factory/factory.go
  src/runtime/virtcontainers/factory/factory_darwin.go
  src/runtime/virtcontainers/factory/factory_linux.go
  src/runtime/virtcontainers/factory/template/template.go
  src/runtime/virtcontainers/factory/template/template_darwin.go
  src/runtime/virtcontainers/factory/template/template_linux.go
  src/runtime/virtcontainers/mount.go
  src/runtime/virtcontainers/mount_darwin.go
  src/runtime/virtcontainers/mount_linux.go
  src/runtime/virtcontainers/mount_linux_test.go
  src/runtime/virtcontainers/mount_test.go
Labels: area/darwin, size/huge

#6047 runtime: Use git rev-parse for the kata-monitor tag
  src/runtime/Makefile
Labels: area/darwin, size/tiny

#6040 dependency: update cgroups-rs
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/libs/kata-sys-util/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/cgroups/mod.rs
  src/tools/runk/Cargo.lock
  src/tools/runk/libcontainer/Cargo.toml
  src/tools/runk/libcontainer/src/utils.rs
Labels: size/large

#6030 runtime: use system pagesize for hugepage test
  src/runtime/virtcontainers/kata_agent_linux_test.go
Labels: size/small

#6078 runk: Upgrade liboci-cli to v0.0.4
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
  src/tools/runk/src/commands/kill.rs
  src/tools/runk/src/main.rs
Labels: size/medium

#6074 runtime: paas enablevhostuserstore annotation to hypervisor config
  src/runtime/pkg/oci/utils.go
Labels: size/tiny

#6085 versions: Update conmon version
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#5812 Utility functions for kata-env
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
  src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/utils.rs
Labels: no-backport-needed, size/large

#6060 runtime:all APIs are hang in the service.mu
  src/runtime/pkg/containerd-shim-v2/wait.go
Labels: size/tiny

#5256 agent: Eliminate unnecessary metrics
  src/agent/src/metrics.rs
Labels: size/large

#6103 versions: Bump QEMU to v7.2.0
  tools/packaging/qemu/patches/7.2.x/no_patches.txt
  tools/packaging/qemu/patches/tag_patches/v7.2.0/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  versions.yaml
Labels: no-backport-needed, size/small

#6096 runtime: Use consts in `kata-runtime check`
  src/runtime/cmd/kata-runtime/kata-check_amd64.go
Labels: no-backport-needed, no-forward-port-needed, size/small

#6098 versions: Upgrade to Cloud Hypervisor v29.0
  versions.yaml
Labels: no-backport-needed, size/tiny

#6117 agent: Improve logging of pull image
  src/agent/src/image_rpc.rs
Labels: no-backport-needed, size/small

#6111 versions: update cni plugins version
  versions.yaml
Labels: no-backport-needed, size/tiny

#6131 docs: Update url link in QAT documentation
  docs/use-cases/using-Intel-QAT-and-kata.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#6120 Adding caching capability for SEV ovmf
  tools/packaging/static-build/cache_components.sh
Labels: size/tiny

#6104 CC: Remove skopeo umoci
  docs/how-to/how-to-build-and-test-ccv0.md
  src/agent/src/config.rs
  src/agent/src/image_rpc.rs
  tools/osbuilder/rootfs-builder/README.md
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/scripts/lib.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components.sh
  versions.yaml
Labels: area/confidential-containers, size/large

#5736 runtime: Start QEMU undaemonized and get logs
  src/runtime/pkg/govmm/qemu/examples_test.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
  src/runtime/pkg/govmm/qemu/qmp.go
  src/runtime/pkg/govmm/qemu/qmp_test.go
  src/runtime/virtcontainers/qemu.go
Labels: size/large

#6106 docs: Fix missing critical steps in how-to-hotplug-memory-arm64.md
  docs/how-to/how-to-hotplug-memory-arm64.md
Labels: size/small

#6081 upcall: add document for upcall
  src/dragonball/README.md
  src/dragonball/docs/images/upcall-architecture.svg
  src/dragonball/docs/upcall.md
Labels: runtime-rs, size/large

#6146 runtime: Add hmp for qemu
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu.go
Labels: size/small

#6023 runtime-rs: add missing config section for share-fs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-dragonball.toml.in
Labels: runtime-rs, size/small

#6141 Add kernel-dragonball-experimental to kata-deploy, kata-deploy-test, and the release
  .github/workflows/kata-deploy-push.yaml
  .github/workflows/kata-deploy-test.yaml
  .github/workflows/release.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, runtime-rs, size/tiny

#6137 docs: Add documentation for building agent with seccomp support.
  docs/Developer-Guide.md
Labels: no-backport-needed, force-skip-ci, size/small

#5616 Built-in Sandbox: add more unit tests for dragonball. Part 5
  src/dragonball/src/address_space_manager.rs
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/vm/mod.rs
  src/dragonball/src/vmm.rs
Labels: size/large
