Repository kata-containers/kata-containers, pull requests merged in 2023-09, with the labels that each got.

#7817 versions: Update alpine to its 3.18 version
  versions.yaml
Labels: no-backport-needed, size/tiny, ok-to-test

#7814 gha: Rebase PR atop of the target branch before testing
  .github/workflows/add-issues-to-project.yaml
  .github/workflows/add-pr-sizing-label.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/darwin-tests.yaml
  .github/workflows/docs-url-alive-check.yaml
  .github/workflows/move-issues-to-in-progress.yaml
  .github/workflows/require-pr-porting-labels.yaml
Labels: size/small, ok-to-test

#7821 agent: avoid possible leakage of storage device
  src/agent/src/sandbox.rs
  src/agent/src/storage/mod.rs
Labels: no-backport-needed, area/agent, size/tiny

#7819 Improve the way to clean up storage devices for sandbox
  src/agent/src/sandbox.rs
  src/agent/src/storage/mod.rs
  src/libs/kata-types/src/mount.rs
Labels: no-backport-needed, area/agent, size/large, ok-to-test

#7800 kata-sys-util: protection: Update TDX checks
  src/libs/kata-sys-util/src/protection.rs
Labels: size/tiny, ok-to-test

#7826 CC | cherry-pick #7819 and #7821 from main branch
  src/agent/src/sandbox.rs
  src/agent/src/storage/mod.rs
  src/libs/kata-types/src/mount.rs
Labels: no-backport-needed, area/agent

#7808 osbuilder: Remove chcon operation for guest SELinux
  tools/osbuilder/image-builder/image_builder.sh
Labels: size/tiny, ok-to-test

#7803 metrics: Add README for kata metrics report
  tests/metrics/README.md
  tests/metrics/report/README.md
Labels: no-backport-needed, no-forward-port-needed, size/medium

#7839 CI: switch static-checks-dragonball CI machines to Azure
  .github/workflows/static-checks-dragonball.yaml
Labels: size/tiny

#7577 metrics: Enable iperf benchmark on gha for kata metrics
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/gha-run.sh
  tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#7714 runtime-rs: Fix volumes and rootfs cleanup issues
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_into_shim.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
Labels: runtime-rs, size/large

#7851 CCv0: packaging: do not install docker-compose-plugin for s390x|ppc64le
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Labels: no-backport-needed, size/tiny

#7854 runtime: Allow virtio_fs_extra_args annotation
  src/runtime/Makefile
Labels: needs-backport, size/tiny

#7843 metrics: Add write 95 percentile FIO value
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#7703 runtime: run prestart hooks before starting VM for FC
  src/runtime/virtcontainers/acrn_arch_base.go
  src/runtime/virtcontainers/acrn_arch_base_test.go
  src/runtime/virtcontainers/acrn_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arch_base_test.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_test.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/types/capabilities.go
  src/runtime/virtcontainers/utils/utils.go
  src/runtime/virtcontainers/utils/utils_test.go
Labels: no-backport-needed, no-forward-port-needed, size/large

#7570 CC | add sealed secret support in Kata
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/Makefile
  src/agent/src/cdh.rs
  src/agent/src/config.rs
  src/agent/src/image_rpc.rs
  src/agent/src/main.rs
  src/agent/src/rpc.rs
  src/libs/protocols/Cargo.toml
  src/libs/protocols/build.rs
  src/libs/protocols/protos/sealed_secret.proto
  src/libs/protocols/src/lib.rs
  src/runtime/Makefile
  src/runtime/config/configuration-clh-tdx.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
  src/runtime/config/configuration-qemu-se.toml.in
  src/runtime/config/configuration-qemu-sev.toml.in
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/config/configuration-remote.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/sandbox.go
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  versions.yaml
Labels: size/huge

#7833 kata-deploy: Create kata-static.tar with correct ownership
  tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
Labels: size/tiny, ok-to-test

#7841 ci: k8s: Add k8s devmapper tests (part 0)
  .github/workflows/ci.yaml
  .github/workflows/run-k8s-tests-on-garm.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: force-skip-ci, size/large

#7860 ci: k8s: Fix typo in run-k8s-tests-on-garm.yaml
  .github/workflows/run-k8s-tests-on-garm.yaml
Labels: force-skip-ci, size/tiny

#6879 Dragonball: optimize the placement of dbs-upcall features
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/vm/mod.rs
Labels: runtime-rs, size/tiny

#7824 metrics: re-enable memory-usage initialization step
  tests/metrics/density/memory_usage.sh
Labels: no-backport-needed, area/metrics, size/tiny, ok-to-test

#7868 ci: k8s: Second round of fix-ups with the devmapper CI
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-garm.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: force-skip-ci, size/small, ok-to-test

#7871 ci: k8s: Add clean-up-garm argument for gha-run.sh
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/k8s-cpu-ns.bats
  tests/integration/kubernetes/k8s-credentials-secrets.bats
  tests/integration/kubernetes/k8s-file-volume.bats
  tests/integration/kubernetes/k8s-inotify.bats
  tests/integration/kubernetes/k8s-nested-configmap-secret.bats
  tests/integration/kubernetes/k8s-pod-quota.bats
  tests/integration/kubernetes/k8s-projected-volume.bats
  tests/integration/kubernetes/k8s-volume.bats
Labels: size/small, ok-to-test

#7870 metrics: fix FIO test initialization
  tests/metrics/storage/fio-k8s/fio-test-ci.sh
Labels: no-backport-needed, size/tiny, ok-to-test

#7867 metrics: Use TensorFlow optimized image
  tests/metrics/machine_learning/resnet50_fp32_dockerfile/Dockerfile
  tests/metrics/machine_learning/resnet50_int8_dockerfile/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7847 CC | versions: Bump to 6.4.14 stable kernel
  tools/packaging/kernel/configs/fragments/common/lsm.conf
  tools/packaging/kernel/configs/fragments/common/netfilter.conf
  tools/packaging/kernel/configs/fragments/common/network.conf
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/6.4.x/no_patches.txt
  versions.yaml
Labels: size/small

#7862 kata-deploy: Switch to an alpine image
  tools/packaging/kata-deploy/Dockerfile
Labels: size/small, ok-to-test

#7865 runtime: Fix more virtiofs args
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/virtiofsd.go
  src/runtime/virtcontainers/virtiofsd_test.go
Labels: needs-backport, size/small, ok-to-test

#7875 kata-deploy: Fix aarch64 image build
  tools/packaging/kata-deploy/Dockerfile
Labels: force-skip-ci, size/tiny

#7883 Revert "CC | versions: Bump to 6.4.14 stable kernel"
  tools/packaging/kernel/configs/fragments/common/lsm.conf
  tools/packaging/kernel/configs/fragments/common/netfilter.conf
  tools/packaging/kernel/configs/fragments/common/network.conf
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/6.4.x/no_patches.txt
  versions.yaml
Labels: size/small

#7884 Update kernel to the latest LTS release (v6.1.52) and bring in erofs patches needed for the CC work
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/6.1.x/0001-erofs-get-rid-of-erofs_inode_datablocks.patch
  tools/packaging/kernel/patches/6.1.x/0002-erofs-get-rid-of-z_erofs_do_map_blocks-forward-decla.patch
  tools/packaging/kernel/patches/6.1.x/0003-erofs-avoid-hardcoded-blocksize-for-subpage-block-su.patch
  tools/packaging/kernel/patches/6.1.x/0004-erofs-set-block-size-to-the-on-disk-block-size.patch
  tools/packaging/kernel/patches/6.1.x/no_patches.txt
  versions.yaml
Labels: size/huge, ok-to-test

#7874 gha: Manually rebase PR atop of the target branch before testing
  .github/workflows/add-pr-sizing-label.yaml
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/ci.yaml
  .github/workflows/move-issues-to-in-progress.yaml
  .github/workflows/require-pr-porting-labels.yaml
  .github/workflows/run-cri-containerd-tests.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-garm.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
  .github/workflows/run-kata-deploy-tests-on-aks.yaml
  .github/workflows/run-kata-deploy-tests-on-tdx.yaml
  .github/workflows/run-metrics.yaml
  .github/workflows/run-nydus-tests.yaml
  .github/workflows/run-vfio-tests.yaml
  tests/git-helper.sh
Labels: force-skip-ci, size/large

#7151 agent: optimize the code of systemd cgroup manager
  src/agent/Cargo.lock
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/cgroups/systemd/common.rs
  src/agent/rustjail/src/cgroups/systemd/dbus_client.rs
  src/agent/rustjail/src/cgroups/systemd/interface/system.rs
  src/agent/rustjail/src/cgroups/systemd/manager.rs
Labels: no-backport-needed, no-forward-port-needed, size/huge, ok-to-test

#7900 ci: Add more target-branch related fixes
  .github/workflows/ci-nightly.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/publish-kata-deploy-payload-amd64.yaml
  .github/workflows/publish-kata-deploy-payload-arm64.yaml
  .github/workflows/publish-kata-deploy-payload-s390x.yaml
Labels: force-skip-ci, size/small

#7901 ci: use github.ref_name instead of $GITHUB_REF_NAME
  .github/workflows/ci-nightly.yaml
  .github/workflows/payload-after-push.yaml
Labels: force-skip-ci, size/small

#7766 runtime-rs: bring hybrid vsock devices in manager.
  src/libs/Cargo.lock
  src/libs/kata-types/src/config/mod.rs
  src/libs/shim-interface/Cargo.toml
  src/libs/shim-interface/src/lib.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/utils.rs
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_vsock.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/utils.rs
  src/runtime-rs/crates/persist/src/lib.rs
  src/runtime-rs/crates/resource/src/lib.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/service/src/manager.rs
Labels: runtime-rs, size/large

#7889 dragonball: fix for non-deterministic builds
  src/dragonball/.gitignore
  src/dragonball/Cargo.lock
Labels: runtime-rs, size/huge, ok-to-test

#7811 versions: Bump rust version
  src/agent/src/config.rs
  src/dragonball/src/dbs_utils/src/net/net_gen/mod.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/libs/safe-path/src/scoped_path_resolver.rs
  src/runtime-rs/crates/resource/src/network/utils/address.rs
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/shm_volume.rs
  src/runtime-rs/crates/resource/src/volume/spdk_volume.rs
  src/tools/agent-ctl/src/client.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/exec_ops.rs
  src/tools/kata-ctl/src/utils.rs
  src/tools/runk/libcontainer/src/utils.rs
  versions.yaml
Labels: no-backport-needed, size/small, ok-to-test

#7887 runtime-rs: hypervisor: Remove debug kernel options
  src/runtime-rs/Makefile
  src/runtime-rs/crates/hypervisor/src/kernel_param.rs
  src/runtime/Makefile
  utils/kata-manager.sh
Labels: runtime-rs, size/small, ok-to-test

#7921 metrics: this PR skips the FIO test temprarily to fix issues
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/gha-run.sh
Labels: no-backport-needed, area/metrics, size/tiny, ok-to-test

#7918 CCv0 bump to rust 1.72
  src/agent/src/config.rs
  src/dragonball/src/dbs_utils/src/net/net_gen/mod.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/libs/safe-path/src/scoped_path_resolver.rs
  src/runtime-rs/crates/resource/src/network/utils/address.rs
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/shm_volume.rs
  src/runtime-rs/crates/resource/src/volume/spdk_volume.rs
  src/tools/agent-ctl/src/client.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/exec_ops.rs
  src/tools/kata-ctl/src/utils.rs
  src/tools/runk/libcontainer/src/utils.rs
  versions.yaml
Labels: size/small

#7899 metrics: Ensure docker is running in init_env
  tests/metrics/lib/common.bash
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7880 image-builder: fix udev error when using docker to build image
  tools/osbuilder/image-builder/image_builder.sh
Labels: no-backport-needed, size/tiny

#7719 Remove gogoproto.nullable extension
  src/libs/protocols/hack/update-generated-proto.sh
  src/libs/protocols/protos/oci.proto
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/csi.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/csipb_test.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/health.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/healthpb_test.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/ocipb_test.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
Labels: no-backport-needed, size/large, ok-to-test

#7917 agent: optimize the code of systemd cgroup manager
  src/agent/Cargo.lock
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/cgroups/systemd/common.rs
  src/agent/rustjail/src/cgroups/systemd/dbus_client.rs
  src/agent/rustjail/src/cgroups/systemd/interface/system.rs
  src/agent/rustjail/src/cgroups/systemd/manager.rs
Labels: no-backport-needed, size/large

#7907 runtime: Naming conflict of network devices
  src/runtime/virtcontainers/network_linux.go
Labels: size/small, ok-to-test

#7878 CC | osbuilder: check rust enviornment before building agent and AA
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: no-backport-needed, size/tiny

#7895 metrics: Remove warning from metrics documentation
  tests/metrics/README.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny

#7923 metrics: Add Cassandra Metrics documentation
  tests/metrics/disk/README.md
Labels: no-backport-needed, no-forward-port-needed, size/small

#7688 CC | support dm-verity tarfs disk image in CoCo
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/storage/block_handler.rs
  src/agent/src/storage/dm_verity.rs
  src/agent/src/storage/fs_handler.rs
  src/agent/src/storage/mod.rs
  src/libs/kata-sys-util/src/mount.rs
  src/libs/kata-types/src/lib.rs
  src/libs/kata-types/src/volume.rs
  src/runtime/pkg/katautils/create.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/fs_share.go
  src/runtime/virtcontainers/fs_share_linux.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/types/virtual_volume.go
  src/runtime/virtcontainers/types/virtual_volume_test.go
Labels: size/huge, ok-to-test

#7925 metrics: Add iperf bandwidth value for kata metrics
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#7905 tests: fix kernel and initrd annotations
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/setup.sh
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#7704 gha: vfio: Import test script
  .github/workflows/run-vfio-tests.yaml
  src/runtime/config/configuration-clh.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/create_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  tests/common.bash
  tests/functional/vfio/gha-run.sh
  tests/functional/vfio/guest-kernel.json.in
  tests/functional/vfio/run.sh
  tests/functional/vfio/vfio.json.in
  tests/functional/vfio/vfio_fedora_vm_wrapper.sh
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/kernel/configs/fragments/x86_64/vfio.conf
  tools/packaging/kernel/kata_config_version
Labels: size/huge, ok-to-test

#7954 ci: cache: Export env vars needed to use ORAS
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: force-skip-ci, size/small

#7937 metrics: Add iperf value for cpu utilization
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#7957 ci: cache: Allow pushing our artefacts to an OCI registry
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/local-build/dockerbuild/install_oras.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: needs-backport, size/large, ok-to-test

#7956 ci: Reduce the size of the AKS VMs
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/inotify-configmap-pod.yaml
Labels: needs-backport, force-skip-ci, size/tiny, ok-to-test

#7959 ci: Run some of the GARM tests in smaller instances
  .github/workflows/run-cri-containerd-tests.yaml
  .github/workflows/run-docker-tests-on-garm.yaml
  .github/workflows/run-k8s-tests-on-garm.yaml
  .github/workflows/run-nerdctl-tests-on-garm.yaml
  .github/workflows/run-nydus-tests.yaml
Labels: size/tiny, ok-to-test

#7964 ci: cache: Use the artefacts stored in ghcr.io/kata-containers/cached-artefacts/${component}
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components_main.sh
Labels: needs-backport, size/large, ok-to-test

#7981 cc|osbuilder: Correct a typo in the initrd-image
  tools/packaging/guest-image/build_image.sh
Labels: no-backport-needed, size/tiny

#7738 runtime: incorrect handling of non-empty []Endpoint parameter in Remo…
  src/runtime/virtcontainers/network_linux.go
Labels: size/small, ok-to-test

#7951 cc|gha: remove build redundancy of kernel and cc-rootfs-initrd for s390x
  .github/workflows/cc-payload-after-push-s390x.yaml
Labels: no-backport-needed, size/medium

#7976 ci: Rework static checks
  .github/workflows/static-checks-dragonball.yaml
  .github/workflows/static-checks.yaml
  ci/install_libseccomp.sh
  src/agent/Makefile
  src/runtime-rs/Makefile
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Makefile
  src/tools/kata-ctl/src/check.rs
  tests/common.bash
  tests/install_go.sh
  tests/install_rust.sh
Labels: needs-backport, force-skip-ci, size/large, ok-to-test

#7973 ci: Use variable size of VMs depending on the tests running
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-garm.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  .github/workflows/run-k8s-tests-on-snp.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: size/medium, ok-to-test

#7806 clh:arm64: use arm AMBA UART for hypervisor debug
  src/runtime/virtcontainers/clh.go
  tools/packaging/kernel/configs/fragments/arm64/serial.conf
  tools/packaging/kernel/kata_config_version
Labels: needs-backport, size/small, ok-to-test

#7953 runtime/qemu: Rework QMP/HMP support
  src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu.go
Labels: needs-backport, size/large, ok-to-test

#7961 Bump nydus versions and update nydus tests
  tests/common.bash
  tests/integration/nydus/gha-run.sh
  tests/integration/nydus/nydus-container.yaml
  tests/integration/nydus/nydus-sandbox.yaml
  tests/integration/nydus/nydus_tests.sh
  tests/integration/nydus/nydusd-config.json
  tests/integration/nydus/snapshotter-config.toml
  tools/packaging/static-build/nydus/build.sh
  versions.yaml
Labels: no-backport-needed, size/large, ok-to-test

#7985 clh: arm: Use static_sandbox_resource_mgmt=true
  src/runtime/Makefile
  src/runtime/arch/amd64-options.mk
  src/runtime/arch/arm64-options.mk
  src/runtime/config/configuration-clh.toml.in
Labels: needs-backport, size/tiny, ok-to-test, backport-to-stable-3.2

#7992 versions: Bump virtiofsd to v1.8.0
  versions.yaml
Labels: needs-backport, size/tiny, ok-to-test

#7983 ci: Create clusters in individual resource groups
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: size/medium, ok-to-test

#7990 metrics: Enable parallel bandwidth iperf limit
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8007 ci: kata-deploy: Fix runner name
  .github/workflows/run-kata-deploy-tests-on-garm.yaml
Labels: force-skip-ci, size/tiny, ok-to-test

#7948 osbuilder: Update api-server-rest
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  tools/osbuilder/rootfs-builder/rootfs.sh
  versions.yaml
Labels: no-backport-needed, size/small

#7998 CC | version: Specify forked / vanilla entries of containerd
  versions.yaml
Labels: size/small

#8004 runtime: support kernel params including spaces
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_test.go
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#8010 CC | osbuild: Reduce guest components binary size with strip
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: size/tiny

#8021 CC | cache: Fix rootfs-image-tdx and rootfs-initrd-sev cached artefacts
  tools/packaging/static-build/cache_components.sh
Labels: size/tiny

#7676 CC | image pulling in the guest without forked containerd
  src/agent/src/image_rpc.rs
  src/agent/src/storage/image_pull_handler.rs
  src/agent/src/storage/mod.rs
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/fs_share_linux.go
  src/runtime/virtcontainers/kata_agent.go
  tools/osbuilder/scripts/lib.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/static-build/nydus/build.sh
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/shim-v2/install_go_rust.sh
Labels: size/large, ok-to-test

#8016 ci: Actually enable the CRI-O tests
  .github/workflows/ci.yaml
Labels: force-skip-ci, size/small

#8032 ci: Trigger payload-after-push on workflow_dispatch
  .github/workflows/payload-after-push.yaml
Labels: force-skip-ci, size/tiny

#8020 gha: Install hunspell for static checks
  .github/workflows/static-checks.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7799 clh: Direct IO support for block devices
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/fc.go
Labels: area/cloud-hypervisor, size/small, ok-to-test

#6706 feat(runtime-rs): introduce huge page mode to select VM RAM's backend
  src/agent/Cargo.lock
  src/libs/kata-types/Cargo.toml
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/tests/test_config.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/tools/kata-ctl/Cargo.lock
Labels: runtime-rs, size/large, ok-to-test

#8030 ci: rootfs-image build-asset is failing
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny, ok-to-test

#8042 gha: Add pandoc as a dependency for static checks
  .github/workflows/static-checks.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8012 osbuild: Reduce guest components binary size with strip
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: size/tiny, ok-to-test

#7966 runtime-rs: Add network support for cloud-hypervisor
  src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Labels: size/large, ok-to-test

#8045 local-build: Fix .docker ownership before build-payload
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#8038 metrics: Enable latency test in gha run script
  .github/workflows/run-metrics.yaml
  tests/metrics/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8028 ci: k8s: crio: Follow up patches to have CRI-O also working as part of our CI
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/tests_common.sh
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: force-skip-ci, size/small, ok-to-test

#7715 CC: kata-deploy: Set the snapshotter in the containerd runtime config
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny

#8050 CC | policy: fix setting the policy path from agent config
  src/agent/src/image_rpc.rs
Labels: no-backport-needed, size/tiny

#7944 runtime-rs: ch: Enable Intel TDX
  src/libs/Cargo.lock
  src/libs/kata-sys-util/src/protection.rs
  src/libs/kata-types/src/config/hypervisor/ch.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
  src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/errors.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Labels: force-skip-ci, size/huge, ok-to-test

#8053 CC | runtime: merge metadata and annotation in imagepullvolume
  src/runtime/virtcontainers/kata_agent.go
Labels: size/tiny

#8054 metrics: Fix C-Ray documentation
  tests/metrics/cpu/README.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8056 metrics: Fix latency yamls path
  tests/metrics/network/latency_kubernetes/latency-network.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8075 ci: Port kata-monitor tests from Jenkins to GHA
  .github/workflows/ci.yaml
  .github/workflows/run-kata-monitor-tests.yaml
  tests/common.bash
  tests/functional/kata-monitor/gha-run.sh
  tests/functional/kata-monitor/kata-monitor-tests.sh
  tests/gha-run-k8s-common.sh
Labels: force-skip-ci, size/huge, ok-to-test

#8058 Upgrade to Cloud Hypervisor v35.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#8036 runtime: fix reading cgroup stats of sandboxes
  src/runtime/virtcontainers/sandbox.go
Labels: needs-backport, size/tiny, ok-to-test

#8068 metrics: Add latency value limits for kata CI
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8077 kata-deploy: build & ship the rust components from src/tools/
  .github/workflows/build-kata-static-tarball-amd64.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/tools/Dockerfile
  tools/packaging/static-build/tools/build-static-tools.sh
  tools/packaging/static-build/tools/build.sh
Labels: force-skip-ci, size/large, ok-to-test

#8066 docs: Update url in kata vra document
  docs/design/kata-vra.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test
