Repository kata-containers/kata-containers, pull requests merged in 2023-11, with the labels that each got.

#8308 release: Fully migrate from hub to gh
  .github/workflows/release.yaml
  tools/packaging/release/README.md
  tools/packaging/release/tag_repos.sh
  tools/packaging/release/update-repository-version.sh
  tools/packaging/scripts/lib.sh
Labels: no-backport-needed, size/medium, ok-to-test

#8348 gha: Add workflow to close stale PRs
  .github/workflows/stale.yaml
Labels: size/small, ok-to-test

#7057 kata-manager: Fix deployment of containerd on architectures other than amd64.
  utils/kata-manager.sh
Labels: size/small, ok-to-test

#8285 Docs: Fix Dragonball link
  docs/hypervisors.md
Labels: size/tiny, ok-to-test

#8368 gha: stale: Fix typo and allow manually triggering it
  .github/workflows/stale.yaml
Labels: safe-to-test, size/tiny, ok-to-test

#8365 kata-manager: Accept only "lts" or "active" as containerd versions
  utils/kata-manager.sh
Labels: size/small, ok-to-test

#8284 runtime-rs: update device pci info for vfio and virtio-blk devices
  src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
Labels: size/large, ok-to-test

#8353 CCv0: Set v0.8.0 tag for image-rs, AA and td-shim
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  versions.yaml
Labels: no-backport-needed, size/tiny

#8217 tests: fixes permission denied when running test
  tests/integration/cri-containerd/integration-tests.sh
Labels: size/tiny, ok-to-test

#8386 runtime-rs: ch: Simplify VSOCK error handling
  src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/errors.rs
Labels: safe-to-test, size/medium, ok-to-test

#8400 CC | agent: fix annotation name to allow cri-o support of CoCo pullimage in guest
  src/agent/src/image_rpc.rs
Labels: no-backport-needed, size/small

#8023 runtime-rs: Update status for pause and resume
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: no-backport-needed, runtime-rs, size/small, ok-to-test

#8367 network: Fix network hotplug for ipvlan and macvlan endpoints for qemu and add tests
  src/runtime/virtcontainers/qemu.go
  tests/integration/nerdctl/gha-run.sh
Labels: size/small, ok-to-test

#8389 runtime: Fix TestCheckHostIsVMContainerCapable unstablity issue
  src/runtime/cmd/kata-runtime/kata-check_amd64_test.go
Labels: size/small, ok-to-test

#8379 Upgrade to Cloud Hypervisor v36.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/ConsoleConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NumaConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmmPingResponse.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_console_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_numa_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vmm_ping_response.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#8411 gha: Fix regex used to get kubectl version from the k3s version
  tests/gha-run-k8s-common.sh
Labels: force-skip-ci, size/tiny, ok-to-test

#8402 network: Backports for Ipvlan qemu fix and related tests
  src/runtime/virtcontainers/qemu.go
  tests/integration/nerdctl/gha-run.sh
Labels: size/small, ok-to-test

#8415 cc: gha: kernel-snp-experimental is not a valid tag
  .github/workflows/cc-payload-amd64.yaml
Labels: size/tiny

#8404 kata-deploy: Allow users to set hypervisor annotations
  tests/integration/kubernetes/gha-run.sh
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/small, ok-to-test

#8370 agent: update AGENT_THREADS metrics value
  src/agent/src/metrics.rs
Labels: size/tiny, ok-to-test

#8169 runtime-rs: fix a typo in shm
  src/runtime-rs/crates/resource/src/volume/mod.rs
  src/runtime-rs/crates/resource/src/volume/shm_volume.rs
Labels: runtime-rs, size/tiny, ok-to-test

#8376 kata-manager: Add support for Docker CLI installation
  utils/kata-manager.sh
Labels: size/large, ok-to-test

#8309 Update release process documentation
  docs/Release-Process.md
Labels: no-backport-needed, ok-to-test

#8374 utils: kata-manager: Ensure only one download URL
  utils/kata-manager.sh
Labels: safe-to-test, size/small, ok-to-test

#8406 docs: add agent policy documentation
  docs/how-to/README.md
  docs/how-to/how-to-use-the-kata-agent-policy.md
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#7675 dragonball: Introduce vhost-net device
  src/dragonball/Cargo.lock
  src/dragonball/Cargo.toml
  src/dragonball/src/api/v1/mod.rs
  src/dragonball/src/api/v1/virtio_net.rs
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/dbs_virtio_devices/Cargo.toml
  src/dragonball/src/dbs_virtio_devices/src/lib.rs
  src/dragonball/src/dbs_virtio_devices/src/net.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/mod.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_kern/mod.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_kern/net.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_kern/test_utils.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/device_manager/vhost_net_dev_mgr.rs
  src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
  src/dragonball/src/error.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
  src/runtime-rs/crates/resource/src/network/endpoint/ipvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/macvlan_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/tap_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/veth_endpoint.rs
  src/runtime-rs/crates/resource/src/network/endpoint/vlan_endpoint.rs
Labels: runtime-rs, size/huge, ok-to-test

#8419 runtime-rs: ch: Fix TDX
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Labels: safe-to-test, size/large, ok-to-test

#8338 metrics: Fix function that completely stops kata containers before running a test
  tests/common.bash
  tests/metrics/lib/common.bash
Labels: no-backport-needed, no-forward-port-needed, area/metrics, size/small, ok-to-test

#8383 utils: kata-manager: Add option to list versions
  utils/kata-manager.sh
Labels: safe-to-test, size/medium, ok-to-test

#8174 ci: Re-add tracing tests and move docker/nerdctl to the basic-ci-amd64.yaml file
  .github/workflows/basic-ci-amd64.yaml
  .github/workflows/run-docker-tests-on-garm.yaml
  .github/workflows/run-nerdctl-tests-on-garm.yaml
  tests/common.bash
  tests/functional/tracing/configure_tracing_for_kata.sh
  tests/functional/tracing/gha-run.sh
  tests/functional/tracing/test-agent-shutdown.sh
  tests/functional/tracing/tracing-test.sh
  tests/integration/docker/gha-run.sh
Labels: force-skip-ci, size/huge, ok-to-test

#8432 gha: Remove docker and nerdctl tests from ci.yaml
  .github/workflows/ci.yaml
Labels: size/small, ok-to-test

#7623 runtime: Improve vCPU allocation for the VMMs
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/acrn_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/clh_test.go
  src/runtime/virtcontainers/factory/factory_linux.go
  src/runtime/virtcontainers/factory/factory_test.go
  src/runtime/virtcontainers/fc.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_config_darwin.go
  src/runtime/virtcontainers/hypervisor_config_linux.go
  src/runtime/virtcontainers/hypervisor_config_linux_test.go
  src/runtime/virtcontainers/macvtap_endpoint.go
  src/runtime/virtcontainers/network_linux.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_test.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
  src/runtime/virtcontainers/tap_endpoint.go
  src/runtime/virtcontainers/tuntap_endpoint.go
  src/runtime/virtcontainers/utils/utils.go
  src/runtime/virtcontainers/utils/utils_test.go
  src/runtime/virtcontainers/vm.go
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/k8s-sandbox-vcpus-allocation.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/pod-sandbox-vcpus-allocation.yaml
Labels: size/large, ok-to-test

#8431 kernel: Fix vsock packets drop when the driver initializes
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/5.10.x/0001-vsock-virtio-avoid-potential-deadlock-when-vsock-dev.patch
  tools/packaging/kernel/patches/5.10.x/0002-vsock-each-transport-cycles-only-on-its-own-sockets.patch
  tools/packaging/kernel/patches/5.10.x/0003-vsock-virtio-initialize-vdev-priv-before-using-VQs.patch
  tools/packaging/kernel/patches/5.10.x/0004-vsock-virtio-enable-VQs-early-on-probe.patch
  tools/packaging/kernel/patches/5.10.x/0005-vsock-virtio-factor-our-the-code-to-initialize-and-d.patch
  tools/packaging/kernel/patches/5.10.x/0006-vsock-virtio-add-support-for-device-suspend-resume.patch
  tools/packaging/kernel/patches/5.10.x/0007-vsock-virtio-initialize-the_virtio_vsock-before-usin.patch
  tools/packaging/kernel/patches/5.19.x/0001-vsock-virtio-initialize-the_virtio_vsock-before-usin.patch
  tools/packaging/kernel/patches/5.19.x/no_patches.txt
  tools/packaging/kernel/patches/6.2-TDX-v1.x/0001-vsock-virtio-initialize-the_virtio_vsock-before-usin.patch
  tools/packaging/kernel/patches/6.2-TDX-v1.x/no_patches.txt
  versions.yaml
Labels: needs-backport, size/huge, ok-to-test

#8426 dragonball: Remove vhost-net dependency on virtio-net
  src/dragonball/src/api/v1/virtio_net.rs
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/dbs_virtio_devices/Cargo.toml
  src/dragonball/src/dbs_virtio_devices/src/lib.rs
  src/dragonball/src/dbs_virtio_devices/src/net.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_kern/net.rs
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#7987 tests|gha: add nightly tests for s390x
  .github/workflows/ci-nightly-s390x.yaml
Labels: no-backport-needed, size/small, ok-to-test

#8460 gha: Keep kata tarballs for 15 days
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: needs-backport, force-skip-ci, size/small, ok-to-test

#8421 tests: Enable stressng scalability test
  tests/stability/gha-run.sh
  tests/stability/stressng.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8453 metrics: Add iperf udp information to README
  tests/metrics/network/README.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7931 tests|gha: add containerd and k8s tests for s390x
  .github/workflows/ci-nightly-s390x.yaml
  .github/workflows/ci.yaml
  .github/workflows/run-cri-containerd-tests-s390x.yaml
  .github/workflows/run-k8s-tests-on-zvsi.yaml
  tests/common.bash
  tests/integration/kubernetes/filter_k8s_test.sh
  tests/integration/kubernetes/gha-run.sh
Labels: no-backport-needed, safe-to-test, size/large, ok-to-test

#7796 StratoVirt: add support for a lightweight VMM StratoVirt in Kata
  .github/workflows/basic-ci-amd64.yaml
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-metrics.yaml
  src/runtime/Makefile
  src/runtime/arch/amd64-options.mk
  src/runtime/arch/arm64-options.mk
  src/runtime/cmd/kata-runtime/kata-check_amd64.go
  src/runtime/config/configuration-stratovirt.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_linux.go
  src/runtime/virtcontainers/stratovirt.go
  src/runtime/virtcontainers/stratovirt_test.go
  src/runtime/virtcontainers/virtcontainers_test.go
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-stratovirt-kata-metric8.toml
  tools/packaging/kata-deploy/examples/nginx-deployment-stratovirt.yaml
  tools/packaging/kata-deploy/examples/test-deploy-kata-stratovirt.yaml
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-stratovirt.yaml
  tools/packaging/static-build/stratovirt/build-static-stratovirt.sh
  versions.yaml
Labels: no-backport-needed, size/huge, ok-to-test

#8345 Fixes make check errors
  src/libs/kata-sys-util/src/protection.rs
  src/libs/kata-types/src/config/shared_mount.rs
Labels: size/small, ok-to-test

#8332 runitme-rs/bugfix: kata pod with multi-containers sharing one direct volume
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/mod.rs
  src/runtime-rs/crates/resource/src/volume/utils.rs
Labels: bug, size/small, ok-to-test

#8478 kata-deploy: Set a default value for ALLOWED_HYPERVISOR_ANNOTATIONS
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: no-backport-needed, size/tiny, ok-to-test

#8465 dragonball: Uniform the spelling of Virtio
  src/dragonball/src/dbs_virtio_devices/src/block/device.rs
  src/dragonball/src/dbs_virtio_devices/src/fs/device.rs
  src/dragonball/src/dbs_virtio_devices/src/vsock/epoll_handler.rs
  src/dragonball/src/device_manager/balloon_dev_mgr.rs
  src/dragonball/src/device_manager/blk_dev_mgr.rs
  src/dragonball/src/device_manager/fs_dev_mgr.rs
  src/dragonball/src/device_manager/mem_dev_mgr.rs
  src/dragonball/src/device_manager/memory_region_handler.rs
  src/dragonball/src/error.rs
Labels: size/medium, ok-to-test

#8451 Dragonball: add PCI bus and PCI interrupt support in mptable Spec
  src/dragonball/src/dbs_boot/src/x86_64/mptable.rs
  src/dragonball/src/dbs_virtio_devices/src/balloon.rs
  src/dragonball/src/vm/x86_64.rs
Labels: runtime-rs, size/medium, ok-to-test

#7046 CC: Remote hypervisor merge to main
  src/runtime/Makefile
  src/runtime/cmd/kata-runtime/kata-check_amd64.go
  src/runtime/cmd/kata-runtime/kata-check_arm64.go
  src/runtime/cmd/kata-runtime/kata-check_ppc64le.go
  src/runtime/cmd/kata-runtime/kata-check_s390x.go
  src/runtime/config/configuration-remote.toml.in
  src/runtime/hack/update-generated-hypervisor-proto.sh
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/protocols/hypervisor/hypervisor.pb.go
  src/runtime/protocols/hypervisor/hypervisor.proto
  src/runtime/protocols/hypervisor/hypervisor_grpc.pb.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_config_darwin.go
  src/runtime/virtcontainers/hypervisor_config_linux.go
  src/runtime/virtcontainers/hypervisor_config_test.go
  src/runtime/virtcontainers/hypervisor_linux.go
  src/runtime/virtcontainers/hypervisor_test.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
  src/runtime/virtcontainers/remote.go
  src/runtime/virtcontainers/remote_test.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/types/sandbox.go
  src/runtime/virtcontainers/types/sandbox_test.go
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-remote.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
Labels: no-backport-needed, size/huge, ok-to-test, merge-to-main

#8471 runtime: Introduce `KataVirtualVolume` structure into go runtime
  src/runtime/virtcontainers/types/virtual_volume.go
  src/runtime/virtcontainers/types/virtual_volume_test.go
Labels: no-backport-needed, area/runtime, size/large, ok-to-test, merge-to-main

#7932 runtime-rs: bringing virtio-fs device in device-manager
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_blk.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_fs.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_vsock.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
  src/runtime-rs/crates/resource/src/rootfs/nydus_rootfs.rs
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_inline.rs
  src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
Labels: no-backport-needed, runtime-rs, size/huge, ok-to-test

#8450 dragonball: add vhost-user connection management logic
  src/dragonball/src/dbs_virtio_devices/Cargo.toml
  src/dragonball/src/dbs_virtio_devices/src/lib.rs
  src/dragonball/src/dbs_virtio_devices/src/mmio/mmio_state.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/mod.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_kern/net.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/mod.rs
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/test_utils.rs
Labels: size/huge, ok-to-test

#8476 tests: k8s: Allow passing rust-runtime env var to kata-deploy
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: force-skip-ci, size/tiny, ok-to-test

#8481 kernel: backport erofs patch to 6.1.52 guest kernel
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/6.1.x/0005-erofs-support-flattened-block-device-for-multi-blob-.patch
Labels: size/large, kernel, ok-to-test

#8473 stable-3.2 | gha: Keep kata tarballs for 15 days
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: size/small

#8467 metrics: Fix result finding in tensorflow benchmark
  tests/metrics/machine_learning/tensorflow_resnet50_fp32.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8422 runtime-rs on arm64: Fixes unable to Boot Container Image using Cloud…
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Labels: safe-to-test, size/tiny, ok-to-test

#8239 runtime: Fix configmap/secrets updates with FS sharing disabled
  src/agent/src/rpc.rs
  src/runtime/virtcontainers/fs_share_linux.go
Labels: no-backport-needed, no-forward-port-needed, area/confidential-containers, size/large, ok-to-test

#8459 github: add workflows for building and publishing kata artefacts on ppc64le
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/ci.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/publish-kata-deploy-payload-ppc64le.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release.yaml
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/local-build/dockerbuild/install_oras.sh
  tools/packaging/static-build/qemu.blacklist
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/shim-v2/build.sh
Labels: no-backport-needed, size/large, ok-to-test

#8501 gha: add cri-containerd workflow for ppc64le
  .github/workflows/ci.yaml
  .github/workflows/run-cri-containerd-tests-ppc64le.yaml
  tests/integration/cri-containerd/gha-run.sh
  tests/integration/cri-containerd/integration-tests.sh
Labels: no-backport-needed, size/medium, ok-to-test

#8497 gha: Disable stratovirt for gha metrics
  .github/workflows/run-metrics.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8533 Revert "runtime: confidential: Do not set the max_vcpu to cpu"
  src/runtime/virtcontainers/hypervisor_config_linux.go
Labels: force-skip-ci, size/tiny, ok-to-test

#8528 tools: Stop building / shipping log-parser-rs
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/static-checks.yaml
Labels: size/tiny, ok-to-test

#8526 gha: fix artefacts build on ppc64le
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/publish-kata-deploy-payload-ppc64le.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8520 runtime: Update hypervisor generated code
  src/runtime/hack/update-generated-hypervisor-proto.sh
  src/runtime/protocols/hypervisor/hypervisor_grpc.pb.go
  src/runtime/protocols/hypervisor/hypervisor_ttrpc.pb.go
  src/runtime/virtcontainers/remote.go
Labels: no-backport-needed, size/small, ok-to-test

#8456 osbuilder: add pkg bash for alpine
  tools/osbuilder/rootfs-builder/alpine/config.sh
Labels: needs-backport, size/tiny, ok-to-test

#8271 tests: more k8s-exec-rejected debug output
  tests/integration/kubernetes/k8s-exec-rejected.bats
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-exec-rejected.yaml
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8537 Cherrypick agent-policy support from main to CCv0
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/Makefile
  src/agent/src/main.rs
  src/agent/src/policy.rs
  src/agent/src/rpc.rs
  src/kata-opa/allow-all.rego
  src/kata-opa/kata-opa.service.in
  src/libs/protocols/protos/agent.proto
  src/runtime/pkg/katautils/create.go
  src/runtime/pkg/oci/utils.go
  src/runtime/virtcontainers/agent.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/mock_agent.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/pkg/mock/mock.go
  tools/osbuilder/rootfs-builder/cbl-mariner/config.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  versions.yaml
Labels: no-backport-needed, size/huge

#8531 metrics: Fix iperf parallel bandwidth limit
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#7815 runtime-rs: Add Hybrid VSOCK device handling for CH
  src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
Labels: no-backport-needed, safe-to-test, runtime-rs, size/medium, ok-to-test
