Repository kata-containers/kata-containers, pull requests merged in 2023-04, with the labels that each got.

#6501 runtime: add filter metrics with specific names
  src/runtime/cmd/kata-monitor/README.md
  src/runtime/pkg/kata-monitor/metrics.go
  src/runtime/pkg/kata-monitor/shim_client.go
Labels: size/medium

#6562 rustjail: Fix panic when cgroup manager fails
  src/agent/rustjail/src/cgroups/systemd/dbus_client.rs
  src/agent/rustjail/src/cgroups/systemd/manager.rs
Labels: needs-backport, area/agent, size/small

#6590 tools: Avoid building the kernel twice
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
Labels: size/tiny

#6607 gha: aks: Use D4s_v5 instance
  .github/workflows/create-aks.yaml
Labels: no-backport-needed, size/tiny

#6596 gha: Only push images to registry after merging a PR
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/publish-kata-deploy-payload-amd64.yaml
  .github/workflows/publish-kata-deploy-payload-arm64.yaml
  .github/workflows/publish-kata-deploy-payload-s390x.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: no-backport-needed, size/large

#6584 gha: Also run k8s tests on AKS with dragonball
  .github/workflows/run-k8s-tests-on-aks.yaml
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: no-backport-needed, size/tiny, ok-to-test

#6601 CC: Add cc-rootfs-initrd to payload image for s390x
  .github/workflows/cc-payload-after-push-s390x.yaml
Labels: no-backport-needed

#6612 gha: k8s-on-aks: Fix cluster name
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: no-backport-needed, size/tiny

#6569 CC | agent: add support for ttrpc + dependency on test PR
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/image_rpc.rs
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/cache_components.sh
  versions.yaml
Labels: size/tiny

#6602 CC | gha: add SNP components to amdx86_64 payload workflows
  .github/workflows/cc-payload-after-push-amd64.yaml
  .github/workflows/cc-payload-amd64.yaml
Labels: size/tiny

#6629 gha: k8s-on-aks: Set {create,delete}_aks as steps
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/publish-kata-deploy-payload-amd64.yaml
  .github/workflows/publish-kata-deploy-payload-arm64.yaml
  .github/workflows/publish-kata-deploy-payload-s390x.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: no-backport-needed, size/large

#6540 docs: update the rust version from version.yaml
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
Labels: size/tiny

#6631 gha: k8s-on-aks: {create,delete} AKS must be a coded-in step
  .github/workflows/create-aks.yaml
  .github/workflows/delete-aks.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: no-backport-needed, size/large

#6205 runtime: support non-root for clh
  docs/how-to/how-to-run-rootless-vmm.md
  src/runtime/config/configuration-clh.toml.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/qemu.go
Labels: no-backport-needed, size/tiny

#6522 tdx: Add artefacts from the latest TDX tools release into main
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/run-k8s-tests-on-tdx.yaml
  src/runtime/Makefile
  src/runtime/arch/amd64-options.mk
  src/runtime/config/configuration-qemu-tdx.toml.in
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/virtcontainers/hypervisor_linux_amd64.go
  src/runtime/virtcontainers/qemu_amd64.go
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
  tools/packaging/kernel/configs/fragments/x86_64/tdx/tdx.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/5.19-TDX-v2.x/no_patches.txt
  tools/packaging/qemu/patches/tag_patches/ad4c7f529a279685da84297773b4ec8080153c2d-plus-TDX-v1.3/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/cache_components_main.sh
  tools/packaging/static-build/ovmf/Dockerfile
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/qemu/build-static-qemu-experimental.sh
  versions.yaml
Labels: no-backport-needed, size/huge

#6618 runtime-rs/virtio-fs: add support extra handler for cache mode.
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
Labels: runtime-rs, size/tiny

#6617 CCv0: runtime: Use static_sandbox_resource_mgmt by default in remote hypervisor
  src/runtime/config/configuration-remote.toml.in
Labels: no-backport-needed

#6641 Backport cgroup fixes to 3.1
  src/agent/rustjail/src/cgroups/systemd/dbus_client.rs
  src/agent/rustjail/src/cgroups/systemd/manager.rs
  src/agent/rustjail/src/cgroups/systemd/subsystem/cpu.rs
Labels: backport, size/small

#6585 nydus_rootfs/prefetch_files: add prefetch_files for RAFS
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/crates/resource/src/rootfs/nydus_rootfs.rs
Labels: size/medium

#6653 backport: Don't create socket file in /run/kata to 3.1
  src/runtime/pkg/containerd-shim-v2/shim_management.go
  src/runtime/pkg/kata-monitor/pprof.go
  src/runtime/pkg/utils/shimclient/shim_management_client.go
Labels: size/tiny

#6658 osbuilder: Enable dbus in the dracut case
  tools/osbuilder/dracut/dracut.conf.d/05-base.conf
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: needs-backport, size/tiny, backport-to-stable-3.1

#6651 CCv0: update dependencies for CoCo release 0.5.0
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  versions.yaml
Labels: no-backport-needed, size/small

#6659 osbuilder: Enable dbus in the dracut case (backport for 3.1)
  tools/osbuilder/dracut/dracut.conf.d/05-base.conf
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: backport, size/tiny

#6661 Update deps for the v0.5.0 release of Confidential Containers
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  versions.yaml
Labels: no-backport-needed, size/small

#6633 versions: Upgrade to Cloud Hypervisor v31.0
  versions.yaml
Labels: no-backport-needed, size/tiny

#6648 gha: tdx: Ensure kata-deploy is removed after the tests run
  .github/workflows/run-k8s-tests-on-tdx.yaml
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime/config/configuration-acrn.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/virtcontainers/clh.go
  tests/integration/kubernetes/k8s-cpu-ns.bats
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: no-backport-needed, size/tiny

#6670 cache-components: Fix caching of TDVF and QEMU for TDX
  .github/workflows/run-k8s-tests-on-tdx.yaml
  tools/packaging/static-build/cache_components_main.sh
Labels: no-backport-needed, size/tiny

#6664 gpu: Do not pass-through PCI (Host) Bridges
  src/runtime/pkg/device/drivers/vfio.go
Labels: size/small

#6676 gpu: Add GPU enabled confguration and runtime
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-gpu.toml.in
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny

#6673 Bump ttrpc to 0.7.2 and protobuf to 3.2.0
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/mock.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/src/device.rs
  src/agent/src/mount.rs
  src/agent/src/netlink.rs
  src/agent/src/rpc.rs
  src/libs/Cargo.lock
  src/libs/protocols/.gitignore
  src/libs/protocols/Cargo.toml
  src/libs/protocols/build.rs
  src/libs/protocols/src/lib.rs
  src/libs/protocols/src/serde_config.rs
  src/libs/protocols/src/trans.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/common/src/types/trans_from_agent.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_into_shim.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/shim/Cargo.toml
  src/runtime-rs/crates/shim/src/shim_delete.rs
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Cargo.toml
  src/tools/agent-ctl/src/utils.rs
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/trace-forwarder/Cargo.lock
  src/tools/trace-forwarder/Cargo.toml
Labels: no-backport-needed, size/tiny

#6680 agent: Fix ut issue caused by fd double closed
  src/agent/src/main.rs
Labels: needs-backport, size/tiny, backport-to-stable-3.1

#6696 kata-manager: Fix containerd download
  utils/kata-manager.sh
Labels: highest-priority, force-skip-ci, size/tiny

#6620 snap: fix docker start fail issue
  snap/snapcraft.yaml
Labels: size/tiny

#6295 kata-ctl: checks for kvm, kvm_intel modules loaded
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/types.rs
Labels: no-backport-needed, size/tiny, kata-ctl

#6685 osbuilder: Fix D-Bus enabling in the dracut case (backport for 3.1)
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: backport

#6710 rustjail: Use CPUWeight with systemd and CgroupsV2
  src/agent/rustjail/src/cgroups/systemd/subsystem/cpu.rs
Labels: no-backport-needed, size/tiny

#6595 gpu: Build and Ship an GPU enabled Kernel
  .github/workflows/build-kata-static-tarball-amd64.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/README.md
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/gpu/nvidia.conf.in
  tools/packaging/kernel/kata_config_version
  tools/packaging/static-build/kernel/Dockerfile
  tools/packaging/static-build/kernel/build.sh
Labels: size/large

#6718 runtime-rs: support keep_abnormal in toml config
  src/libs/kata-types/src/config/runtime.rs
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/health_check.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: runtime-rs, size/small

#6660 Implement the "kata-ctl env" command
  .gitignore
  src/libs/kata-types/src/config/agent.rs
  src/libs/kata-types/src/config/default.rs
  src/libs/kata-types/src/config/mod.rs
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/Makefile
  src/tools/kata-ctl/src/arch/aarch64/mod.rs
  src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/kata-ctl/src/arch/x86_64/mod.rs
  src/tools/kata-ctl/src/args.rs
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/main.rs
  src/tools/kata-ctl/src/ops.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  src/tools/kata-ctl/src/ops/env_ops.rs
  src/tools/kata-ctl/src/ops/version.rs.in
  src/tools/kata-ctl/src/utils.rs
Labels: size/tiny

#6712 gha: Also run k8s tests on qemu-sev
  .github/workflows/ci-on-push.yaml
  .github/workflows/run-k8s-tests-on-sev.yaml
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: size/medium
