Repository kata-containers/kata-containers, pull requests merged in 2024-10, with the labels that each got.

#10374 tests: Skip k8s-block-volume.bats for qemu-runtime-rs
  tests/integration/kubernetes/k8s-block-volume.bats
Labels: size/tiny, ok-to-test

#10369 metrics: Update fast footprint script to use grep
  tests/metrics/density/fast_footprint.sh
Labels: area/metrics, size/tiny, ok-to-test

#10371 k8s: tests: Re-enable empty-dirs tests for TDX / coco-qemu-dev
  tests/integration/kubernetes/k8s-empty-dirs.bats
Labels: size/tiny, ok-to-test

#10165 runtime-rs: add network device hotplugging to qemu-rs
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
Labels: size/large, ok-to-test

#10375 k8s:kbs: Add trap statement to clean up tmp files
  tests/integration/kubernetes/confidential_kbs.sh
Labels: size/tiny, ok-to-test

#10134 ci.ocp: Sort images according to git
  ci/openshift-ci/bisect-range.sh
Labels: size/small, ok-to-test

#10381 osbuilder: Remove duplicated arch variable definition
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: size/tiny, ok-to-test

#9637 CI: Select jobs by touched code
  .github/workflows/ci-on-push.yaml
  .github/workflows/ci.yaml
  .github/workflows/gatekeeper-skipper.yaml
  .github/workflows/gatekeeper.yaml
  .github/workflows/static-checks-self-hosted.yaml
  .github/workflows/static-checks.yaml
  tools/testing/gatekeeper/jobs.py
  tools/testing/gatekeeper/required-tests.yaml
  tools/testing/gatekeeper/skips.py
Labels: force-skip-ci, size/huge, ok-to-test

#10376 gha: enable AUTO_GENERATE_POLICY where needed
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-kata-coco-tests.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: size/small, ok-to-test

#10384 tests: k8s: AUTO_GENERATE_POLICY=yes for local testing
  tests/integration/kubernetes/tests_common.sh
Labels: size/small, ok-to-test

#10389 build: Fix RPM build fail due to AGENT_POLICY
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: ok-to-test

#10383 image-builder: Remove unused variable
  tools/osbuilder/image-builder/image_builder.sh
Labels: size/tiny, ok-to-test

#10363 Support Confidential Sealed Secrets (as volume)
  src/agent/src/cdh.rs
  src/agent/src/main.rs
  src/agent/src/rpc.rs
  tests/integration/kubernetes/k8s-sealed-secret.bats
  tests/integration/kubernetes/runtimeclass_workloads/pod-sealed-secret-as-file.yaml
Labels: size/large, ok-to-test

#10390 local-build: add ability to build rootfs-image-mariner
  .github/workflows/build-kata-static-tarball-amd64.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  versions.yaml
Labels: size/small, ok-to-test

#10388 tools/osbuilder/tests: Add trap statement in test images script
  tools/osbuilder/tests/test_images.sh
Labels: size/tiny, ok-to-test

#10404 Revert "agent:cdh: unittest for sealed secret as file"
  src/agent/src/cdh.rs
Labels: size/medium, ok-to-test

#10407 packaging: Remove unused variable in build kernel script
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
Labels: size/tiny, ok-to-test

#10397 build: mariner: Remove the ability to build the marine initrd
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  versions.yaml
Labels: size/small, ok-to-test

#10401 Kbs deploy overlays update
  tests/integration/kubernetes/confidential_kbs.sh
  versions.yaml
Labels: size/small, ok-to-test

#10406 agent:cdh: fix unit tests about sealed secret
  src/agent/src/cdh.rs
Labels: size/medium, ok-to-test

#10409 kbs: ita: Ensure the proper image / image_tag is used for ITA
  tests/integration/kubernetes/confidential_kbs.sh
  versions.yaml
Labels: size/tiny, ok-to-test

#10415 tools/osbuilder/tests: Remove egrep in test images script
  tools/osbuilder/tests/test_images.sh
Labels: size/tiny, ok-to-test

#10402 ci: Install build dependencies for building agent-ctl with image pull.
  .github/workflows/build-checks.yaml
  tools/packaging/static-build/tools/Dockerfile
Labels: size/tiny, ok-to-test

#10426 genpolicy: read binaryData value as String
  src/tools/genpolicy/src/config_map.rs
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-configmap.yaml
Labels: size/tiny, ok-to-test

#10416 ci: static_sandbox_resource_mgmt for cbl-mariner
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#10417 tests: k8s-inotify.bats improvements
  tests/integration/kubernetes/k8s-inotify.bats
Labels: size/small, ok-to-test

#10412 agent: config: Use rstest for unit tests
  src/agent/src/config.rs
Labels: size/huge, ok-to-test

#10430 docs: Update CI documentation
  ci/README.md
Labels: force-skip-ci, size/small

#10435 runtime-rs: Use vCPU and memory values from config
  src/runtime-rs/crates/hypervisor/src/firecracker/fc_api.rs
Labels: size/tiny, ok-to-test

#10433 ci: add provenance attestation for agent artifact
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/large, ok-to-test

#10437 ci: don't parse oci image for cached artifacts
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: force-skip-ci, size/small

#10421 kata-agent: fixing bug of unable setting hostname correctly.
  src/agent/src/rpc.rs
  tests/integration/kubernetes/k8s-hostname.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/pod-hostname.yaml
Labels: size/medium, ok-to-test

#10420 runtime-rs: support virtio-scsi device in qemu-rs
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
Labels: size/medium, ok-to-test

#10443 release: Bump VERSION to 3.10.0
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: size/tiny, ok-to-test

#10439 tools: Change PACKAGES var for cbl-mariner
  tools/osbuilder/rootfs-builder/cbl-mariner/config.sh
Labels: size/tiny, ok-to-test

#10446 workflows: Ensure shim-v2 is built as the last asset
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: size/large

#10208 runtime: Failed to clean up resources when QEMU is terminated
  src/runtime/virtcontainers/qemu.go
Labels: size/small, ok-to-test

#10438 docs: Fix misspelling in CI documentation
  ci/README.md
Labels: force-skip-ci, size/tiny

#10452 tests: Add trap statement in kata doc script
  tests/kata-doc-to-script.sh
Labels: size/tiny, ok-to-test

#10461 workflows: devel: Follow-up on the manually triggered jobs
  .github/workflows/ci-devel.yaml
Labels: size/tiny

#10463 agent: Correct rustjail device filemode permission typo
  src/agent/rustjail/src/container.rs
Labels: size/small, ok-to-test

#10467 release: Bump version to 3.10.1
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: size/tiny, ok-to-test

#10471 workflows: Possibly fix the release workflow
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: force-skip-ci, size/tiny

#10466 re-enable measured rootfs build & tests
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-coco-dev.toml.in
  tests/gha-adjust-to-use-prebuilt-components.sh
  tests/integration/kubernetes/k8s-measured-rootfs.bats
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/shim-v2/build.sh
Labels: size/large, ok-to-test

#10473 build: cache: Ensure shim-v2-root_hash.txt is in "${workdir}"
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny, ok-to-test

#10074 runtime: log vm start error before cleanup
  src/runtime/virtcontainers/sandbox.go
Labels: size/tiny, ok-to-test

#10475 Revert "tests: Add trap statement in kata doc script"
  tests/kata-doc-to-script.sh
Labels: size/tiny, ok-to-test

#10462 tests: Increase time to run stressng k8s tests
  tests/stability/kubernetes_stressng.sh
Labels: ok-to-test

#10474 packaging: Remove kernel config repo variable as it is unused
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
Labels: size/tiny, ok-to-test

#10476 gha: Switch KUBERNETES from k3s to kubeadm on s390x
  .github/workflows/run-k8s-tests-on-zvsi.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: size/small, ok-to-test

#10425 genpolicy: support darwin target
  src/agent/Cargo.lock
  src/libs/Cargo.lock
  src/libs/kata-sys-util/Cargo.toml
  src/libs/kata-sys-util/README.md
  src/libs/kata-sys-util/src/spec.rs
  src/libs/protocols/Cargo.toml
  src/libs/protocols/src/trans.rs
  src/runtime-rs/Cargo.lock
  src/tools/agent-ctl/Cargo.lock
  src/tools/genpolicy/Cargo.lock
  src/tools/kata-ctl/Cargo.lock
  src/tools/runk/Cargo.lock
Labels: size/huge, ok-to-test
