Repository kata-containers/kata-containers, pull requests merged in 2024-04, with the labels that each got.

#9345 agent: Fix errors in `make check`
  src/agent/rustjail/src/mount.rs
  src/agent/src/mount.rs
  src/agent/src/rpc.rs
  src/agent/src/signal.rs
Labels: size/small, ok-to-test

#9358 gha: Update journal log names for nerdctl artifacts
  tests/integration/nerdctl/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#9275 kata-agent: Change order of guest hook and bind mount processing
  src/agent/src/rpc.rs
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#9365 versions: Remove runc version information
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, ok-to-test

#9397 versions: Remove conmon information from versions.yaml
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#9409 gha: Define GH_PR_NUMBER variable in gha run k8s common script
  tests/gha-run-k8s-common.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#9411 tests: k8s-job: wait for job successful create
  tests/integration/kubernetes/k8s-job.bats
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#9413 gha: ensure unique resource group name
  tests/gha-run-k8s-common.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8782 bugfix and refactor device increate count
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_blk.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
  src/runtime-rs/crates/hypervisor/src/device/util.rs
Labels: no-backport-needed, size/large, ok-to-test

#8840 tdx: Update TDX artefacts to be used with the Ubuntu 23.10 / CentOS 9 stream OSVs.
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
  src/runtime/virtcontainers/hypervisor_linux_amd64.go
  src/runtime/virtcontainers/qemu.go
  tools/packaging/qemu/patches/tag_patches/tdx-qemu-next-2023.9.21-v8.1.0/no_patches.txt
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/qemu/Dockerfile
  versions.yaml
Labels: size/large, ok-to-test

#9273 tests: Support for kbs setup on kcli
  tests/integration/kubernetes/confidential_kbs.sh
Labels: size/small, ok-to-test

#9419 metrics: Improve latency test cleanup
  tests/metrics/network/latency_kubernetes/latency-network.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#9415 GHA: Implement secondary GITHUB_WORKSPACE cleanup on 1st failure
  .github/workflows/build-checks.yaml
Labels: no-backport-needed, size/tiny, ok-to-test

#9372 docs: kata-manager: Update with latest details
  utils/README.md
Labels: size/large, ok-to-test

#8870 port attestation agent from CCv0 branch to main branch
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/README.md
  src/agent/src/config.rs
  src/agent/src/main.rs
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/confidential_kbs.sh
  tests/integration/kubernetes/filter_out_per_arch/aarch64.yaml
  tests/integration/kubernetes/filter_out_per_arch/ppc64le.yaml
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/k8s-confidential-attestation.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/pod-attestable.yaml
  tools/packaging/static-build/coco-guest-components/Dockerfile
  tools/packaging/static-build/coco-guest-components/build.sh
  versions.yaml
Labels: size/large, ok-to-test

#9369 agent:image: Support different pause image in the guest for guest pull
  src/agent/src/image.rs
Labels: size/medium, ok-to-test

#9421 gha: Bump various actions to use Node.js 20
  .github/workflows/basic-ci-amd64.yaml
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/ci.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/publish-kata-deploy-payload-amd64.yaml
  .github/workflows/publish-kata-deploy-payload-arm64.yaml
  .github/workflows/publish-kata-deploy-payload-ppc64le.yaml
  .github/workflows/publish-kata-deploy-payload-s390x.yaml
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/release.yaml
  .github/workflows/run-cri-containerd-tests-ppc64le.yaml
  .github/workflows/run-cri-containerd-tests-s390x.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-garm.yaml
  .github/workflows/run-kata-monitor-tests.yaml
  .github/workflows/run-metrics.yaml
  .github/workflows/run-runk-tests.yaml
Labels: size/large

#8988 docs: adding an initial CI documentation
  ci/README.md
  docs/README.md
  tests/cmd/check-spelling/kata-dictionary.dic
Labels: no-backport-needed, size/large, ok-to-test

#9185 genpolicy: Add optional toggle to pull images using containerd
  .github/workflows/build-checks.yaml
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/genpolicy-advanced-command-line-parameters.md
  src/tools/genpolicy/src/config_map.rs
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/job.rs
  src/tools/genpolicy/src/list.rs
  src/tools/genpolicy/src/main.rs
  src/tools/genpolicy/src/no_policy.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
  src/tools/genpolicy/src/replica_set.rs
  src/tools/genpolicy/src/replication_controller.rs
  src/tools/genpolicy/src/secret.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/src/yaml.rs
  tests/integration/kubernetes/filter_out_per_arch/aarch64.yaml
  tests/integration/kubernetes/filter_out_per_arch/ppc64le.yaml
  tests/integration/kubernetes/filter_out_per_arch/s390x.yaml
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/k8s-pod-manifest-v1.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/pod-manifest-v1.yaml
  tests/integration/kubernetes/tests_common.sh
Labels: no-backport-needed, no-forward-port-needed, size/huge, ok-to-test

#9391 add onednn and openvino ml-benchmarks
  tests/metrics/lib/common.bash
  tests/metrics/machine_learning/onednn-dockerfile/Dockerfile
  tests/metrics/machine_learning/onednn.sh
  tests/metrics/machine_learning/openvino-dockerfile/Dockerfile
  tests/metrics/machine_learning/openvino.sh
Labels: no-backport-needed, no-forward-port-needed, area/metrics, size/large, ok-to-test

#9450 gha: Fix indentation in gha run script
  tests/integration/kubernetes/gha-run.sh
Labels: size/tiny, ok-to-test

#9423 tests: Improve the kbs_k8s_delete function
  tests/integration/kubernetes/confidential_kbs.sh
Labels: area/confidential-containers, size/tiny, ok-to-test

#9439 tests: k8s: inject agent policy failures
  tests/integration/kubernetes/k8s-policy-job.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-job.yaml
  tests/integration/kubernetes/tests_common.sh
Labels: size/large, ok-to-test

#9424 CC: run guest-pull tests on non-TEE jobs
  .github/workflows/run-kata-coco-tests.yaml
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/k8s-guest-pull-image.bats
Labels: area/ci, area/confidential-containers, size/medium, ok-to-test

#9454 gha: Define unbound PULL TYPE variable
  tests/integration/kubernetes/gha-run.sh
Labels: size/tiny, ok-to-test

#9430 agent: shutdown vm on exit when agent is used as init process
  src/agent/src/main.rs
Labels: size/small, ok-to-test

#9403 CI: Enable GHA cri-containerd workflow for runtime-rs with QEMU
  .github/workflows/basic-ci-amd64.yaml
  .github/workflows/run-cri-containerd-tests-s390x.yaml
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in
  tests/common.bash
  tests/integration/cri-containerd/integration-tests.sh
Labels: runtime-rs, size/small, ok-to-test

#9469 kernel: Adjust s390x config for confidential containers
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/kernel/kata_config_version
Labels: size/tiny, ok-to-test

#9404 ci.ocp: Increase the MCP update time
  ci/openshift-ci/cluster/install_kata.sh
Labels: size/tiny, ok-to-test

#9471 version: Add coco name and version for {image,initrd} for s390x
  versions.yaml
Labels: size/tiny, ok-to-test

#9479 gha: make run-kata-coco-tests inherit secrets
  .github/workflows/ci.yaml
Labels: area/ci, area/confidential-containers, size/tiny, ok-to-test

#9353 runtime-rs: refactor qemu driver
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/hypervisor/src/qemu/network.rs
  src/runtime-rs/crates/hypervisor/src/utils.rs
Labels: size/huge, ok-to-test

#9464 tests: k8s: inject agent policy failures (part2)
  tests/integration/kubernetes/k8s-policy-rc.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-rc.yaml
Labels: size/large, ok-to-test

#9294 genpolicy: support insecure registries and custom pause containers
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/settings.rs
  src/tools/genpolicy/src/utils.rs
Labels: size/medium, ok-to-test

#9084 docs: Document Intel Discrete GPUs usage with Kata
  docs/hypervisors.md
  docs/use-cases/GPU-passthrough-and-Kata.md
  docs/use-cases/Intel-Discrete-GPU-passthrough-and-Kata.md
  tests/cmd/check-spelling/data/acronyms.txt
  tests/cmd/check-spelling/data/main.txt
  tests/cmd/check-spelling/kata-dictionary.dic
Labels: size/large, ok-to-test

#9473 version: add initrd, image NVIDIA sections
  versions.yaml
Labels: size/small, ok-to-test

#9492 tests: k8s: inject agent policy failures (part 3)
  tests/integration/kubernetes/k8s-policy-pod.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-configmap.yaml
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
Labels: size/large, ok-to-test

#9489 rootfs: Make OPA build working in docker for s390x and pp…
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/scripts/lib.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small, ok-to-test

#9505 gha: Remove k8s-cri-containerd-rhel9-e2e-tests for s390x
  .github/workflows/ci-nightly-s390x.yaml
Labels: size/small, ok-to-test

#9503 gha: stale: Remove the start-date
  .github/workflows/stale.yaml
Labels: force-skip-ci, size/tiny, ok-to-test

#9508 gha: Make integration tests for s390x run on s390x-large runners
  .github/workflows/run-cri-containerd-tests-s390x.yaml
  .github/workflows/run-k8s-tests-on-zvsi.yaml
Labels: size/tiny, ok-to-test

#9501 kata: Remove check for "Fixes" in PR
  .github/workflows/commit-message-check.yaml
  .github/workflows/move-issues-to-in-progress.yaml
Labels: size/small, ok-to-test

#9516 release: bump version for 3.4.0 release
  VERSION
Labels: size/tiny, ok-to-test

#9513 gha: stale: Bump stalebot version
  .github/workflows/stale.yaml
Labels: force-skip-ci, size/tiny, ok-to-test

#9521 gha: tag k8s tests on ppc64le to ppc64le-runner-01
  .github/workflows/run-k8s-tests-on-ppc64le.yaml
Labels: ok-to-test

#9490 gha: move attestation tests to run-k8s-tests-coco-nontee
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-kata-coco-tests.yaml
Labels: area/ci, area/confidential-containers, size/small, ok-to-test

#9518 agent: update cargo.lock
  src/agent/Cargo.lock
Labels: size/small, ok-to-test

#9517 runtime-rs: Update storage source for pci block devices
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
Labels: size/small, ok-to-test

#9335 passfd-io: fix FIFO opening and vsock handling
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/process.rs
  src/agent/src/rpc.rs
  src/dragonball/src/dbs_virtio_devices/src/vsock/csm/connection.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/passfd_io.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/shim_io.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
Labels: size/large, ok-to-test

#9494 CC: Enable guest-pull tests on non-TEE for s390x
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/run-k8s-tests-on-zvsi.yaml
  docs/how-to/how-to-run-kata-containers-with-SE-VMs.md
  tools/packaging/guest-image/build_se_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
Labels: size/medium, ok-to-test

#9432 clh: isClhRunning waits for full timeout when clh exits
  src/runtime/virtcontainers/clh.go
Labels: size/tiny, ok-to-test

#9535 kata-deploy: Stop append `log_level = "debug"` for CRI-O
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#9428 genpolicy: implement default methods for K8sResource trait
  src/tools/genpolicy/src/config_map.rs
  src/tools/genpolicy/src/list.rs
  src/tools/genpolicy/src/no_policy.rs
  src/tools/genpolicy/src/secret.rs
  src/tools/genpolicy/src/yaml.rs
Labels: size/large, ok-to-test

#9510 agent: use regorus instead of opa
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/main.rs
  src/agent/src/policy.rs
  tests/integration/kubernetes/k8s-policy-job.bats
  tests/integration/kubernetes/k8s-policy-pod.bats
  tests/integration/kubernetes/k8s-policy-rc.bats
  tests/integration/kubernetes/k8s-policy-set-keys.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/tests_common.sh
Labels: size/huge, ok-to-test

#9525 gha: Enable k8s tests for cloud hypervisor with devicemapper
  tests/integration/kubernetes/gha-run.sh
Labels: safe-to-test, size/small, ok-to-test

#9549 build: Fix tarball not building correctly in docker
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Labels: size/tiny, ok-to-test

#9530 genpolicy: changing caching so the tool can run concurrently with itself
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
Labels: size/large, ok-to-test

#9519 runtime-rs: Add RTC to QEMU cmdline
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
Labels: size/small, ok-to-test

#9528 doc: fix missing document link
  docs/install/README.md
Labels: force-skip-ci, size/tiny, ok-to-test

#9562 build: Update golang version to 1.22.2
  .github/workflows/darwin-tests.yaml
  .github/workflows/docs-url-alive-check.yaml
  tests/.golangci.yml
  versions.yaml
Labels: size/small, ok-to-test

#9559 rootfs: Stop building and shipping OPA
  src/kata-opa/kata-opa.service.in
  tools/osbuilder/rootfs-builder/cbl-mariner/config.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/scripts/lib.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  versions.yaml
Labels: size/large, ok-to-test

#9551 runtime-rs: support IOMMU in qemu VMs
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
Labels: size/large, ok-to-test

#9570 workflow: static-checks: Skip commit checks for dependabout
  .github/workflows/commit-message-check.yaml
Labels: force-skip-ci, size/tiny, ok-to-test

#9552 runtime: new qemu-coco-dev configuration
  .github/workflows/run-kata-coco-tests.yaml
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-coco-dev.toml.in
  tests/integration/kubernetes/confidential_common.sh
  tests/integration/kubernetes/k8s-confidential-attestation.bats
  tests/integration/kubernetes/k8s-guest-pull-image.bats
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-qemu-coco-dev.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
Labels: size/huge, ok-to-test
