Repository kata-containers/kata-containers, pull requests merged in 2024-12, with the labels that each got.

#10595 gatekeeper: add run-k8s-tests-on-zvsi(devmapper) to required jobs
  tools/testing/gatekeeper/required-tests.yaml
Labels: size/tiny, ok-to-test

#10590 ci: Fix variant for confidential targets
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny, ok-to-test

#10609 ci: Fix Docker publishing for CSI driver
  .github/workflows/ci.yaml
Labels: force-skip-ci, size/tiny

#10592 policy: add constants to rules.rego
  src/tools/genpolicy/rules.rego
Labels: size/small, ok-to-test

#10608 policy: ignore optional metadata uid field
  src/tools/genpolicy/src/obj_meta.rs
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
Labels: size/tiny, ok-to-test

#10612 ci: Fix Docker publishing for CSI driver, 2nd try
  .github/workflows/ci.yaml
Labels: force-skip-ci, size/tiny

#10563 coco: ci: Fully implement compilation of CSI driver and require it for CoCo tests [2/x]
  .github/workflows/ci.yaml
  src/tools/csi-kata-directvolume/.gitignore
  src/tools/csi-kata-directvolume/release-tools/build.make
  src/tools/csi-kata-directvolume/release-tools/verify-go-version.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/tools/.gitignore
  tools/packaging/static-build/tools/Dockerfile
  tools/packaging/static-build/tools/build.sh
Labels: size/medium, ok-to-test

#10574 Add subchannel support to qemu-runtime-rs for s390x
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
Labels: size/large, ok-to-test

#10604 genpolicy: align state path getter and setter
  src/tools/genpolicy/rules.rego
Labels: size/tiny, ok-to-test

#10607 runtime: skip logging some of the dial errors
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
Labels: size/small, ok-to-test

#10588 metrics: Increase minval range for failing tests
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: size/small, ok-to-test

#10617 tests: Skip k8s job test on qemu-coco-dev
  tests/integration/kubernetes/k8s-job.bats
Labels: size/tiny, ok-to-test

#10572 ci.gatekeeper: Update existing results
  tools/testing/gatekeeper/jobs.py
Labels: size/tiny, ok-to-test

#10551 kata-deploy: Add support to multi-installation
  tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-deploy.yaml
  tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-rbac.yaml
  tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/post-delete-job.yaml
  tools/packaging/kata-deploy/helm-chart/kata-deploy/values.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/kata-rbac/base/kata-rbac.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/large, ok-to-test

#10627 release: helm: Add the chart as part of the release
  .github/workflows/release.yaml
  tools/packaging/release/release.sh
Labels: force-skip-ci, size/small

#10548 runtime: Set memory config shared=false when shared_fs=None in CLH.
  src/runtime/virtcontainers/clh.go
Labels: size/small, ok-to-test

#10631 Action lint workflow
  .github/actionlint.yaml
  .github/workflows/actionlint.yaml
  .github/workflows/add-issues-to-project.yaml
  .github/workflows/add-pr-sizing-label.yaml
  .github/workflows/build-checks.yaml
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/cargo-deny-runner.yaml
  .github/workflows/ci-nightly-s390x.yaml
  .github/workflows/ci-weekly.yaml
  .github/workflows/darwin-tests.yaml
  .github/workflows/docs-url-alive-check.yaml
  .github/workflows/kata-runtime-classes-sync.yaml
  .github/workflows/move-issues-to-in-progress.yaml
  .github/workflows/publish-kata-deploy-payload-amd64.yaml
  .github/workflows/publish-kata-deploy-payload-arm64.yaml
  .github/workflows/publish-kata-deploy-payload-ppc64le.yaml
  .github/workflows/publish-kata-deploy-payload-s390x.yaml
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/run-cri-containerd-tests-ppc64le.yaml
  .github/workflows/run-k8s-tests-on-amd64.yaml
  .github/workflows/run-k8s-tests-on-ppc64le.yaml
  .github/workflows/run-k8s-tests-on-zvsi.yaml
  .github/workflows/run-kata-coco-stability-tests.yaml
  .github/workflows/run-kata-coco-tests.yaml
  .github/workflows/static-checks.yaml
  src/runtime/pkg/govmm/.github/workflows/main.yml
Labels: force-skip-ci, size/large

#10593 policy: improve pod namespace validation
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/policy.rs
  tests/integration/kubernetes/k8s-limit-range.bats
  tests/integration/kubernetes/tests_common.sh
Labels: size/medium, ok-to-test

#10581 Revert "ci: Skip the failing tests in SNP"
  tests/integration/kubernetes/k8s-confidential-attestation.bats
  tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
  tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
  tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
Labels: ok-to-test

#10638 runtime-rs: Fix the issues with stderr fifo
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
Labels: size/tiny, ok-to-test

#10641 runtime-rs: Ignore BUILD_TYPE if it is not release
  src/runtime-rs/Makefile
Labels: size/tiny, ok-to-test

#10643 runtime-rs & agent: Fix the issues with bind volumes
  src/agent/rustjail/src/mount.rs
  src/libs/kata-sys-util/src/mount.rs
  src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
  src/runtime-rs/crates/resource/src/volume/direct_volume.rs
  src/runtime-rs/crates/resource/src/volume/direct_volumes/spdk_volume.rs
  src/runtime-rs/crates/resource/src/volume/direct_volumes/vfio_volume.rs
  src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
  src/runtime-rs/crates/resource/src/volume/shm_volume.rs
Labels: size/small, ok-to-test

#10492 qemu: Upgrade qemu 9.1.2
  tools/packaging/qemu/patches/9.1.x/no_patches.txt
  tools/packaging/qemu/patches/tag_patches/v9.1.2/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/static-build/qemu/Dockerfile
  tools/packaging/static-build/qemu/build-base-qemu.sh
  tools/packaging/static-build/qemu/build-qemu.sh
  versions.yaml
Labels: size/medium, ok-to-test

#10660 vfio-ap: Assign default string "0" for empty APID and APQI
  tests/functional/vfio-ap/run.sh
Labels: size/tiny, ok-to-test

#10655 kata-ctl: fix outdated comments
  src/tools/kata-ctl/src/ops/exec_ops.rs
Labels: size/tiny, ok-to-test

#10663 release: Bump version to 3.12.0
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: size/tiny, ok-to-test

#10669 qemu: Fix aarch64 build
  tools/packaging/scripts/configure-hypervisor.sh
Labels: size/tiny, ok-to-test

#10620 workflows: Remove potential timing issues with artifacts
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: force-skip-ci, size/small

#10675 release: Abort if release version exists
  tools/packaging/release/release.sh
Labels: force-skip-ci, size/tiny

#10668 doc: Update the release process
  docs/Release-Process.md
Labels: size/tiny, ok-to-test

#9387 packaging: fix the broken usage help
  tools/packaging/guest-image/build_image.sh
  tools/packaging/guest-image/build_se_image.sh
Labels: size/small, ok-to-test

#10676 tests: Fix qemu-coc-dev skip
  tests/integration/kubernetes/k8s-job.bats
Labels: size/tiny, ok-to-test

#10380 doc: Add required jobs info
  ci/README.md
  tests/cmd/check-spelling/kata-dictionary.dic
Labels: size/medium, ok-to-test

#10685 workflows: Add timeout to some ppc64le steps
  .github/workflows/run-cri-containerd-tests-ppc64le.yaml
Labels: force-skip-ci, size/tiny

#10686 workflows: Add more ppc64le timeouts
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/publish-kata-deploy-payload-ppc64le.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/run-k8s-tests-on-ppc64le.yaml
Labels: force-skip-ci, size/tiny

#10683 runtime-rs: Remove unneeded `mut` from `new_hypervisor()`
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/firecracker/mod.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/hypervisor/src/remote/mod.rs
  src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
Labels: size/small, ok-to-test
