Repository kata-containers/kata-containers, pull requests merged in 2024-11, with the labels that each got.

#10442 ci: Use ubuntu for static building of kata tools.
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-copy-libseccomp-installer.sh
  tools/packaging/static-build/tools/Dockerfile
  tools/packaging/static-build/tools/build-static-tools.sh
  tools/packaging/static-build/tools/build.sh
Labels: size/medium, ok-to-test

#10453 runtime: Add GPU annotations for remote hypervisor
  docs/how-to/how-to-set-sandbox-config-kata.md
  src/runtime/config/configuration-remote.toml.in
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/remote.go
Labels: size/medium, ok-to-test, area/gpu

#10481 agent: perform attestation init w/o process launch
  src/agent/src/main.rs
Labels: size/medium, ok-to-test

#10485 gha: Fix source for gha stability run script
  tests/stability/gha-stability-run.sh
Labels: force-skip-ci, size/tiny

#10395 agent-ctl: Add support to test kata-agent's container creation APIs.
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Cargo.toml
  src/tools/agent-ctl/src/client.rs
  src/tools/agent-ctl/src/image.rs
  src/tools/agent-ctl/src/main.rs
  src/tools/agent-ctl/src/types.rs
  src/tools/agent-ctl/src/utils.rs
  src/tools/agent-ctl/template/oci_config.json
  tests/functional/kata-agent-apis/api-tests/test_create_container.bats
  tests/functional/kata-agent-apis/setup_common.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/huge, ok-to-test

#10459 tests: k8s: Update bats
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/confidential_kbs.sh
  tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
  tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
  tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
  tests/integration/kubernetes/k8s-guest-pull-image.bats
  tests/integration/kubernetes/k8s-liveness-probes.bats
  tests/integration/kubernetes/k8s-measured-rootfs.bats
  tests/integration/kubernetes/k8s-sealed-secret.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: size/small, ok-to-test

#10490 builds: ovmf: Workaround Zeex repo becoming private
  tools/packaging/static-build/ovmf/build-ovmf.sh
Labels: size/tiny, ok-to-test

#9480 image: Add suffix to image or initrd depending on the NVIDIA driver version
  tools/packaging/guest-image/build_image.sh
Labels: size/small, ok-to-test

#10488 build: kernel: Teach our machinery to deal with -rc kernels
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
  versions.yaml
Labels: size/large, ok-to-test

#10491 agent: fix typo on getting EphemeralHandler size option
  src/agent/src/storage/ephemeral_handler.rs
Labels: size/tiny, ok-to-test

#10496 ci: export CONTAINER_RUNTIME to the test scripts
  .github/workflows/run-k8s-tests-on-amd64.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: size/tiny

#10495 ci: skip nginx connectivity test with qemu/crio
  tests/integration/kubernetes/k8s-nginx-connectivity.bats
Labels: size/tiny, ok-to-test

#10486 workflows: Use AUTO_GENERATE_POLICY for qemu-coco-dev
  .github/workflows/ci.yaml
  .github/workflows/run-kata-coco-tests.yaml
  src/runtime/config/configuration-qemu-coco-dev.toml.in
  tests/integration/kubernetes/tests_common.sh
Labels: size/small

#10493 gha: Add install kata tools as part of the stability workflow
  .github/workflows/run-kata-coco-stability-tests.yaml
  tests/stability/gha-stability-run.sh
Labels: force-skip-ci, size/tiny

#10500 runtime: Files are not synced between host and guest VMs
  src/runtime/virtcontainers/fs_share_linux.go
Labels: size/tiny, ok-to-test

#9584 kata-agent: Add CDI support
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/device/mod.rs
  src/agent/src/rpc.rs
Labels: size/large, ok-to-test, area/gpu

#10505 metrics: Skip metrics on stratovirt
  .github/workflows/run-metrics.yaml
Labels: force-skip-ci, size/tiny

#10506 workflow: Remove/skip runk CI
  .github/workflows/basic-ci-amd64.yaml
  .github/workflows/build-checks.yaml
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/run-runk-tests.yaml
Labels: force-skip-ci, size/small

#10498 tests: k8s: Update image pull timeout error
  tests/integration/kubernetes/k8s-guest-pull-image.bats
Labels: size/tiny, ok-to-test

#10517 tests: remove manifest v1 test
  tests/integration/kubernetes/filter_out_per_arch/aarch64.yaml
  tests/integration/kubernetes/filter_out_per_arch/ppc64le.yaml
  tests/integration/kubernetes/filter_out_per_arch/s390x.yaml
  tests/integration/kubernetes/k8s-pod-manifest-v1.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/pod-manifest-v1.yaml
Labels: size/medium, ok-to-test

#10513 ci: tdx: kbs: Ensure https_proxy is taken in consideration
  tests/integration/kubernetes/confidential_kbs.sh
Labels: size/small, ok-to-test

#10515 gha: Hardcode ubuntu-22.04 instead of latest
  .github/workflows/ci-weekly.yaml
  .github/workflows/gatekeeper-skipper.yaml
  .github/workflows/gatekeeper.yaml
  .github/workflows/run-kata-coco-stability-tests.yaml
  src/runtime/pkg/govmm/.github/workflows/main.yml
Labels: ok-to-test

#10508 gha: Get artifacts when installing kata tools in stability workflow
  .github/workflows/run-kata-coco-stability-tests.yaml
  tests/stability/gha-stability-run.sh
Labels: force-skip-ci, size/tiny

#10539 ci: Temporarily skip SNP CI
  .github/workflows/run-kata-coco-tests.yaml
Labels: force-skip-ci, size/tiny

#10521 osbuilder: remove redundant env variable
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
Labels: size/tiny, ok-to-test

#10431 genpolicy: add state to policy
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/policy.rs
  src/tools/genpolicy/rules.rego
Labels: size/large, ok-to-test

#9195 runtime: Set maxvcpus equal to vcpus for the static resources case
  src/runtime/pkg/oci/utils.go
Labels: size/tiny, ok-to-test

#10542 kernel: add CONFIG_KEYS=y to enable kernel keyring
  tools/packaging/kernel/configs/fragments/common/base.conf
  tools/packaging/kernel/kata_config_version
Labels: size/tiny, ok-to-test

#10514 agent: overwrite OCI process spec when overwriting pause image
  src/agent/src/image.rs
  src/agent/src/rpc.rs
Labels: size/medium, ok-to-test

#10545 runtime: fix comment to accurately reflect clh behavior
  src/runtime/virtcontainers/clh.go
Labels: size/tiny, ok-to-test

#10552 release: Bump version to 3.11.0
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: size/tiny, ok-to-test

#10558 ci: Re-enable SNP CI
  .github/workflows/run-kata-coco-tests.yaml
  tests/integration/kubernetes/k8s-confidential-attestation.bats
  tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
  tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
  tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
Labels: size/small, ok-to-test

#10447 ci: Required jobs
  tools/testing/gatekeeper/required-tests.yaml
Labels: size/large, ok-to-test

#10520 osbuilder: Drop Clear Linux
  docs/Developer-Guide.md
  docs/design/architecture/guest-assets.md
  tools/osbuilder/README.md
  tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
  tools/osbuilder/rootfs-builder/clearlinux/config.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/tests/test_config.sh
Labels: size/medium, ok-to-test

#10464 gpu: NVIDIA GPU initrd/image build
  tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/huge, ok-to-test, area/gpu

#10386 docs: Fix several build failures when I tried the procedures in "Kata Containers with AMD SEV-SNP VMs"
  docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md
Labels: size/small, ok-to-test

#10516 ci: Fix error on self-hosted machines
  src/agent/src/device/mod.rs
Labels: size/small, ok-to-test

#10543 genpolicy: avoid regorus warning
  src/tools/genpolicy/rules.rego
Labels: size/tiny, ok-to-test

#10577 runtime-rs: fix vfio device name combination issue
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
Labels: size/tiny, ok-to-test

#10584 kata-deploy: Support containerd configuration version 3
  tools/packaging/kata-deploy/kata-deploy/overlays/k0s/mount_k0s_conf.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/small, ok-to-test

#10586 workflows: Remove rootfs binary artifacts
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: force-skip-ci, size/medium

#10561 coco: ci: Lay groundwork for compiling and publishing CSI driver image [1/x]
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/ci.yaml
  .github/workflows/publish-csi-driver-amd64.yaml
  .github/workflows/run-kata-coco-tests.yaml
  tests/integration/kubernetes/gha-run.sh
  tools/packaging/kata-deploy/local-build/Makefile
Labels: force-skip-ci, size/large, ok-to-test

#10564 runtime: clh: addNet() logging clean-up
  src/runtime/virtcontainers/clh.go
Labels: size/tiny, ok-to-test

#10589 gha: Unbreak CI and work around workflow limit
  .github/workflows/ci.yaml
  .github/workflows/publish-csi-driver-amd64.yaml
Labels: force-skip-ci, size/large

#10594 ci: unbreak: Reallow no-op builds
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: force-skip-ci, size/small

#10597 Unbreak the CI, 3rd attempt
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small
