Repository kata-containers/kata-containers, pull requests merged in 2024-06, with the labels that each got.

#9749 CoCo: introduce config for guest-components procs
  src/agent/README.md
  src/agent/src/config.rs
  src/agent/src/main.rs
Labels: size/large, ok-to-test

#9377 deps: bumping yq to v4.40.7
  .github/workflows/build-checks.yaml
  ci/install_libseccomp.sh
  ci/install_yq.sh
  docs/Developer-Guide.md
  docs/how-to/how-to-pull-images-in-guest-with-kata.md
  docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md
  src/runtime/Makefile
  src/runtime/golang.mk
  src/runtime/virtcontainers/pkg/cloud-hypervisor/Makefile
  tests/cmd/github-labels/github-labels.sh
  tests/common.bash
  tests/functional/kata-deploy/kata-deploy.bats
  tests/functional/kata-monitor/gha-run.sh
  tests/functional/vfio/vfio_fedora_vm_wrapper.sh
  tests/gha-run-k8s-common.sh
  tests/install_go.sh
  tests/install_rust.sh
  tests/integration/cri-containerd/gha-run.sh
  tests/integration/kubernetes/confidential_kbs.sh
  tests/integration/kubernetes/filter_k8s_test.sh
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/k8s-exec-rejected.bats
  tests/integration/kubernetes/k8s-policy-job.bats
  tests/integration/kubernetes/k8s-policy-pod.bats
  tests/integration/kubernetes/k8s-policy-rc.bats
  tests/integration/kubernetes/lib.sh
  tests/integration/kubernetes/runtimeclass_workloads/pod-sandbox-vcpus-allocation.yaml
  tests/integration/kubernetes/setup.sh
  tests/integration/kubernetes/tests_common.sh
  tests/integration/nydus/gha-run.sh
  tests/integration/runk/gha-run.sh
  tests/integration/runk/runk-tests.bats
  tests/stability/soak_parallel_rm.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/README.md
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
  tools/packaging/release/release.sh
  tools/packaging/scripts/gen_versions_txt.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/agent/build.sh
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
  tools/packaging/static-build/coco-guest-components/build.sh
  tools/packaging/static-build/firecracker/build-static-firecracker.sh
  tools/packaging/static-build/initramfs/build.sh
  tools/packaging/static-build/nydus/build.sh
  tools/packaging/static-build/ovmf/build.sh
  tools/packaging/static-build/pause-image/build.sh
  tools/packaging/static-build/qemu/build-static-qemu.sh
  tools/packaging/static-build/stratovirt/build-static-stratovirt.sh
  tools/packaging/static-build/tools/build.sh
  tools/packaging/static-build/virtiofsd/build.sh
Labels: size/huge, ok-to-test

#9769 ci: remove sudo and make sure artifacts is owned by user
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/initrd-builder/initrd_builder.sh
  tools/packaging/guest-image/build_image.sh
Labels: size/small, ok-to-test

#9765 CI: disable jobs that failed > 50% on nightly CI recently - part 1
  .github/actionlint.yaml
  .github/workflows/basic-ci-amd64.yaml
  .github/workflows/run-kata-monitor-tests.yaml
Labels: area/ci, size/small, ok-to-test

#9773 GHA: Use qemu-coco-dev for k8s nydus test on s390x
  .github/workflows/run-k8s-tests-on-zvsi.yaml
  tests/integration/kubernetes/tests_common.sh
Labels: size/small, ok-to-test

#9725 genpolicy: add ability to filter for runtimeClassName
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/src/yaml.rs
  tests/integration/kubernetes/k8s-policy-pod.bats
  tests/integration/kubernetes/tests_common.sh
Labels: size/large, ok-to-test

#9770 tests: Use variable definition for better uniformity
  tests/integration/kubernetes/confidential_kbs.sh
Labels: size/tiny, ok-to-test

#9678 TEEs: Skip a few CI tests for SEV/SNP
  src/runtime/Makefile
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/k8s-kill-all-process-in-container.bats
  tests/integration/kubernetes/k8s-shared-volume.bats
  tests/integration/kubernetes/k8s-sysctls.bats
  tests/integration/kubernetes/runtimeclass_workloads/pod-file-volume.yaml
  tests/integration/kubernetes/runtimeclass_workloads/pod-readonly-volume.yaml
  tests/integration/kubernetes/setup.sh
  tests/integration/kubernetes/tests_common.sh
Labels: size/small, ok-to-test

#9214 kata-deploy: install oras using release artefacts on ppc64le
  tools/packaging/kata-deploy/local-build/dockerbuild/install_oras.sh
Labels: size/small, ok-to-test

#9702 docs: Adding blog submission guidelines
  docs/Blog-Post-Submission-Guide.md
  docs/README.md
Labels: size/medium, ok-to-test

#9760 kata-manager: Add symlinks for runc and slirp4netns
  utils/kata-manager.sh
Labels: size/tiny, ok-to-test

#9782 ci.ocp: Switch base to centos-9
  ci/openshift-ci/images/Dockerfile.buildroot
Labels: size/tiny, ok-to-test

#9768 ci: kbs: Enable CDH tests for TDX
  tests/integration/kubernetes/confidential_kbs.sh
  tests/integration/kubernetes/k8s-confidential-attestation.bats
Labels: size/tiny, ok-to-test

#9800 ci: tdx: Re-enable a bunch of volume related tests
  tests/integration/kubernetes/k8s-credentials-secrets.bats
  tests/integration/kubernetes/k8s-inotify.bats
  tests/integration/kubernetes/k8s-nested-configmap-secret.bats
  tests/integration/kubernetes/k8s-projected-volume.bats
  tests/integration/kubernetes/k8s-volume.bats
Labels: ok-to-test

#9779 tests: Fix indentation in common script
  tests/common.bash
Labels: ok-to-test

#9151 runtime: enable kernel-hashes for SNP confidential container
  src/runtime/Makefile
  src/runtime/pkg/govmm/qemu/qemu.go
  versions.yaml
Labels: size/small, ok-to-test

#9785 CI: Introduce retry mechanism for kubectl in gha-run.sh
  tests/common.bash
  tests/integration/kubernetes/gha-run.sh
Labels: size/medium, ok-to-test

#9809 tests: k8s: use newer yq command line format
  tests/integration/kubernetes/k8s-policy-pod.bats
Labels: size/tiny, ok-to-test

#9784 kata-types: fix bug in kata-types several test cases
  src/libs/kata-types/src/capabilities.rs
  src/libs/kata-types/tests/texture/configuration-anno-0.toml
  src/libs/kata-types/tests/texture/configuration-anno-1.toml
Labels: size/tiny, ok-to-test

#9811 agent: convert enum vals to kebab-case in cfg file
  src/agent/src/config.rs
Labels: size/small, ok-to-test

#9808 genpolicy: load OCI version from settings
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/settings.rs
Labels: size/small, ok-to-test

#9819 agent: config: Ensure envs take precedence
  src/agent/src/config.rs
Labels: size/medium, ok-to-test

#9821 metrics: Use function definition to have uniformity
  tests/metrics/time/launch_times.sh
Labels: size/small, ok-to-test

#9537 kata-deploy: configuring CRI-O for guest-pull image pulling
  tests/integration/kubernetes/gha-run.sh
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: area/kata-deploy, area/confidential-containers, size/small, ok-to-test

#9706 genpolicy: add support for devices
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/containerd.rs
  src/tools/genpolicy/src/persistent_volume_claim.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  tests/integration/kubernetes/k8s-policy-pvc.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod-pvc.yaml
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pvc.yaml
Labels: size/large, ok-to-test

#9790 Kill some dead runtime code
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
  src/runtime/virtcontainers/qemu.go
Labels: size/small, ok-to-test

#9844 tests: fix yq command line in k8s-policy-pvc
  tests/integration/kubernetes/k8s-policy-pvc.bats
Labels: size/tiny, ok-to-test

#9843 ci: fix the expected yq version string
  ci/install_yq.sh
Labels: size/tiny, ok-to-test

#9827 runtime: avoid panic on metrics gathering
  src/runtime/virtcontainers/remote.go
Labels: size/tiny, ok-to-test

#9818 runtime: fix minor spelling issues
  src/runtime/pkg/govmm/qemu/qmp.go
Labels: size/tiny, ok-to-test

#9575 versions: Upgrade to Cloud Hypervisor v39.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api_default.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DebugConsoleConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DeviceConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PciSegmentConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/RateLimitGroupConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VirtQueueAffinity.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmAddUserDevice.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_debug_console_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_pci_segment_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_rate_limit_group_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_virt_queue_affinity.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_add_user_device.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: size/huge, ok-to-test

#9832 tests: setup: Improve setup script for kubernetes tests
  tests/integration/kubernetes/setup.sh
Labels: size/small, ok-to-test

#9726 tests: kbs: Use nodeport deployment from upstream trustee
  tests/integration/kubernetes/confidential_kbs.sh
Labels: area/confidential-containers, size/small, ok-to-test

#9836 sandbox: fix the issue of double initial_size_manager config
  src/runtime-rs/crates/runtimes/src/manager.rs
Labels: size/small, ok-to-test

#9840 versions: Bump rust toolchain
  src/dragonball/src/address_space_manager.rs
  src/dragonball/src/device_manager/mod.rs
  versions.yaml
Labels: size/small, ok-to-test

#9838 CI: remove sudo from GHA
  .github/workflows/build-kata-static-tarball-amd64.yaml
Labels: force-skip-ci, size/tiny

#9815 genpolicy: fix settings path flag name
  src/tools/genpolicy/src/settings.rs
Labels: size/tiny, ok-to-test

#9786 genpolicy: add back support for insecure
  src/tools/genpolicy/src/registry.rs
Labels: size/tiny, ok-to-test

#9861 release: Bump VERSIONS file to 3.6.0
  VERSION
Labels: size/tiny, ok-to-test

#9833 tests/k8s: run for qemu-runtime-rs on AKS
  .github/workflows/run-k8s-tests-on-aks.yaml
  tests/integration/kubernetes/k8s-cpu-ns.bats
  tests/integration/kubernetes/k8s-number-cpus.bats
  tests/integration/kubernetes/k8s-sandbox-vcpus-allocation.bats
Labels: area/ci, runtime-rs, size/small, ok-to-test

#9862 tests: Use selector rather than pod name for kubectl logs/describe
  tests/integration/kubernetes/gha-run.sh
Labels: size/tiny, ok-to-test

#9860 Tokio vulnerability bump
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/libs/Cargo.lock
  src/libs/shim-interface/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/linux_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/shim-ctl/Cargo.toml
  src/runtime-rs/crates/shim/Cargo.toml
  src/tools/agent-ctl/Cargo.lock
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
Labels: area/agent, lang/rust, runtime-rs, size/huge, ok-to-test

#9834 sandbox: fix the issue of failed to get the vmm master tid
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
Labels: size/tiny, ok-to-test

#9772 runtime-rs: add base qmp framework
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
Labels: size/large, ok-to-test

#9869 ci: tdx: Disable TDX CI
  .github/workflows/run-kata-coco-tests.yaml
Labels: force-skip-ci, size/large, ok-to-test

#9877 ci: gha no sudo ppc64
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
Labels: size/tiny, ok-to-test

#9870 runtime-rs: adjust qemu vm shutdown behaviour
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
Labels: size/small, ok-to-test

#9882 ci: tdx: Use vanilla k8s instead of k3s
  .github/workflows/run-kata-coco-tests.yaml
Labels: size/tiny

#9149 qemu: upgrade to 8.2.4
  tools/packaging/qemu/patches/tag_patches/v8.2.4/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  versions.yaml
Labels: size/small, ok-to-test

#9874 tests: nerdctl: Fix variables names and remove network
  tests/integration/nerdctl/gha-run.sh
Labels: size/tiny, ok-to-test

#9884 ci: tdx: Re-enable TDX CI
  .github/workflows/run-kata-coco-tests.yaml
Labels: size/large

#9881 runtime: Support policy in remote hypervisor
  src/runtime/virtcontainers/kata_agent.go
Labels: size/small, ok-to-test

#9886 kernel: Add CONFIG_S390_UV_UAPI for s390x
  tools/packaging/kernel/configs/fragments/s390/base.conf
  tools/packaging/kernel/kata_config_version
Labels: size/tiny, ok-to-test

#9856 genpolicy: reject untested CreateContainer field values
  src/tools/genpolicy/rules.rego
Labels: size/small, ok-to-test

#9876 ci: remove sudo from s390x build
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: force-skip-ci, size/tiny, ok-to-test

#9875 ci: gha no sudo arm64
  .github/workflows/build-kata-static-tarball-arm64.yaml
Labels: force-skip-ci, size/tiny, ok-to-test

#9579 genpolicy: ignore SeccompProfile in PodSpec
  src/tools/genpolicy/src/pod.rs
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
Labels: size/small, ok-to-test

#9872 metrics: Improve variable definition in memory inside containers script
  tests/metrics/density/memory_usage_inside_container.sh
Labels: size/small, ok-to-test

#9830 runtime-rs: fix the bug of func count_files
  src/libs/kata-types/src/k8s.rs
Labels: size/small, ok-to-test

#9903 workflow: coco: Add auth registry secret
  .github/workflows/run-kata-coco-tests.yaml
Labels: force-skip-ci, size/tiny

#9864 genpolicy: allow specifying layer cache file
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
  src/tools/genpolicy/src/utils.rs
  tests/integration/kubernetes/k8s-policy-pod.bats
Labels: size/medium, ok-to-test

#9906 tests: attestation: Restrict sample policy use
  tests/integration/kubernetes/k8s-confidential-attestation.bats
Labels: size/tiny, ok-to-test

#9887 ci.ocp: Ensure we smoke-test with the right runtime class
  ci/openshift-ci/run_smoke_test.sh
  ci/openshift-ci/smoke/http-server.yaml.in
  ci/openshift-ci/test.sh
Labels: size/tiny, ok-to-test

#9897 tests: Increase timeout to crictl calls on kata monitor tests
  tests/functional/kata-monitor/kata-monitor-tests.sh
Labels: size/small, ok-to-test

#9879 runtime-rs: remove attempt to access sandbox bundle from container bu…
  src/runtime-rs/crates/shim/src/shim_start.rs
Labels: size/medium, ok-to-test

#9913 kata-ctl: Update Cargo.lock
  src/tools/kata-ctl/Cargo.lock
Labels: size/large, ok-to-test

#9916 gpu: Missing separator
  src/runtime/config/configuration-qemu-nvidia-gpu-snp.toml.in
Labels: size/tiny, ok-to-test

#9923 tests: Increase interval and max_tries for kubectl_retry
  tests/common.bash
Labels: size/tiny, ok-to-test

#9849 runtime: fix missing of VhostUserDeviceReconnect parameter assignment
  src/runtime/pkg/katautils/config.go
Labels: size/large, ok-to-test

#9918 rootfs: Fix spurious error
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
Labels: size/tiny, ok-to-test
