Repository kata-containers/kata-containers, pull requests merged in 2024-02, with the labels that each got.

#8941 genpolicy: allow separate paths for rules and settings files
  src/tools/genpolicy/genpolicy-advanced-command-line-parameters.md
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/settings.rs
  src/tools/genpolicy/src/utils.rs
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#8929 runtime-rs: report error on missing or empty fields in configuration
  src/libs/kata-types/src/annotations/mod.rs
Labels: no-backport-needed, size/small, ok-to-test

#8974 runtime: add SingleContainer when obtaining OCI Spec
  src/runtime/virtcontainers/sandbox.go
Labels: no-backport-needed, size/tiny, ok-to-test

#8931 runtime: merged ValidCgroupPath method
  src/runtime/pkg/resourcecontrol/cgroups.go
  src/runtime/pkg/resourcecontrol/utils_linux.go
  src/runtime/pkg/resourcecontrol/utils_linux_test.go
Labels: no-backport-needed, size/large, ok-to-test

#7483 runtime-rs: improving io performance using dragonball's vsock fd passthrough
  src/agent/Cargo.lock
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/process.rs
  src/agent/src/config.rs
  src/agent/src/main.rs
  src/agent/src/passfd_io.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/agent/src/signal.rs
  src/dragonball/src/dbs_virtio_devices/src/vsock/csm/connection.rs
  src/dragonball/src/dbs_virtio_devices/src/vsock/muxer/muxer_impl.rs
  src/libs/kata-types/src/config/agent.rs
  src/libs/kata-types/src/config/default.rs
  src/libs/kata-types/src/config/mod.rs
  src/libs/kata-types/src/config/runtime.rs
  src/libs/protocols/protos/agent.proto
  src/runtime-rs/Cargo.lock
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/hypervisor_persist.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/mod.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/passfd_io.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/tools/runk/libcontainer/src/container.rs
Labels: no-backport-needed, no-forward-port-needed, runtime-rs, size/huge, soc, ok-to-test

#8977 genpolicy: support non-default namespace name
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/src/config_map.rs
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/job.rs
  src/tools/genpolicy/src/list.rs
  src/tools/genpolicy/src/no_policy.rs
  src/tools/genpolicy/src/obj_meta.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/replica_set.rs
  src/tools/genpolicy/src/replication_controller.rs
  src/tools/genpolicy/src/secret.rs
  src/tools/genpolicy/src/settings.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/yaml.rs
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#8966 genpolicy: ignore empty YAML as input
  src/tools/genpolicy/src/policy.rs
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8994 ci: aks: switch from eastus2 to eastus region
  tests/gha-run-k8s-common.sh
Labels: no-backport-needed, size/tiny, ok-to-test

#8957 gha: add kubernetes tests workflow for ppc64le
  .github/workflows/ci.yaml
  .github/workflows/run-k8s-tests-on-ppc64le.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#8987 packaging: cache: Fix caching kernels which rely on extra modules
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/kata_config_version
Labels: size/large, ok-to-test

#8454 runtime-rs: make compilation for QEMU on s390x
  src/runtime-rs/Makefile
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: no-backport-needed, runtime-rs, size/medium, ok-to-test

#8760 runtime: Reduce the mount points with namespace isolation
  src/runtime/pkg/containerd-shim-v2/service.go
Labels: no-backport-needed, size/small, ok-to-test

#9000 packaging: Fix pushing artefacts to the registry
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny

#8654 ci/openshift-ci: Move openshift-ci from the tests repo here
  README.md
  ci/openshift-ci/cluster/configs/selinux.conf
  ci/openshift-ci/cluster/deploy_webhook.sh
  ci/openshift-ci/cluster/deployments/configmap_installer_kernel.yaml
  ci/openshift-ci/cluster/deployments/configmap_installer_qemu.yaml
  ci/openshift-ci/cluster/deployments/configmap_kata-webhook.yaml.in
  ci/openshift-ci/cluster/deployments/machineconfig_sandboxedcontainers_extension.yaml
  ci/openshift-ci/cluster/deployments/machineconfig_selinux.yaml.in
  ci/openshift-ci/cluster/deployments/relabel_selinux.yaml
  ci/openshift-ci/cluster/install_kata.sh
  ci/openshift-ci/lib.sh
  ci/openshift-ci/run_smoke_test.sh
  ci/openshift-ci/smoke/http-server.yaml
  ci/openshift-ci/smoke/service.yaml
  ci/openshift-ci/smoke/service_kubernetes.yaml
  ci/openshift-ci/test.sh
  tools/testing/kata-webhook/.gitignore
  tools/testing/kata-webhook/Dockerfile
  tools/testing/kata-webhook/README.md
  tools/testing/kata-webhook/common.bash
  tools/testing/kata-webhook/create-certs.sh
  tools/testing/kata-webhook/deploy/webhook-registration.yaml.tpl
  tools/testing/kata-webhook/deploy/webhook.yaml
  tools/testing/kata-webhook/go.mod
  tools/testing/kata-webhook/go.sum
  tools/testing/kata-webhook/main.go
  tools/testing/kata-webhook/webhook-check.sh
Labels: size/huge, ok-to-test

#9001 packaging: Don't build the confidential / sev kernel twice -- part III
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: ok-to-test

#8996 gha: k8s: Add cloud-hypervisor (runtime-rs) support
  .github/workflows/run-k8s-tests-on-aks.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8978 runtime: packaging: Use confidential kernel instead of the TDX one
  .github/workflows/build-kata-static-tarball-amd64.yaml
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-sev.toml.in
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/kata_config_version
Labels: size/medium, ok-to-test

#8983 packaging: Add confidential image / initrd
  .github/workflows/build-kata-static-tarball-amd64.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  versions.yaml
Labels: size/small, ok-to-test

#9007 gha: delete azure RG only if it exists
  tests/gha-run-k8s-common.sh
Labels: no-backport-needed, no-forward-port-needed, area/ci, size/tiny, ok-to-test

#9012 kata-monitor: fix agentUrl from containerd shim
  src/runtime/pkg/kata-monitor/monitor.go
Labels: no-backport-needed, size/tiny, ok-to-test

#9015 runtime: display accurate error msg to avoid misleading users.
  src/runtime/pkg/containerd-shim-v2/shim_management.go
  src/runtime/pkg/kata-monitor/pprof.go
  src/runtime/pkg/utils/shimclient/shim_management_client.go
Labels: no-backport-needed, size/small, ok-to-test

#9005 static-checks: Install clang in the ci environments
  .github/workflows/static-checks.yaml
Labels: no-backport-needed, size/tiny, ok-to-test

#9011 runtime: Replace TEE specific initrd / image for the confidential one
  .github/workflows/build-kata-static-tarball-amd64.yaml
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-sev.toml.in
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
Labels: size/small, ok-to-test

#9022 rootfs: confidential: Install coco-guest-components
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/coco-guest-components/build-static-coco-guest-components.sh
  tools/packaging/static-build/coco-guest-components/build.sh
Labels: size/medium, ok-to-test, merge-to-main

#8552 runtime: missing port type in the DeviceInfo
  src/runtime/virtcontainers/physical_endpoint.go
Labels: area/runtime, area/vfio, size/tiny, ok-to-test

#9019 gha: add GOPATH env var to the ppc64le k8s workflow
  .github/workflows/run-k8s-tests-on-ppc64le.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#9025 cri-containerd: fix loop in TestContainerMemoryUpdate()
  tests/integration/cri-containerd/integration-tests.sh
Labels: no-backport-needed, area/testing, size/tiny, ok-to-test

#9020 gha: Run static-checks on self-hosted runners conditionally
  .github/workflows/build-checks.yaml
  .github/workflows/static-checks-self-hosted.yaml
  .github/workflows/static-checks.yaml
Labels: no-backport-needed, size/large, ok-to-test

#8628 tests: k8s: Enable tests for cloud hypervisor runtime-rs without devicemapper
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/k8s-cpu-ns.bats
  tests/integration/kubernetes/k8s-number-cpus.bats
  tests/integration/kubernetes/k8s-sandbox-vcpus-allocation.bats
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8951 metrics: Update packages for TensorFlow ResNet Int8 Dockerfile
  tests/metrics/machine_learning/resnet50_int8_dockerfile/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8958 kata-manager: Add support for nerdctl installation
  utils/kata-manager.sh
Labels: size/large, ok-to-test

#9045 nydus: Bump nydus snapshotter version to v0.13.7
  tests/common.bash
  versions.yaml
Labels: no-backport-needed, size/tiny, ok-to-test

#9029 genpolicy: mount source for non-confidential guest
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/src/mount_and_storage.rs
  src/tools/genpolicy/src/settings.rs
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8922 tests: k8s-attach-handlers auto-generated policy
  tests/common.bash
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/k8s-attach-handlers.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/setup.sh
  tests/integration/kubernetes/tests_common.sh
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#9043 runtime-rs: fix assert error in `make check`
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
Labels: no-backport-needed, size/tiny, ok-to-test

#9037 runtime: fix creation of SEV confidential container on SNP enabled host.
  src/runtime/virtcontainers/qemu_amd64.go
Labels: size/tiny, ok-to-test

#9031 packaging/osbuilder: allow to pull and unpack pause image
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/release/release-notes.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/pause-image/Dockerfile
  tools/packaging/static-build/pause-image/build-static-pause-image.sh
  tools/packaging/static-build/pause-image/build.sh
  versions.yaml
Labels: no-backport-needed, size/large, ok-to-test, merge-to-main

#9061 tests:k8s: make add_kernel_initrd_anotations function generic
  tests/integration/kubernetes/setup.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8585 gha: Setup nydus snapshotter for CoCo tests
  tests/integration/kubernetes/gha-run.sh
Labels: no-backport-needed, size/medium, ok-to-test

#9047 docs: Remove jenkins reference in kernel documentation
  tools/packaging/kernel/README.md
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#9051 tests: k8s: k8s-copy-file auto-generated policy
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/policy.rs
  tests/integration/kubernetes/k8s-attach-handlers.bats
  tests/integration/kubernetes/k8s-copy-file.bats
  tests/integration/kubernetes/tests_common.sh
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#8455 runtime-rs: Add a new config option for QEMU
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-qemu.toml.in
Labels: no-backport-needed, runtime-rs, size/huge, ok-to-test

#9068 tools: avoid rootfs-image build "ln -s" error
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
Labels: no-backport-needed, size/tiny, ok-to-test

#8936 tests: cri-o: Use packages from pkgs.k8s.io
  tests/common.bash
  versions.yaml
Labels: size/small, ok-to-test

#9070 tests: k8s: avoid deleting unrelated pods
  tests/integration/kubernetes/tests_common.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#9080 release: Don't ship the pause-image / coco-guest-components as part of the release artefacts
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: size/tiny, ok-to-test

#9082 tests: Remove kata-deploy-tdx test and ensure kata-deploy is always cleaned up before starting the tests
  .github/workflows/run-kata-coco-tests.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: size/medium, ok-to-test

#9026 packaging: Remove leftovers from the transition from TEE specific kernel / initrd / image to the "confidential" ones
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
  versions.yaml
Labels: size/large, ok-to-test

#9098 runtime: Update runc to v1.1.12
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/github.com/safchain/ethtool/ethtool.go
  src/runtime/vendor/modules.txt
Labels: size/tiny, ok-to-test

#9091 packaging: Add the kata manager script
  .github/workflows/build-kata-static-tarball-amd64.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: safe-to-test, size/medium, ok-to-test

#9099 CI|k8s: Skip vcpu allocation test for s390x
  tests/integration/kubernetes/filter_out_per_arch/s390x.yaml
Labels: no-backport-needed, size/tiny, ok-to-test

#9023 tools.kata-webhook: Fix lib path
  tools/testing/kata-webhook/webhook-check.sh
Labels: no-backport-needed, no-forward-port-needed, area/ci, size/tiny, ok-to-test

#9112 runtime: fix checksum mismatch error in `make vendor`
  src/runtime/go.sum
  src/runtime/vendor/github.com/safchain/ethtool/ethtool.go
Labels: no-backport-needed, size/tiny, ok-to-test

#9108 ci: k8s: Fix checks used to skip confidential tests
  tests/integration/kubernetes/k8s-confidential.bats
Labels: size/tiny, ok-to-test

#9086 packaging: qemu-snp-experimental: support host kernel with gmem
  tools/packaging/qemu/patches/8.2.x/no_patches.txt
  tools/packaging/qemu/patches/tag_patches/b6ee1218e6c9b98a556841615dd10d094e648393/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/static-build/qemu/Dockerfile
  versions.yaml
Labels: size/small, ok-to-test

#8647 Cleanup network to make sure physical interfaces are restores back to original host driver.
  src/runtime/virtcontainers/api.go
  src/runtime/virtcontainers/network_linux.go
Labels: size/small, ok-to-test

#9079 docs: Update CI link into the README
  README.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#9090 gha: docker: Pull docker image as part of the dependencies
  tests/integration/docker/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#9073 tests: k8s: generated policy for additional tests
  src/tools/genpolicy/rules.rego
  tests/integration/kubernetes/k8s-caps.bats
  tests/integration/kubernetes/k8s-configmap.bats
  tests/integration/kubernetes/k8s-copy-file.bats
  tests/integration/kubernetes/k8s-cpu-ns.bats
  tests/integration/kubernetes/k8s-credentials-secrets.bats
  tests/integration/kubernetes/k8s-custom-dns.bats
  tests/integration/kubernetes/k8s-env.bats
  tests/integration/kubernetes/k8s-file-volume.bats
  tests/integration/kubernetes/k8s-job.bats
  tests/integration/kubernetes/k8s-kill-all-process-in-container.bats
  tests/integration/kubernetes/k8s-limit-range.bats
  tests/integration/kubernetes/k8s-memory.bats
  tests/integration/kubernetes/k8s-number-cpus.bats
  tests/integration/kubernetes/k8s-oom.bats
  tests/integration/kubernetes/k8s-optional-empty-configmap.bats
  tests/integration/kubernetes/tests_common.sh
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#9130 runtime-rs: bugfix for GPU passthrough failed with InvalidOperation.
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
Labels: no-backport-needed, size/tiny, ok-to-test

#9122 gha: try to cleanup nydus snapshotter before deploying it
  tests/integration/kubernetes/gha-run.sh
Labels: no-backport-needed, size/tiny, ok-to-test

#9132 gha: bump nydus snapshotter version to v0.13.8
  versions.yaml
Labels: no-backport-needed, size/tiny, ok-to-test

#9125 agent: Run container workload in its own cgroup namespace (cgroup v2 guest only)
  src/agent/Cargo.lock
  src/agent/rustjail/src/container.rs
Labels: size/small, ok-to-test

#9115 scripts: Add an enhanced die function
  tests/common.bash
  tests/error.sh
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#9142 build-checks: Install protoc in the ci environments
  .github/workflows/build-checks.yaml
Labels: no-backport-needed, size/tiny, ok-to-test

#9076 packaging: release notes: Don't show shortlist by default, and add survey link
  tools/packaging/release/release-notes.sh
Labels: safe-to-test, size/small, ok-to-test

#9100 runtime: remove kata_shim_netdev metric
  src/runtime-rs/crates/runtimes/src/shim_metrics.rs
  src/runtime/pkg/containerd-shim-v2/shim_metrics.go
Labels: size/medium, ok-to-test

#9146 release: Update everything in this repo related to the release and its process
  .github/workflows/add-backport-label.yaml
  .github/workflows/auto-backport.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/release-major.yaml
  .github/workflows/release-minor.yaml
  .github/workflows/release.yaml
  .github/workflows/require-pr-porting-labels.yaml
  docs/Release-Process.md
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/stable/env_stable_conf.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/stable/kustomization.yaml
  tools/packaging/release/release.sh
  tools/packaging/release/tag_repos.sh
  tools/packaging/release/tag_repos_test.sh
  tools/packaging/release/update-repository-version.sh
  tools/packaging/release/update-repository-version_test.sh
Labels: size/huge, ok-to-test

#9153 runtime: clh: minimum 10s timeout for CreateVM + BootVM
  src/runtime/virtcontainers/clh.go
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#9110 agent: Add all agent configuration options to README
  src/agent/README.md
Labels: no-backport-needed, size/small, ok-to-test

#9116 gha: k8s: prepare AKS workflow to install the CoCo KBS
  .github/workflows/run-k8s-tests-on-aks.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, area/ci, size/small, ok-to-test

#9009 tests/runk: fix the "run ps command" flaky test
  .github/workflows/run-runk-tests.yaml
  tests/integration/runk/gha-run.sh
  tests/integration/runk/runk-tests.bats
  tests/integration/runk/runk-tests.sh
Labels: no-backport-needed, no-forward-port-needed, area/ci, area/testing, size/large, ok-to-test

#9172 docs: Update Code PR advice document
  docs/code-pr-advice.md
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#9170 release: Add the needed fixes for the release process
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/release.yaml
  docs/Release-Process.md
  tools/packaging/release/release-notes.sh
  tools/packaging/release/release.sh
Labels: size/large, ok-to-test

#9188 releases: Second round of follow-up fixes
  .github/workflows/payload-after-push.yaml
Labels: size/tiny

#9176 docs: renew stale link
  docs/design/architecture/README.md
Labels: size/tiny, ok-to-test

#9180 rootfs: Fix PAUSE_IMAGE_TARBALL addition to the rootfs
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: size/tiny, ok-to-test

#9182 gha: Add cloud-hypervisor (runtime-rs) support to cri-containerd tests
  .github/workflows/basic-ci-amd64.yaml
  tests/integration/cri-containerd/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#9139 genpolicy: panic when we see a volume mount subpath
  src/tools/genpolicy/src/mount_and_storage.rs
  src/tools/genpolicy/src/pod.rs
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test
