Repository kata-containers/kata-containers, pull requests merged in 2024-01, with the labels that each got.

#8771 dbs-pci: introduce Cargo.lock to prevent the influence from upstream
  src/dragonball/.gitignore
  src/dragonball/src/dbs_pci/Cargo.lock
  src/dragonball/src/dbs_utils/Cargo.lock
  src/dragonball/src/dbs_virtio_devices/Cargo.lock
Labels: size/huge, ok-to-test

#8757 runtime-rs|agent|protocols|agent-ctl: Bump ttrpc and containerd-shim-protos versions
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/libs/Cargo.lock
  src/libs/protocols/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/shim/Cargo.toml
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Cargo.toml
  src/tools/agent-ctl/src/client.rs
Labels: no-backport-needed, size/huge, ok-to-test

#8766 metrics: Improve iperf3 cleanup
  tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8759 docs: Update docs for new StratoVirt VMM introduction
  docs/Developer-Guide.md
  docs/design/virtualization.md
  docs/hypervisors.md
  tests/cmd/check-spelling/data/projects.txt
  tests/cmd/check-spelling/kata-dictionary.dic
  tools/packaging/kata-deploy/README.md
Labels: no-backport-needed, size/medium, ok-to-test

#8776 tests: Add hypervisor component to kill kata components function
  tests/common.bash
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8735 agent: hold lock while setting new policy
  src/agent/src/policy.rs
  src/agent/src/rpc.rs
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#8773 agent: Fix an issue reporting OOM events by mistake
  src/agent/rustjail/src/cgroups/notifier.rs
Labels: no-backport-needed, size/small, ok-to-test

#8326 agent: use method params instead of const params in functions
  src/agent/src/network.rs
Labels: size/tiny, ok-to-test

#8778 packaging: Fix indentation of build static stratovirt
  tools/packaging/static-build/stratovirt/build-static-stratovirt.sh
Labels: no-backport-needed, no-forward-port-needed, ok-to-test

#8772 tests: list the current k8s pods
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: size/tiny, ok-to-test

#8749 runtime-rs: fixup the of bridge vfio device between runtime-rs and dr…
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
Labels: no-backport-needed, runtime-rs, size/medium, ok-to-test

#8753 TEEs: Introduce kernel-confidential
  .github/workflows/build-kata-static-tarball-amd64.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/common/base.conf
  tools/packaging/kernel/configs/fragments/common/fs.conf
  tools/packaging/kernel/configs/fragments/common/lsm.conf
  tools/packaging/kernel/configs/fragments/common/netfilter.conf
  tools/packaging/kernel/configs/fragments/common/network.conf
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/kernel/configs/fragments/x86_64/confidential/sev.conf
  tools/packaging/kernel/configs/fragments/x86_64/confidential/snp.conf
  tools/packaging/kernel/configs/fragments/x86_64/confidential/tdx.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/6.7.x/no_patches.txt
  tools/packaging/qemu/patches/8.1.x/no_patches.txt
  tools/packaging/qemu/patches/tag_patches/tdx-qemu-upstream-2023.9.21-v8.1.0/no_patches.txt
  tools/packaging/scripts/configure-hypervisor.sh
  tools/packaging/static-build/qemu/build-static-qemu-experimental.sh
  versions.yaml
Labels: size/medium, ok-to-test

#8796 versions: Update runc version
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8780 runtime-rs: Forward events to containerd via ttrpc
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/runtimes/common/src/message.rs
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/service/src/event.rs
  src/runtime-rs/crates/service/src/lib.rs
  src/runtime-rs/crates/service/src/manager.rs
Labels: no-backport-needed, size/huge, ok-to-test

#8693 runtime: Allow no initrd path for IBM Z Secure Execution
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/types/asset.go
Labels: no-backport-needed, area/runtime, size/small, ok-to-test

#8657 gha: Fix the failure of gha metrics for StratoVirt
  .github/workflows/run-metrics.yaml
  tests/common.bash
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-stratovirt-kata-metric8.toml
  tests/metrics/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#8248 tools: add policy generation tool
  docs/how-to/README.md
  docs/how-to/how-to-use-the-kata-agent-policy.md
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/Makefile
  src/tools/genpolicy/README.md
  src/tools/genpolicy/genpolicy-advanced-command-line-parameters.md
  src/tools/genpolicy/genpolicy-auto-generated-policy-details.md
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/samples/pod-one-container.yaml
  src/tools/genpolicy/src/config_map.rs
  src/tools/genpolicy/src/containerd.rs
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/job.rs
  src/tools/genpolicy/src/list.rs
  src/tools/genpolicy/src/main.rs
  src/tools/genpolicy/src/mount_and_storage.rs
  src/tools/genpolicy/src/no_policy.rs
  src/tools/genpolicy/src/obj_meta.rs
  src/tools/genpolicy/src/persistent_volume_claim.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/pod_template.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/replica_set.rs
  src/tools/genpolicy/src/replication_controller.rs
  src/tools/genpolicy/src/secret.rs
  src/tools/genpolicy/src/settings.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/src/verity.rs
  src/tools/genpolicy/src/volume.rs
  src/tools/genpolicy/src/yaml.rs
Labels: no-backport-needed, no-forward-port-needed, size/huge, ok-to-test

#8763 Fix backport check hub
  .github/workflows/add-backport-label.yaml
  ci/gh-util.sh
Labels: no-backport-needed, size/large, ok-to-test

#8803 runtime-rs: ch: Unbreak CH driver
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Labels: safe-to-test, size/small, ok-to-test

#8737 ci: test dragonball stability and cri-containerd
  tests/common.bash
  tests/integration/cri-containerd/gha-run.sh
  tests/integration/cri-containerd/integration-tests.sh
  tests/stability/gha-run.sh
Labels: no-backport-needed, size/medium, ok-to-test

#8792 metrics: Use a specific python version to run tensorflow benchmark
  tests/metrics/machine_learning/tensorflow_nhwc_dockerfile/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8817 genpolicy: "cargo fmt -- --check" clean-up
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/volume.rs
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#8819 dragonball: Remove unused definition
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
Labels: no-backport-needed, ok-to-test

#8827 tests: cbl-mariner: disable k8s-oom.bats
  tests/integration/kubernetes/k8s-oom.bats
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8822 genpolicy: cargo clippy fixes
  src/tools/genpolicy/src/list.rs
  src/tools/genpolicy/src/main.rs
  src/tools/genpolicy/src/mount_and_storage.rs
  src/tools/genpolicy/src/no_policy.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/secret.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/src/yaml.rs
Labels: no-backport-needed, no-forward-port-needed, size/large, ok-to-test

#8830 metrics: Remove iperf3 server protocol
  tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-deployment.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8708 runtime-rs: bugfix for DirectVolume/rawblock when driver is blk
  src/runtime-rs/crates/resource/src/volume/utils.rs
Labels: no-backport-needed, size/small, ok-to-test

#8837 genpolicy: temporarily disable allow_storages()
  src/tools/genpolicy/rules.rego
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8814 tools: genpolicy static checks
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/static-checks.yaml
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/README.md
  src/tools/genpolicy/src/verity.rs
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/tools/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#8808 tests: Ignore virtiofs contribution to memory usage when it is disabled.
  tests/metrics/density/memory_usage.sh
Labels: no-backport-needed, no-forward-port-needed, area/metrics, size/small, ok-to-test

#8836 genpolicy: use root path from cbl-mariner Guest VM
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8710 runtime-rs: ch: Implement minimal implementation for missing thread/pid APIs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Labels: safe-to-test, size/small, ok-to-test

#8845 tools: install genpolicy settings files
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8485 GHA: Enable static check for s390x, aarch64 and ppc64le
  .github/workflows/static-checks.yaml
  ci/install_yq.sh
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/src/device.rs
  src/agent/src/netlink.rs
  src/agent/src/random.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
  src/dragonball/Makefile
  src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
  src/dragonball/src/device_manager/mod.rs
  src/runtime-rs/Makefile
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime/cmd/kata-runtime/kata-env_ppc64le_test.go
  src/tools/agent-ctl/Makefile
  src/tools/kata-ctl/Makefile
  src/tools/kata-ctl/src/arch/s390x/mod.rs
  src/tools/runk/Makefile
  src/tools/runk/libcontainer/src/init_builder.rs
  src/tools/trace-forwarder/Makefile
Labels: no-backport-needed, size/large, ok-to-test

#8185 Add qemu cmdline generation framework
  src/libs/kata-types/src/config/default.rs
  src/libs/kata-types/src/config/hypervisor/qemu.rs
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
Labels: runtime-rs, size/huge, ok-to-test

#8862 genpolicy: ignore pod DNS settings
  src/tools/genpolicy/src/pod.rs
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8855 versions: Update firecracker version
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8857 gha: get ready to install genpolicy
  .github/workflows/ci.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  tests/integration/kubernetes/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8872 gpu: Add NVIDIA GPU Confidential kernel target
  .github/workflows/build-kata-static-tarball-amd64.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
  tools/packaging/static-build/kernel/Dockerfile
Labels: no-backport-needed, size/small, ok-to-test, area/gpu

#8812 runtime: remove SharedVersions field dead code
  src/runtime/pkg/govmm/qemu/qemu.go
Labels: no-backport-needed, size/small, ok-to-test

#7146 docs: provide a guide for how to use IBM Secure Execution
  docs/how-to/README.md
  docs/how-to/how-to-run-kata-containers-with-SE-VMs.md
Labels: no-backport-needed, size/large, ok-to-test

#8884 versions: Update libseccomp to version v2.5.5
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8901 gpu: remove GHA target first then remove the obsoleted Makefile targets
  .github/workflows/build-kata-static-tarball-amd64.yaml
Labels: size/tiny, ok-to-test, area/gpu

#8898 tests: k8s: bats --show-output-of-passing-tests
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8908 tools: allow all users to execute genpolicy
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test

#8876 metrics: Update packages needed for ResNet50 FP32 Dockerfile
  tests/metrics/machine_learning/resnet50_fp32_dockerfile/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8904 tools: Use defined variable in build base qemu script
  tools/packaging/static-build/qemu/build-base-qemu.sh
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8905 qemu: enable TPM
  tools/packaging/scripts/configure-hypervisor.sh
Labels: no-backport-needed, size/tiny, ok-to-test

#8916 packaging: Don't always build the kata-agent
  .gitignore
  tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
  tools/osbuilder/rootfs-builder/cbl-mariner/Dockerfile.in
  tools/osbuilder/rootfs-builder/centos/Dockerfile.in
  tools/osbuilder/rootfs-builder/debian/Dockerfile.in
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-copy-libseccomp-installer.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/agent/Dockerfile
  tools/packaging/static-build/agent/build-static-agent.sh
  tools/packaging/static-build/agent/build.sh
Labels: size/large, ok-to-test

#8914 tests: Add IBM SE to the basic confidential test
  .github/workflows/ci-nightly-s390x.yaml
  tests/integration/kubernetes/confidential_common.sh
  tests/integration/kubernetes/k8s-confidential.bats
  tests/integration/kubernetes/k8s-cpu-ns.bats
  tests/integration/kubernetes/k8s-inotify.bats
Labels: no-backport-needed, size/small, ok-to-test

#8909 genpolicy: add shareProcessNamespace support
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/config_map.rs
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/job.rs
  src/tools/genpolicy/src/list.rs
  src/tools/genpolicy/src/no_policy.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/replica_set.rs
  src/tools/genpolicy/src/replication_controller.rs
  src/tools/genpolicy/src/secret.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/yaml.rs
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#8926 gha: Cache the agent for non-x86_64 arches
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: no-backport-needed, size/tiny, ok-to-test

#8947 gha: azure: Set the correct subscription to the account
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-kata-deploy-tests-on-aks.yaml
  tests/gha-run-k8s-common.sh
Labels: size/tiny

#8375 arm64: agent_policy build always pulls amd64 opa binary
  tools/osbuilder/rootfs-builder/rootfs.sh
  versions.yaml
Labels: no-backport-needed, size/small, ok-to-test

#8933 packaging: Build coco-guest-components
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/release/release-notes.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/coco-guest-components/Dockerfile
  tools/packaging/static-build/coco-guest-components/build-static-coco-guest-components.sh
  tools/packaging/static-build/coco-guest-components/build.sh
  versions.yaml
Labels: size/large, ok-to-test

#8934 genpolicy: ignore the nodeName field
  src/tools/genpolicy/src/pod.rs
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8918 genpolicy: optional PodTemplateSpec metadata field
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/job.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/pod_template.rs
  src/tools/genpolicy/src/replica_set.rs
  src/tools/genpolicy/src/replication_controller.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/yaml.rs
Labels: no-backport-needed, no-forward-port-needed, size/medium, ok-to-test

#8959 gha: cri-o: Bump runners to 22.04
  .github/workflows/run-k8s-tests-with-crio-on-garm.yaml
Labels: size/tiny

#8924 genpolicy: fix ConfigMap volume mount paths
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/src/secret.rs
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8932 dragonball: fix noop-method-call warning
  src/dragonball/src/dbs_virtio_devices/src/block/handler.rs
Labels: size/small, ok-to-test

#8938 runtime-rs: Log qemu's stderr in shim log
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
Labels: size/medium, ok-to-test

#8956 packaging: Use Ubuntu 20.04 for building an agent
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/agent/Dockerfile
Labels: no-backport-needed, size/small, ok-to-test

#8269 kata-deploy: fix deprecations on kustomization files
  tools/packaging/kata-deploy/kata-cleanup/base/kustomization.yaml
  tools/packaging/kata-deploy/kata-cleanup/overlays/k3s/kustomization.yaml
  tools/packaging/kata-deploy/kata-cleanup/overlays/rke2/kustomization.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kustomization.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/k0s/kustomization.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/k3s/kustomization.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/rke2/kustomization.yaml
  tools/packaging/kata-deploy/kata-deploy/overlays/stable/kustomization.yaml
  tools/packaging/kata-deploy/kata-rbac/base/kustomization.yaml
Labels: area/kata-deploy, size/medium, ok-to-test

#8962 genpolicy: ignore volume configMap optional field
  src/tools/genpolicy/src/volume.rs
Labels: no-backport-needed, no-forward-port-needed, size/tiny, ok-to-test

#8964 tests: Re-arranged nerdctl tests
  tests/integration/nerdctl/gha-run.sh
Labels: no-backport-needed, no-forward-port-needed, size/small, ok-to-test
