Repository kata-containers/kata-containers, pull requests merged in 2024-05, with the labels that each got.

#9573 kata-deploy: configure debugging for crio
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#9563 build: Build the shipped agent with policy enabled
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  docs/how-to/how-to-run-kata-containers-with-SE-VMs.md
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small, ok-to-test

#9592 tests: adapt Mariner CI to unblock CH v39 upgrade
  src/tools/genpolicy/rules.rego
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/setup.sh
Labels: size/tiny, ok-to-test

#9600 versions: Remove oci information from versions file
  versions.yaml
Labels: size/small, ok-to-test

#9582 build: fix the confusing build message if yq doesn't exist in GOPATH/bin
  src/runtime/golang.mk
Labels: size/tiny, ok-to-test

#9598 runtime-rs: fix the issue of the leak of dead shim
  src/runtime-rs/crates/runtimes/src/manager.rs
Labels: size/tiny, ok-to-test

#9601 qemu: the error is logged only when it occurs
  src/runtime/virtcontainers/qemu_arm64.go
Labels: size/tiny, ok-to-test

#9607 ci: Stop building TDX specific QEMU and OVMF
  .github/workflows/build-kata-static-tarball-amd64.yaml
Labels: size/tiny

#9596 db: fix the issue of failed to init pci root bus
  src/dragonball/src/device_manager/vfio_dev_mgr/pci_vfio.rs
Labels: size/small, ok-to-test

#9609 tests: pull-image: Don't run on TEEs
  tests/integration/kubernetes/k8s-guest-pull-image.bats
Labels: size/tiny, ok-to-test

#9482 kernel: Add caching of kernel-headers
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/kata_config_version
Labels: size/small, ok-to-test

#9608 tdx: Adapt kata-deploy to use QEMU / OVMF from the distros
  src/runtime/Makefile
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/govmm/qemu/qemu_test.go
  src/runtime/virtcontainers/qemu.go
  tests/integration/kubernetes/k8s-measured-rootfs.bats
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/td-shim/Dockerfile
  tools/packaging/static-build/td-shim/build-td-shim.sh
  tools/packaging/static-build/td-shim/build.sh
  versions.yaml
Labels: size/large, ok-to-test

#9484 deploy: Add runtimeClasses relating to the NVIDIA GPU
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-qemu-nvidia-gpu-snp.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-qemu-nvidia-gpu-tdx.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
Labels: size/medium, ok-to-test

#9616 deploy: Fix wrong pushing of artifacts
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/kata_config_version
Labels: size/small, ok-to-test

#9626 release: Bump VERSIONS file to 3.5.0
  VERSION
Labels: size/tiny, ok-to-test

#9571 runtime-rs: Fix constructing the RTC struct
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
Labels: ok-to-test

#9585 debugging: adding a script and instructions for debugging the GO shim
  docs/Debug-shim-guide.md
  docs/Developer-Guide.md
  tools/containerd-shim-katadbg-v2
Labels: size/large, ok-to-test

#9629 kata-deploy: Fix tdx_not_supported call
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#9632 local-build: Ensure the default rootfs is built with AGENT_POLICY=yes
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny, ok-to-test

#9618 gpu: Add build targets for GPU rootfs initrd/image
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small, ok-to-test

#9438 tests: Add k8s negative policy test
  tests/integration/kubernetes/k8s-confidential-attestation.bats
Labels: area/confidential-containers, size/small, ok-to-test

#9638 CI: Use `--abbrev=9` explicitly for abbreviated commit hash
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/scripts/lib.sh
Labels: size/tiny, ok-to-test

#9627 gha: Fix indentation in gha run k8s common
  tests/gha-run-k8s-common.sh
Labels: size/large, ok-to-test

#9610 metrics: Fix random write value for FIO
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: size/small, ok-to-test

#9636 version: Bump nydus snapshotter to v0.13.13
  versions.yaml
Labels: size/tiny, ok-to-test

#9617 deploy: Add artefact repository
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small, ok-to-test

#9550 Tag component caches
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release-s390x.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/medium, ok-to-test

#9644 workflow: Remove if from env conditional
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: force-skip-ci, size/small, ok-to-test

#9647 ci: cache: Fix unbound variable
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny, ok-to-test

#9615 metrics: Update launch times script
  tests/metrics/time/launch_times.sh
Labels: size/large, ok-to-test

#9650 Caching tagging update part iii
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/medium, ok-to-test

#9613 tests: pull-image: Only skip tests for TEEs
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/confidential_common.sh
  tests/integration/kubernetes/k8s-confidential-attestation.bats
  tests/integration/kubernetes/k8s-confidential.bats
  tests/integration/kubernetes/k8s-guest-pull-image.bats
  tests/integration/kubernetes/lib.sh
Labels: size/medium, ok-to-test

#9655 CI: Append arch type to initramfs-cryptsetup image
  tools/packaging/static-build/initramfs/build.sh
Labels: size/tiny, ok-to-test

#9659 ci: cache: Filter out non-printable characters from tag
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny, ok-to-test

#9662 Fix launch times timestamp generation.
  tests/common.bash
  tests/metrics/time/launch_times.sh
Labels: area/metrics, ok-to-test

#9673 Revert "ci: azure: Workaround azure cli installation script"
  tests/gha-run-k8s-common.sh
Labels: size/tiny, ok-to-test

#9315 TEEs: Use `shared_fs=none` for TDX
  src/runtime/Makefile
  tests/integration/kubernetes/k8s-credentials-secrets.bats
  tests/integration/kubernetes/k8s-custom-dns.bats
  tests/integration/kubernetes/k8s-file-volume.bats
  tests/integration/kubernetes/k8s-guest-pull-image.bats
  tests/integration/kubernetes/k8s-inotify.bats
  tests/integration/kubernetes/k8s-kill-all-process-in-container.bats
  tests/integration/kubernetes/k8s-liveness-probes.bats
  tests/integration/kubernetes/k8s-nested-configmap-secret.bats
  tests/integration/kubernetes/k8s-projected-volume.bats
  tests/integration/kubernetes/k8s-shared-volume.bats
  tests/integration/kubernetes/k8s-sysctls.bats
  tests/integration/kubernetes/k8s-volume.bats
  tests/integration/kubernetes/setup.sh
Labels: size/medium, ok-to-test

#9671 fix: kata-deploy.sh VERSION_ID unbound-variable
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#9675 gha: release: Set inherit secrets on tarball builds
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
Labels: force-skip-ci, size/tiny, ok-to-test

#9660 genpolicy: detect empty string in ns as default
  src/tools/genpolicy/src/policy.rs
Labels: size/small, ok-to-test

#9452 gha: Add support to install KBS to k8s TDX GHA workflow
  .github/workflows/run-kata-coco-tests.yaml
  tests/integration/kubernetes/confidential_kbs.sh
  tests/integration/kubernetes/gha-run.sh
Labels: area/confidential-containers, size/medium, ok-to-test

#9658 CI: Migrate vfio-ap test files from tests repo
  tests/functional/vfio-ap/Dockerfile
  tests/functional/vfio-ap/run.sh
Labels: size/large, ok-to-test

#9657 runtime: Disable number of cpu comparison on remote hypervisor scenario
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
Labels: size/medium, ok-to-test

#9624 runtime: fix duplicated devices requested to the agent
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
Labels: size/small, ok-to-test

#9641 runtime: Add missing check in ResizeMemory for CH
  src/runtime/virtcontainers/clh.go
Labels: size/tiny, ok-to-test

#9642 runtime-rs: Drop some useless QEMU arguments
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
Labels: size/small, ok-to-test

#9682 runtime: tdx: Allow default_{cpu,memory} annotations
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-tdx.toml.in
Labels: size/tiny, ok-to-test

#9653 runtime: Enable connection to Quote Generation Service (QGS)
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-tdx.toml.in
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu_amd64.go
Labels: size/medium, ok-to-test

#9684 ci: cache: Add arch suffix to all cache tags
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small, ok-to-test

#9685 tests: Fix indentation in confidential common script
  tests/integration/kubernetes/confidential_common.sh
Labels: size/small, ok-to-test

#9681 gha: Enable install kbs and coco components for TDX, but still skip the CDH test
  tests/integration/kubernetes/confidential_kbs.sh
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/k8s-confidential-attestation.bats
  versions.yaml
Labels: area/confidential-containers, size/medium, ok-to-test

#9686 metrics: Fix minvalue for boot time
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
Labels: size/tiny, ok-to-test

#9696 tests/k8s: skip custom DNS tests on confidential jobs
  tests/integration/kubernetes/k8s-custom-dns.bats
Labels: area/confidential-containers, size/tiny, ok-to-test

#9698 tests/k8s: disable "fail-fast" behavior by default
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: area/ci, size/small, ok-to-test

#9605 kata-agent: update env PCIDEVICE_<prefix>_<resource-name>_INFO
  src/agent/src/device.rs
Labels: size/tiny, ok-to-test

#9690 runtime-rs: Remove obsoleted dial_timeout config
  src/libs/Cargo.lock
  src/runtime-rs/config/configuration-cloud-hypervisor.toml.in
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in
Labels: size/large, ok-to-test

#9583 runtime: make kata-runtime check error more understandable when /dev/kvm doesn't exist
  src/runtime/cmd/kata-runtime/kata-check.go
Labels: size/tiny, ok-to-test

#9687 agent: collect PCI address mapping for both vfio-pci-gk and vfio-pci device
  src/agent/src/device.rs
Labels: area/arm, size/small, ok-to-test, area/dpu

#9604 runtime-rs: add QMP support for Qemu(part I)
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
Labels: size/large, ok-to-test

#9693 Adjust indentation in ifneq statements within Makefile in runtime-rs
  src/runtime-rs/Makefile
Labels: size/tiny, ok-to-test

#9656 runtime-rs: document architecture & implementation conventions in qem…
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
Labels: size/medium, ok-to-test

#9268 kata-agent: CreateContainer Hook
  src/agent/rustjail/src/container.rs
Labels: size/small, ok-to-test, area/gpu

#9721 kata-deploy / kata-cleanup / ci: Fixes and improvements to kata-deploy / kata-cleanup and its usage in the CI
  tests/functional/kata-deploy/kata-deploy.bats
  tests/functional/kata-deploy/run-kata-deploy-tests.sh
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tools/packaging/kata-deploy/kata-cleanup/overlays/k0s/kustomization.yaml
  tools/packaging/kata-deploy/kata-cleanup/overlays/k0s/mount_k0s_conf.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/large, ok-to-test

#8861 gpu: reintroduce pcie_root_port and add pcie_switch_port
  src/runtime/cmd/kata-runtime/kata-env.go
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/containerd-shim-v2/create_test.go
  src/runtime/pkg/device/config/config.go
  src/runtime/pkg/device/drivers/utils.go
  src/runtime/pkg/device/drivers/vfio.go
  src/runtime/pkg/device/manager/manager.go
  src/runtime/pkg/hypervisors/hypervisor_state.go
  src/runtime/pkg/katatestutils/utils.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/sandbox.go
Labels: size/huge, ok-to-test, area/gpu

#9727 ci: ovmf without sudo
  tools/packaging/static-build/ovmf/build.sh
Labels: size/tiny, ok-to-test

#9728 ci: guest-components without sudo
  tools/packaging/static-build/coco-guest-components/Dockerfile
  tools/packaging/static-build/coco-guest-components/build-static-coco-guest-components.sh
  tools/packaging/static-build/coco-guest-components/build.sh
Labels: size/medium, ok-to-test

#9677 metrics: Improve variable definition in memory usage script
  tests/metrics/density/memory_usage.sh
Labels: size/small, ok-to-test

#9736 ci: qemu no sudo
  tools/packaging/static-build/qemu/build-base-qemu.sh
Labels: size/tiny, ok-to-test

#9733 ci: tools no sudo
  tools/packaging/static-build/tools/Dockerfile
  tools/packaging/static-build/tools/build-static-tools.sh
  tools/packaging/static-build/tools/build.sh
Labels: size/small, ok-to-test

#9679 kata-manager: Copy cni files under /opt/cni
  utils/kata-manager.sh
Labels: ok-to-test

#9730 ci: kernel no sudo
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/kata_config_version
  tools/packaging/static-build/kernel/build.sh
Labels: size/small, ok-to-test

#9729 ci: build agent without sudo
  tools/packaging/static-build/agent/Dockerfile
  tools/packaging/static-build/agent/build-static-agent.sh
  tools/packaging/static-build/agent/build.sh
Labels: size/medium, ok-to-test

#9739 ci: initramfs no sudo
  tools/packaging/static-build/initramfs/Dockerfile
  tools/packaging/static-build/initramfs/build.sh
Labels: size/tiny, ok-to-test

#9734 ci: virtiofsd no sudo
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
  tools/packaging/static-build/virtiofsd/build.sh
  tools/packaging/static-build/virtiofsd/gnu/Dockerfile
  tools/packaging/static-build/virtiofsd/musl/Dockerfile
Labels: size/medium, ok-to-test

#9731 ci: pause-image no sudo
  tools/packaging/static-build/pause-image/build-static-pause-image.sh
  tools/packaging/static-build/pause-image/build.sh
Labels: size/small, ok-to-test

#9732 ci: shim-v2 no sudo
  tools/packaging/static-build/shim-v2/Dockerfile
  tools/packaging/static-build/shim-v2/build.sh
  tools/packaging/static-build/shim-v2/install_go_rust.sh
Labels: size/large, ok-to-test

#9743 ci: Fix tools builder images
  tools/packaging/scripts/lib.sh
Labels: size/tiny, ok-to-test

#9639 runtime-rs: Add RNG to QEMU cmdline
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
Labels: size/medium, ok-to-test

#9746 ci: pin the nydus-snapshotter image version
  tests/integration/kubernetes/gha-run.sh
Labels: area/ci, size/tiny, ok-to-test

#9694 tests: enable guest-pull on all k8s tests for the qemu-coco-dev configuration
  tests/integration/kubernetes/k8s-empty-dirs.bats
  tests/integration/kubernetes/k8s-file-volume.bats
  tests/integration/kubernetes/k8s-kill-all-process-in-container.bats
  tests/integration/kubernetes/k8s-seccomp.bats
  tests/integration/kubernetes/k8s-shared-volume.bats
  tests/integration/kubernetes/k8s-sysctls.bats
  tests/integration/kubernetes/setup.sh
Labels: area/testing, area/confidential-containers, size/small, ok-to-test

#9747 ci: Remove all git config safe.directory
  ci/lib.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Labels: size/small, ok-to-test

#9737 ci: kata-deploy no sudo
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
Labels: size/small, ok-to-test

#8944 threat-model: Add VFIO, ACPI and KVM/VMM threat-model descriptions
  docs/threat-model/threat-model.md
Labels: area/documentation, size/large, ok-to-test

#9757 ci: k8s: Skip empty dir tests also for TDX
  tests/integration/kubernetes/k8s-empty-dirs.bats
Labels: size/tiny, ok-to-test

#9751 tests/k8s: print logs on fail only (k8s-confidential-attestation.bats)
  tests/integration/kubernetes/k8s-confidential-attestation.bats
Labels: area/testing, size/tiny, ok-to-test
