Repository kata-containers/kata-containers, pull requests merged in 2024-09, with the labels that each got.

#10236 agent: Update image-rs to 02af65abc
  src/agent/Cargo.lock
  src/agent/Cargo.toml
Labels: size/large, ok-to-test

#10204 kata-deploy: helm: Add INSTALLATION_PREFIX
  tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-deploy.yaml
  tools/packaging/kata-deploy/helm-chart/kata-deploy/values.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/large, ok-to-test

#10238 ci: Remove stdio tests
  .github/workflows/basic-ci-amd64.yaml
  tests/integration/stdio/stdio-tests.sh
Labels: size/large, ok-to-test

#10247 metrics: Remove metrics report for Kata Containers
  tests/metrics/README.md
  tests/metrics/report/README.md
  tests/metrics/report/grabdata.sh
  tests/metrics/report/makereport.sh
  tests/metrics/report/report_dockerfile/Dockerfile
  tests/metrics/report/report_dockerfile/dut-details.R
  tests/metrics/report/report_dockerfile/fio-reads.R
  tests/metrics/report/report_dockerfile/fio-writes.R
  tests/metrics/report/report_dockerfile/footprint-density.R
  tests/metrics/report/report_dockerfile/genreport.sh
  tests/metrics/report/report_dockerfile/html.Rmd
  tests/metrics/report/report_dockerfile/lifecycle-time.R
  tests/metrics/report/report_dockerfile/mem-in-cont.R
  tests/metrics/report/report_dockerfile/memory-footprint.R
  tests/metrics/report/report_dockerfile/metrics_report.Rmd
  tests/metrics/report/report_dockerfile/network-cpu.R
Labels: size/huge, ok-to-test

#10233 agent:cdh: Refactor CDHClient usage and initialization
  src/agent/src/cdh.rs
  src/agent/src/main.rs
  src/agent/src/rpc.rs
Labels: size/large, ok-to-test

#10250 runtime: fix bad default machine_type for remote hypervisor
  src/runtime/pkg/katautils/config.go
Labels: size/tiny, ok-to-test

#10254 runtime: Don't error out about SNP cert path on non SNP platforms
  src/runtime/pkg/katautils/config.go
Labels: ok-to-test

#10244 gha: Turn on KBS for qemu-coco-dev on s390x
  .github/workflows/run-k8s-tests-on-zvsi.yaml
  tests/integration/kubernetes/confidential_kbs.sh
Labels: size/small, ok-to-test

#10229 versions: Update firecracker version to 1.8.0
  versions.yaml
Labels: size/tiny, ok-to-test

#10237 tests: Enable k8s soak stability test for Kata CoCo CI
  .github/workflows/run-kata-coco-stability-tests.yaml
  tests/stability/gha-stability-run.sh
Labels: area/confidential-containers, size/tiny, ok-to-test

#10251 genpolicy: support readonly hostpath
  src/tools/genpolicy/src/mount_and_storage.rs
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-rc.yaml
Labels: size/small, ok-to-test

#10263 ci: Add workflow to run kata-agent api tests using kata-agent-ctl
  .github/workflows/basic-ci-amd64.yaml
  tests/functional/kata-agent-apis/gha-run.sh
  tests/functional/kata-agent-apis/run-agent-api-tests.sh
  tests/functional/kata-agent-apis/setup_common.sh
Labels: size/large, ok-to-test

#10255 ci: send SIGKILL to kill kata components
  tests/common.bash
Labels: size/tiny, ok-to-test

#10270 ci: Enable kata agent API tests
  .github/workflows/basic-ci-amd64.yaml
  tests/functional/kata-agent-apis/api-tests/dummy.bats
  tests/functional/kata-agent-apis/gha-run.sh
  tests/functional/kata-agent-apis/run-agent-api-tests.sh
Labels: size/small, ok-to-test

#10268 genpolicy: add support for PodDisruptionBudget yaml
  src/tools/genpolicy/src/yaml.rs
Labels: size/tiny, ok-to-test

#10267 metrics: Update openVINO and oneDNN tests references
  tests/metrics/machine_learning/onednn.sh
  tests/metrics/machine_learning/openvino.sh
Labels: force-skip-ci, size/tiny

#10245 agent: Refactor storage handler registration
  src/agent/src/storage/bind_watcher_handler.rs
  src/agent/src/storage/block_handler.rs
  src/agent/src/storage/ephemeral_handler.rs
  src/agent/src/storage/fs_handler.rs
  src/agent/src/storage/image_pull_handler.rs
  src/agent/src/storage/local_handler.rs
  src/agent/src/storage/mod.rs
  src/libs/kata-types/src/mount.rs
Labels: size/large, ok-to-test

#10213 Refine device management for kata-agent
  src/agent/src/device.rs
  src/agent/src/device/block_device_handler.rs
  src/agent/src/device/mod.rs
  src/agent/src/device/network_device_handler.rs
  src/agent/src/device/nvdimm_device_handler.rs
  src/agent/src/device/scsi_device_handler.rs
  src/agent/src/device/vfio_device_handler.rs
  src/agent/src/rpc.rs
  src/agent/src/storage/bind_watcher_handler.rs
  src/agent/src/storage/block_handler.rs
  src/agent/src/storage/ephemeral_handler.rs
  src/agent/src/storage/fs_handler.rs
  src/agent/src/storage/local_handler.rs
  src/libs/kata-types/src/device.rs
  src/libs/kata-types/src/handler.rs
  src/libs/kata-types/src/lib.rs
  src/libs/kata-types/src/mount.rs
Labels: size/huge, ok-to-test

#10257 kata-deploy: Remove kata-cleanup unneeded vars
  tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
Labels: ok-to-test

#10272 runtime: qemu: tdx: Add support for setting mrconfigid / mrowner / mrownerconfig
  src/runtime/pkg/govmm/qemu/qemu.go
Labels: size/small, ok-to-test

#10253 Add support of dragonball virtio-balloon free page reporting
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  tools/packaging/kernel/configs/fragments/build-type/dragonball-experimental/mm.conf
  tools/packaging/kernel/configs/fragments/build-type/dragonball-experimental/virtio.conf
  tools/packaging/kernel/kata_config_version
Labels: size/medium, ok-to-test

#10277 tests: Increase timeout to wait for soak stability test deployment
  tests/stability/kubernetes_soak_test.sh
Labels: size/tiny

#10282 runtime-rs: configuration-dragonball.toml.in: Remove duplication
  src/runtime-rs/config/configuration-dragonball.toml.in
Labels: size/tiny, ok-to-test

#10276 runtime: Fix runtime/cdi panic with assignment to entry in nil map
  src/runtime/virtcontainers/container.go
Labels: size/tiny, ok-to-test

#10292 ci: tdx: Adapt how we get the host IP
  tests/integration/kubernetes/confidential_kbs.sh
Labels: size/tiny, ok-to-test

#10294 Bump guest-components / trustee to a version that supports ITA
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
  versions.yaml
Labels: size/medium, ok-to-test

#10289 tests: Enable stressng k8s stability test for Kata CoCo CI
  tests/stability/gha-stability-run.sh
  tests/stability/kubernetes_soak_test.sh
Labels: force-skip-ci, size/tiny

#10295 metrics: Remove unused remove img var in common script
  tests/metrics/lib/common.bash
Labels: size/tiny, ok-to-test

#10291 genpolicy: fix and re-enable create container UID verification
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
  tests/integration/kubernetes/k8s-policy-pod.bats
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
Labels: size/large, ok-to-test

#10309 tests: Introduce retry mechanism for helm install
  tests/integration/kubernetes/gha-run.sh
Labels: size/small, ok-to-test

#10304 tests: Fix indentation in the cri containerd tests
  tests/integration/cri-containerd/integration-tests.sh
Labels: force-skip-ci, size/medium

#10316 tests: k8s-inotify: pod termination polling
  tests/integration/kubernetes/k8s-inotify.bats
Labels: size/tiny, ok-to-test

#10313 CoCo: Bump Coco components to 0.10 releases
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  tools/osbuilder/rootfs-builder/alpine/config.sh
  versions.yaml
Labels: size/small, ok-to-test

#10009 Merge to main: supporting pull cosign signed images
  src/agent/Makefile
  src/agent/README.md
  src/agent/src/config.rs
  src/agent/src/image.rs
  tests/integration/kubernetes/confidential_common.sh
  tests/integration/kubernetes/k8s-confidential-attestation.bats
  tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
  tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
  tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
  tests/integration/kubernetes/k8s-guest-pull-image.bats
  tests/integration/kubernetes/k8s-sealed-secret.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/tests_common.sh
Labels: size/large, ok-to-test

#10315 doc: Update how-to-run-kata-containers-with-SE-VMs.md
  docs/how-to/how-to-run-kata-containers-with-SE-VMs.md
  tools/packaging/guest-image/build_se_image.sh
  tools/packaging/guest-image/lib_se.sh
Labels: size/medium, ok-to-test

#10321 local-build: Fix unbound variable issue for lib_se.sh
  .github/workflows/build-kata-static-tarball-s390x.yaml
  tools/packaging/guest-image/lib_se.sh
Labels: size/tiny, ok-to-test

#10303 agent: add support to provide default agent policy via env
  src/agent/src/config.rs
  src/agent/src/main.rs
  src/agent/src/policy.rs
  tests/functional/kata-agent-apis/setup_common.sh
Labels: size/medium, ok-to-test

#10323 kata-deploy: Switch Kubernetes URL
  tests/gha-run-k8s-common.sh
  tools/packaging/kata-deploy/Dockerfile
  tools/packaging/kata-deploy/action/Dockerfile
Labels: size/tiny, ok-to-test

#10324 ci: Fix indentation of install libseccomp script
  ci/install_libseccomp.sh
Labels: force-skip-ci, size/medium

#10308 agent-ctl: Add SetPolicy support
  src/tools/agent-ctl/src/client.rs
  src/tools/agent-ctl/src/types.rs
  src/tools/agent-ctl/src/utils.rs
  tests/functional/kata-agent-apis/api-tests/test_set_policy.bats
  tests/functional/kata-agent-apis/setup_common.sh
Labels: size/large, ok-to-test

#10306 genpolicy: get UID from PodSecurityContext
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/job.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/replica_set.rs
  src/tools/genpolicy/src/replication_controller.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/yaml.rs
  tests/integration/kubernetes/k8s-policy-deployment.bats
  tests/integration/kubernetes/k8s-policy-job.bats
  tests/integration/kubernetes/k8s-policy-rc.bats
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-deployment.yaml
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-rc.yaml
Labels: size/large, ok-to-test

#10279 agent: Fix CPU usage reporting for cgroup v2 in kata-agent
  src/agent/rustjail/src/cgroups/fs/mod.rs
Labels: size/small, ok-to-test

#10243 virtcontainers: allow specifying nydus-overlayfs binary by path
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/katautils/create.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/fs_share_linux.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/mount_linux.go
Labels: ok-to-test

#10283 shim: Fix memory usage reporting for cgroup v2
  src/runtime/pkg/containerd-shim-v2/metrics.go
Labels: size/large, ok-to-test

#10274 runtime: Enable Image annotation for remote hypervisor
  src/runtime/config/configuration-remote.toml.in
  src/runtime/virtcontainers/remote.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/sandbox_test.go
Labels: size/small, ok-to-test

#10334 release: Bump version to 3.9.0
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: force-skip-ci, size/tiny

#10336 gha: Increase timeout to run k8s tests on TDX
  .github/workflows/run-kata-coco-tests.yaml
Labels: size/tiny, ok-to-test

#10239 acrn: Drop support
  docs/design/architecture_3.0/README.md
  docs/how-to/README.md
  docs/how-to/how-to-set-sandbox-config-kata.md
  docs/how-to/how-to-use-kata-containers-with-acrn.md
  docs/how-to/offline_cpu.sh
  docs/hypervisors.md
  src/libs/kata-types/src/annotations/mod.rs
  src/runtime-rs/Makefile
  src/runtime-rs/crates/hypervisor/src/hypervisor_persist.rs
  src/runtime/Makefile
  src/runtime/arch/amd64-options.mk
  src/runtime/cmd/kata-runtime/kata-check_amd64.go
  src/runtime/cmd/kata-runtime/kata-env_test.go
  src/runtime/config/configuration-acrn.toml.in
  src/runtime/pkg/device/drivers/block.go
  src/runtime/pkg/hypervisors/hypervisor_state.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/virtcontainers/acrn.go
  src/runtime/virtcontainers/acrn_arch_base.go
  src/runtime/virtcontainers/acrn_arch_base_test.go
  src/runtime/virtcontainers/acrn_test.go
  src/runtime/virtcontainers/documentation/api/1.0/api.md
  src/runtime/virtcontainers/fs_share_linux.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_linux.go
  src/runtime/virtcontainers/hypervisor_test.go
  src/runtime/virtcontainers/persist.go
  src/runtime/virtcontainers/persist/api/config.go
  src/runtime/virtcontainers/persist/api/interface.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
  src/runtime/virtcontainers/sandbox_test.go
  src/runtime/virtcontainers/types/asset.go
  src/runtime/virtcontainers/types/asset_test.go
  src/runtime/virtcontainers/virtcontainers_test.go
Labels: size/huge, ok-to-test

#10335 kata-deploy: clean up and fix docs for k0s
  tools/packaging/kata-deploy/README.md
Labels: force-skip-ci, size/medium, ok-to-test

#10339 runtime-rs: fix the issue of using block_on
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
Labels: size/tiny, ok-to-test

#10232 tests: Fix loop device handling for exec_host()
  tests/integration/kubernetes/confidential_common.sh
  tests/integration/kubernetes/k8s-file-volume.bats
  tests/integration/kubernetes/k8s-guest-pull-image.bats
  tests/integration/kubernetes/k8s-volume.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/custom-node-debugger.yaml
  tests/integration/kubernetes/tests_common.sh
Labels: size/large, ok-to-test

#10337 doc: Update the release process
  docs/Release-Process.md
Labels: force-skip-ci, size/small, ok-to-test

#10329 tools.kata-webhook: Specify runtime class using configMap
  tools/testing/kata-webhook/deploy/webhook.yaml
  tools/testing/kata-webhook/webhook-check.sh
Labels: size/tiny, ok-to-test

#9977 runtime: add DAN support for VFIO network device in Go kata-runtime
  src/runtime/virtcontainers/endpoint.go
  src/runtime/virtcontainers/endpoint_test.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/network_linux.go
  src/runtime/virtcontainers/network_linux_test.go
  src/runtime/virtcontainers/persist/api/network.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/types/dan.go
  src/runtime/virtcontainers/vfio_endpoint.go
Labels: size/large, ok-to-test

#10328 tests: Improve k8s negative tests
  tests/integration/kubernetes/k8s-confidential-attestation.bats
  tests/integration/kubernetes/k8s-file-volume.bats
  tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
  tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
  tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
  tests/integration/kubernetes/k8s-liveness-probes.bats
  tests/integration/kubernetes/k8s-sealed-secret.bats
  tests/integration/kubernetes/k8s-volume.bats
  tests/integration/kubernetes/lib.sh
  tests/integration/kubernetes/tests_common.sh
Labels: size/large, ok-to-test

#10345 ci: Reorder webhook deployment
  ci/openshift-ci/cluster/deploy_webhook.sh
Labels: size/small, ok-to-test

#10348 tests: Delete custom node debugger pod on EXIT
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: size/small, ok-to-test

#10330 Some prepared work for sandbox api support
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/firecracker/inner.rs
  src/runtime-rs/crates/hypervisor/src/firecracker/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/firecracker/mod.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/runtimes/common/src/error.rs
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_into_shim.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/service/src/manager.rs
  src/runtime-rs/crates/service/src/task_service.rs
  src/runtime-rs/crates/shim-ctl/src/main.rs
Labels: size/large, ok-to-test

#10293 runtime-rs: Notify containerd when process exits
  src/runtime-rs/crates/runtimes/common/src/message.rs
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_into_shim.rs
  src/runtime-rs/crates/runtimes/common/src/types/utils.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: size/large, SOC, ok-to-test

#10351 agent: fix the issue of setup sandbox pidns
  src/agent/src/rpc.rs
Labels: size/tiny, ok-to-test

#10349 sandbox: refactor the sandbox init process
  src/runtime-rs/crates/resource/src/cpu_mem/initial_size.rs
  src/runtime-rs/crates/runtimes/common/src/runtime_handler.rs
  src/runtime-rs/crates/runtimes/common/src/sandbox.rs
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/runtimes/linux_container/src/lib.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/runtime-rs/crates/runtimes/wasm_container/src/lib.rs
Labels: size/large, ok-to-test

#10219 runtime-rs: Port TAP implementation from dragonball
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/tap.rs
  src/runtime-rs/crates/hypervisor/src/utils.rs
Labels: size/large, SOC, ok-to-test

#10357 gha: Add ita_key as a github secret
  .github/workflows/run-kata-coco-tests.yaml
Labels: size/tiny

#10342 docs: Remove qemu information not longer valid
  docs/Developer-Guide.md
Labels: force-skip-ci, size/small

#10305 ci:tdx: Use an ITA key for TDX
  tests/integration/kubernetes/confidential_kbs.sh
  tests/integration/kubernetes/gha-run.sh
Labels: size/small, ok-to-test

#10312 runtime-rs: Add Configurable Compilation for Dragonball in Runtime-rs
  docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
  src/runtime-rs/Makefile
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: size/medium, SOC, ok-to-test

#10340 genpolicy: validate create sandbox storages
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/settings.rs
  tests/integration/kubernetes/tests_common.sh
Labels: size/medium, ok-to-test
