Repository kata-containers/kata-containers, pull requests merged in 2025-02, with the labels that each got.

#10751 snp: update kata to use latest upstream packages for snp
  docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu_amd64.go
  tools/packaging/static-build/ovmf/build-ovmf.sh
  versions.yaml
Labels: size/medium, ok-to-test

#10828 versions: Fix formatting
  versions.yaml
Labels: size/small, ok-to-test

#10827 versions: Bump golang version
  .github/workflows/darwin-tests.yaml
  .github/workflows/docs-url-alive-check.yaml
  versions.yaml
Labels: size/tiny, ok-to-test

#10826 workflows: Add delete kata-deploy timeouts for crio tests
  .github/workflows/run-k8s-tests-on-amd64.yaml
Labels: force-skip-ci, area/ci, size/tiny

#10811 CLH: config: add hypervisor_loglevel
  src/runtime/config/configuration-clh.toml.in
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/hypervisor.go
Labels: size/small, ok-to-test

#10812 gpu: Fix arm64 build
  tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: size/large, ok-to-test

#10824 Updates in prep of rust 1.80 bump
  src/agent/Cargo.lock
  src/agent/rustjail/src/mount.rs
  src/agent/src/cdh.rs
  src/agent/src/config.rs
  src/agent/src/linux_abi.rs
  src/agent/src/mount.rs
  src/agent/src/netlink.rs
  src/agent/src/random.rs
  src/agent/src/sandbox.rs
  src/agent/src/util.rs
  src/dragonball/Cargo.lock
  src/dragonball/Cargo.toml
  src/dragonball/Makefile
  src/dragonball/src/config_manager.rs
  src/dragonball/src/dbs_interrupt/src/kvm/msi_generic.rs
  src/dragonball/src/dbs_legacy_devices/src/i8042.rs
  src/dragonball/src/dbs_pci/Cargo.toml
  src/dragonball/src/device_manager/vfio_dev_mgr/mod.rs
  src/dragonball/src/vcpu/vcpu_impl.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/libs/Cargo.lock
  src/libs/kata-sys-util/src/protection.rs
  src/libs/safe-path/src/lib.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
  src/runtime-rs/crates/hypervisor/src/device/pci_path.rs
  src/runtime-rs/crates/hypervisor/src/device/util.rs
  src/runtime-rs/crates/hypervisor/src/firecracker/fc_api.rs
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
  src/runtime-rs/crates/resource/src/network/network_pair.rs
  src/runtime-rs/crates/resource/src/network/utils/link/driver_info.rs
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/service/src/event.rs
  src/tools/agent-ctl/Cargo.lock
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/src/arch/mod.rs
  src/tools/kata-ctl/src/arch/powerpc64/mod.rs
  src/tools/kata-ctl/src/ops/exec_ops.rs
  src/tools/kata-ctl/src/types.rs
  src/tools/kata-ctl/src/utils.rs
  src/tools/runk/libcontainer/src/init_builder.rs
  src/tools/trace-forwarder/Cargo.lock
  tools/packaging/static-build/qemu/Dockerfile
  utils.mk
Labels: size/huge, ok-to-test

#10841 local-build: Do not build measured rootfs on s390x
  tests/integration/kubernetes/k8s-guest-pull-image.bats
  tests/integration/kubernetes/k8s-measured-rootfs.bats
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small, ok-to-test

#10842 tests: disable k8s-policy-job.bats on coco-dev
  tests/integration/kubernetes/k8s-policy-job.bats
Labels: size/tiny, ok-to-test

#10791 gpu: Add first target and fix extratarballs
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
Labels: do-not-merge, force-skip-ci, size/medium

#10857 ci: Only use the Ubuntu TDX machine in the CI
  .github/actionlint.yaml
  .github/workflows/run-kata-coco-tests.yaml
Labels: force-skip-ci, size/small

#10860 workflows: build: Do not store unnecessary content on the tarball
  .github/workflows/build-kata-static-tarball-amd64.yaml
Labels: force-skip-ci, size/small

#10814 gha: Add shellcheck
  .github/workflows/shellcheck.yaml
Labels: force-skip-ci, size/small

#10850 Clean the config block_device_cache_direct of runtime-rs
  src/runtime-rs/config/configuration-cloud-hypervisor.toml.in
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/config/configuration-rs-fc.toml.in
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
Labels: size/medium, ok-to-test

#10866 gpu: enable confidential initrd build
  .github/workflows/build-kata-static-tarball-amd64.yaml
Labels: force-skip-ci, size/tiny

#10810 Skipping SNP and SEV from deploying and deleting Snapshotter
  tests/integration/kubernetes/gha-run.sh
Labels: size/tiny, ok-to-test

#10864 packaging: Move builds to Ubuntu 22.04
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
  tools/packaging/static-build/agent/Dockerfile
  tools/packaging/static-build/coco-guest-components/Dockerfile
  tools/packaging/static-build/initramfs/Dockerfile
  tools/packaging/static-build/ovmf/Dockerfile
  tools/packaging/static-build/shim-v2/Dockerfile
  tools/packaging/static-build/tools/Dockerfile
Labels: size/medium, ok-to-test

#10613 policy: add policy crate and add network namespace check to policy
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/policy/Cargo.toml
  src/agent/policy/src/lib.rs
  src/agent/policy/src/policy.rs
  src/agent/src/main.rs
  src/agent/src/policy.rs
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/lib.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/createcontainer/network_namespace/pod.yaml
  src/tools/genpolicy/tests/testdata/createcontainer/network_namespace/testcases.json
Labels: size/huge, ok-to-test

#10869 ci: k8s: Bump kcli image version
  tests/gha-run-k8s-common.sh
Labels: size/tiny, ok-to-test

#10832 ci: Update yq to v4.44.5 to support riscv64
  ci/install_yq.sh
Labels: size/tiny, ok-to-test

#10874 tests: Skip block volume test on fc, stratovirt
  tests/integration/kubernetes/k8s-block-volume.bats
Labels: size/small, ok-to-test

#10877 CI: Deprecate SEV
  .github/workflows/run-kata-coco-tests.yaml
Labels: force-skip-ci, size/medium

#10879 packaging(release): Properly handle version tag for the release bundle
  tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
Labels: area/packaging, area/release, size/tiny, ok-to-test

#10845 Add process to init subcgroup when we're using dind with cgroups v2
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/systemd/dbus_client.rs
  src/agent/rustjail/src/cgroups/systemd/manager.rs
Labels: size/small, ok-to-test

#10851 agent: Bump image-rs to 514c561d93
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/image.rs
  src/agent/src/rpc.rs
  tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
Labels: size/large, ok-to-test

#10885 agent: Bump agent crates to resolve CVEs
  src/agent/Cargo.lock
Labels: security, size/large, ok-to-test

#10786 gpu: Update config files
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-nvidia-gpu-snp.toml.in
  src/runtime/config/configuration-qemu-nvidia-gpu-tdx.toml.in
  src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
Labels: size/small, ok-to-test

#10878 gpu: agent cdi timeout
  src/agent/src/config.rs
  src/agent/src/device/mod.rs
  src/agent/src/rpc.rs
Labels: size/medium, ok-to-test

#10880 release: Bump version to 3.14.0
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: area/release, size/tiny, ok-to-test

#10890 release: Remove artifacts for release
  .github/workflows/build-kata-static-tarball-arm64.yaml
Labels: force-skip-ci

#10896 genpolicy: bump oci-distribution to v0.12.0
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
Labels: size/large, ok-to-test

#10895 agent: make policy feature optional again
  src/agent/Cargo.lock
  src/agent/Cargo.toml
Labels: size/small, ok-to-test

#10894 example: Use multi-arch image for test-deploy-kata-qemu.yaml
  tools/packaging/kata-deploy/examples/test-deploy-kata-qemu.yaml
Labels: size/small, ok-to-test

#10893 ci: Fix spell_check and improve header_check
  tests/cmd/check-spelling/data/main.txt
  tests/cmd/check-spelling/kata-dictionary.dic
  tests/static-checks.sh
Labels: size/small, ok-to-test

#10867 gpu: QEMU SNP+TDX experimental updates
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/qemu/patches/tag_patches/gpu-snp-20250211/no_patches.txt
  versions.yaml
Labels: size/small, ok-to-test

#10868 QEMU TDX experimental workflow
  .github/workflows/build-kata-static-tarball-amd64.yaml
  tools/packaging/qemu/patches/tag_patches/gpu-tdx-20250211/no_patches.txt
Labels: force-skip-ci, size/tiny

#10903 tests: Support systemd unit files in /usr/lib as well as /lib
  tests/common.bash
Labels: size/tiny, ok-to-test

#10818 agent: clear log pipes if denied by policy
  src/agent/src/rpc.rs
  tests/integration/kubernetes/k8s-policy-logs.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: size/medium, ok-to-test

#10904 GHA: Turn off MEASURED_ROOTFS in build-kata-static-tarball-s390x
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: size/tiny, ok-to-test

#10906 shim-v2: Remove MEASURED_ROOTFS assignment for s390x
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny, ok-to-test

#10743 IOMMUFD GPU enhancement
  src/runtime/pkg/device/config/config.go
  src/runtime/pkg/device/drivers/utils.go
  src/runtime/pkg/device/drivers/vfio.go
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_arch_base.go
Labels: size/large, ok-to-test

#10784 Disabling Nesting Check for SNP upstream
  src/runtime/config/configuration-qemu-snp.toml.in
Labels: size/tiny, ok-to-test

#10881 minor build fixes
  src/agent/.cargo/config.toml
  tools/packaging/kata-deploy/local-build/dockerbuild/install_oras.sh
Labels: size/tiny, ok-to-test

#10929 arm: ci: k8s: Enable CI
  .github/actionlint.yaml
  .github/workflows/ci.yaml
  .github/workflows/run-k8s-tests-on-arm64.yaml
  tests/integration/kubernetes/k8s-memory.bats
  tests/integration/kubernetes/k8s-pod-quota.bats
  tests/integration/kubernetes/k8s-sandbox-vcpus-allocation.bats
Labels: force-skip-ci, size/large

#10932 workflows: Refactor publish workflows
  .github/workflows/ci-devel.yaml
  .github/workflows/ci-weekly.yaml
  .github/workflows/ci.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/publish-kata-deploy-payload-arm64.yaml
  .github/workflows/publish-kata-deploy-payload-ppc64le.yaml
  .github/workflows/publish-kata-deploy-payload-s390x.yaml
  .github/workflows/publish-kata-deploy-payload.yaml
Labels: force-skip-ci, size/large

#10921 build: Drop redundant ARCH override
  src/agent/Makefile
  src/runtime-rs/Makefile
  src/tools/agent-ctl/Makefile
  src/tools/genpolicy/Makefile
  src/tools/runk/Makefile
  src/tools/trace-forwarder/Makefile
Labels: size/small, ok-to-test

#10931 gpu: IOMMUFD fix
  src/runtime/pkg/device/drivers/utils.go
Labels: size/tiny, ok-to-test

#10934 agent: Fix non-guest-pull build
  src/agent/src/cdh.rs
  src/agent/src/rpc.rs
Labels: size/tiny, ok-to-test

#10935 runtime: add cause to CDI errors
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/virtcontainers/sandbox.go
Labels: size/tiny, ok-to-test

#10654 genpolicy: add get_process_fields to CronJob
  src/tools/genpolicy/src/cronjob.rs
Labels: size/tiny, ok-to-test

#10925 genpolicy: fail when layer can't be processed
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
Labels: size/tiny, ok-to-test

#10652 genpolicy: support sysctls from PodSpec and environment defaults
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/containerd.rs
  src/tools/genpolicy/src/cronjob.rs
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/job.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/replica_set.rs
  src/tools/genpolicy/src/replication_controller.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/yaml.rs
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/createcontainer/sysctls/pod.yaml
  src/tools/genpolicy/tests/testdata/createcontainer/sysctls/testcases.json
Labels: size/huge, ok-to-test

#10930 workflows: Add codeql config
  .github/workflows/codeql.yml
Labels: force-skip-ci, size/medium

#10883 ci: k8s: Pin k0s version to get cri-o tests back working
  tests/gha-run-k8s-common.sh
  versions.yaml
Labels: size/small, ok-to-test

#10803 versions: update confidential initrd to 22.04
  tests/integration/kubernetes/k8s-guest-pull-image.bats
  tools/osbuilder/initrd-builder/initrd_builder.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  versions.yaml
Labels: size/small, ok-to-test

#10953 ci: Add shellcheckrc
  shellcheckrc
Labels: force-skip-ci, size/small

#10960 kata-deploy: k0s: Fix drop-in path
  tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/_helpers.tpl
  tools/packaging/kata-deploy/kata-cleanup/overlays/k0s/mount_k0s_conf.yaml
Labels: size/tiny, ok-to-test
