Repository kata-containers/kata-containers, pull requests merged in 2025-03, with the labels that each got.

#10870 gpu: add module signing
  tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/gpu/nvidia.x86_64.conf.in
  tools/packaging/kernel/kata_config_version
  tools/packaging/static-build/kernel/build.sh
Labels: size/large, ok-to-test

#10817 Fix virtio-net-ccw
  src/agent/src/ccw.rs
  src/agent/src/device/network_device_handler.rs
  src/agent/src/rpc.rs
  src/libs/protocols/protos/types.proto
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_dan.rs
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs
  src/runtime/virtcontainers/endpoint.go
  src/runtime/virtcontainers/ipvlan_endpoint.go
  src/runtime/virtcontainers/macvlan_endpoint.go
  src/runtime/virtcontainers/macvtap_endpoint.go
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/physical_endpoint.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/sandbox.go
  src/runtime/virtcontainers/tap_endpoint.go
  src/runtime/virtcontainers/tuntap_endpoint.go
  src/runtime/virtcontainers/types/ccw.go
  src/runtime/virtcontainers/types/ccw_test.go
  src/runtime/virtcontainers/veth_endpoint.go
  src/runtime/virtcontainers/vfio_endpoint.go
  src/runtime/virtcontainers/vhostuser_endpoint.go
Labels: size/large, ok-to-test

#10965 gpu: fix init symlinks
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Labels: size/tiny, ok-to-test, area/gpu

#10955 runtime: Properly set default hyp loglevel to 1
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
Labels: size/tiny, ok-to-test

#10954 Rework and fix metrics issues
  .github/workflows/ci.yaml
  .github/workflows/run-metrics.yaml
  tests/common.bash
  tests/integration/kubernetes/gha-run.sh
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
  tests/metrics/gha-run.sh
  tests/metrics/lib/common.bash
  tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
  tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-daemonset.yaml
  tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-deployment.yaml
  tests/metrics/network/latency_kubernetes/latency-network.sh
Labels: force-skip-ci, size/large

#10971 agent: Enable VFIO and initContainers
  src/agent/src/device/mod.rs
  src/agent/src/rpc.rs
  src/agent/src/sandbox.rs
Labels: size/small, ok-to-test

#10982 agent: fix permisssion according to runc
  src/agent/rustjail/src/mount.rs
Labels: size/small, ok-to-test

#10981 runtime: Remove console=ttysclp0 for s390x
  src/runtime/virtcontainers/qemu_s390x.go
Labels: size/tiny, ok-to-test

#10937 kata-types: Fix bugs related to annotations in kata-types
  src/libs/kata-types/tests/test_config.rs
Labels: size/small, ok-to-test

#10975 runtime-rs: Fix log_level's comments in configuration-dragonball.toml.in
  src/runtime-rs/config/configuration-dragonball.toml.in
Labels: size/tiny, ok-to-test

#10862 runtime-rs: Enable IBM SE for QEMU
  src/libs/kata-types/src/config/hypervisor/qemu.rs
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-qemu-se-runtime-rs.toml.in
  src/runtime-rs/crates/hypervisor/src/device/driver/protection_device.rs
  src/runtime-rs/crates/hypervisor/src/kernel_param.rs
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  tests/common.bash
  tools/packaging/kata-deploy/helm-chart/kata-deploy/values.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-qemu-se-runtime-rs.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: runtime-rs, size/huge, ok-to-test

#10876 ci: cri-containerd: upgrade the LTS / Active versions for containerd
  .github/workflows/basic-ci-amd64.yaml
  tests/integration/cri-containerd/integration-tests.sh
  versions.yaml
Labels: size/small, ok-to-test

#10941 runtime-rs: remove snp certs path support from qemu-rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/protection_device.rs
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: size/small, ok-to-test

#10985 runtime-rs: Remove s390x conditional compilation
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/kernel_param.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: size/medium, ok-to-test

#10760 add the Route flags suport when adding the route in the guest
  src/agent/Cargo.toml
  src/agent/src/netlink.rs
  src/libs/protocols/protos/types.proto
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/network/dan.rs
  src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_dan.rs
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs
  src/runtime-rs/crates/resource/src/network/network_model/tc_filter_model.rs
  src/runtime-rs/crates/resource/src/network/network_pair.rs
  src/runtime-rs/crates/resource/src/network/utils/address.rs
  src/runtime-rs/crates/resource/src/network/utils/link/manager.rs
  src/runtime-rs/crates/resource/src/network/utils/link/mod.rs
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
Labels: size/huge, ok-to-test

#10987 kata-deploy: Use docker.io for all architectures
  tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Labels: size/tiny, ok-to-test

#10992 gha: always delete workspace on rebase error
  tests/git-helper.sh
Labels: size/small, ok-to-test

#10998 runtime-rs: Add mem-agent config to clh and qemu config file
  src/runtime-rs/config/configuration-cloud-hypervisor.toml.in
  src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in
Labels: size/large, ok-to-test

#11000 tests: k8s: log kubectl exec ouput
  tests/integration/kubernetes/k8s-configmap.bats
  tests/integration/kubernetes/k8s-env.bats
  tests/integration/kubernetes/tests_common.sh
Labels: size/small, ok-to-test

#10948 ci: Refactor matrix for `build-checks`
  .github/workflows/build-checks-preview-riscv64.yaml
  .github/workflows/build-checks.yaml
Labels: size/large, ok-to-test

#10973 ci: temporarily avoid using the Mariner Host image
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/setup.sh
  tests/integration/kubernetes/tests_common.sh
Labels: size/small, ok-to-test

#11006 tests: fix confidential ssh Dockerfile
  tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/Dockerfile
Labels: size/tiny, ok-to-test

#11009 tests: k8s: skip trusted storage tests for qemu-tdx
  tests/integration/kubernetes/k8s-guest-pull-image.bats
Labels: size/tiny, ok-to-test

#10994 runtime-rs: Add guest swap support
  src/agent/src/rpc.rs
  src/libs/kata-types/src/config/hypervisor/dragonball.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/src/config/hypervisor/qemu.rs
  src/libs/protocols/protos/agent.proto
  src/runtime-rs/config/configuration-cloud-hypervisor.toml.in
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in
  src/runtime-rs/crates/agent/src/kata/agent.rs
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/lib.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/resource/src/cpu_mem/mem.rs
  src/runtime-rs/crates/resource/src/cpu_mem/mod.rs
  src/runtime-rs/crates/resource/src/cpu_mem/swap.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
Labels: size/huge, ok-to-test

#10990 workflows: shellcheck: Expand vendor ignore
  .github/workflows/shellcheck.yaml
  .github/workflows/shellcheck_required.yaml
Labels: size/tiny, ok-to-test

#10892 ci: Change the way we modify runtimeclass in webhook
  ci/openshift-ci/cluster/deploy_webhook.sh
  ci/openshift-ci/cluster/deployments/configmap_kata-webhook.yaml.in
Labels: size/small, ok-to-test

#11001 kernel: Support and enable riscv kernel build
  .github/actionlint.yaml
  .github/workflows/build-kata-static-tarball-riscv64.yaml
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/common/acpi.conf
  tools/packaging/kernel/configs/fragments/riscv/base.conf
  tools/packaging/kernel/configs/fragments/riscv/mmu.conf
  tools/packaging/kernel/configs/fragments/riscv/pci.conf
  tools/packaging/kernel/kata_config_version
Labels: size/large, ok-to-test

#10967 ci: Add coco required tests
  tools/testing/gatekeeper/required-tests.yaml
Labels: force-skip-ci, size/tiny

#11022 tests: k8s-policy-pod: safer host path volume source
  tests/integration/kubernetes/k8s-policy-pod.bats
Labels: size/small, ok-to-test

#11012 policy: validate pod generated name
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/obj_meta.rs
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/createcontainer/generate_name/pod.yaml
  src/tools/genpolicy/tests/testdata/createcontainer/generate_name/testcases.json
Labels: size/large, ok-to-test

#10983 genpolicy: Introduce UpdateInterfaceRequest rules in genpolicy-settings
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/updateinterface/pod.yaml
  src/tools/genpolicy/tests/testdata/updateinterface/testcases.json
Labels: size/large, ok-to-test

#10939 tools: initialize unbound variables in rootfs.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: size/tiny, ok-to-test

#10889 runtime: make SNP IDBlock configurable
  src/runtime/config/configuration-qemu-nvidia-gpu-snp.toml.in
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/katautils/config.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu_amd64.go
Labels: size/medium, ok-to-test

#11015 CI: Mark SNP as a Required test
  tools/testing/gatekeeper/required-tests.yaml
Labels: force-skip-ci, size/tiny

#11042 runtime-rs: Support and enable build on riscv64
  .github/workflows/build-checks-preview-riscv64.yaml
  src/libs/kata-sys-util/src/protection.rs
  src/runtime-rs/arch/riscv64gc-options.mk
Labels: size/small, ok-to-test

#11002 Bump Trustee and Guest Components for coco v0.13.0
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  versions.yaml
Labels: size/huge, ok-to-test

#11045 security: ci: Pin third-party actions to commit hashes
  .github/cargo-deny-composite-action/cargo-deny-skeleton.yaml.in
  .github/workflows/PR-wip-checks.yaml
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-riscv64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/ci-weekly.yaml
  .github/workflows/ci.yaml
  .github/workflows/commit-message-check.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/publish-kata-deploy-payload.yaml
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/release.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-kata-coco-stability-tests.yaml
  .github/workflows/run-kata-coco-tests.yaml
  .github/workflows/run-kata-deploy-tests-on-aks.yaml
  .github/workflows/shellcheck.yaml
  .github/workflows/shellcheck_required.yaml
  src/runtime/pkg/govmm/.github/workflows/main.yml
Labels: size/large, ok-to-test

#11043 release: Bump version to 3.15.0
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: size/tiny, ok-to-test

#11024 tests: k8s: retry "kubectl exec" on empty output
  tests/integration/kubernetes/tests_common.sh
Labels: size/small, ok-to-test

#11046 build: drop libtdx-attest
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
  tools/packaging/static-build/coco-guest-components/Dockerfile
Labels: size/small, ok-to-test

#11061 ci: Generalize `GITHUB_RUNNER_CI_ARM64`
  .github/workflows/build-checks.yaml
  src/runtime/cmd/kata-runtime/kata-check_arm64_test.go
  src/runtime/cmd/kata-runtime/kata-env_arm64_test.go
  src/runtime/cmd/kata-runtime/kata-env_test.go
Labels: size/small, ok-to-test

#11069 kata-deploy: return exit code for invalid argument
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#11010 metrics: Test improvements
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/gha-run.sh
  tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: size/small, ok-to-test

#11075 genpolicy: add support for BUILD_TYPE=debug
  src/tools/genpolicy/Makefile
Labels: size/tiny, ok-to-test

#11074 genpolicy: Refactor tests to allow different request types in a testcases json.
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/copyfile/testcases.json
  src/tools/genpolicy/tests/testdata/createcontainer/generate_name/testcases.json
  src/tools/genpolicy/tests/testdata/createcontainer/network_namespace/testcases.json
  src/tools/genpolicy/tests/testdata/createcontainer/sysctls/testcases.json
  src/tools/genpolicy/tests/testdata/createsandbox/testcases.json
  src/tools/genpolicy/tests/testdata/updateinterface/testcases.json
  src/tools/genpolicy/tests/testdata/updateroutes/testcases.json
Labels: size/medium, ok-to-test

#10984 tests: kata-deploy: The rest of the ground work to rewrite the kata-deploy tests
  tests/functional/kata-deploy/kata-deploy.bats
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/gha-run.sh
Labels: size/large, ok-to-test

#11053 ci: shellcheck fixes
  ci/darwin-test.sh
  ci/gh-util.sh
  ci/install_libseccomp.sh
  ci/install_yq.sh
  ci/openshift-ci/bisect-range.sh
  ci/openshift-ci/cleanup.sh
  ci/openshift-ci/cluster/deploy_webhook.sh
  ci/openshift-ci/cluster/install_kata.sh
  ci/openshift-ci/lib.sh
  ci/openshift-ci/run_smoke_test.sh
  ci/openshift-ci/sample-test-reproducer.sh
  ci/openshift-ci/test.sh
Labels: size/large, ok-to-test

#11086 tests: Make sure /etc/containerd before writing config
  tests/common.bash
Labels: size/tiny, ok-to-test

#11059 tests: k8s: clean-up shellcheck warnings in tests_common.sh
  tests/integration/kubernetes/tests_common.sh
Labels: size/medium, ok-to-test

#11063 runtime-rs: update the protobuf to 3.7.1
  src/agent/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/src/lib.rs
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/shim/Cargo.toml
Labels: size/medium, ok-to-test

#11056 runtime: Support and enable build on riscv64
  .github/workflows/build-checks-preview-riscv64.yaml
  src/runtime/Makefile
  src/runtime/arch/riscv64-options.mk
  src/runtime/cmd/kata-runtime/kata-check_data_riscv64_test.go
  src/runtime/cmd/kata-runtime/kata-check_generic_test.go
  src/runtime/cmd/kata-runtime/kata-check_riscv64.go
  src/runtime/cmd/kata-runtime/kata-check_riscv64_test.go
  src/runtime/cmd/kata-runtime/kata-env_riscv64_test.go
  src/runtime/go-test.sh
  src/runtime/pkg/govmm/vmm_riscv64.go
  src/runtime/virtcontainers/factory/template/template_riscv64.go
  src/runtime/virtcontainers/hypervisor_linux_riscv64.go
  src/runtime/virtcontainers/qemu_riscv64.go
Labels: size/large, ok-to-test

#11058 ci: Update static-checks strings
  tools/testing/gatekeeper/required-tests.yaml
Labels: size/large, ok-to-test

#11088 kata-deploy: Fix kata-cleanup's CrashLoopBackOff
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#11081 tests: Enable sealed secrets for all TEEs
  src/agent/src/rpc.rs
  tests/integration/kubernetes/confidential_kbs.sh
  tests/integration/kubernetes/k8s-sealed-secret.bats
Labels: size/medium, ok-to-test

#11085 runtime-go: qemu: Fix sandbox start failing with virtio-mem enable on arm64
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_arm64_test.go
  tools/packaging/kernel/configs/fragments/arm64/virtio.conf
  tools/packaging/kernel/kata_config_version
Labels: size/tiny, ok-to-test
