Repository kata-containers/kata-containers, pull requests merged in 2025-07, with the labels that each got.

#11248 genpolicy: add validation for storages
  src/tools/genpolicy/.gitignore
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/mount_and_storage.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/yaml.rs
  src/tools/genpolicy/tests/policy/main.rs
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/config_map/config_map.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/config_map/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/config_map/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/container_image/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/container_image/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/emptydir/testcases.json
  src/tools/genpolicy/tests/policy/testdata/state/execprocess/testcases.json
  tests/integration/kubernetes/tests_common.sh
Labels: size/huge, ok-to-test

#11499 gha: Eliminate use of force-skip-ci label
  .github/workflows/PR-wip-checks.yaml
  .github/workflows/cargo-deny-runner.yaml
  .github/workflows/commit-message-check.yaml
Labels: force-skip-ci

#11510 runtime-rs: make the resize_vcpu api support sync
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/device_manager/vfio_dev_mgr/mod.rs
  src/dragonball/src/vcpu/vcpu_manager.rs
  src/dragonball/src/vm/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
Labels: ok-to-test

#11482 runtime-rs: refactor and fix the implementation of guest-pull
  src/libs/kata-types/src/mount.rs
  src/runtime-rs/crates/resource/src/rootfs/virtual_volume.rs
Labels: ok-to-test

#11517 gpu: NVRC static build
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Labels: ok-to-test

#11506 Remove atty dependency
  .github/dependabot.yml
  src/dragonball/Cargo.lock
  src/libs/Cargo.lock
  src/libs/logging/Cargo.toml
  src/mem-agent/example/Cargo.lock
  src/mem-agent/example/Cargo.toml
  src/mem-agent/example/ctl.rs
  src/mem-agent/example/share/option.rs
  src/mem-agent/example/srv.rs
  src/runtime-rs/Cargo.lock
  src/tools/agent-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.lock
  src/tools/trace-forwarder/Cargo.lock
Labels: security, ok-to-test

#11336 gpu: Update runtimeClasses for correct podoverhead
  tools/packaging/kata-deploy/runtimeclasses/kata-qemu-nvidia-gpu-snp.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-qemu-nvidia-gpu-tdx.yaml
  tools/packaging/kata-deploy/runtimeclasses/kata-qemu-nvidia-gpu.yaml
Labels: ok-to-test

#11513 tools: port the dragonball kernel patch to 6.12.x
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/6.12.x/dragonball-experimental/0001-upcall-establish-upcall-server.patch
  tools/packaging/kernel/patches/6.12.x/dragonball-experimental/0002-upcall-introduce-device-manager-upcall-service.patch
  tools/packaging/kernel/patches/6.12.x/dragonball-experimental/0003-upcall-add-cpu-hotplug-hot-unplug-into-device-manage.patch
  tools/packaging/kernel/patches/6.12.x/dragonball-experimental/0004-upcall-add-virtio-mmio-hotplug-hot-unplug-into-devic.patch
  tools/packaging/kernel/patches/6.12.x/dragonball-experimental/0005-upcall-dragonball-devmgr-suppots-cpu-hotplug-on-arm6.patch
  tools/packaging/kernel/patches/6.12.x/dragonball-experimental/0006-msi-control-msi-irq-number-activated.patch
  tools/packaging/kernel/patches/6.12.x/dragonball-experimental/0007-smp-update-bringup_nonboot_cpus-parameters.patch
  tools/packaging/kernel/patches/6.12.x/dragonball-experimental/0008-upcall-add-pci-hotplug-hot-unplug-support.patch
  versions.yaml
Labels: ok-to-test

#11530 tests: runtimeclasses: Adjust gpu runtimeclasses
  tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
Labels: ok-to-test

#11494 versions: bump opa 1.5.1 -> 1.6.0
  versions.yaml
Labels: ok-to-test

#11537 runtime/runtime-rs: Set shared_fs to none for IBM SEL in config file
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-qemu-se-runtime-rs.toml.in
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-se.toml.in
Labels: ok-to-test

#11529 tests: k0s: Always use latest version, apart from CRI-O tests
  .github/workflows/run-k8s-tests-on-amd64.yaml
  tests/functional/kata-deploy/kata-deploy.bats
  tests/gha-run-k8s-common.sh
  versions.yaml
Labels: ok-to-test

#11549 runtime-rs: Switch tempdir to tempfile
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Labels: security, ok-to-test

#11554 gh: Fix released VERSION file
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
Labels: force-skip-ci, ok-to-test

#11491 runtime-rs: Change default block device driver from virtio-scsi to virtio-blk-*
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-cloud-hypervisor.toml.in
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in
  src/runtime-rs/config/configuration-qemu-se-runtime-rs.toml.in
  src/runtime-rs/config/configuration-rs-fc.toml.in
Labels: ok-to-test

#11550 runtime-rs | trace-forwarder: Bump chrono crate version
  src/runtime-rs/Cargo.lock
  src/tools/trace-forwarder/Cargo.lock
Labels: security, ok-to-test

#11521 versions: Bump idna crate to >= 1.0.3
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/tools/genpolicy/Cargo.lock
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/kata-ctl/src/check.rs
Labels: security, ok-to-test

#11480 mem-agent: Update to https://github.com/teawater/mem-agent/tree/kata-20250627
  src/agent/Cargo.toml
  src/agent/src/config.rs
  src/agent/src/rpc.rs
  src/mem-agent/.gitignore
  src/mem-agent/Cargo.lock
  src/mem-agent/Cargo.toml
  src/mem-agent/Makefile
  src/mem-agent/example/Cargo.lock
  src/mem-agent/example/Cargo.toml
  src/mem-agent/example/build.rs
  src/mem-agent/example/ctl.rs
  src/mem-agent/example/protocols/mod.rs
  src/mem-agent/example/protocols/protos/google/protobuf/empty.proto
  src/mem-agent/example/protocols/protos/google/protobuf/timestamp.proto
  src/mem-agent/example/protocols/protos/mem-agent.proto
  src/mem-agent/example/share/misc.rs
  src/mem-agent/example/share/mod.rs
  src/mem-agent/example/share/option.rs
  src/mem-agent/example/share/rpc.rs
  src/mem-agent/example/srv.rs
  src/mem-agent/src/agent.rs
  src/mem-agent/src/cgroup.rs
  src/mem-agent/src/compact.rs
  src/mem-agent/src/lib.rs
  src/mem-agent/src/memcg.rs
  src/mem-agent/src/mglru.rs
  src/mem-agent/src/misc.rs
  src/mem-agent/src/psi.rs
Labels: ok-to-test

#11555 Rust advisory fixes pre 3.19.0
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/libs/kata-sys-util/Cargo.toml
  src/libs/kata-types/Cargo.toml
  src/libs/protocols/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/tools/agent-ctl/Cargo.toml
  src/tools/genpolicy/Cargo.toml
  src/tools/runk/Cargo.toml
  src/tools/runk/libcontainer/Cargo.toml
Labels: security, ok-to-test

#11567 Remove gpu admin tools
  tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Labels: ok-to-test

#11571 build: Fix cache for nvidia-gpu-initrd builds
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  tools/packaging/kata-deploy/local-build/Makefile
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: ok-to-test

#11082 kernel: debug config
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/common/debug.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/static-build/kernel/build.sh
Labels: size/large, ok-to-test

#11575 runk: Fix build errors
  src/tools/runk/src/commands/list.rs
Labels: ok-to-test

#11504 agent: fix the issue of parent writer pipe fd leak
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/process.rs
  src/agent/src/rpc.rs
Labels: ok-to-test

#11577 deps(chore): bump guest-components to candidate v0.14.0
  versions.yaml
Labels: ok-to-test

#11558 helm: add nodeSelector support to kata-deploy chart
  src/runtime/pkg/README.md
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/k8s-cpu-ns.bats
  tools/packaging/kata-deploy/helm-chart/README.md
  tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-deploy.yaml
  tools/packaging/kata-deploy/helm-chart/kata-deploy/values.yaml
Labels: ok-to-test

#11576 chore: Update protobuf to fix CVE-2025-53605
  src/agent/Cargo.lock
  src/dragonball/Cargo.lock
  src/dragonball/Cargo.toml
  src/libs/protocols/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/runtime-rs/crates/service/src/manager.rs
  src/tools/agent-ctl/Cargo.lock
  src/tools/genpolicy/Cargo.lock
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
Labels: security, ok-to-test

#11596 release: Bump version to 3.19.0
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: ok-to-test

#11597 release: Copy the VERSION file to the tarball
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
Labels: ok-to-test

#11604 release: Bump version to 3.19.1
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: ok-to-test

#11579 runtime-rs: Support hotplugging host block devices within qemu-rs
  src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
Labels: ok-to-test

#11598 runtime-rs: Add full cgroups support on host
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/cgroups/mod.rs
  src/runtime-rs/crates/resource/src/cgroups/resource.rs
  src/runtime-rs/crates/resource/src/cgroups/resource_inner.rs
  src/runtime-rs/crates/resource/src/cgroups/utils.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/shim/src/bin/main.rs
  tests/integration/kubernetes/k8s-oom.bats
  tests/integration/kubernetes/runtimeclass_workloads/pod-oom.yaml
Labels: ok-to-test

#11626 versions: Upgrade to Cloud Hypervisor v47.0
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: ok-to-test

#11618 dragonball: Fix warnings in default build
  src/dragonball/dbs_utils/src/net/mac.rs
  src/dragonball/dbs_virtio_devices/src/vsock/mod.rs
  src/dragonball/src/api/v1/vmm_action.rs
  src/dragonball/src/device_manager/mod.rs
Labels: ok-to-test

#11619 ci: Try passing api token into githubh api call
  .github/workflows/basic-ci-amd64.yaml
  .github/workflows/basic-ci-s390x.yaml
  .github/workflows/run-cri-containerd-tests.yaml
  .github/workflows/run-kata-monitor-tests.yaml
  .github/workflows/run-runk-tests.yaml
  tests/common.bash
Labels: force-skip-ci, ok-to-test

#11385 ci/gatekeeper: make run-k8s-tests-coco-nontee job required
  tools/testing/gatekeeper/required-tests.yaml
Labels: area/ci, ok-to-test

#11553 genpolicy: reduce complexity
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/lib.rs
  src/tools/genpolicy/src/main.rs
  src/tools/genpolicy/src/mount_and_storage.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
  src/tools/genpolicy/src/settings.rs
  src/tools/genpolicy/src/verity.rs
  src/tools/genpolicy/tests/policy/testdata/createcontainer/generate_name/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/gid/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/network_namespace/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/runas/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/supplemental_groups/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/sysctls/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/config_map/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/container_image/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/emptydir/testcases.json
  src/tools/genpolicy/tests/policy/testdata/state/createcontainer/testcases.json
  src/tools/genpolicy/tests/policy/testdata/state/execprocess/testcases.json
  tests/integration/kubernetes/tests_common.sh
Labels: ok-to-test

#11627 Updated Firecracker Version to 1.12.1
  versions.yaml
Labels: ok-to-test

#11639 gpu: guest components
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Labels: ok-to-test

#11632 runtime: reproducible generation of Golang proto bindings
  .github/workflows/static-checks.yaml
  src/agent/Makefile
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent_ttrpc.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
  src/runtime/virtcontainers/pkg/mock/mock.go
  tools/packaging/static-build/codegen/Dockerfile
  versions.yaml
Labels: ok-to-test
