Repository kata-containers/kata-containers, pull requests merged in 2025-01, with the labels that each got.

#10696 kata-ctl: direct-volume: Auto create KATA_DIRECT_VOLUME_ROOT_PATH
  src/tools/kata-ctl/src/ops/volume_ops.rs
Labels: size/tiny, ok-to-test

#10702 CI: change the containerd tarball name from cri-containerd-cni to containerd
  tests/common.bash
  tests/functional/kata-monitor/gha-run.sh
  tests/integration/cri-containerd/gha-run.sh
  tests/integration/nydus/gha-run.sh
  tests/integration/runk/gha-run.sh
  tests/integration/stdio/gha-run.sh
  versions.yaml
Labels: size/large, ok-to-test

#10468 versions: Move kernel to the latest 6.12 release (the current LTS)
  tests/integration/kubernetes/k8s-empty-dirs.bats
  tests/integration/kubernetes/runtimeclass_workloads/pod-oom.yaml
  tools/packaging/kernel/configs/fragments/arm64/base.conf
  tools/packaging/kernel/configs/fragments/common/cgroup.conf
  tools/packaging/kernel/configs/fragments/s390/base.conf
  tools/packaging/kernel/configs/fragments/s390/secure-execution.conf
  tools/packaging/kernel/configs/fragments/s390/vfio-ap.conf
  tools/packaging/kernel/configs/fragments/whitelist.conf
  tools/packaging/kernel/configs/fragments/x86_64/acpi.conf
  tools/packaging/kernel/configs/fragments/x86_64/base.conf
  tools/packaging/kernel/configs/fragments/x86_64/mmu.conf
  tools/packaging/kernel/kata_config_version
  tools/packaging/kernel/patches/6.12.x/no_patches.txt
  versions.yaml
Labels: size/small, ok-to-test

#10718 metrics: Increase latency minimum range
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: size/tiny, ok-to-test

#10717 tests: Re-enable oom tests for mariner
  tests/integration/kubernetes/k8s-oom.bats
Labels: size/tiny, ok-to-test

#10541 Update Trustee and Guest Components
  tools/packaging/static-build/coco-guest-components/build-static-coco-guest-components.sh
  versions.yaml
Labels: size/small, ok-to-test

#10714 virtiofsd: Update to its v1.13.0 ( + one patch) release :-)
  tests/integration/kubernetes/k8s-empty-dirs.bats
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
  tools/packaging/static-build/virtiofsd/build.sh
  versions.yaml
Labels: size/small, ok-to-test

#9871 tests/gha-run-k8s-common: shorten AKS cluster name
  tests/gha-run-k8s-common.sh
Labels: area/ci, size/small, ok-to-test

#10721 metrics: Increase latency test range
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
Labels: size/tiny, ok-to-test

#10719 runtime: use actual booleans for QMP `device_add` boolean options
  src/runtime/pkg/govmm/qemu/qmp.go
Labels: size/tiny, ok-to-test

#10730 versions: Bump trustee to latest
  versions.yaml
Labels: size/tiny, ok-to-test

#10731 rootfs: reduced console output by default
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Labels: size/tiny, ok-to-test

#10727 image: bump mariner guest version to 3.0
  tools/osbuilder/rootfs-builder/cbl-mariner/Dockerfile.in
  tools/osbuilder/rootfs-builder/cbl-mariner/config.sh
  versions.yaml
Labels: size/tiny, ok-to-test

#10735 tests: Introduce retry_kubectl_apply() for trusted storage
  tests/integration/kubernetes/k8s-guest-pull-image.bats
  tests/integration/kubernetes/lib.sh
Labels: size/medium, ok-to-test

#10738 runtime: skip empty Guest console output lines
  src/runtime/virtcontainers/sandbox.go
Labels: size/small, ok-to-test

#10742 release: Bump version to 3.13.0
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: size/tiny, ok-to-test

#10741 virtiofsd: Update ubuntu to 22.04 for gnu target
  tools/packaging/static-build/virtiofsd/gnu/Dockerfile
Labels: size/tiny, ok-to-test

#10736 gpu: Fix rootfs build
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Labels: size/tiny, ok-to-test

#10764 gpu: Add rootfs target amd64/arm64
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
Labels: force-skip-ci, size/tiny

#10769 Revert "gpu: Add rootfs target amd64/arm64"
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
Labels: force-skip-ci, size/tiny

#10754 ci: Unify on `$GH_PR_NUMBER` environment variable
  .github/workflows/gatekeeper.yaml
  .github/workflows/run-k8s-tests-on-amd64.yaml
  .github/workflows/run-k8s-tests-on-ppc64le.yaml
  .github/workflows/run-k8s-tests-on-zvsi.yaml
  .github/workflows/run-kata-coco-tests.yaml
  .github/workflows/run-kata-deploy-tests-on-garm.yaml
  tests/integration/kubernetes/confidential_common.sh
  tools/testing/gatekeeper/jobs.py
Labels: force-skip-ci, size/small

#10770 gpu: Add kernel dep for the non coco use-case
  tools/packaging/kata-deploy/local-build/Makefile
Labels: size/tiny, ok-to-test

#10773 ci: Retry on failure of Create AKS cluster
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-kata-coco-stability-tests.yaml
  .github/workflows/run-kata-coco-tests.yaml
  .github/workflows/run-kata-deploy-tests-on-aks.yaml
Labels: force-skip-ci, size/small

#10775 agent: Update ttrpc to include the fix for connectivity issues
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/libs/Cargo.lock
  src/libs/protocols/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/service/Cargo.toml
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Cargo.toml
  src/tools/genpolicy/Cargo.lock
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
Labels: size/large, ok-to-test

#10776 workflows: Switch to github-hosted arm runners
  .github/actionlint.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/publish-kata-deploy-payload-arm64.yaml
  .github/workflows/release-arm64.yaml
Labels: force-skip-ci, size/small

#10762 libs/kata-types: Remove config enable_swap
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/tests/test_config.rs
  src/libs/kata-types/tests/texture/configuration-anno-0.toml
  src/libs/kata-types/tests/texture/configuration-anno-1.toml
  src/runtime-rs/tests/texture/configuration-qemu.toml
Labels: size/small, ok-to-test

#10777 gpu: Fix arm64 kernel build
  tools/packaging/kernel/configs/fragments/gpu/nvidia.arm64.conf.in
  tools/packaging/kernel/kata_config_version
Labels: size/tiny, ok-to-test

#10755 rootfs-confidential: Ensure systemd is used as init
  tests/integration/kubernetes/k8s-confidential.bats
  tests/integration/kubernetes/runtimeclass_workloads/pod-confidential-unencrypted.yaml
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small, ok-to-test

#10732 rootfs: minor systemd file deletion cleanup
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: size/medium, ok-to-test

#10779 workflows: Move arm static checks runner
  .github/workflows/static-checks-self-hosted.yaml
  tools/testing/gatekeeper/required-tests.yaml
Labels: force-skip-ci, size/tiny, ok-to-test

#10740 virtiofsd: Enable build for RISC-V
  tools/packaging/scripts/lib.sh
  tools/packaging/static-build/virtiofsd/build.sh
  tools/packaging/static-build/virtiofsd/gnu/Dockerfile
Labels: size/tiny, ok-to-test

#10766 Remove shebang in non-executable completion script
  src/runtime/data/completions/bash/kata-runtime
Labels: size/tiny, ok-to-test

#10782 metrics: Increase minval range for blogbench test
  tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
Labels: size/tiny, ok-to-test

#10794 versions: Bump Ubuntu base image & initrd
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  versions.yaml
Labels: size/large, ok-to-test

#10790 kernel: Add CONFIG_TMPFS_XATTR to tdx.conf
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/common/confidential_containers/tmpfs.conf
  tools/packaging/kernel/kata_config_version
Labels: size/tiny, ok-to-test

#10749 gpu: Add driver version selection
  tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/large, ok-to-test

#10767 Enable VFIO-AP coldplug for s390x
  src/agent/src/device/vfio_device_handler.rs
  src/libs/kata-types/src/device.rs
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/kata_agent.go
  src/runtime/virtcontainers/kata_agent_test.go
  src/runtime/virtcontainers/sandbox_test.go
  tests/functional/vfio-ap/container-config.json.in
  tests/functional/vfio-ap/run.sh
Labels: size/large, ok-to-test

#10805 egrep/fgrep removal
  ci/gh-util.sh
  docs/Developer-Guide.md
  docs/install/minikube-installation-guide.md
  docs/use-cases/using-Intel-QAT-and-kata.md
  docs/use-cases/using-SRIOV-and-kata.md
  src/runtime/data/completions/bash/kata-runtime
  src/runtime/data/kata-collect-data.sh.in
  tests/functional/tracing/test-agent-shutdown.sh
  tests/functional/vfio/vfio_fedora_vm_wrapper.sh
  tests/metrics/cmd/checkmetrics/vendor/golang.org/x/sys/unix/mkerrors.sh
  tests/metrics/density/footprint_data.sh
  tests/static-checks.sh
Labels: size/large, ok-to-test

#10823 packaging: virtiofsd: Allow building a specific commit
  tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
Labels: size/tiny, ok-to-test
