Repository kata-containers/kata-containers, pull requests merged in 2025-04, with the labels that each got.

#11100 kata-deploy: remove the double "/"
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#11104 kata-deploy: Create runtimeclasses by default
  tests/functional/kata-deploy/kata-deploy.bats
  tests/integration/kubernetes/gha-run.sh
  tools/packaging/kata-deploy/README.md
  tools/packaging/kata-deploy/helm-chart/kata-deploy/values.yaml
  tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Labels: size/small, ok-to-test

#11097 kata-deploy: add INSTALLATION_PREFIX validation
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/small, ok-to-test

#11114 agent: Allow users to build without guest-pull
  src/agent/Cargo.toml
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/tiny, ok-to-test

#11094 ci: Enable `build-kata-static-tarball-riscv64.yaml`
  .github/workflows/ci.yaml
Labels: force-skip-ci, size/tiny, ok-to-test

#11103 policy: Add missing input validations for ExecProcessRequest
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/execprocess/pod.yaml
  src/tools/genpolicy/tests/testdata/execprocess/testcases.json
Labels: size/large, ok-to-test

#10724 versions: Upgrade to Cloud Hypervisor v45.0
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PayloadConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_payload_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: size/large, ok-to-test

#11128 ci: Remove metric jobs
  .github/workflows/ci.yaml
Labels: force-skip-ci, size/tiny

#11129 runtime-rs: Extend runtime-rs workspace and centralize local dependencies
  src/runtime-rs/Cargo.toml
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
  src/runtime-rs/crates/persist/Cargo.toml
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/linux_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/shim-ctl/Cargo.toml
  src/runtime-rs/crates/shim/Cargo.toml
  src/runtime-rs/tests/utils/Cargo.toml
Labels: size/large, ok-to-test

#10938 runtime-rs: Simplify iommu group base name extraction from symlink
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
Labels: size/small, ok-to-test

#11090 ci: required-tests fixes/updates
  tools/testing/gatekeeper/required-tests.yaml
Labels: size/tiny, ok-to-test

#10678 ci: Update gatekeeper tests for md files
  tools/testing/gatekeeper/required-tests.yaml
Labels: size/tiny, ok-to-test

#11106 agent: Inherit rust workspace settings
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/policy/Cargo.toml
  src/agent/rustjail/Cargo.toml
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/cgroups/mock.rs
  src/agent/rustjail/src/cgroups/systemd/cgroups_path.rs
  src/agent/rustjail/src/cgroups/systemd/common.rs
  src/agent/rustjail/src/cgroups/systemd/dbus_client.rs
  src/agent/rustjail/src/cgroups/systemd/manager.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/lib.rs
  src/agent/rustjail/src/specconv.rs
  src/agent/vsock-exporter/Cargo.toml
Labels: size/large, ok-to-test

#11134 rust: Add rust-toolchain.toml
  rust-toolchain.toml
  versions.yaml
Labels: size/tiny, ok-to-test

#11142 build: User-facing improvements for the build scripts
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  versions.yaml
Labels: size/medium, ok-to-test

#11026 ci.ocp: Override default runtimeclass CPU resources
  ci/openshift-ci/test.sh
Labels: size/tiny, ok-to-test

#10999 gpu: Update creation permissions
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Labels: size/tiny, ok-to-test

#11157 ci: demote CoCo non-TEE to non-required from gatekeeper
  tools/testing/gatekeeper/required-tests.yaml
Labels: area/ci, size/tiny, ok-to-test

#11113 genpolicy: Add container_id & related policy container data to state.
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/execprocess/testcases.json
  src/tools/genpolicy/tests/testdata/state/createcontainer/pod.yaml
  src/tools/genpolicy/tests/testdata/state/createcontainer/testcases.json
  src/tools/genpolicy/tests/testdata/state/execprocess/pod.yaml
  src/tools/genpolicy/tests/testdata/state/execprocess/testcases.json
Labels: size/huge, ok-to-test

#11158 runtime-rs: Use bitwise or assign for bitflags
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs
  src/runtime-rs/crates/resource/src/network/utils/address.rs
  src/runtime-rs/crates/resource/src/network/utils/link/manager.rs
Labels: size/tiny, ok-to-test

#11178 versions: Switch gperf mirror
  versions.yaml
Labels: size/tiny, ok-to-test

#11150 gpu: Fix CDI annotations
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/device/config/config.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/sandbox.go
Labels: size/large, ok-to-test

#10610 Feat | Implement initdata for bare-metal/qemu hypervisor
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/initdata.rs
  src/agent/src/main.rs
  src/agent/testdata/initdata.img
  src/runtime/pkg/govmm/qemu/qemu.go
  src/runtime/pkg/oci/utils.go
  src/runtime/pkg/oci/utils_test.go
  src/runtime/pkg/types/types.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/qemu.go
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_amd64_test.go
  src/runtime/virtcontainers/qemu_arch_base.go
  src/runtime/virtcontainers/qemu_arm64.go
  src/runtime/virtcontainers/qemu_arm64_test.go
  src/runtime/virtcontainers/qemu_ppc64le.go
  src/runtime/virtcontainers/qemu_ppc64le_test.go
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_s390x_test.go
  src/runtime/virtcontainers/qemu_test.go
  tests/integration/kubernetes/confidential_common.sh
  tests/integration/kubernetes/k8s-initdata.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: size/huge, ok-to-test

#11184 ci: retry genpolicy execution
  tests/integration/kubernetes/tests_common.sh
Labels: size/small, ok-to-test

#11189 temp: ci: Fix AKS cluster creation
  tests/gha-run-k8s-common.sh
Labels: size/tiny, ok-to-test

#11153 build: Allow users to build the go, rust, or both runtimes
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/shim-v2/build.sh
Labels: size/medium, ok-to-test

#11191 release: Bump version to 3.16.0
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: size/tiny, ok-to-test

#11186 kernel: Add CONFIG_TASKSTATS (and related) configs
  tools/packaging/kernel/configs/fragments/common/base.conf
  tools/packaging/kernel/kata_config_version
Labels: ok-to-test

#11166 kata-types: Optimize memory adjuesting by only gathering memory info
  src/libs/kata-types/Cargo.toml
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/src/config/hypervisor/qemu.rs
  src/libs/kata-types/src/config/hypervisor/remote.rs
  src/libs/kata-types/src/device.rs
  src/libs/kata-types/src/handler.rs
Labels: size/small, ok-to-test

#10579 kata-sys-utils: Introduce pcilibs for getting pci devices info
  src/libs/Cargo.lock
  src/libs/kata-sys-util/Cargo.toml
  src/libs/kata-sys-util/src/lib.rs
  src/libs/kata-sys-util/src/pcilibs/devices.rs
  src/libs/kata-sys-util/src/pcilibs/mod.rs
  src/libs/kata-sys-util/src/pcilibs/pci_manager.rs
Labels: size/huge, ok-to-test

#11044 ci: Extend basic s390x tests
  .github/workflows/basic-ci-s390x.yaml
  .github/workflows/ci.yaml
  .github/workflows/run-cri-containerd-tests-s390x.yaml
  tools/testing/gatekeeper/required-tests.yaml
Labels: force-skip-ci, area/ci, area/s390x, size/large

#11185 runtime: clh: Add reclaim_guest_freed_memory [BACKPORT]
  src/runtime/config/configuration-clh.toml.in
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/oci/utils.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/pkg/annotations/annotations.go
Labels: size/medium, ok-to-test

#11098 versions: Bump golang version
  .github/workflows/darwin-tests.yaml
  .github/workflows/docs-url-alive-check.yaml
  src/runtime/go.mod
  src/tools/csi-kata-directvolume/go.mod
  src/tools/log-parser/go.mod
  tests/go.mod
  tests/integration/cri-containerd/gha-run.sh
  tests/metrics/cmd/checkmetrics/go.mod
  tools/testing/kata-webhook/go.mod
  versions.yaml
Labels: size/small, ok-to-test

#10882 tests: confidential: Add KBS logging
  tests/integration/kubernetes/confidential_common.sh
  tests/integration/kubernetes/confidential_kbs.sh
  tests/integration/kubernetes/k8s-confidential-attestation.bats
  tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
  tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
  tests/integration/kubernetes/k8s-sealed-secret.bats
Labels: size/small, ok-to-test

#10940 ci.ocp: Add peer-pods setup script
  ci/openshift-ci/README.md
  ci/openshift-ci/peer-pods-azure.sh
Labels: size/large

#11212 GHA: Add VFIO-AP to s390x nightly tests for CoCo
  .github/workflows/ci-nightly-s390x.yaml
Labels: force-skip-ci

#11164 tests/k8s: fix kbs installation on Azure AKS
  .github/workflows/run-kata-coco-tests.yaml
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/confidential_kbs.sh
Labels: area/ci, area/testing, size/medium, ok-to-test

#11077 genpolicy: Align GID behavior with CRI and enable GID policy checks.
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/cronjob.rs
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/job.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
  src/tools/genpolicy/src/replica_set.rs
  src/tools/genpolicy/src/replication_controller.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/yaml.rs
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/createcontainer/generate_name/testcases.json
  src/tools/genpolicy/tests/testdata/createcontainer/network_namespace/testcases.json
  src/tools/genpolicy/tests/testdata/createcontainer/security_context/pod.yaml
  src/tools/genpolicy/tests/testdata/createcontainer/security_context/testcases.json
  src/tools/genpolicy/tests/testdata/createcontainer/sysctls/testcases.json
  src/tools/genpolicy/tests/testdata/state/createcontainer/testcases.json
  tests/integration/kubernetes/k8s-policy-deployment-sc.bats
  tests/integration/kubernetes/run_kubernetes_tests.sh
  tests/integration/kubernetes/runtimeclass_workloads/k8s-layered-sc-deployment.yaml
  tests/integration/kubernetes/runtimeclass_workloads/k8s-pod-sc-deployment.yaml
  tests/integration/kubernetes/runtimeclass_workloads/k8s-pod-sc-nobodyupdate-deployment.yaml
  tests/integration/kubernetes/tests_common.sh
Labels: size/huge, ok-to-test

#11211 dragonball: Remove package lockfiles
  src/dragonball/dbs_pci/Cargo.lock
  src/dragonball/dbs_utils/Cargo.lock
  src/dragonball/dbs_virtio_devices/Cargo.lock
  tests/common.bash
Labels: size/huge, ok-to-test
