Repository kata-containers/kata-containers, pull requests merged in 2025-09, with the labels that each got.

#11759 genpolicy: print Input and Policy storages
  src/tools/genpolicy/rules.rego
Labels: ok-to-test

#11752 runtime-rs: Remove default value of Linux.Resources.Devices and correctly set Hooks in OCI Spec to meet with Agent Policy requirements
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: ok-to-test

#11615 security: gha: Run Zizmor in auditor mode
  .github/workflows/zizmor.yaml
Labels: security

#11756 ci: cri-containerd-amd64: add logging for curl failures
  tests/common.bash
Labels: ok-to-test

#11770 agent-ctl: version: bump hypervisor
  src/tools/agent-ctl/Cargo.lock
Labels: security, ok-to-test

#11746 versions: Bump gopkg.in/yaml.v3
  tests/go.mod
  tests/go.sum
  tests/vendor/gopkg.in/yaml.v3/parserc.go
  tests/vendor/modules.txt
Labels: security, ok-to-test

#11754 versions: Tidy up go.mod versions
  src/tools/log-parser/go.mod
  tests/go.mod
  tests/metrics/cmd/checkmetrics/go.mod
Labels: ok-to-test

#11782 genpolicy: Enhance policy rule for runtime-rs scenarios
  src/tools/genpolicy/rules.rego
Labels: ok-to-test

#11766 kata-types: Support create_container_timeout set within configuration
  src/libs/kata-types/src/config/agent.rs
  src/runtime-rs/config/configuration-cloud-hypervisor.toml.in
  src/runtime-rs/config/configuration-dragonball.toml.in
  src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in
  src/runtime-rs/config/configuration-qemu-se-runtime-rs.toml.in
  src/runtime-rs/config/configuration-remote.toml.in
  src/runtime-rs/config/configuration-rs-fc.toml.in
Labels: ok-to-test

#11796 clh: Update to v48.0 release
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/.openapi-generator/FILES
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NumaConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/SgxEpcConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_numa_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_sgx_epc_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
  src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
  versions.yaml
Labels: ok-to-test

#11799 runtime-rs: Bugfix for kata virtual volume overlay fstype
  src/runtime-rs/crates/resource/src/rootfs/virtual_volume.rs
Labels: ok-to-test

#11801 runtime-rs: Enable share-rw=true when hotplug block device within qemu
  src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
Labels: ok-to-test

#11773 runtime-rs: add the sandbox's shm volume support
  src/libs/kata-sys-util/src/k8s.rs
  src/libs/kata-types/src/mount.rs
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/share_fs/mod.rs
  src/runtime-rs/crates/resource/src/volume/ephemeral_volume.rs
  src/runtime-rs/crates/resource/src/volume/mod.rs
  src/runtime-rs/crates/resource/src/volume/shm_volume.rs
  src/runtime-rs/crates/runtimes/common/src/types/mod.rs
  src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: ok-to-test

#11811 tools: agent-ctl: Fix unresolved ch import
  src/tools/agent-ctl/Cargo.toml
  src/tools/agent-ctl/src/vm/vm_ops.rs
Labels: ok-to-test

#11812 kata-manager: Handle zst unpacking
  utils/kata-manager.sh
Labels: ok-to-test

#11783 kata-agent: Rename misleading variable in config parsing
  src/agent/src/config.rs
Labels: ok-to-test

#11753 runtime-rs: Fix annotations within runtime-rs to pass the agent policy check
  src/libs/kata-types/src/container.rs
  src/runtime-rs/crates/runtimes/src/manager.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: ok-to-test

#11822 runtime: Set maxmem to initialmem on s390x when memory hotplug is disabled
  src/runtime/virtcontainers/qemu_s390x.go
  src/runtime/virtcontainers/qemu_s390x_test.go
Labels: ok-to-test

#11830 gpu: Add correct latest driver per default
  tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
Labels: ok-to-test

#11495 runtime-rs: align SELinux feature with runtime-go (#9866)
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
  src/runtime-rs/crates/hypervisor/src/firecracker/inner.rs
  src/runtime-rs/crates/hypervisor/src/firecracker/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/firecracker/mod.rs
  src/runtime-rs/crates/hypervisor/src/lib.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
  src/runtime-rs/crates/hypervisor/src/remote/inner.rs
  src/runtime-rs/crates/hypervisor/src/remote/mod.rs
  src/runtime-rs/crates/hypervisor/src/selinux.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
  src/tools/agent-ctl/src/vm/vm_ops.rs
Labels: ok-to-test

#11638 ci.ocp: More debug output and tweaks
  ci/openshift-ci/peer-pods-azure.sh
Labels: ok-to-test

#11769 Enhance block device AIO mode
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/resource/src/cpu_mem/swap.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
  src/runtime-rs/crates/resource/src/volume/block_volume.rs
  src/runtime-rs/crates/resource/src/volume/direct_volumes/rawblock_volume.rs
  src/runtime-rs/crates/resource/src/volume/direct_volumes/spdk_volume.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: ok-to-test

#11844 runtime-rs: set the default block driver as virtio-scsi for qemu
  src/runtime-rs/Makefile
Labels: ok-to-test

#11847 tests: agent-ctl: Fix cleanup for testing with qemu
  tests/functional/kata-agent-apis/api-tests/test_vm_GuestDetails.bats
Labels: ok-to-test

#11848 GHA: Pin Alpine to 3.20 for tee-unencrypted image
  tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/Dockerfile
Labels: ok-to-test

#11719 csi-kata-directvolume: Add basic SPDK volume support
  src/tools/csi-kata-directvolume/README.md
  src/tools/csi-kata-directvolume/cmd/directvolplugin/main.go
  src/tools/csi-kata-directvolume/deploy/kata-directvolume/csi-directvol-plugin.yaml
  src/tools/csi-kata-directvolume/docs/spdk-usage.md
  src/tools/csi-kata-directvolume/examples/pod-with-spdkvol/csi-app.yaml
  src/tools/csi-kata-directvolume/examples/pod-with-spdkvol/csi-pvc.yaml
  src/tools/csi-kata-directvolume/examples/pod-with-spdkvol/csi-storageclass.yaml
  src/tools/csi-kata-directvolume/pkg/directvolume/controllerserver.go
  src/tools/csi-kata-directvolume/pkg/directvolume/controllerserver_test.go
  src/tools/csi-kata-directvolume/pkg/directvolume/directvolume.go
  src/tools/csi-kata-directvolume/pkg/directvolume/nodeserver.go
  src/tools/csi-kata-directvolume/pkg/directvolume/nodeserver_test.go
  src/tools/csi-kata-directvolume/pkg/spdkrpc/jsonrpc.go
  src/tools/csi-kata-directvolume/pkg/state/state.go
  src/tools/csi-kata-directvolume/pkg/utils/utils.go
Labels: ok-to-test

#11854 tests/k8s: Add set -euo pipefail to lib.sh
  tests/integration/kubernetes/k8s-parallel.bats
  tests/integration/kubernetes/lib.sh
  tests/integration/kubernetes/tests_common.sh
Labels: ok-to-test

#11856 gpu: Add libgcc for RUST libc=gnu builds
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Labels: ok-to-test

#11849 libs: Fix the test_parse_mount_options failure on ppc64le
  src/libs/kata-sys-util/src/mount.rs
Labels: ok-to-test

#11858 tests: k8s: auto-generate policy for additional tests
  tests/integration/kubernetes/k8s-credentials-secrets.bats
  tests/integration/kubernetes/k8s-liveness-probes.bats
  tests/integration/kubernetes/k8s-nginx-connectivity.bats
Labels: ok-to-test

#11846 Revert "ci: temporarily avoid using the Mariner Host image"
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/setup.sh
  tests/integration/kubernetes/tests_common.sh
Labels: ok-to-test

#11636 ci: add genpolicy build for Darwin
  .github/workflows/darwin-tests.yaml
  ci/darwin-test.sh
  src/agent/Cargo.toml
  src/libs/kata-types/Cargo.toml
  src/libs/kata-types/src/mount.rs
  src/runtime-rs/Cargo.toml
  src/tools/genpolicy/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  tests/common.bash
  tests/install_rust.sh
Labels: ok-to-test

#11850 runtime: config: allow TDX QGS port=0
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
Labels: ok-to-test

#11869 kata-sys-util: format mount.rs
  src/libs/kata-sys-util/src/mount.rs
Labels: ok-to-test
