Repository kata-containers/kata-containers, pull requests merged in 2025-06, with the labels that each got.

#11329 Fix | Support initdata for SNP
  src/runtime/pkg/govmm/qemu/qemu.go
  tests/integration/kubernetes/k8s-initdata.bats
Labels: ok-to-test

#11340 image: custom guest rootfs image file size alignment
  tools/osbuilder/image-builder/image_builder.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: ok-to-test

#10748 doc: Add Helm Chart entry
  docs/install/README.md
  tools/packaging/kata-deploy/helm-chart/README.md
Labels: force-skip-ci, size/large, ok-to-test

#11383 Switch docker hub mirroring to ghcr.io
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/release.yaml
Labels: force-skip-ci

#11334 workflows: Replace secrets: inherit
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-riscv64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/ci-coco-stability.yaml
  .github/workflows/ci-devel.yaml
  .github/workflows/ci-nightly.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/ci-weekly.yaml
  .github/workflows/ci.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/publish-kata-deploy-payload.yaml
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/release.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-zvsi.yaml
  .github/workflows/run-kata-coco-stability-tests.yaml
  .github/workflows/run-kata-coco-tests.yaml
  .github/workflows/run-kata-deploy-tests-on-aks.yaml
Labels: force-skip-ci

#11357 dragonball: Remove a useless dead_code attribute
  src/dragonball/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
Labels: ok-to-test

#11381 runtime-rs: Log error instead of format
  src/runtime-rs/crates/resource/src/share_fs/sandbox_bind_mounts.rs
Labels: ok-to-test

#11396 ci: Fix Mariner rootfs build failure
  tools/osbuilder/rootfs-builder/cbl-mariner/Dockerfile.in
Labels: ok-to-test

#11377 runtime-rs: Reduce the number of duplicate log entries being printed
  src/runtime-rs/crates/agent/src/kata/mod.rs
  src/runtime-rs/crates/agent/src/log_forwarder.rs
  src/runtime-rs/crates/agent/src/sock/hybrid_vsock.rs
  src/runtime-rs/crates/agent/src/sock/mod.rs
  src/runtime-rs/crates/agent/src/sock/remote.rs
  src/runtime-rs/crates/agent/src/sock/vsock.rs
Labels: ok-to-test

#11391 runtime-rs: Skip test on RISC-V architecture
  src/runtime-rs/Makefile
Labels: ok-to-test

#11388 ci: Use OIDC to log into Azure
  .github/workflows/ci-coco-stability.yaml
  .github/workflows/ci-devel.yaml
  .github/workflows/ci-nightly.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/ci-weekly.yaml
  .github/workflows/ci.yaml
  .github/workflows/cleanup-resources.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-kata-coco-stability-tests.yaml
  .github/workflows/run-kata-coco-tests.yaml
  .github/workflows/run-kata-deploy-tests-on-aks.yaml
  tests/functional/kata-deploy/gha-run.sh
  tests/gha-run-k8s-common.sh
  tests/integration/kubernetes/gha-run.sh
  tests/stability/gha-stability-run.sh
  tools/packaging/kata-deploy/action/Dockerfile
  tools/packaging/kata-deploy/action/action.yml
  tools/packaging/kata-deploy/action/entrypoint.sh
  tools/packaging/kata-deploy/action/kubernetes-containerd.json
  tools/packaging/kata-deploy/action/setup-aks.sh
  tools/packaging/kata-deploy/action/test-kata.sh
Labels: force-skip-ci

#11398 Revert "ci: Fix Mariner rootfs build failure"
  tools/osbuilder/rootfs-builder/cbl-mariner/Dockerfile.in
Labels: ok-to-test

#11345 protocols: Fix the noise caused by non-formatted codes in protocols
  src/libs/protocols/src/lib.rs
  src/libs/protocols/src/trans.rs
Labels: ok-to-test

#11343 Enables block device and disable virtio-fs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
Labels: ok-to-test

#11407 nvidia-rootfs: only copy `kata-opa` if `AGENT_POLICY` is enabled
  tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Labels: ok-to-test

#11305 versions: Bump Rust from 1.80.0 to 1.85.1
  rust-toolchain.toml
  src/agent/Cargo.toml
  src/agent/rustjail/src/cgroups/fs/mod.rs
  src/agent/rustjail/src/container.rs
  src/agent/rustjail/src/mount.rs
  src/agent/src/image.rs
  src/agent/src/linux_abi.rs
  src/agent/src/pci.rs
  src/agent/src/sandbox.rs
  src/agent/src/storage/mod.rs
  src/dragonball/dbs_acpi/src/rsdp.rs
  src/dragonball/dbs_acpi/src/sdt.rs
  src/dragonball/dbs_boot/src/x86_64/layout.rs
  src/dragonball/dbs_interrupt/src/kvm/mod.rs
  src/dragonball/dbs_legacy_devices/src/cmos.rs
  src/dragonball/dbs_pci/src/configuration.rs
  src/dragonball/dbs_pci/src/msi.rs
  src/dragonball/dbs_pci/src/msix.rs
  src/dragonball/dbs_pci/src/vfio.rs
  src/dragonball/dbs_utils/src/rate_limiter.rs
  src/dragonball/dbs_virtio_devices/src/balloon.rs
  src/dragonball/dbs_virtio_devices/src/block/handler.rs
  src/dragonball/dbs_virtio_devices/src/block/request.rs
  src/dragonball/dbs_virtio_devices/src/mmio/mod.rs
  src/dragonball/dbs_virtio_devices/src/net.rs
  src/dragonball/dbs_virtio_devices/src/vhost/vhost_kern/net.rs
  src/dragonball/dbs_virtio_devices/src/vhost/vhost_user/block.rs
  src/dragonball/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
  src/dragonball/dbs_virtio_devices/src/vhost/vhost_user/net.rs
  src/dragonball/dbs_virtio_devices/src/vsock/device.rs
  src/dragonball/src/device_manager/balloon_dev_mgr.rs
  src/dragonball/src/device_manager/mem_dev_mgr.rs
  src/dragonball/src/device_manager/mod.rs
  src/dragonball/src/vm/aarch64.rs
  src/dragonball/src/vm/mod.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
  src/runtime-rs/crates/hypervisor/src/firecracker/fc_api.rs
  src/runtime-rs/crates/hypervisor/src/firecracker/inner_hypervisor.rs
  src/runtime-rs/crates/resource/src/cdi_devices/container_device.rs
  src/runtime-rs/crates/resource/src/rootfs/nydus_rootfs.rs
  src/runtime-rs/crates/resource/src/share_fs/sandbox_bind_mounts.rs
  src/tools/agent-ctl/Cargo.lock
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/verity.rs
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/src/check.rs
  src/tools/kata-ctl/src/ops/check_ops.rs
  versions.yaml
Labels: size/large, ok-to-test

#11411 runk: Switch users crate
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
Labels: ok-to-test

#11412 genpolicy: fix rules syntax issues, rego v1 compatibility; ci: checks for rego parsing
  .github/workflows/static-checks.yaml
  src/tools/genpolicy/rules.rego
  tests/install_opa.sh
  tests/install_regorus.sh
  tests/static-checks.sh
  versions.yaml
Labels: ok-to-test

#11418 agent: add feature flag to secure_mount method
  src/agent/src/cdh.rs
Labels: ok-to-test

#11197 Move image pull abilities to CDH
  docs/design/arch-images/guest-image-management-architecture.png
  docs/design/arch-images/guest-image-management-details.png
  docs/design/kata-guest-image-management-design.md
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/Makefile
  src/agent/README.md
  src/agent/src/confidential_data_hub/image.rs
  src/agent/src/confidential_data_hub/mod.rs
  src/agent/src/config.rs
  src/agent/src/device/vfio_device_handler.rs
  src/agent/src/features.rs
  src/agent/src/image.rs
  src/agent/src/main.rs
  src/agent/src/rpc.rs
  src/agent/src/storage/image_pull_handler.rs
  src/agent/src/storage/mod.rs
  src/libs/protocols/protos/confidential_data_hub.proto
  tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
  tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
  tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
  tests/integration/kubernetes/k8s-initdata.bats
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/packaging/guest-image/build_image.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/agent/build-static-agent.sh
  tools/packaging/static-build/agent/build.sh
  tools/packaging/static-build/coco-guest-components/Dockerfile
  tools/packaging/static-build/coco-guest-components/build-static-coco-guest-components.sh
  versions.yaml
Labels: size/huge, ok-to-test

#11389 workflows: Set persist-credentials: false on checkout
  .github/workflows/actionlint.yaml
  .github/workflows/basic-ci-amd64.yaml
  .github/workflows/basic-ci-s390x.yaml
  .github/workflows/build-checks-preview-riscv64.yaml
  .github/workflows/build-checks.yaml
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-riscv64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/cargo-deny-runner.yaml
  .github/workflows/ci-weekly.yaml
  .github/workflows/ci.yaml
  .github/workflows/cleanup-resources.yaml
  .github/workflows/codeql.yml
  .github/workflows/darwin-tests.yaml
  .github/workflows/docs-url-alive-check.yaml
  .github/workflows/gatekeeper-skipper.yaml
  .github/workflows/gatekeeper.yaml
  .github/workflows/kata-runtime-classes-sync.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/publish-kata-deploy-payload.yaml
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/release.yaml
  .github/workflows/run-cri-containerd-tests-ppc64le.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-amd64.yaml
  .github/workflows/run-k8s-tests-on-arm64.yaml
  .github/workflows/run-k8s-tests-on-ppc64le.yaml
  .github/workflows/run-k8s-tests-on-zvsi.yaml
  .github/workflows/run-kata-coco-stability-tests.yaml
  .github/workflows/run-kata-coco-tests.yaml
  .github/workflows/run-kata-deploy-tests-on-aks.yaml
  .github/workflows/run-kata-deploy-tests.yaml
  .github/workflows/run-kata-monitor-tests.yaml
  .github/workflows/run-metrics.yaml
  .github/workflows/run-runk-tests.yaml
  .github/workflows/shellcheck.yaml
  .github/workflows/shellcheck_required.yaml
  .github/workflows/static-checks.yaml
  src/runtime/pkg/govmm/.github/workflows/main.yml
Labels: force-skip-ci

#11359 Fix logging on virtiofs shutdown
  src/runtime/virtcontainers/clh.go
Labels: ok-to-test

#10698 runtime-rs: Support Pull Image in Guest with Kata Volume for CoCo
  src/libs/kata-types/src/mount.rs
  src/runtime-rs/crates/resource/src/manager.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
  src/runtime-rs/crates/resource/src/rootfs/virtual_volume.rs
  src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Labels: size/large, ok-to-test

#11394 kata-deploy: accept 25.04 as supported distro for TDX
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: ok-to-test

#11427 rootfs: Bump rootfs-{image,initrd} to 24.04
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  versions.yaml
Labels: ok-to-test

#11400 ci: Add optional govulncheck security scanning to static checks
  .github/workflows/govulncheck.yaml
  .github/workflows/static-checks.yaml
  tests/govulncheck-runner.sh
Labels: ok-to-test

#11429 Cri containerd required test rename
  tools/testing/gatekeeper/required-tests.yaml
Labels: ok-to-test

#11337 gpu: Fix module signing
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/fragments/common/signing/module_signing.conf
  tools/packaging/kernel/configs/fragments/gpu/nvidia.x86_64.conf.in
  tools/packaging/kernel/kata_config_version
Labels: ok-to-test

#11432 versions: Bump golang to 1.23.10
  .github/workflows/darwin-tests.yaml
  .github/workflows/docs-url-alive-check.yaml
  versions.yaml
Labels: security, ok-to-test

#11433 workflows: Add fail-fast: false to cri-containerd tests
  .github/workflows/ci.yaml
Labels: force-skip-ci

#11435 workflows: Fix permissions
  .github/workflows/ci-weekly.yaml
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release-s390x.yaml
Labels: force-skip-ci

#11443 tests: update container image for ci and unit test
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/runas/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/runas/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/supplemental_groups/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/supplemental_groups/testcases.json
  tests/integration/kubernetes/runtimeclass_workloads/k8s-layered-sc-deployment.yaml
  tests/integration/kubernetes/runtimeclass_workloads/k8s-pod-sc-deployment.yaml
  tests/integration/kubernetes/runtimeclass_workloads/k8s-pod-sc-nobodyupdate-deployment.yaml
  tests/integration/kubernetes/runtimeclass_workloads/k8s-pod-sc-supplementalgroups-deployment.yaml
  tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-deployment.yaml
Labels: ok-to-test

#11331 workflow: Remove code injection in helm login
  .github/workflows/release.yaml
Labels: security, do-not-merge, force-skip-ci

#11448 ci: Remove duplicated `rust-vmm` dependencies
  .github/dependabot.yml
  src/dragonball/out
Labels: ok-to-test

#11420 workflows: Pin action hashes
  .github/workflows/actionlint.yaml
  .github/workflows/basic-ci-amd64.yaml
  .github/workflows/basic-ci-s390x.yaml
  .github/workflows/build-checks-preview-riscv64.yaml
  .github/workflows/build-checks.yaml
  .github/workflows/build-kata-static-tarball-amd64.yaml
  .github/workflows/build-kata-static-tarball-arm64.yaml
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/build-kata-static-tarball-riscv64.yaml
  .github/workflows/build-kata-static-tarball-s390x.yaml
  .github/workflows/cargo-deny-runner.yaml
  .github/workflows/ci-weekly.yaml
  .github/workflows/ci.yaml
  .github/workflows/cleanup-resources.yaml
  .github/workflows/codeql.yml
  .github/workflows/darwin-tests.yaml
  .github/workflows/docs-url-alive-check.yaml
  .github/workflows/gatekeeper-skipper.yaml
  .github/workflows/gatekeeper.yaml
  .github/workflows/kata-runtime-classes-sync.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/publish-kata-deploy-payload.yaml
  .github/workflows/release-amd64.yaml
  .github/workflows/release-arm64.yaml
  .github/workflows/release-ppc64le.yaml
  .github/workflows/release-s390x.yaml
  .github/workflows/release.yaml
  .github/workflows/run-cri-containerd-tests.yaml
  .github/workflows/run-k8s-tests-on-aks.yaml
  .github/workflows/run-k8s-tests-on-amd64.yaml
  .github/workflows/run-k8s-tests-on-arm64.yaml
  .github/workflows/run-k8s-tests-on-ppc64le.yaml
  .github/workflows/run-k8s-tests-on-zvsi.yaml
  .github/workflows/run-kata-coco-stability-tests.yaml
  .github/workflows/run-kata-coco-tests.yaml
  .github/workflows/run-kata-deploy-tests-on-aks.yaml
  .github/workflows/run-kata-deploy-tests.yaml
  .github/workflows/run-kata-monitor-tests.yaml
  .github/workflows/run-metrics.yaml
  .github/workflows/run-runk-tests.yaml
  .github/workflows/shellcheck.yaml
  .github/workflows/shellcheck_required.yaml
  .github/workflows/stale.yaml
  .github/workflows/static-checks.yaml
Labels: security, force-skip-ci, ok-to-test

#11426 genpolicy: prevent corruption of the layer cache file
  src/tools/genpolicy/src/layers_cache.rs
  src/tools/genpolicy/src/lib.rs
  src/tools/genpolicy/src/main.rs
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/tests/policy/main.rs
Labels: ok-to-test

#11181 runtime-rs: Implement Initdata Spec Support in runtime-rs for CoCo
  src/agent/Cargo.lock
  src/agent/src/initdata.rs
  src/libs/Cargo.lock
  src/libs/kata-types/Cargo.toml
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/libs/kata-types/src/initdata.rs
  src/libs/kata-types/src/lib.rs
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/hypervisor/src/device/driver/protection_device.rs
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/coco_data/initdata.rs
  src/runtime-rs/crates/resource/src/coco_data/initdata_block.rs
  src/runtime-rs/crates/resource/src/coco_data/mod.rs
  src/runtime-rs/crates/resource/src/lib.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: size/huge, ok-to-test

#11466 runtime-rs: add the blockfile based rootfs support
  src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
  src/runtime-rs/crates/resource/src/rootfs/mod.rs
Labels: ok-to-test

#11467 runtime-rs: fix the issue return the wrong volume
  src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
Labels: ok-to-test

#11468 runtime-rs: Support shared fs with "none" on non-tee platforms
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
Labels: ok-to-test

#11422 runtime-rs: Add the memory and vcpu hotplug for cloud-hypervisor
  src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
  src/runtime-rs/crates/hypervisor/ch-config/src/net_util.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner.rs
  src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
  src/runtime-rs/crates/hypervisor/src/ch/mod.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/utils.rs
Labels: ok-to-test

#11392 ci: Run zizmor for GHA security analysis
  .github/workflows/zizmor.yaml
Labels: security, ok-to-test

#11461 versions: Bump guest-components
  src/tools/agent-ctl/Cargo.lock
  src/tools/agent-ctl/Cargo.toml
  src/tools/agent-ctl/src/image.rs
  versions.yaml
Labels: ok-to-test

#11470 runtime-rs: Fix calculation of odd memory sizes
  src/runtime-rs/crates/resource/src/cpu_mem/initial_size.rs
Labels: ok-to-test

#11474 runtime-rs: Add GPU annotations for remote hypervisor
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/config/configuration-remote.toml.in
  src/runtime-rs/crates/hypervisor/src/remote/inner.rs
Labels: ok-to-test

#11484 version: Bump nydus-snapshotter
  versions.yaml
Labels: ok-to-test
