Repository kata-containers/kata-containers, pull requests merged in 2025-05, with the labels that each got.

#11223 ci: revert temp: ci: Fix AKS cluster creation
  tests/gha-run-k8s-common.sh
Labels: size/tiny, ok-to-test

#11206 runtime: remove wrong xfs options
  src/runtime-rs/crates/hypervisor/src/kernel_param.rs
  src/runtime/virtcontainers/hypervisor.go
  src/runtime/virtcontainers/hypervisor_test.go
Labels: size/small, ok-to-test

#11217 Runtime rs centralise workspace config
  .github/workflows/build-checks-preview-riscv64.yaml
  .github/workflows/build-checks.yaml
  .github/workflows/static-checks.yaml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/runtime-rs/crates/agent/Cargo.toml
  src/runtime-rs/crates/hypervisor/Cargo.toml
  src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
  src/runtime-rs/crates/persist/Cargo.toml
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/runtimes/Cargo.toml
  src/runtime-rs/crates/runtimes/common/Cargo.toml
  src/runtime-rs/crates/runtimes/linux_container/Cargo.toml
  src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
  src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml
  src/runtime-rs/crates/service/Cargo.toml
  src/runtime-rs/crates/shim-ctl/Cargo.toml
  src/runtime-rs/crates/shim/Cargo.toml
  src/runtime-rs/tests/utils/Cargo.toml
Labels: size/huge, ok-to-test

#11204 versions: Bump golang.org/x/net
  src/tools/csi-kata-directvolume/go.mod
  src/tools/csi-kata-directvolume/go.sum
  tools/testing/kata-webhook/go.mod
  tools/testing/kata-webhook/go.sum
Labels: size/small, ok-to-test

#11146 dragonball: Put local dependencies into workspace
  src/dragonball/Cargo.toml
  src/dragonball/dbs_boot/Cargo.toml
  src/dragonball/dbs_interrupt/Cargo.toml
  src/dragonball/dbs_legacy_devices/Cargo.toml
  src/dragonball/dbs_pci/Cargo.toml
  src/dragonball/dbs_upcall/Cargo.toml
  src/dragonball/dbs_virtio_devices/Cargo.toml
Labels: size/medium, ok-to-test

#11228 gpu: Set the ARCH explicilty for driver builds
  tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
Labels: size/tiny, ok-to-test

#11230 runtime: remove wrong qemu-system-x86_64 option
  src/runtime/virtcontainers/qemu_amd64.go
  src/runtime/virtcontainers/qemu_arch_base.go
Labels: size/tiny, ok-to-test

#11209 shimv2: fix the issue logger write failed
  src/runtime-rs/crates/shim/src/logger.rs
Labels: size/tiny, ok-to-test

#11227 agent: netlink: Only add an ipv6 address if ipv6 is enabled
  src/agent/src/netlink.rs
Labels: size/small, ok-to-test

#11202 runtime-rs: Upgrade `rust-netlink` crates
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_dan.rs
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs
  src/runtime-rs/crates/resource/src/network/network_model/test_network_model.rs
  src/runtime-rs/crates/resource/src/network/network_pair.rs
  src/runtime-rs/crates/resource/src/network/utils/address.rs
  src/runtime-rs/crates/resource/src/network/utils/link/manager.rs
Labels: size/large, ok-to-test

#11172 EROFS Snapshotter Support in Kata
  src/agent/src/storage/fs_handler.rs
  src/libs/kata-types/src/mount.rs
  src/runtime/pkg/containerd-shim-v2/create.go
  src/runtime/pkg/katautils/create.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/fs_share_linux.go
  src/runtime/virtcontainers/kata_agent.go
Labels: size/large, ok-to-test

#11232 runtime: add the mtu support for updating routes
  src/agent/src/netlink.rs
  src/libs/protocols/protos/types.proto
  src/runtime-rs/crates/agent/src/kata/trans.rs
  src/runtime-rs/crates/agent/src/types.rs
  src/runtime-rs/crates/resource/src/network/dan.rs
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_dan.rs
  src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs
  src/runtime/virtcontainers/network.go
  src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
Labels: size/small, ok-to-test

#11116 kata-debug: Make path resolution more robust
  tools/packaging/kata-debug/kata-debug-build-and-upload-payload.sh
Labels: size/tiny, ok-to-test

#11123 runtime: Add Path for kata-deploy
  src/runtime/data/kata-collect-data.sh.in
Labels: size/small, ok-to-test

#11127 genpolicy: improve validation for mounts
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/createcontainer/volumes/emptydir/pod.yaml
  src/tools/genpolicy/tests/testdata/createcontainer/volumes/emptydir/testcases.json
Labels: size/huge, ok-to-test

#11076 Bind/associate for VFIO-AP
  docs/README.md
  docs/use-cases/CEX-passthrough-and-coco.md
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/src/cdh.rs
  src/agent/src/device/vfio_device_handler.rs
  src/libs/protocols/protos/confidential_data_hub.proto
Labels: size/large, ok-to-test

#10986 genpolicy: support secrets to be referenced for pod envs
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/src/config_map.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/tests/generate/main.rs
  src/tools/genpolicy/tests/generate/testdata/config_map.yaml
  src/tools/genpolicy/tests/generate/testdata/pod_with_config_map_ref.yaml
  src/tools/genpolicy/tests/generate/testdata/pod_with_secret_ref.yaml
  src/tools/genpolicy/tests/generate/testdata/secret.yaml
  src/tools/genpolicy/tests/policy/main.rs
  src/tools/genpolicy/tests/policy/testdata/copyfile/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/copyfile/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/generate_name/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/generate_name/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/network_namespace/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/network_namespace/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/sysctls/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/sysctls/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/emptydir/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/emptydir/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createsandbox/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createsandbox/testcases.json
  src/tools/genpolicy/tests/policy/testdata/state/createcontainer/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/state/createcontainer/testcases.json
  src/tools/genpolicy/tests/policy/testdata/state/execprocess/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/state/execprocess/testcases.json
  src/tools/genpolicy/tests/policy/testdata/updateinterface/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/updateinterface/testcases.json
  src/tools/genpolicy/tests/policy/testdata/updateroutes/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/updateroutes/testcases.json
Labels: size/huge, ok-to-test

#11250 versions: Update tempfile crate
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/libs/Cargo.lock
  src/libs/kata-sys-util/Cargo.toml
  src/libs/kata-types/Cargo.toml
  src/libs/logging/Cargo.toml
  src/libs/safe-path/Cargo.toml
  src/libs/shim-interface/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/Cargo.toml
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/kata-ctl/Cargo.lock
  src/tools/kata-ctl/Cargo.toml
  src/tools/runk/Cargo.lock
  src/tools/runk/Cargo.toml
  src/tools/runk/libcontainer/Cargo.toml
  src/tools/trace-forwarder/Cargo.lock
  src/tools/trace-forwarder/Cargo.toml
Labels: size/huge, ok-to-test

#11199 helm: Avoid appending the multiInstallSuffix several times
  tools/packaging/kata-deploy/scripts/kata-deploy.sh
Labels: size/tiny, ok-to-test

#11262 runtime/config: Add VFIO config for IBM SEL
  src/runtime-rs/Makefile
  src/runtime-rs/config/configuration-qemu-se-runtime-rs.toml.in
  src/runtime/Makefile
  src/runtime/config/configuration-qemu-se.toml.in
Labels: size/small, ok-to-test

#11255 ci: gatekeeper: skip docker tests
  tools/testing/gatekeeper/required-tests.yaml
Labels: force-skip-ci, size/tiny

#11253 versions: Bump golang.org/x/oauth2
  src/runtime/go.mod
  src/runtime/go.sum
  src/runtime/vendor/golang.org/x/oauth2/LICENSE
  src/runtime/vendor/golang.org/x/oauth2/README.md
  src/runtime/vendor/golang.org/x/oauth2/internal/client_appengine.go
  src/runtime/vendor/golang.org/x/oauth2/internal/transport.go
  src/runtime/vendor/golang.org/x/oauth2/oauth2.go
  src/runtime/vendor/golang.org/x/oauth2/pkce.go
  src/runtime/vendor/golang.org/x/oauth2/token.go
  src/runtime/vendor/google.golang.org/appengine/LICENSE
  src/runtime/vendor/google.golang.org/appengine/internal/api.go
  src/runtime/vendor/google.golang.org/appengine/internal/api_classic.go
  src/runtime/vendor/google.golang.org/appengine/internal/api_common.go
  src/runtime/vendor/google.golang.org/appengine/internal/app_id.go
  src/runtime/vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  src/runtime/vendor/google.golang.org/appengine/internal/base/api_base.proto
  src/runtime/vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  src/runtime/vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  src/runtime/vendor/google.golang.org/appengine/internal/identity.go
  src/runtime/vendor/google.golang.org/appengine/internal/identity_classic.go
  src/runtime/vendor/google.golang.org/appengine/internal/identity_flex.go
  src/runtime/vendor/google.golang.org/appengine/internal/identity_vm.go
  src/runtime/vendor/google.golang.org/appengine/internal/internal.go
  src/runtime/vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  src/runtime/vendor/google.golang.org/appengine/internal/log/log_service.proto
  src/runtime/vendor/google.golang.org/appengine/internal/main.go
  src/runtime/vendor/google.golang.org/appengine/internal/main_common.go
  src/runtime/vendor/google.golang.org/appengine/internal/main_vm.go
  src/runtime/vendor/google.golang.org/appengine/internal/metadata.go
  src/runtime/vendor/google.golang.org/appengine/internal/net.go
  src/runtime/vendor/google.golang.org/appengine/internal/regen.sh
  src/runtime/vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  src/runtime/vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  src/runtime/vendor/google.golang.org/appengine/internal/transaction.go
  src/runtime/vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  src/runtime/vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  src/runtime/vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  src/runtime/vendor/modules.txt
Labels: size/tiny, ok-to-test

#11251 Rust vulns 9th may 2025
  src/agent/Cargo.lock
  src/dragonball/Cargo.lock
  src/libs/Cargo.lock
  src/libs/kata-types/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/resource/Cargo.toml
  src/runtime-rs/crates/resource/src/volume/hugepage.rs
  src/tools/agent-ctl/Cargo.lock
  src/tools/genpolicy/Cargo.lock
  src/tools/kata-ctl/Cargo.lock
  src/tools/runk/Cargo.lock
  src/tools/trace-forwarder/Cargo.lock
Labels: size/huge, ok-to-test

#11264 helm: release: Publish our helm charts to the OCI registries
  .github/workflows/release.yaml
Labels: size/small

#11246 osbuilder: ubuntu: Switch from multistrap to mmdebstrap
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
  tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
Labels: size/small, ok-to-test

#11265 Bump: libz-sys crate to address CVE
  src/dragonball/Cargo.lock
  src/runtime-rs/Cargo.lock
Labels: size/medium, ok-to-test

#11272 Enable edk2 for arm64
  .github/workflows/build-kata-static-tarball-arm64.yaml
  src/runtime/Makefile
  src/runtime/arch/arm64-options.mk
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
  tools/packaging/static-build/ovmf/build-ovmf.sh
  tools/packaging/static-build/ovmf/build.sh
  versions.yaml
Labels: size/small, ok-to-test

#11257 confidential guest kernel hardening changes
  src/runtime/virtcontainers/qemu.go
  tools/packaging/kernel/build-kernel.sh
  tools/packaging/kernel/configs/README.md
  tools/packaging/kernel/configs/fragments/common/mmio.conf
  tools/packaging/kernel/configs/fragments/common/virtio-extras.conf
  tools/packaging/kernel/configs/fragments/common/virtio.conf
  tools/packaging/kernel/kata_config_version
  versions.yaml
Labels: size/small, ok-to-test

#11274 ci: k8s: arm: Enable skipped tests
  tests/integration/kubernetes/k8s-memory.bats
  tests/integration/kubernetes/k8s-pod-quota.bats
Labels: size/tiny, ok-to-test

#11214 genpolicy: Enable AdditionalGids checks in rules.rego
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/yaml.rs
  src/tools/genpolicy/tests/policy/main.rs
  src/tools/genpolicy/tests/policy/testdata/createcontainer/generate_name/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/network_namespace/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/runas/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/runas/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/supplemental_groups/pod.yaml
  src/tools/genpolicy/tests/policy/testdata/createcontainer/security_context/supplemental_groups/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/sysctls/testcases.json
  src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/emptydir/testcases.json
  src/tools/genpolicy/tests/policy/testdata/state/createcontainer/testcases.json
  src/tools/genpolicy/tests/policy/testdata/state/execprocess/testcases.json
  tests/integration/kubernetes/k8s-policy-deployment-sc.bats
  tests/integration/kubernetes/runtimeclass_workloads/k8s-pod-sc-supplementalgroups-deployment.yaml
Labels: size/huge, ok-to-test

#10578 runtime-rs: Introduce PCIe Port devices in runtime-rs for qemu-rs
  src/libs/kata-types/src/annotations/mod.rs
  src/libs/kata-types/src/config/hypervisor/dragonball.rs
  src/libs/kata-types/src/config/hypervisor/mod.rs
  src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in
  src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/driver/port_device.rs
  src/runtime-rs/crates/hypervisor/src/device/mod.rs
  src/runtime-rs/crates/hypervisor/src/device/topology.rs
  src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
  src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/resource/src/lib.rs
  src/runtime-rs/crates/resource/src/manager_inner.rs
  src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Labels: size/huge, ok-to-test

#11287 runtime: Fix logging for remote hypervisor
  src/runtime/virtcontainers/remote.go
Labels: size/small, ok-to-test

#11283 config: Fix typos
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu-coco-dev.toml.in
  src/runtime/config/configuration-qemu-nvidia-gpu-snp.toml.in
  src/runtime/config/configuration-qemu-nvidia-gpu-tdx.toml.in
  src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
  src/runtime/config/configuration-qemu-se.toml.in
  src/runtime/config/configuration-qemu-sev.toml.in
  src/runtime/config/configuration-qemu-snp.toml.in
  src/runtime/config/configuration-qemu-tdx.toml.in
  src/runtime/config/configuration-qemu.toml.in
  src/runtime/config/configuration-stratovirt.toml.in
Labels: size/small, ok-to-test

#11271 ci: gatekeeper: Require names update
  tools/testing/gatekeeper/required-tests.yaml
Labels: size/tiny

#11273 config: update QEMU TDX configuration
  src/runtime/arch/amd64-options.mk
Labels: size/tiny, ok-to-test

#11277 osbuilder: ubuntu: Expose REPO_URL variables
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/rootfs-builder/ubuntu/config.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
  tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Labels: size/small, ok-to-test

#11233 genpolicy: validate input process fields for ExecProcessRequest
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/tests/policy/testdata/state/execprocess/testcases.json
Labels: size/large, ok-to-test

#11259 Update Trustee and Guest Components for CoCo v0.14.0
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
  tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
  tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
  tests/integration/kubernetes/k8s-guest-pull-image.bats
  tests/integration/kubernetes/k8s-initdata.bats
  versions.yaml
Labels: size/huge, ok-to-test

#11289 runtime: Preserve hotplug devices for vfio-coldplug mode
  src/runtime/virtcontainers/container.go
Labels: ok-to-test

#11144 Support hot-plug block device in qemu-rs with QMP
  src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
  src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
Labels: size/large, ok-to-test

#11298 release: Bump version to 3.17.0
  VERSION
  tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml
Labels: size/tiny, ok-to-test

#11293 tests/k8s: increase wait time of KBS service ingress
  tests/integration/kubernetes/confidential_kbs.sh
Labels: area/ci, area/testing, size/tiny, ok-to-test

#11130 tests/k8s: better tests reporting for CI
  .github/workflows/run-kata-coco-tests.yaml
  tests/integration/kubernetes/.gitignore
  tests/integration/kubernetes/gha-run.sh
  tests/integration/kubernetes/run_kubernetes_tests.sh
Labels: area/ci, area/testing, size/medium, ok-to-test

#11267 osbuilder: lib.sh: Fix indent
  tools/osbuilder/scripts/lib.sh
Labels: size/small, ok-to-test

#11254 runtime-rs: fix vfio pci address domain 0001 problem
  src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
Labels: size/small, ok-to-test, area/gpu

#11294 tests/k8s: delint confidential_kbs.sh
  tests/integration/kubernetes/confidential_kbs.sh
Labels: area/testing, size/large, ok-to-test

#11270 tools.testing: Add methods to simplify gatekeeper development
  tools/testing/gatekeeper/jobs.py
Labels: size/medium, ok-to-test

#11320 workflows: gatekeeper: Update permissions
  .github/workflows/gatekeeper.yaml
Labels: force-skip-ci, size/tiny

#11319 workflows: Delete workflows
  .github/workflows/add-issues-to-project.yaml
  .github/workflows/add-pr-sizing-label.yaml
  .github/workflows/move-issues-to-in-progress.yaml
Labels: force-skip-ci, size/large

#11322 workflows: Add explicit permissions for attestation
  .github/workflows/build-kata-static-tarball-ppc64le.yaml
  .github/workflows/ci-coco-stability.yaml
  .github/workflows/ci-devel.yaml
  .github/workflows/ci-nightly.yaml
  .github/workflows/ci-on-push.yaml
  .github/workflows/payload-after-push.yaml
  .github/workflows/release.yaml
Labels: force-skip-ci, size/medium

#11314 genpolicy: fix svc_name regex
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/rules.rego
  src/tools/genpolicy/src/policy.rs
Labels: size/small, ok-to-test

#11346 rust: Update cgroups-rs to its v0.3.5 release
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/runtime-rs/Cargo.lock
  src/runtime-rs/crates/resource/Cargo.toml
  src/tools/runk/Cargo.lock
  src/tools/runk/libcontainer/Cargo.toml
Labels: ok-to-test
